cmd/glbc/main.go, pkg/context/context.go, pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/controller/utils_test.go
Some simple refactor that required by the following NEG changes.
=> PRE-NEG changes

pkg/controller/cluster_manager.go
deleteType,invalidPort,nameLenLimit
=> Delete unreferenced constants

pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/controller/utils.go, pkg/utils/taskqueue.go, pkg/utils/taskqueue_test.go
- Adds unit test for TaskQueue
- Fixes minor violation of abstractions in controller_test.go
=> Move taskQueue to utils.PeriodicTaskQueue

cmd/glbc/main.go, pkg/annotations/annotations.go, pkg/annotations/ingress.go, pkg/annotations/ingress_test.go, pkg/annotations/service.go, pkg/annotations/service_test.go, pkg/backends/backends.go, pkg/backends/backends_test.go, pkg/controller/controller.go, pkg/controller/fakes.go, pkg/controller/translator/translator.go, pkg/controller/utils.go, pkg/controller/utils_test.go, pkg/healthchecks/healthchecks.go, pkg/healthchecks/healthchecks_test.go, pkg/healthchecks/interfaces.go, pkg/loadbalancers/loadbalancers.go, pkg/loadbalancers/loadbalancers_test.go, pkg/networkendpointgroup/controller.go, pkg/utils/gceurlmap.go, pkg/utils/gceurlmap_test.go, pkg/utils/utils.go, pkg/utils/utils_test.go
Move K8sAnnotationPrefix into annotations
Move AppProtocol and associated constants into annotations package ￼…
Remove stuttering IngAnnotations -> Ingress
Remove stuttering SvcAnnotations -> Service
Split off gceurlmap into its own file
=> Minor cleanup

cmd/glbc/app/clients.go, cmd/glbc/app/clients_test.go
@nicksardo might have the most context.
Ref https://docs.google.com/document/d/1E2ufxZGujFCYKYOsvBjb4VMNjBy8CM-MMycoT_UVwIs/edit#heading=h.t6chylryqex6.
=> Add unit test for the generated GCE config reader func

pkg/context/context.go, pkg/controller/cluster_manager.go, pkg/controller/node.go, pkg/controller/translator/translator_test.go, pkg/controller/utils.go
This was somehow missing from the branch that was merged
=> Code review comments

docs/testing.md
Really rough draft for some documentation that helps explain how to run some e2e tests locally.
=> Add some documentation for how to run e2e tests locally.

docs/annotations.md
=> update: s_k/ingress-k/ingress-gce_ in annotations.md

deploy/glbc/script.sh
=> Fix copyright in deploy/glbc/script.sh

pkg/loadbalancers/fakes.go, pkg/loadbalancers/interfaces.go
Fixes https://github.com/kubernetes/ingress-gce/issues/162
cc @nicksardo @G-Harmon
=> Adding ListUrlMaps to LoadBalancers interface

pkg/controller/cluster_manager.go, pkg/controller/controller.go, pkg/firewalls/firewalls.go, pkg/firewalls/firewalls_test.go
=> Cherry-pick checkpoint changes to 1.0

deploy/glbc/README.md
=> Small changes to deploy/glbc/README

pkg/apis/backendconfig/v1alpha1/types.go
This is just to get a tentative spec checked in so I can start working on wiring up the actual implementation for the features. 
The spec is still subject to change.
=> Introduce configuration for IAP & CDN into BackendConfig spec

pkg/backends/backends.go, pkg/backends/backends_test.go, pkg/healthchecks/fakes.go, pkg/instances/fakes.go, pkg/instances/instances.go, pkg/loadbalancers/certificates.go, pkg/loadbalancers/fakes.go, pkg/loadbalancers/forwarding_rules.go, pkg/loadbalancers/l7.go, pkg/loadbalancers/loadbalancers_test.go, pkg/loadbalancers/target_proxies.go, pkg/loadbalancers/url_maps.go, pkg/neg/fakes.go, pkg/neg/syncer.go, pkg/utils/utils.go, pkg/utils/utils_test.go
Reverts kubernetes/ingress-gce#304
=> Revert "Use cloud ResourceID for URL parsing and generation"

pkg/backends/backends.go, pkg/backends/interfaces.go, pkg/composite/composite.go, pkg/composite/composite_test.go
fyi @MrHohn
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubernetes/ingress-gce/313)
=> Moved BackendService composite type to its own package

cmd/echo/app/handlers.go
Using the request query string, we can turn caching on and off.
Verified it works as expected:
Request: curl localhost:8080/?cache=true
```
HTTP/1.1 200 OK
Cache-Control: max-age=86400,public
Content-Type: application/json
Date: Wed, 06 Jun 2018 18:38:31 GMT
Content-Length: 247
```
Request: curl localhost:8080/?cache=[false,blah,empty]
```
HTTP/1.1 200 OK
Content-Type: application/json
Date: Wed, 06 Jun 2018 18:38:31 GMT
Content-Length: 247
```
=> Support caching in echoserver

pkg/controller/translator/translator.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubernetes/ingress-gce/322)
=> Fix ingress translation logic to not GC backend if non-fatal error occurred

pkg/utils/namer.go, pkg/utils/namer_test.go
=> Handle empty cluster name in sslcert namer

cmd/e2e-test/basic_test.go, pkg/e2e/helpers.go, pkg/fuzz/gcp.go
This avoids leaking resources during cluster teardown in the
normal case.
=> Delete ingress and wait for resource deletion

cmd/glbc/main.go, pkg/flags/flags.go
https://github.com/kubernetes/ingress-gce/issues/274
=> use flag instead of gate for NEG

pkg/fuzz/gcp.go
Seems like resourceType was mistakenly hardcoded.
=> Fix hasAlphaResource and hasBetaResource

pkg/e2e/fixtures.go, pkg/e2e/framework.go
=> Add backendconfig client to e2e framework

deploy/glbc/script.sh
Fixes #363
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubernetes/ingress-gce/368)
=> Update deploy script to edit copy of default backend service yaml

cmd/e2e-test/run.sh
=> Fix run.sh to properly print exit code of test run

pkg/neg/manager.go, pkg/neg/utils.go, pkg/neg/utils_test.go
=> PortNameMap should also compare values

cmd/glbc/main.go, pkg/controller/controller.go, pkg/controller/utils.go, pkg/neg/controller.go, pkg/neg/syncer.go, pkg/neg/utils.go, pkg/neg/utils_test.go
=> Some fixes for 1.2

pkg/e2e/helpers.go
=> Increase timeout on waiting for GLBC resource deletion

pkg/backendconfig/backendconfig.go
=> Cherrypick #383: Unmask get backend config errors

README.md, examples/deployment/gce-ingress-controller.yaml, examples/multi-path/gce-multi-path-ingress.yaml, examples/multi-path/svc.yaml
Patches up some holes created by #150
=> Documentation fixes

pkg/neg/syncer.go
Line 127: SyncNetworkEndpiontGroupFailed->SyncNetworkEndpointGroupFailed
=> Typo in message: SyncNetworkEndpiontGroupFailed->SyncNetworkEndpointGroupFailed

cmd/glbc/main.go, pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/neg/controller.go, pkg/neg/controller_test.go
The functions which create the LB controller and the NEG controller return an error for no apparent reason
=> Remove error return value from controller initialization

deploy/glbc/yaml/rbac.yaml
=> Fix issue with yaml in glbc deploy/

cmd/e2e-test/backend_config_test.go, cmd/e2e-test/security_policy_test.go
=> Bump timeout in tests to match reality

pkg/backends/features/securitypolicy_test.go
/assign @rramkumar1 
cc @bowei
=> unit test: add locking when read from shared map

pkg/context/context.go
=> Expose newIndexer in pkg/context

docs/annotations.md
Add a reference link for now.
@rramkumar1 @bowei
=> Add doc link for backend config

README.md
=> Add a version mapping for both GCE and GKE clusters

OWNERS
=> Add myself to OWNERS so I can do a release.

pkg/controller/controller.go
Ignore a 404 error since we are purposefully trying to get a backend that does not exist.
=> Fix main controller health check

pkg/neg/controller.go, pkg/neg/controller_test.go, pkg/neg/interfaces.go, pkg/neg/manager.go, pkg/neg/manager_test.go, pkg/neg/types/types.go, pkg/neg/types/types_test.go, pkg/neg/utils.go, pkg/neg/utils_test.go
=> Move NegStatus and PortNameMap to pkg/neg/types

pkg/utils/finalizer.go, pkg/utils/finalizer_test.go
=> Export getPatchBytes in pkg/util

pkg/controller/controller.go, pkg/controller/utils.go, pkg/utils/utils.go
=> Move joinErrs() to utils and export it

pkg/utils/patch.go, pkg/utils/patch_test.go
=> Remove JSONMergePatch util

pkg/loadbalancers/url_maps.go
=> Cherrypick of #434 on release 1.3

pkg/backends/ig_linker_test.go, pkg/backends/integration_test.go, pkg/backends/interfaces.go, pkg/backends/neg_linker.go, pkg/backends/neg_linker_test.go
=> Modify GroupKey type to contain group name + modify NEG linker to consider provided name

pkg/utils/namer.go, pkg/utils/namer_test.go
=> include NEG naming scheme for NameBelongsToCluster

pkg/utils/finalizer.go
=> Expose utils.hasFinalizer

pkg/utils/taskqueue.go
=> Allow for setting the rate limiter on the work queue

cmd/e2e-test/readme.md
Thinking this might be helpful as it isn't quite obvious to me.
=> Add an example for running specific test case to readme

CHANGELOG.md
/assign @MrHohn 
Once we become better with our issue tracking in terms of labels, the output of this script will be even better.
=> Replace existing CHANGELOG.md with one generated via a script

README.md, deploy/glbc/yaml/default-http-backend.yaml, examples/deployment/gce-ingress-controller.yaml
=> defaultbackend image now has the architecture in the image name

pkg/loadbalancers/certificates.go
Because of a bug Ingress adds all ManagedCertificate objects in the cluster to the load balancer if managed-certificates annotation is not empty. Instead it should only add the objects found in the annotation. This PR fixes this bug.
=> Fix wrong filtering of ManagedCertificate objects.

cmd/glbc/main.go, pkg/flags/flags.go, pkg/neg/controller.go, pkg/neg/controller_test.go, pkg/neg/manager.go, pkg/neg/manager_test.go, pkg/neg/utils.go
enable transaction syncer as default in order for CI to pick up.
=> add a flag to control neg syncer type

pkg/instances/instances.go, pkg/instances/instances_test.go
This reverts commit fbe88aa88b961ab683af8486da6e040cbd75584c.
/assign @bowei
=> Revert "Remove unused named ports from instance group's"

pkg/controller/translator/translator_test.go
=> add unit test for GetZoneForNode helper func

README.md
=> Add link to OSS Ingress docs in README.md

pkg/controller/translator/translator.go
Cherrypick #576 into 1.4 release
=> do not use condition predicate while getting zone for node

pkg/controller/controller.go, pkg/controller/controller_test.go
=> Cherry-picking #547 onto 1.4 branch

pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/controller/types.go, pkg/utils/finalizer.go
=> Cherry-pick #613 onto 1.4, part 1

README.md
=> Update GKE version mapping in README

cmd/glbc/main.go
=> Cherrypick #623 on 1.4 branch

pkg/utils/namer.go, pkg/utils/namer_test.go
=> Cherrypick #650 into release 1.5 branch

deploy/glbc/yaml/glbc.yaml
=> Update glbc.yaml with latest minor release tag

pkg/controller/translator/translator.go
=> Cherrypick #576 into release 1.4 branch

CONTRIBUTING.md
Previous links pointed to old repo.
=> Update CONTRIBUTING.md with up-to-date links

cmd/glbc/main.go, pkg/flags/flags.go
=> More cleanup of unused flags

pkg/loadbalancers/l7s_test.go, pkg/utils/namer.go
=> Cherry pick #688 into release.15

cmd/glbc/main.go, pkg/flags/flags.go
=> Completely remove EnableBackendConfig flag

cmd/e2e-test/basic_test.go, pkg/e2e/fixtures.go, pkg/fuzz/features/static_ip.go, pkg/fuzz/helpers.go
Porting from k/k. Note the PR to remove the tests in k/k is https://github.com/kubernetes/kubernetes/pull/75892
Ref: #667
=> Static IP E2E test

cmd/e2e-test/basic_test.go, pkg/e2e/fixtures.go, pkg/fuzz/features/static_ip.go
Followup to #705 
/hold until I verify the test also fully passes.
=> Make sure static-ip validator is not run if annotation is empty + clean up addresses after test

docs/contrib/dev-setup.md
=> Update contributor docs to reference k/k Github workflow

CHANGELOG.md, README.md
=> Update CHANGELOG.md and version mapping for v1.5.1 release

pkg/neg/controller_test.go, pkg/neg/types/types.go, pkg/neg/types/types_test.go
follow up of #720
No functional change. harden unit testing
=> harden NegStaus unit testing with ParseNegStatus

pkg/fuzz/features/neg.go
Modify the neg feature validator to check if at least one URLmap is targetting the NEG/IG backend service. This is to guarantee that the correct backend service is fully configured with URLMap. This prevents flaky test when new Backend service is created but the old backend service is still hooked with existing URLmap. Hence making test cases validating white box configurations to fail every now and then. 
@spencerhance
=> check if at least one URLmap is targetting the backend service in NEG feature validator

pkg/fuzz/features/neg.go
=> Fix url map -> backend service link check in neg validator

pkg/annotations/service.go, pkg/annotations/service_test.go, pkg/neg/controller.go, pkg/neg/controller_test.go, pkg/neg/types/types.go, pkg/neg/types/types_test.go
This aims to make it easier to vendor pkg/annotations from a different repo
=> move NegStatus from pkg/neg to pkg/annotations

pkg/neg/syncers/transaction.go, pkg/neg/syncers/transaction_table.go, pkg/neg/syncers/transaction_table_test.go, pkg/neg/syncers/transaction_test.go
Follow up of: https://github.com/kubernetes/ingress-gce/pull/734
Only the last commit is more stuff than #734
=> Use transactionTable via Interface

pkg/tls/tls.go
=> Cherrypick #728 onto 1.5 branch. 

docs/deploy/resources/rbac.yaml
This work came out of https://github.com/kubernetes/kubernetes/pull/77140
/assign rramkumar1
=> Update canonical rbac.yaml with latest, minimal bindings

pkg/loadbalancers/l7.go
This will allow users to properly debug when we cannot setup frontend resources for them. Before this, the user would be blind as to why those resources were not setup.
=> Emit event if Ingress spec does not contain valid config to setup frontend resources

cmd/e2e-test/draining_test.go
=> bump draining poll timeout to reduce flakes

pkg/context/context.go
Fix controller panic caused by https://github.com/kubernetes/ingress-gce/pull/806
=> fix panic caused by the ingress api migration

docs/faq/gce.md
=> Update gce.md with links that don't return 404

cmd/e2e-test/neg_test.go
=> add namespace in the ingress builder

cmd/glbc/app/init.go, cmd/glbc/main.go, pkg/context/context.go, pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/controller/translator/translator.go, pkg/controller/translator/translator_test.go, pkg/controller/utils.go, pkg/firewalls/controller.go, pkg/firewalls/controller_test.go, pkg/neg/controller.go, pkg/neg/controller_test.go, pkg/neg/manager_test.go, pkg/neg/syncers/batch_test.go, pkg/neg/syncers/syncer_test.go, pkg/neg/syncers/transaction_test.go
L7-ILB needs to use a NEG for the default backend instead of an IG
=> NEG support default backend for L7-ILB

cmd/e2e-test/neg_test.go, pkg/e2e/fixtures.go
=> try to spread the pods across zone to avoid test timeout

cmd/e2e-test/ilb_test.go
=> Remove word 'Basic' from ILB e2e test

cmd/glbc/app/clients.go
=> Use protobufs for communication with apiserver

pkg/neg/readiness/reflector.go, pkg/neg/readiness/reflector_test.go
=> Cherrypick #834 into release 1.6

pkg/firewalls/controller.go, pkg/firewalls/firewalls.go, pkg/firewalls/firewalls_test.go
=> Cherry pick #851

cmd/e2e-test/basic_https_test.go, cmd/e2e-test/ilb_test.go, pkg/e2e/cert.go
Also add support for regional ssl certs in the e2e framework
=> Add more e2e tests for L7-ILB

LIMITATIONS.md, README.md, docs/faq/gce.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubernetes/ingress-gce/862)
=> Some documentation fixes to reflect current state of world

pkg/loadbalancers/features/l7ilb.go
Update List Subnets call to Beta since it now supports L7-ILB fields
This should also be cherry-picked to 1.7 branch for 1.7.1
=> Update list subnets call to Beta for L7-ILB

cmd/glbc/app/clients.go
Cherrypick of #847
/assign @bowei @freehan
=>  Cherrypick to 1.7 branch: Use protobufs for communication with apiserver

cmd/e2e-test/ilb_test.go, pkg/e2e/fixtures.go
Update subnet to /24 instead of /22
Add retry logic for 10 different possible subnets
=> Fix CreateILBSubnet() logic in e2e tests

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubernetes/ingress-gce/888)
=> Update version mapping in README

pkg/loadbalancers/features/l7ilb.go
Cherry pick #895 [Fix ILB subnet discovery to check for VPC as well] into release-1.7
=> Cherry pick #895 into 1 7

pkg/loadbalancers/features/l7ilb.go
=> Cherry Pick #869 [Update list subnets call to Beta for L7-ILB] to release-1.7

pkg/neg/controller.go
#900 [enqueue default backend for NEG processing]
=> Cherry pick #900 into release-1.7

pkg/backends/backends.go
ref: https://github.com/kubernetes/ingress-gce/issues/35
=> iterate more than one backend for backend service status

cmd/e2e-test/timeout_test.go
=> Add e2e test for connection timeout with l7-ilb

cmd/e2e-test/affinity_test.go, pkg/fuzz/features/affinity.go
=> Add session affinity e2e tests for l7-ilb

pkg/loadbalancers/l7s.go
=> Fix return value

pkg/loadbalancers/l7s.go
Cherrypick https://github.com/kubernetes/ingress-gce/pull/946 [Fix return value] into release-1.7
=> Cherrypick #946 into Release 1.7

cmd/glbc/main.go, pkg/controller/controller.go, pkg/sync/sync.go, pkg/utils/common/finalizer.go
=> Cherrypick #948[Fix naming scheme on creation] into release 1.8

cmd/e2e-test/upgrade/basic_http.go
Introduced in https://github.com/kubernetes/ingress-gce/pull/951
=> Bugfix: Fix service name in upgrade test

cmd/e2e-test/upgrade/basic_http.go
The upgrade test is failing with the following error:
`
basic_http.go:106: error updating Ingress test-sandbox-f00f98973031357/ing1: Operation cannot be fulfilled on ingresses.networking.k8s.io "ing1": the object has been modified; please apply your changes to the latest version and try again
`
Ingress upgrade is failing if we pass in ingress returned by k8s API server to CRUD framework. 
This PR updates ingress object passed to PostUpgrade step, back to ingress generated by `IngressBuilder`.
=> Bugfix: Fix ingress passed to postUpgrade

cmd/glbc/app/init.go, pkg/context/context.go
=> Cherry pick #961 [Fix default backend port bug for neg ilb] into release-1.8

pkg/e2e/helpers.go
wait.Poll condition func should log error but not return error.
=> Fix e2e helper: WaitForNegs

pkg/composite/gen.go, pkg/composite/gen/main.go
https://github.com/kubernetes/ingress-gce/pull/987 fixed this for Create, Delete, Update but missed the Get API.
Fixing it here.
@spencerhance 
=> Fix the 'Get' & 'List' Composite API to call the underlying Regional service API 

pkg/metrics/metrics.go
=> Register NEG usage metrics

pkg/loadbalancers/forwarding_rules.go
Fixes https://github.com/kubernetes/ingress-gce/issues/993
=> Bugfix: Use Static IP to create forwarding rule when available

cmd/e2e-test/asm_test.go, cmd/e2e-test/main_test.go, pkg/e2e/framework.go, pkg/e2e/sandbox.go
The test will test if Istio:DestinationRule CRD exist.
=> Remove enable-istio flag for e2e test.

pkg/composite/composite.go
Depends on https://github.com/kubernetes/ingress-gce/pull/1017
=> Add SetSslPolicyForTargetHttpsProxy() to composite

pkg/composite/gen.go, pkg/composite/gen/main.go, pkg/composite/gen_test.go, pkg/composite/meta/meta.go, pkg/healthchecks/healthchecks.go, pkg/neg/types/mock.go
Make conversion to composite type safe to avoid silent bugs.
=> Typesafe composite conversion

pkg/backends/syncer.go, pkg/backends/syncer_test.go, pkg/healthchecks/healthchecks.go, pkg/healthchecks/healthchecks_test.go
Towards reducing the surface area around healthchecks
=> Move apply probe to healthchecks package

cmd/e2e-test/affinity_test.go, cmd/e2e-test/backend_config_test.go, cmd/e2e-test/cdn_test.go, cmd/e2e-test/customrequestheaders_test.go, cmd/e2e-test/draining_test.go, cmd/e2e-test/iap_test.go, cmd/e2e-test/security_policy_test.go, cmd/e2e-test/timeout_test.go
=> Fix backendconfig annotation key for beta

cmd/e2e-test/basic_test.go, pkg/e2e/helpers.go, pkg/fuzz/validator.go
=> Bugfix: Fix frontend resource deletion test 

pkg/flags/flags.go, pkg/healthchecks/healthchecks.go, pkg/healthchecks/healthchecks_test.go
-enable-backendconfig-healthcheck will enable the backendconfig healthcheck feature
=> Add feature flag `EnableBackendConfigHealthCheck`

cmd/glbc/app/clients.go, cmd/glbc/main.go, pkg/controller/controller.go
https://github.com/kubernetes/ingress-gce/issues/1049
=> Cherrypick #1051[Fix kube-config for CRD informers] into release-1.8

cmd/glbc/app/clients.go, cmd/glbc/main.go, pkg/controller/controller.go
https://github.com/kubernetes/ingress-gce/issues/1049
=> Cherrypick #1051[Fix kube-config for CRD informers] into release-1.7

pkg/e2e/helpers.go
=> Increase GCLB deletion timeout

pkg/e2e/helpers.go
=> Increase GLBC timeout to 60 minutes

CONTRIBUTING.md
=> trivial: fixed broken link in Markdown

pkg/backends/backends.go
Cherry pick of #1062 to the 1.9 branch
=> Cherry Pick #1062 to Release 1.9 [Update BackendConfig LoadBalancingScheme for L7-ILB to INTERNAL_MANAGED]

pkg/apis/frontendconfig/v1beta1/types.go, pkg/apis/frontendconfig/v1beta1/zz_generated.openapi.go
=> Cherry-pick #1082 to release-1.9 [Update FrontendConfig v1beta1 API so that Spec and Status fields are omitempty]

pkg/backendconfig/backendconfig.go, pkg/crd/crd.go
/assign @rramkumar1 
fixes #1055
=> Enable pruning of unknown fields for CRDs

pkg/crd/crd_test.go
=> Add test for pruning unknown fields of CRDs

pkg/e2e/framework.go, pkg/e2e/helpers.go
=> Wait for backendconfig CRD to be established

cmd/e2e-test/sslpolicy_test.go, pkg/e2e/framework.go, pkg/fuzz/helpers.go, pkg/loadbalancers/target_proxies.go
Also includes some frontendconfig helpers for e2e tests
=> e2e tests for SslPolicy

pkg/controller/node.go, pkg/instances/instances.go
=> Cherry Pick #1107 [Wait for caches to sync before running node sync] to release-1.9

pkg/backends/features/logging.go, pkg/composite/gen.go, pkg/composite/gen/main.go
=> Cherrpick #1119 [Force send Enable field for LogConfig] into release-1.9

pkg/utils/common/finalizer.go
=> Use patch for updating ingress/service finalizers

hack/run-local-glbc.sh
ref: https://github.com/kubernetes/ingress-gce/pull/1101
/assign @bowei
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubernetes/ingress-gce/1124)
=> Add back local run script which was deleted

pkg/fuzz/gcp.go
Fix a e2e test failure when NEG defaulting is enabled.
=> Wait for NEGs deletion based on deletion option

README.md
Hide the link at the bottom of README, which leads to a 404 page
=> Commented out broken link

docs/faq/README.md
Signed-off-by: knrt10 <tripathi.kautilya@gmail.com>
=> Fix broken link in faq

pkg/controller/node.go, pkg/instances/instances.go
There can be a race condition where the queue somehow triggers
before the caches are able to sync.
Improve logging around the event for better debugging in the future.
=> Cherrypick: Wait for caches to sync before running node sync

pkg/neg/syncers/transaction.go
Cherrypick of https://github.com/kubernetes/ingress-gce/pull/1192
=> Handle error when calculating endpoints for NEG.

cmd/e2e-test/sslpolicy_test.go, pkg/apis/frontendconfig/v1beta1/zz_generated.openapi.go, pkg/frontendconfig/client/clientset/versioned/clientset.go, pkg/frontendconfig/client/clientset/versioned/typed/frontendconfig/v1beta1/fake/fake_frontendconfig.go, pkg/frontendconfig/client/clientset/versioned/typed/frontendconfig/v1beta1/frontendconfig.go, pkg/frontendconfig/client/informers/externalversions/frontendconfig/v1beta1/frontendconfig.go
Makes the client methods compatible with k8s v1.18
=> Update generated code for frontendconfig CRD

pkg/svcneg/svcneg.go
=> Cherry pick #1212 [Fix negv1beta1 import]

cmd/e2e-test/healthcheck_test.go, pkg/firewalls/controller.go, pkg/firewalls/controller_test.go, pkg/firewalls/firewalls_test.go, pkg/utils/utils.go
Fixes the issue where custom health check ports are not exposed via the firewall
=> Expose custom health check ports in the firewall

cmd/e2e-test/asm_test.go, pkg/e2e/helpers.go
This should reduce ASM test failures and make them easier to debug
=> Increase NEG Poll Timeout and use subtests in ASM tests

cmd/e2e-test/asm_test.go
=> fix TestASM test flakes

pkg/flags/flags.go
=> Cherry Pick #1230 [Enable neg crd by default]

cmd/e2e-test/basic_test.go, cmd/e2e-test/ilb_test.go, pkg/e2e/fixtures.go, pkg/fuzz/helpers.go
=> Add e2e test for internal static IP

pkg/metrics/features.go, pkg/metrics/metrics_test.go
This will need to be cherry-picked to release-1.10
=> Add HTTPS Redirects to Metrics

pkg/controller/controller.go, pkg/metrics/features.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, pkg/metrics/types.go
=> Cherry-pick #1233 [Add missing features to ingress metrics] into release-1-10

pkg/metrics/features.go, pkg/metrics/metrics_test.go
=> Cherry-pick #1239 [Add HTTPS Redirects to Metrics] into release-1-10

pkg/loadbalancers/forwarding_rules.go, pkg/loadbalancers/l4.go
=> Cherrypick PR 1241(Lookup forwarding rule before deletion on protocol change) into release-1.10

pkg/annotations/service.go, pkg/annotations/service_test.go, pkg/l4/l4controller.go, pkg/l4/l4controller_test.go, pkg/loadbalancers/l4.go, pkg/loadbalancers/l4_test.go, pkg/utils/patch.go, pkg/utils/utils.go
=> cherrypick PR 1236(resource annotations for ILB) into release-1.10

pkg/loadbalancers/url_maps.go
- Fix bug where v1 namer is used and empty string ends up in the get call
- Remove get call unless feature is enabled
(running e2e test)
/hold
cc: @skmatti 
=> Update ensureRedirectUrlMap() logic

pkg/loadbalancers/url_maps.go
=> Cherry-pick #1227 [Update ensureRedirectUrlMap() logic] into release-1.10

pkg/context/context.go, pkg/healthchecks/healthchecks_l4.go, pkg/l4/l4controller.go, pkg/l4/l4controller_test.go, pkg/loadbalancers/l4.go, pkg/loadbalancers/l4_test.go, pkg/neg/controller.go, pkg/neg/controller_test.go, pkg/neg/types/interfaces.go, pkg/neg/types/types.go, pkg/neg/types/types_test.go, pkg/test/utils.go, pkg/utils/namer/interfaces.go, pkg/utils/namer/l4_namer.go, pkg/utils/namer/l4_namer_test.go, pkg/utils/namer/namer.go, pkg/utils/serviceport.go
Cherrypick https://github.com/kubernetes/ingress-gce/pull/1254 into release-1.10
=> Cherrypick of L4 V2 Namer PR - 1254

cmd/e2e-test/ilb_test.go, pkg/e2e/cert.go
Removes hardcoded region and updates API to GA
=> Fix Pre-shared Cert Region for ILB HTTPS Tests

CHANGELOG.md, README.md
- Updates changelog up to v1.10.3
- Updates version mapping up to v1.9.9
Issue: #1216
We will have to update the releases page as well
=> Update version mapping and Changelog

pkg/neg/manager.go, pkg/neg/manager_test.go, pkg/neg/types/types.go
Cherry pick fix #1264 
Ensures neg crs on all desired ports
=> Cherry Pick #1264 [Ensure neg cr cherry pick]

pkg/e2e/cert.go
Previously Regional Certs were not getting deleted.
=> Fix SSL Certs Leak in ILB Tests

pkg/annotations/ingress.go, pkg/controller/controller.go, pkg/loadbalancers/interfaces.go, pkg/loadbalancers/l7s.go, pkg/loadbalancers/l7s_test.go, pkg/loadbalancers/loadbalancers_test.go, pkg/sync/interfaces.go, pkg/sync/sync.go, pkg/utils/utils.go
=> Cherry-pick #1259 [Fix GC for switching between LB Scopes on Namer V2] into release-1-9

pkg/annotations/ingress.go, pkg/controller/controller.go, pkg/loadbalancers/interfaces.go, pkg/loadbalancers/l7s.go, pkg/loadbalancers/l7s_test.go, pkg/loadbalancers/loadbalancers_test.go, pkg/loadbalancers/url_maps.go, pkg/sync/interfaces.go, pkg/sync/sync.go, pkg/utils/utils.go
=> Cherry-pick #1259 [Fix GC for switching between LB Scopes on Namer V2] into release-1-10

pkg/neg/metrics/metrics.go
=> Cherry Pick #1280 [Change neg metric name]

pkg/controller/controller.go
There is a race condition in the controller that causes
the user defined annotations to get overwritten in some
edge cases. The controller retrives the ingress resource at https://github.com/kubernetes/ingress-gce/blob/d9a00eafd11df479ded327c697241971e57b691e/pkg/controller/controller.go#L637
and updates the annotations at
https://github.com/kubernetes/ingress-gce/blob/d9a00eafd11df479ded327c697241971e57b691e/pkg/controller/controller.go#L728.
All the user updated annotations during this time period
will be lost.
=> Improve the logic that updates ingress resource annotations

pkg/loadbalancers/certificates.go, pkg/loadbalancers/loadbalancers_test.go, pkg/translator/translator.go, pkg/translator/translator_test.go
=> Refactor SSLCertificates into Translator Package

pkg/controller/controller.go
There is a race condition in the controller that causes
the user defined annotations to get overwritten in some
edge cases. The controller retrives the ingress resource at https://github.com/kubernetes/ingress-gce/blob/d9a00eafd11df479ded327c697241971e57b691e/pkg/controller/controller.go#L637
and updates the annotations at
https://github.com/kubernetes/ingress-gce/blob/d9a00eafd11df479ded327c697241971e57b691e/pkg/controller/controller.go#L728.
All the user updated annotations during this time period
will be lost.
=> Cherrypick #1282[Improve ingress resource annotations update logic] into release-1.10

pkg/healthchecks/healthchecks_test.go
=> Add tests for regional health check deletions

pkg/composite/composite.go
=> Cherry-pick #1293 [Fix bug in composite funcs without full regional support] into release-1.9

pkg/composite/composite.go
=> Cherry-pick #1293 into release-1-10

pkg/neg/manager.go
=> add logging in NEG GC

pkg/neg/manager.go
=> Cherry-pick #1297 into release-1-10

pkg/neg/manager.go, pkg/neg/manager_test.go, pkg/neg/syncers/transaction.go, pkg/neg/syncers/utils.go, pkg/neg/syncers/utils_test.go, pkg/neg/types/cloudprovideradapter.go, pkg/utils/negdescription.go, pkg/utils/negdescription_test.go
Cherrypick #1303 to release 1.10 branch
=> Cherrypick #1303 [Mitigate NEG GC Race and add Logging] to release 1.10

pkg/utils/utils.go, pkg/utils/utils_test.go
- if annotation is present, controller will manage the ingress
cc/ @spencerhance
=> Ignore Ingresses that have spec.ingressClassName

Dockerfile.404-server-with-metrics, cmd/404-server-with-metrics/prometheus.yml, cmd/404-server-with-metrics/server-with-metrics.go
/assign @rramkumar1 
cc: @vbannai 
Cherry-picking so this can be included in the next tag and pushed to k8s.gcr.io
=> Cherry-pick #1312 [This PR fixes the /metrics from being exposed to the Internet...] into release-1-10

pkg/loadbalancers/forwarding_rules.go
related to https://github.com/kubernetes/kubernetes/issues/96513
The ILB code in this repo does not have the same issue, but it would be good to log the diff anyway.
@freehan @skmatti
=> Log the Forwarding rule diff in L4 ILB.

pkg/loadbalancers/forwarding_rules.go
Cherrypick of https://github.com/kubernetes/ingress-gce/pull/1321 into 1.10
=> Add logs to include what changed in a forwarding rule.

cmd/glbc/main.go, pkg/neg/controller.go, pkg/neg/controller_test.go, pkg/neg/manager.go, pkg/neg/manager_test.go
I will push separate PRs for different flags.
=> remove EnableNonGCPMode flag from NEG controller

cmd/glbc/main.go, pkg/context/context.go, pkg/flags/flags.go, pkg/neg/controller.go, pkg/neg/controller_test.go, pkg/neg/syncers/transaction_test.go, pkg/neg/syncers/utils.go, pkg/neg/syncers/utils_test.go
=> remove EnableNegCrd flag

cmd/glbc/main.go, pkg/flags/flags.go, pkg/serviceattachment/serviceattachment.go
- Add enable-psc flag
- Add ServiceAttachment CRD Meta
=> Ensure ServiceAttachment CRD when PSC is enabled

pkg/backends/features/features.go, pkg/neg/types/mock.go, pkg/neg/types/types.go
Removed unused alpha mocks for NEGs.
=> Switch to using beta neg API for VM_IP_NEGs.

pkg/backends/features/features.go, pkg/neg/types/mock.go, pkg/neg/types/types.go
Cherrypick of https://github.com/kubernetes/ingress-gce/pull/1333
=> Switch to using beta API for VM_IP_NEGs.

pkg/l4/l4controller.go, pkg/l4/l4controller_test.go, pkg/metrics/metrics.go, pkg/test/utils.go
=> Add a new metric for L4 ILB Sync latency

pkg/l4/l4controller.go, pkg/l4/l4controller_test.go, pkg/metrics/metrics.go, pkg/test/utils.go
Cherrypick of https://github.com/kubernetes/ingress-gce/pull/1338
=> Cherrypick ILB latency metric addition into 1.10

go.mod, vendor/modules.txt
Similar to https://github.com/kubernetes/ingress-gce/pull/1346
@swetharepakula
=> Autogenerated output of `go mod vendor`

cmd/e2e-test/neg_test.go, pkg/e2e/helpers.go
* Due to multiple versions of error, check for one of the possible
error messages
=> Check for new error msg in TestNegCRDErrorEvents

README.md
trivial, update version mapping
=> Readme: update version mapping

pkg/l4/l4controller.go
=> Check L4 ILB controller health - cherrypick of https://github.com/kubernetes/ingress-gce/pull/1355

pkg/annotations/service.go, pkg/l4/l4controller_test.go, pkg/loadbalancers/l4.go, pkg/loadbalancers/l4_test.go, pkg/utils/namer/l4_namer.go, pkg/utils/namer/l4_namer_test.go
=> Create a unique name for healthcheck firewall rule - Cherrypick of https://github.com/kubernetes/ingress-gce/pull/1356

pkg/neg/controller.go
Add CRD schemes so that event recorder can use them
=> Crd events

pkg/neg/controller.go
- sharing `scheme.Scheme` can cause concurrency issues
=> Initialize a scheme specific for neg controller

pkg/neg/manager.go, pkg/neg/manager_test.go
* if GC encounters a 401 error when querying for a NEG, treat as if NEG
was never created
=> Ignore 401 Bad request errors during NEG GC

pkg/neg/controller.go
- Initialize a scheme specific for neg controller since
sharing `scheme.Scheme` can cause concurrency issues
=> Cherrypick #1362 & #1361 Add NEG CRD scheme to event recorder

cmd/glbc/main.go, pkg/context/context.go, pkg/controller/controller_test.go, pkg/controller/translator/translator_test.go, pkg/firewalls/controller_test.go, pkg/l4/l4controller_test.go, pkg/psc/controller.go, pkg/psc/controller_test.go
ProcessServiceAttachment handles service attachment creations and updates.
=> Service Attachment Creations and Update

pkg/context/context.go, pkg/psc/controller.go, pkg/psc/controller_test.go
- Add event scheme to event recorders
=> Service Attachment Garbage Collection

cmd/glbc/main.go, pkg/context/context.go, pkg/psc/controller.go
=> Run PSC Controller when enabled

cmd/e2e-test/psc_test.go, pkg/e2e/fixtures.go, pkg/e2e/framework.go, pkg/e2e/helpers.go, pkg/fuzz/gcp.go
=> PSC Lifecycle E2E Test

pkg/backends/features/features.go, pkg/backends/features/features_test.go, pkg/backends/features/securitypolicy.go, pkg/backends/features/securitypolicy_test.go, pkg/backends/syncer.go, pkg/composite/composite.go
=> Graduate Cloud Armor security policy to GA

pkg/backends/features/features.go, pkg/neg/syncers/syncer_test.go, pkg/neg/syncers/transaction_test.go, pkg/neg/types/mock.go, pkg/neg/types/types.go
=> Switch to using GA API for VM_IP NEGs.

cmd/glbc/main.go, pkg/controller/translator/translator.go, pkg/controller/translator/translator_test.go, pkg/flags/flags.go
- If disabled, only support ImplementationSpecific path type
- If disabled, do not ensure GCPIngressParams CRD
=> Feature Gate Ingress GA features

cmd/glbc/main.go, pkg/backends/backends.go, pkg/context/context.go, pkg/firewalls/firewalls_l4.go, pkg/flags/flags.go, pkg/healthchecks/healthchecks_l4.go, pkg/l4/l4controller.go, pkg/l4/l4controller_test.go, pkg/loadbalancers/forwarding_rules.go, pkg/loadbalancers/l4.go, pkg/loadbalancers/l4_test.go, pkg/utils/taskqueue.go, pkg/utils/taskqueue_test.go, pkg/utils/utils.go
Also modified L4 Firewall rule logic to only set a description if needed. 
@swetharepakula
=> Run multiple worker routines for L4 Services.

pkg/l4/l4controller_test.go
The current timeout causes flakes, especially on prow.
/assign @swetharepakula @freehan
=> Increase timeout for l4 controller test.

pkg/neg/metrics/metrics.go
Cherrypick #1417 into `release-1.10`
=> CherryPick #1417 Fix Neg Metric Buckets

pkg/neg/metrics/metrics.go
Cherrypick #1417 into release-1.11
=> Cherrypick #1447 Neg metrics into release 1.11

pkg/neg/syncers/transaction.go
* Ensures that initialization is calculated correctly when the condition is created.
=> Return expectedCondition so timestamp is populated

pkg/neg/syncers/transaction.go
=> [Cherrypick #1423] Fix Neg Init metrics into release 1.10

pkg/neg/syncers/transaction.go
=> [Cherrypick #1423] Fix Neg Init metrics into release 1.11

pkg/neg/syncers/transaction.go
This PR aims to improve NEG syncer performance at scale. 
It just reverse the order between Getting Existing Endpoints in NEG and wanted Endpoints. This is to prevent rate limiting on ListNetworkEndpoint calls would make NEG syncer sync older wanted Endpoints. This would make sure more Endpoint updates get reflected even rate limiting is throttling ListNE API
=> retrieve NEG endpoints before getting the wanted Endpoints

pkg/metrics/features.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, pkg/psc/controller.go, pkg/psc/metrics/metrics.go, pkg/psc/metrics/types.go
Cherrypick #1434 into release 1.11
=> [Cherrypick #1434] PSC Usage and Internal Metrics to 1.11

pkg/metrics/features.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, pkg/psc/controller.go, pkg/psc/metrics/metrics.go, pkg/psc/metrics/types.go
Cherrypick #1434 into release 1.12
=> [Cherrypick #1434] PSC Usage and Internal Metrics to 1.12

pkg/annotations/service.go, pkg/l4/l4controller.go, pkg/l4/l4controller_test.go, pkg/l4/metrics/metrics.go, pkg/loadbalancers/l4.go, pkg/loadbalancers/l4_test.go, pkg/metrics/metrics.go, pkg/test/utils.go, pkg/utils/utils.go, pkg/utils/utils_test.go
=> Cherrypick PR#1436 - Add a new L4 ILB metric for sync errors.

pkg/l4/l4controller.go, pkg/loadbalancers/forwarding_rules.go
=> Fix log message/comment.

pkg/l4/l4controller.go, pkg/loadbalancers/forwarding_rules.go
Original PR - https://github.com/kubernetes/ingress-gce/pull/1444
=> Cherrypick of log fix

pkg/apis/serviceattachment/v1alpha1/types.go, pkg/apis/serviceattachment/v1alpha1/zz_generated.openapi.go
=> Add lastSyncTimestamp json tag

pkg/neg/controller.go
* catches cleanup required when ingress class changes
=> Process service if old ingress class was glbc

pkg/l4/l4controller.go
This avoids a race condition where the service status could be cleared during a type change from Internal to External Loadbalancer.
=> Switch the order of L4 service status reset and annotations reset.

pkg/context/context.go
=> [Cherrypick #1458 into release-1.11]stop periodic resync on endpoints object

OWNERS
=> Add prameshj and swetharepakula into the OWNER file

pkg/context/context.go
=> [Cherrypick #1458 into release-1.12] stop periodic resync on endpoints object

pkg/psc/controller.go
* ignores the controller made updates to service attachments
=> Do not process status only updates

pkg/psc/controller.go, pkg/psc/controller_test.go
* process spec and periodic enqueues of service attachments
* ignores the controller made updates to service attachments
* ignores updates made after ServiceAttachment CR has already been deleted
=> fix should process conditions

pkg/neg/controller.go
=> Convert old ingress properly

pkg/e2e/helpers.go, pkg/fuzz/gcp.go, pkg/psc/controller.go, pkg/psc/controller_test.go
=> Use PSC Beta APIs

pkg/annotations/service.go, pkg/l4/l4controller.go, pkg/l4/l4controller_test.go, pkg/l4/metrics/metrics.go, pkg/loadbalancers/l4.go, pkg/loadbalancers/l4_test.go, pkg/metrics/metrics.go, pkg/test/utils.go, pkg/utils/utils.go, pkg/utils/utils_test.go
Cherrypick of https://github.com/kubernetes/ingress-gce/pull/1436/
It was previously cherry-picked only into 1.11.
/assign @swetharepakula @freehan
=> ILB metrics cherrypick into 1.12

build/rules.mk
Existing make rules pushes `$(REGISTRY)/$(CONTAINER_PREFIX)-$(BINARY)-$(ARCH)` images, e.g., `k8s.gcr.io/ingress-gce-glbc-amd64` and `k8s.gcr.io/ingress-gce-glbc-arm64`. The change in addition pushes `$(REGISTRY)/$(CONTAINER_PREFIX)-$(BINARY)` image, which is a multiarch image (Docker manifest list) that references per-arch images, e.g., `k8s.gcr.io/ingress-gce-glbc`. 
This change is backwards compatible: consumers can continue to use `k8s.gcr.io/ingress-gce-glbc-amd64`, but they are recommended to use `k8s.gcr.io/ingress-gce-glbc` which works transparently for different host architectures. 
**Example Images**
* multiarch image: `docker pull congliu01/ingress-gce-glbc:v1.12.0-54-g66e35535-dirty`
* arm64 image: `docker pull congliu01/ingress-gce-glbc-arm64:v1.12.0-54-g66e35535-dirty`
* …
=> Add push-multiarch rule to push multiarch images (docker manifest list)

pkg/l4/l4controller.go, pkg/loadbalancers/forwarding_rules.go
Cherrypick of https://github.com/kubernetes/ingress-gce/pull/1444
=> Log fix cherrypick into 1.12

pkg/l4/l4controller.go
Cherrypick of https://github.com/kubernetes/ingress-gce/pull/1454/
=> Cherrypick L4 status/annotation reset order change into 1.12

pkg/metrics/features.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, pkg/psc/controller.go, pkg/psc/metrics/types.go
* ensure err is reused in processServiceAttachment for more accurate
ServiceAttachment error state metrics
=> Emit total number of services metrics

pkg/flags/flags.go, pkg/ratelimit/ratelimit.go, pkg/ratelimit/ratelimit_test.go
Allows global scaling of all rate limits via command line flags
=> Add rate limiting scaling parameter

pkg/psc/controller.go, pkg/psc/controller_test.go
* ProducerForwardingRule -> TargetService
* ConsumerForwardingRules -> ConnectedEndpoints
* ConsumerForwardingRule.ForwardingRule -> ConnectedEndpoint.Endpoint
For reference: PSC API [changes](https://cloud.google.com/vpc/docs/configure-private-service-connect-producer#api-changes)
=> Use the new ServiceAttachment fields over deprecated ones

pkg/psc/controller.go
* log lines should use '%s' or '%q'
=> Wrap errors using '%w' in the format strings

pkg/controller/controller.go, pkg/flags/flags.go
=> Cherry-pick #1492 [Update Ingress Sync Queue to use multiple workers] into release-1-12

pkg/controller/controller.go, pkg/flags/flags.go
=> Cherry-pick #1492 [Update Ingress Sync Queue to use multiple workers] into release-1-11

pkg/psc/controller.go, pkg/psc/controller_test.go
The following errors will not be counted as failed syncs for PSC metrics:
* GCE Resource Not Found
* GCE Bad Gateway
* Service Not Found in Store
* FwdRule IP does not match Service
/assign @prameshj @freehan
=> Filter errors when marking sync failures for metrics

pkg/psc/controller.go, pkg/psc/controller_test.go
Adds Accept And Reject lists to the Service Attachment spec
/assign @prameshj @freehan
=> Process Accept and Reject lists for ServiceAttachment

pkg/context/context.go, pkg/flags/flags.go, pkg/psc/controller.go, pkg/psc/controller_test.go, pkg/utils/descutils/utils.go, pkg/utils/descutils/utils_test.go, pkg/utils/serviceattachment/svcattachmentdesc.go, pkg/utils/serviceattachment/svcattachmentdesc_test.go
GCE ServiceAttachment description will have a link to the cluster and a link to the K8s Service Attachment CR
=> Add standard k8s resource description for ServiceAttachments

pkg/psc/controller.go
=> Emit success event after Service Attachment creation

pkg/psc/controller.go, pkg/psc/controller_test.go
* all validation will be left to the GCE Service Attachment API
=> Process updates to ServiceAttachment spec

pkg/controller/controller.go
=> Add debug GC log lines during Ingress sync

pkg/controller/controller.go
Cherrypick of #1509 into release-1.13
/assign @prameshj 
/cc @freehan
=> [Cherrypick #1509] Add debug GC log lines during Ingress sync

pkg/controller/controller.go
Cherrypick #1511 into release-1.13
=> [Cherrpick #1511] Add lock to GC into release-1.13

pkg/neg/controller.go, pkg/neg/controller_test.go, pkg/neg/syncers/endpoints_calculator.go, pkg/neg/syncers/subsets.go
Cherrypick of https://github.com/kubernetes/ingress-gce/pull/1517
=> [1.13] Enqueue Node updates to VM_IP_NEG controller

pkg/neg/controller_test.go
=> Add comment to ILB nodes test, remove extra sleep.

pkg/neg/controller.go, pkg/neg/controller_test.go, pkg/neg/syncers/endpoints_calculator.go, pkg/neg/syncers/subsets.go
=> [1.11] Enqueue Node updates to VM_IP_NEG controller

pkg/neg/controller.go, pkg/neg/controller_test.go, pkg/neg/syncers/endpoints_calculator.go, pkg/neg/syncers/subsets.go
Cherrypick of https://github.com/kubernetes/ingress-gce/pull/1517 into 1.12
=> [1.12] Enqueue Node updates to VM_IP_NEG controller.

pkg/loadbalancers/l7.go, pkg/loadbalancers/loadbalancers_test.go, pkg/utils/utils_test.go
Fix the error message for when HTTP and HTTPS are both disabled
=> Fix err msg

pkg/instances/instances.go
Cherry-pick of #1524 into release-1.13
=> [Cherrypick #1524] Instance url fix remove 1.13

pkg/utils/utils.go
Cherrypick of https://github.com/kubernetes/ingress-gce/pull/1523
=> [1.13] Updated the value of LabelNodeRoleExcludeBalancer to the V1 string

hack/run-local-glbc.sh, pkg/backends/neg_linker.go, pkg/backends/neg_linker_test.go
This handles the case where the user updates their Service definition.
=> Update Backends if the settings change w/ same Backends

cmd/glbc/app/init.go
Check for v1 IngressClass resource instead of v1beta1.
=> Check for v1 IngressClass resource

pkg/utils/utils.go, pkg/utils/utils_test.go
Cherrypick of https://github.com/kubernetes/ingress-gce/pull/1537
=> [1.13]  Allow Unschedulable nodes to be part of the LB backends list

pkg/controller/translator/translator.go, pkg/controller/translator/translator_test.go
=> [Cherrypick #1538] Always enable pathtype into release 1.13

cmd/glbc/app/init.go
=> [Cherrypick #1536] Check for v1 IngressClass resource into release-1.13

pkg/neg/readiness/poller.go, pkg/neg/readiness/poller_test.go
=> [Cherrypick #1543] Skip unsupported healths during NEG polling 

pkg/l4/l4controller.go, pkg/l4/l4controller_test.go, pkg/loadbalancers/forwarding_rules.go, pkg/loadbalancers/l4.go, pkg/neg/controller.go, pkg/neg/controller_test.go, pkg/utils/utils.go
Cherrypick of https://github.com/kubernetes/ingress-gce/pull/1545
=> [1.13] Mitigate race condition between service controller and subsetting controller for existing services.

pkg/neg/syncers/endpoints_calculator_test.go
=> Fix comment for ep calculator test - local mode

pkg/backends/neg_linker.go, pkg/backends/neg_linker_test.go, pkg/controller/controller.go, pkg/l4/l4controller.go
This avoids unnecessary NEG API calls if possible. That would speed up ingress processing/
=> skip NEG API call for NEG linker if possible

pkg/context/context.go
This adds a new lock instead of reusing healthcheck lock. Healthcheck lock is taken before running all the healthcheck functions ( for neg, l7, l4 controllers).
Since this happens periodically, it would be wasteful for event recorder to wait for the same lock.
Cherrypick of https://github.com/kubernetes/ingress-gce/pull/1565
=> [1.13] Add a lock for the recorders map.

pkg/metrics/metrics.go
This metric contains the version of the controller.  It can be overridden with the `INGRESS_VERSION` environment variable.
=> Add component version metric

pkg/context/context.go
=> reorder lock vars to prefix the map they guard.

pkg/l4/l4controller.go, pkg/l4/l4controller_test.go, pkg/loadbalancers/forwarding_rules.go, pkg/loadbalancers/l4.go, pkg/neg/controller.go, pkg/neg/controller_test.go, pkg/utils/utils.go
Cherrypick of 3 PRs - https://github.com/kubernetes/ingress-gce/pull/1545, https://github.com/kubernetes/ingress-gce/pull/1552, https://github.com/kubernetes/ingress-gce/pull/1554
=> [1.11] Prevent race conditions between service and subsetting controllers.

docs/deploy/gke/csm/default-http-backend.yaml, docs/deploy/gke/csm/glbc.yaml, docs/deploy/gke/non-gcp/default-http-backend.yaml, docs/deploy/gke/non-gcp/glbc.yaml, docs/deploy/resources/glbc.yaml, docs/troubleshooting/troubleshooting.md
fixes: no matches for kind "Deployment" in version "extensions/v1beta1"
=> Update deployment apiVersion from extensions/v1beta1 to apps/v1

pkg/neg/controller.go, pkg/neg/manager.go, pkg/neg/manager_test.go, pkg/neg/syncers/transaction.go, pkg/neg/syncers/transaction_test.go, pkg/neg/types/fakes.go
cherrypick #1600 into release-1.12
=> [Cherrypick #1600 into 1.12] Zone change 1.12

pkg/healthchecks/healthchecks_l4.go, pkg/l4netlb/l4netlbcontroller.go, pkg/l4netlb/l4netlbcontroller_test.go, pkg/loadbalancers/l4.go, pkg/loadbalancers/l4_test.go, pkg/loadbalancers/l4netlb.go, pkg/loadbalancers/l4netlb_test.go, pkg/test/gcehooks.go, pkg/test/utils.go, pkg/utils/common/finalizer.go, pkg/utils/utils.go
Add L4NetLB finalizer
Handle L4 External LoadBalancer service deletion
Add unit tests for L4NetLBController
=> Implement delete function for L4NetLB

pkg/apis/serviceattachment/v1/types.go, pkg/apis/serviceattachment/v1beta1/types.go, pkg/psc/controller.go, pkg/psc/controller_test.go
=> Allow users to specify resource url for the nat subnet

pkg/neg/controller.go, pkg/neg/manager.go, pkg/neg/manager_test.go, pkg/neg/syncers/transaction.go, pkg/neg/syncers/transaction_test.go, pkg/neg/types/fakes.go
* VmIpPort NEGs should be synced when node change results in a zone
being added or removed
* Node informer event handlers are initialized in all cases
Cherrypick #1600 into 1.14
=> [Cherrypick #1600 to 1.14] Trigger sync for certain node changes

pkg/apis/serviceattachment/v1beta1/types.go, pkg/psc/controller.go, pkg/psc/controller_test.go
=> [Cherrypick #1608 in 1.13] Allow users to specify resource url for the nat subnet

pkg/apis/serviceattachment/v1beta1/types.go, pkg/psc/controller.go, pkg/psc/controller_test.go
=> [Cherrpick #1608 to 1.14] Allow users to specify resource url for the nat subnet

cmd/glbc/main.go, pkg/flags/flags.go, pkg/flags/l4netlbrbsmode.go, pkg/flags/l4netlbrbsmode_test.go
Rbs mode flag will enalbe L4 External LoadBalancer Controller
RbsMode has 4 values and its behaviour for L4NetLbController
will be implemented later
=> Add Rbs mode flag

pkg/l4/l4controller.go, pkg/l4netlb/l4netlbcontroller.go, pkg/l4netlb/l4netlbcontroller_test.go, pkg/loadbalancers/l4netlb.go, pkg/test/gcehooks.go, pkg/test/utils.go, pkg/utils/loadbalancers/ports.go, pkg/utils/loadbalancers/ports_test.go
Add function to L4NetLBController which handles External L4 LoadBalancer services update
=> Update L4NetLB services

cmd/e2e-test/cdn_test.go
* older ingress versions will be unable to use the new expanded config
options and cannot pass the new tests
/assign @prameshj @bowei
=> Add back original CDN test for older Ingress Versions

pkg/backends/backends.go, pkg/firewalls/firewalls_l4.go, pkg/healthchecks/healthchecks_l4.go, pkg/healthchecks/healthchecks_l4_test.go, pkg/l4netlb/l4netlbcontroller_test.go, pkg/loadbalancers/forwarding_rules.go, pkg/loadbalancers/l4.go, pkg/loadbalancers/l4_test.go, pkg/loadbalancers/l4netlb.go, pkg/loadbalancers/l4netlb_test.go, pkg/utils/utils.go
Theres is an issue related to shared regional helath check.
Needs to investigate this futher.
This reverts commit d0a64f6482889bbca39b9787b31e92692f7a3543, reversing
changes made to 5618499ddca31dc286dc6faec617d55c5e3c67b7.
=> Revert "Merge pull request #1606 from kl52752/healthCheckFix"

pkg/loadbalancers/l4.go, pkg/loadbalancers/l4_test.go
Fix firewall rule deletion in L4 LBs
=> [1.13] Fix ILB HC firewall rule deletion (CP PR #1625)

pkg/loadbalancers/l4.go, pkg/loadbalancers/l4_test.go
Fix firewall rule deletion in L4 LBs
=> [1.14] Fix ILB HC firewall rule deletion (CP PR #1625)

pkg/l4/l4controller_test.go, pkg/l4netlb/l4netlbcontroller_test.go, pkg/loadbalancers/l4.go, pkg/loadbalancers/l4_test.go, pkg/loadbalancers/l4netlb.go
When service ExternalTrafficPolicy is updated a new helath check is
created. In update function we don't try to delete old health check due
to performance reason. When service is deleted we need to check both
shared and non-shared health checks to prevent resource leak.
=> Clean up health check on service deletion

cmd/glbc/main.go
Ref https://github.com/kubernetes/ingress-gce/issues/1590
/assign @bowei @freehan
=> Migrate gce-ingress to configmaps-leases leaderelection lock

pkg/l4lb/l4netlbcontroller_test.go, pkg/loadbalancers/forwarding_rules.go, pkg/loadbalancers/l4netlb.go
Forwarding rule name for NetLB should align with legacy forwarding rule
name.
=> Rename NetLB forwarding rule

cmd/glbc/main.go, pkg/l4lb/l4controller.go, pkg/l4lb/l4controller_test.go, pkg/l4lb/l4netlbcontroller.go, pkg/l4lb/l4netlbcontroller_test.go, pkg/loadbalancers/l4.go, pkg/loadbalancers/l4_test.go, pkg/loadbalancers/l4netlb.go, pkg/loadbalancers/l4netlb_test.go, pkg/loadbalancers/l4syncresult.go
This pull request addresses open issues in https://github.com/kubernetes/ingress-gce/pull/1629
=> Extract common parts for L4 LoadBalancers - Part 2

hack/setup-local.sh
If in proejct there are multiple instances in one zone there might be an
error in chosing instance for node tag.
Instance should be select from cluster's instance group.
=> Fix instance selection for node Tag

pkg/firewalls/firewalls_l4.go, pkg/loadbalancers/l4.go, pkg/loadbalancers/l4_test.go, pkg/loadbalancers/l4netlb.go
Extract common L4 LB firewall functions
=> Extract common parts for L4 LoadBalancers - Part 3

pkg/neg/syncers/transaction.go
Remove defer from the mainline function
=> Fix unhandled err variable

pkg/neg/syncers/transaction.go
- `err` was being redefined inside a scope which causes the error handling
to be missed
- Remove defer from the mainline function to avoid having the developer
need to maintain the variable to be alive through the whole body of
the function.
=> [Cherrypick #1660 into release-1.15] Fix unhandled err variable

pkg/neg/syncers/transaction.go
- `err` was being redefined inside a scope which causes the error handling
to be missed
- Remove defer from the mainline function to avoid having the developer
need to maintain the variable to be alive through the whole body of
the function.
=> [Cherrypick #1660 into release-1.14] Fix unhandled err variable

pkg/l4lb/l4netlbcontroller.go, pkg/l4lb/l4netlbcontroller_test.go
We were checking only for TCPForwardingRule, or UDPForwardingRule key existence in annotations, and were considering such services as RBS L4 NetLB
But ILB services also have these keys, but with different values
This pr adds check if value of this annotation matches L4NetLB naming
=> Add check for forwarding rule name in annotation for l4 rbs

pkg/neg/syncers/transaction_test.go, pkg/neg/syncers/utils_test.go
* test that errors from endpoint calculations do not cause endpoints
to be dropped
/cc @robscott @bowei
=> Add unit test for syncInternal error handling

pkg/neg/syncers/transaction_test.go
=> Remove debug print statement

OWNERS
Cherry-picking new members to release 1.17
=> Add new members to OWNERS file

pkg/neg/controller.go
=> Add minor logs to track processing track for neg controller

pkg/l4lb/l4netlbcontroller.go, pkg/loadbalancers/l4_test.go, pkg/loadbalancers/l4netlb.go, pkg/loadbalancers/l4netlb_test.go
This removes number of arguments for L4NetLB constructor
This will also be useful for adding EnableDualStack in L4 NetLB
/assign @kl52752
=> Create struct argument L4NetLBParams for L4NetLB constructor

pkg/metrics/features.go, pkg/metrics/metrics.go
Fixing typos (probably), we were never exposing Network Tier Metrics
/assign @kl52752
=> Fix L4 Premium Network Tier metric, fix comments

cmd/404-server-with-metrics/server-with-metrics.go
This PR cherry-picks change to the 404 server with metrics from master to release-1.20. The change adds to 404 server the functionality to return status code.
=> [Cherrypick #1844] cherry pick 404-server-with-metrics change to release 1.20

pkg/neg/syncers/transaction.go
Added error checking functions in transactionSyncer.go for syncer's error state get/set/reset.
=> Create Error State Interface

cmd/e2e-test/run.sh
The subnet field was added in #1867 but missed adding it to the CMD variable.
=> Fixes subnet in e2e test command

pkg/healthchecksl4/healthchecksl4.go
Simple logs fix
We should add logcheck linter to auto verify klog calls, created task for it
=> Fix logs, use proper format strings argument types

pkg/metrics/metrics.go
=> Change dual-stack ILB metrics to use snake case labels

pkg/utils/utils.go, pkg/utils/utils_test.go
It is not used anymore after PR #1907
=> Cleanup node port utils GetNodePorts

pkg/neg/metrics/metrics.go
Update the bucket for the histogram metric NegOperationEndpoints.
=> Update neg endpoint metrics histogram bucket

pkg/neg/metrics/metrics.go, pkg/neg/metrics/neg_metrics_collector.go
Create NEG metrics collector that would periodically emit NEG syncer metrics.
=> Create NEG metrics collector interface

pkg/neg/types/types.go, pkg/neg/types/types_test.go
=> Only process IPv4 Endpoints

Makefile
Edit verbose option to get more logs for debugging image push error.
=> Edit verbose option

pkg/neg/metrics/neg_metrics_collector.go
Reverts kubernetes/ingress-gce#1912
=> Revert "Add metrics for syncer states"

pkg/neg/controller_test.go, pkg/neg/manager.go, pkg/neg/manager_test.go
=> Replace fetch from apiserver with informer cache while processing SvcNeg

pkg/flags/flags.go, pkg/neg/syncers/transaction.go
Create a flag that enables degraded mode endpoint calculation.
=> Create the flag for degraded mode

pkg/neg/syncers/utils.go, pkg/neg/syncers/utils_test.go
Filter pods from non-existent node in degraded mode
=> Filter pods from non-existent node in degraded mode

pkg/neg/controller_test.go, pkg/neg/manager.go, pkg/neg/manager_test.go
=>  [Cherry pick #1967] Replace fetch from apiserver with informer cache while processing SvcNeg

pkg/metrics/workqueue.go
=> [Cherry pick #1981] Add smaller bucket sizes for workqueue metrics

pkg/ratelimit/metrics/metrics.go, pkg/ratelimit/ratelimit.go
This change introduces rate limiter latency metrics
=> Introduce rate limiter latency metrics

pkg/flags/flags.go, pkg/healthchecks/healthcheck.go, pkg/healthchecks/healthchecks.go, pkg/healthchecks/healthchecks_test.go, pkg/translator/healthchecks.go, pkg/utils/healthchecks.go
~~Safeguarding the main change from https://github.com/kubernetes/ingress-gce/pull/2008/ with a flag.~~
Safeguard the changes from https://github.com/kubernetes/ingress-gce/pull/2008/ with a flag. Test dynamically enabling this flag.
=> Flag for changes regarding health checks with BackendConfig

pkg/neg/syncers/transaction.go
#2051
Deferring lock create deadlock with commitTransaction.
=> [Cherry pick #2051] Fix syncLock deadlock

pkg/backends/neg_linker.go, pkg/backends/neg_linker_test.go
=> Change diffBackends for NEG to not compare the API versions.

pkg/backends/features/logging.go, pkg/backends/features/logging_test.go
=> Set SampleRate to 0 when LogConfig is disabled for BackendService

pkg/neg/syncers/endpoints_calculator.go, pkg/neg/syncers/utils.go, pkg/neg/syncers/utils_test.go, pkg/neg/types/network_endpoint.go
=> Add IPv6 address when calculating target endpoints within L7EndpointsCalculator

pkg/neg/syncers/transaction.go, pkg/neg/syncers/transaction_test.go, pkg/neg/syncers/utils.go, pkg/neg/syncers/utils_test.go
=> Add label propagation logic and update unit tests

cmd/e2e-test/neg_test.go, hack/run-local-glbc.sh, pkg/e2e/fixtures.go, pkg/e2e/helpers.go
=> Label propagation e2e test

pkg/neg/metrics/neg_metrics_collector.go, pkg/neg/metrics/syncer_metrics.go
Added metrics to collect the current count of syncers in each status, and the count of each sync result.
=> Neg sync metric

pkg/neg/controller.go, pkg/neg/controller_test.go
Return error when service uses ipv6 only. Remove this validation when single stack ipv6 endpoint is supported.
=> Add validation for ipv6 only service

pkg/neg/syncers/dualstack/migrator.go, pkg/neg/syncers/dualstack/migrator_test.go, pkg/neg/syncers/transaction.go
=> Implement Pause and Continue for NEG DualStackMigrator

pkg/neg/syncers/dualstack/migrator.go, pkg/neg/syncers/dualstack/migrator_test.go
=> Implement heuristics for detaching migration endpoints

pkg/firewalls/controller.go, pkg/firewalls/controller_test.go
The purpose is to create a firewall rule enabling traffic to port 7877 serving transparent health checks.
~Child PR dependent on https://github.com/kubernetes/ingress-gce/pull/2081, please review the commit titled "Add firewall rule for Transparent Health Checks".~
=> Add firewall rule for Transparent Health Checks

cmd/check-gke-ingress/app/ingress/rule.go, cmd/check-gke-ingress/app/ingress/rule_test.go
=> Add CheckBackendConfigAnnotation rule to check-gke-ingress

go.mod
=> Update go version to 1.20 to match the image build version

pkg/neg/syncers/dualstack/migrator.go, pkg/neg/syncers/dualstack/migrator_test.go, vendor/k8s.io/klog/v2/internal/verbosity/verbosity.go, vendor/k8s.io/klog/v2/ktesting/options.go, vendor/k8s.io/klog/v2/ktesting/setup.go, vendor/k8s.io/klog/v2/ktesting/testinglogger.go, vendor/modules.txt
=> Integration tests for NEG DualStack Migrator

pkg/neg/metrics/metrics.go
Add buckets for syncer staleness metrics.
=> Add buckets for syncer staleness metrics

cmd/check-gke-ingress/app/ingress/rule.go, cmd/check-gke-ingress/app/ingress/rule_test.go
=> Add CheckFrontendConfigExistence to check-gke-ingress

docs/deploy/gke/gke-self-managed.sh
=> Allow IAM policy changes to not require user interactive prompt

cmd/check-gke-ingress/app/ingress/rule.go, cmd/check-gke-ingress/app/ingress/rule_test.go
=> Add CheckAppProtocolAnnotation to check-gke-ingress

cmd/check-gke-ingress/app/ingress/rule.go, cmd/check-gke-ingress/app/ingress/rule_test.go
=> Add CheckL7ILBFrontendConfig to check-gke-ingress

OWNERS
Hoping to learn and help in the process. :)
=> Add gauravkghildiyal to reviewers

cmd/check-gke-ingress/app/ingress/rule.go
=> Fix potential nil pointer panic in check-gke-ingress

Dockerfile.check-gke-ingress, Makefile
=> Add Dockerfile for check-gke-ingress

cmd/check-gke-ingress/app/ingress/ingress.go, cmd/check-gke-ingress/app/ingress/rule.go, cmd/check-gke-ingress/app/ingress/rule_test.go
=> Add frontendConfig annotation check before frontendConfig checks and update tests

pkg/l4lb/l4netlbcontroller.go, pkg/l4lb/l4netlbcontroller_test.go, pkg/loadbalancers/l4netlb.go, pkg/loadbalancers/l4netlbipv6.go
This PR contains the implementation of multinetworking support for external load balancer services.
=> Multi networking support for NetLB

cmd/check-gke-ingress/app/command/root.go, cmd/check-gke-ingress/app/ingress/ingress.go, cmd/check-gke-ingress/app/ingress/rule_test.go
=> Add support to enable single ingress check

pkg/context/context.go
Doing so avoids caching unneeded configmaps in memory.
=> Use field selector to get ASM configmap

pkg/loadbalancers/l4_test.go, pkg/loadbalancers/l4netlb_test.go
I am working on adding checking for IPv6 subnet before starting to sync IPv6 resources (if it has external IPv6 ranges for NetLB and internal ranges for ILB)
In our tests, we never created subnets before, so they don't exist, and I need to add this common functionality to all dualstack test cases
So the first step is this -- refactor test a bit and move almost copy-pasted part of creating some fake resources into common function. Later, I will add creating cluster subnet in this function
=> Move common setup in l4 dualstack tests to separate function

pkg/controller/controller.go, pkg/firewalls/controller.go, pkg/firewalls/controller_test.go, pkg/flags/flags.go, pkg/healthchecks/healthchecks.go, pkg/healthchecks/healthchecks_test.go, pkg/translator/healthchecks.go, pkg/translator/healthchecks_test.go
Integer flag to overwrite the default THC port.
=> Flag for THC port

CHANGELOG.md
/assign @aojea 
/cc @gauravkghildiyal , @cezarygerard
=> Update Changelog for tags 1.16 to 1.24

pkg/loadbalancers/features/l7ilb.go
Reverts https://github.com/kubernetes/ingress-gce/pull/2189
=> Revert "[Cherry-pick #2186 -> 1.22] Include proxy-only subnet with purpose=REGIONAL_MANAGED_PROXY..."

pkg/backends/features/securitypolicy.go, pkg/backends/features/securitypolicy_test.go, pkg/metrics/features.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go
cc @bowei @sawsa307 @gauravkghildiyal
=> Revert fix for issue #1706

pkg/backends/features/securitypolicy.go, pkg/backends/features/securitypolicy_test.go, pkg/metrics/features.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go
=> Cherry pick 1.24

pkg/loadbalancers/l4ipv6.go, pkg/loadbalancers/l4netlbipv6.go
Cynthia suggested better error message, and I agree
=> Improve no IPv6 ranges in subnet error message

pkg/loadbalancers/l4_test.go, pkg/loadbalancers/l4ipv6.go, pkg/loadbalancers/l4netlb_test.go, pkg/loadbalancers/l4netlbipv6.go
What a miss :D
/assign @code-elinka @aojea
=> Fix error message, arguments were misplaced, restructure unit tests

pkg/servicemetrics/servicemetrics.go, pkg/servicemetrics/servicemetrics_test.go
/assign @swetharepakula @gauravkghildiyal
=> Fix panic on empty ipFamilies, happens on ExternalName service

pkg/servicemetrics/servicemetrics.go, pkg/servicemetrics/servicemetrics_test.go
/assign @swetharepakula @gauravkghildiyal
=> [Cherry-pick 1.23] Fix panic on empty ipFamilies, happens on ExternalName service

pkg/utils/utils.go, pkg/utils/utils_test.go
* Remove infinite for loop since errors.As finds the relevant error
* Add tests to validate the functions work for multi-wrapped errors
/assign @bowei 
/cc @gauravkghildiyal
=> [Cherry-pick #2232] Refactor ServerErrror helper functions

pkg/controller/translator/translator.go, pkg/instancegroups/manager.go, pkg/l4lb/l4controller.go, pkg/l4lb/l4netlbcontroller.go
This will help us debug customer issues in the future
=> Improve debug logging around instance group management

pkg/l4lb/l4controller.go, pkg/l4lb/l4controller_test.go, pkg/l4lb/l4netlbcontroller.go, pkg/l4lb/l4netlbcontroller_test.go, pkg/neg/controller.go, pkg/neg/controller_test.go
Do not process services with LoadBalancerClass in:
- L4 ILB controller
- L4 NetLB controller
- VM_IP_NEG in NEG controller
=> Ignore L4 services with LoadBalancerClass set

pkg/neg/metrics/metrics.go
=> [Cherry-pick #1925 -> 1.20] Update neg endpoint metrics histogram bucket

pkg/neg/controller_test.go, pkg/neg/manager.go, pkg/neg/manager_test.go
=> [Cherry-pick #1967 -> 1.20] Replace fetch from apiserver with informer cache while processing SvcNeg

pkg/metrics/workqueue.go
=> [Cherry-pick #1981 -> 1.20]  Add smaller bucket sizes for workqueue metrics

Makefile
=> [1.23] Update go version to 1.20.8

Makefile
=> [1.25] Update go version to 1.20.8

pkg/network/network.go
Make these user errors. We don't want these to show up as persistent errors when the user mistypes the network name.
=> Multinet - treat network configuration errors as user errors

Makefile
=> Update go build image version to 1.20.8 on master

pkg/neg/syncers/utils.go
=> Fix log in label propagation

pkg/loadbalancers/certificates.go
/assign @swetharepakula @spencerhance
=> Do not log certificates values

pkg/healthchecks/healthchecks.go
/assign @DamianSawicki @gauravkghildiyal
=> Remove unused argument ilB from generateServiceInfo

pkg/utils/common/finalizer.go, pkg/utils/namer/serviceattachmentnamer.go, pkg/utils/utils.go
/assign @swetharepakula @gauravkghildiyal
=> Remove unused code from utils

cmd/glbc/main.go, pkg/context/context.go, pkg/flags/flags.go
Defaults to false, should be no-op change
=> Add EnableIngressRegionalExternal flag

OWNERS
=> Adds spencerhance as "approver" in OWNERS

pkg/context/context.go, pkg/controller/translator/testdata/ingress-gce-regional.json, pkg/controller/translator/testdata/ingress-gce-regional.yaml, pkg/controller/translator/translator.go, pkg/controller/translator/translator_test.go, pkg/utils/serviceport.go
Just passing flag for now, should be no-op changes
=> Add L7XLBRegionalEnabled to translator and service port 

pkg/healthchecks/healthchecks.go
/assign @swetharepakula @spencerhance 
/cc @bowei
=> Simplify if order, no logic change, no-op change

pkg/healthchecks/healthchecks.go
- These functions are not specific to ILB
- Should not change any logic
- Adds more logs
It will help later to add RegionalExternal
=> Rename get/update/delete+ILB functions to get/update/delete+Regional

pkg/annotations/ingress.go
=> Rename GceL7XLBRegionalIngressClass to gce-regional-external

cmd/glbc/main.go, pkg/neg/controller.go, pkg/neg/controller_test.go
- No-op change for now
- We will use it later to process negs for gce-regional ingresses
/assign @swetharepakula @spencerhance 
/cc @bowei
=> Add and pass enableL7XLBRegional to NEG controller

pkg/controller/translator/translator_test.go
- Remove wantPort, wantedPort from test cases
- Add wantServicePort to test cases
- Compare result service port using cmp.Diff
This will also help to later unit-test that for gce-regional we setup proper ServicePort flags
/assign @swetharepakula @spencerhance 
/cc @bowei
=> Refactor TestGetServicePort, add cmp.Diff with result ServicePort

pkg/loadbalancers/features/features.go
- Technically, this file could be refactored and removed, but this is out of scope of current work
=> Add scope and versions for L7 RXLB

pkg/loadbalancers/certificates.go, pkg/loadbalancers/forwarding_rules.go, pkg/loadbalancers/target_proxies.go, pkg/loadbalancers/url_maps.go, pkg/translator/translator.go, pkg/translator/translator_test.go
- For IsL7XLBRegional construct EXTERNAL_MANAGED forwarding rules
- Add utils.IsGCEL7XLBRegionalIngress for every place of NewTranslator
=> Add IsL7XLBRegional to translator

pkg/neg/controller.go, pkg/neg/controller_test.go
=> Add syncing default backends for L7 Regional XLB

pkg/neg/controller_test.go
- This test was passing, only because we were using global controller where we kept adding new ingresses without removing one from previous test cases
=> Fix broken unit test, remove using global controller

pkg/backends/features/features.go
- Technically this file could be removed, but I am keeping the changes small
=> Set proper features and scope for L7 Regional XLB ServicePort

pkg/flags/flags.go, pkg/utils/utils.go, pkg/utils/utils_test.go
=>  Add flag to disable handling Ingress class = gce

pkg/backends/backends.go
=> Create EXTERNAL_MANAGED backend services for Regional External Ingress

cmd/e2e-test/affinity_beta_test.go, cmd/e2e-test/affinity_test.go
- Almost a full copy of existent affinity test
- Verified with local run, passed
=> Add affinity e2e test for gce-regional-external 

cmd/e2e-test/app_protocols_test.go
- Almost full copy of existent App Protocol test for Global XLB
=> Add App Protocol e2e tests for Ingress Regional XLB

cmd/e2e-test/backend_config_test.go
- Almost a full copy of existent TestBackendConfigNegatives test
=> Add e2e test that verifies CDN and IAP does not work with RXLB

pkg/loadbalancers/addresses.go
- Need to specify address NetworkTier = Standard for RXLB
- The error was hard to find, so adding a log for it
=> Fix HTTPs to share address with HTTP for RXLB

pkg/neg/syncers/utils.go
* Added missing metrics collection for NegControllerErrorCount metrics in toZoneNetworkEndpointMap and toZoneNetworkEndpointMapDegradedMode.
=> Added missing NEG Controller Error metrics collection.

cmd/e2e-test/basic_https_test.go, pkg/loadbalancers/addresses.go
- Almost a full copy of TestILBHttps
=> Add HTTPs e2e test for Regional XLB

cmd/e2e-test/regional_xlb_test.go, pkg/e2e/fixtures.go
- Add utils function to create Regional External Static IP
=> Add TestRegionalXLBStaticIP e2e test

cmd/e2e-test/regional_xlb_test.go
=> Add TestRXLBILBShared e2e test

cmd/e2e-test/regional_xlb_test.go
- This test verifies transition between default backend, RXLB, ILB
This test is almost a full copy of TestILBUpdate
=> Add TestRegionalXLBILBTransition e2e test

cmd/e2e-test/draining_test.go
=> Rename TestRegionalXLBDraining -> TestRegionalXLBDrain

cmd/e2e-test/logging_test.go
- Almost a full copy of existent TestLogging
=> Add backend config Logging e2e test for RegionalXLB ingress

cmd/e2e-test/healthcheck_test.go
- Almost a full copy of TestHealthCheck
- Verified locally, passed
=> Add e2e test for BackendConfig HealthCheck for RXLB Ingress

cmd/e2e-test/v2frontendnamer_test.go
=> Fix ingKey for log message

pkg/backends/backends.go, pkg/l4lb/l4lbcommon.go, pkg/loadbalancers/l4.go, pkg/loadbalancers/l4netlb.go
Just debug logging, no logic change
=> Add more debug logs for L4 Multinetworking and L4 SSA

pkg/backends/backends.go, pkg/neg/syncers/utils.go
Fix some missing values
also add information about the network used when creating NEG
=> Minor fixes and updates to logging related to multinet

Makefile
=> Update go base image to 1.20.12

Makefile
=> Update base go build image to 1.20.12

Makefile
=> Update go based image to 1.20.12

pkg/utils/zonegetter/node-state.md, pkg/utils/zonegetter/zone_getter.go, pkg/utils/zonegetter/zone_getter_test.go
/assign @swetharepakula @bowei
=> Add a refactored ZoneGetter package and filter nodes with providerID

cmd/e2e-test/timeout_test.go
- Almost a full copy of existent Timeout test
- Verified with local run, passed
=> Add TestRegionalXLBCT to test ConnectionTimeout for Regional XLB Ingress

pkg/controller/controller.go
/assign @swetharepakula @spencerhance
=> Emit a warning if customer uses ingress class gce when it is not supported

pkg/loadbalancers/target_proxies.go
=> [Cherry-pick #1961 -> 1.20]  Add nil check for FrontendConfig in checkProxy()

pkg/backends/neg_linker.go, pkg/backends/neg_linker_test.go
=> [Cherry-pick #2054 -> 1.20] Change diffBackends for NEG to not compare the API versions.

pkg/network/network.go, pkg/network/network_test.go
- only services in network type L3 are supported.
- multinet services with externalTrafficPolicy other than Local are not supported for now.
=> Add some validations for L4 multinetwork services

pkg/network/network.go, pkg/network/network_test.go
Cherry pick of #2402
- only services in network type L3 are supported.
- multinet services with externalTrafficPolicy other than Local are not supported for now.
=> [Cherry pick #2402 -> 1.26] Add some validations for L4 multinetwork services.

pkg/instancegroups/manager.go, pkg/instancegroups/manager_test.go
=> Change instanceGroup manager logic to use zone information from GCE when removing nodes

OWNERS
=> Move mmamczur and code-elinka to approvers and add alexkats

pkg/network/network.go, pkg/network/network_test.go
Reverts kubernetes/ingress-gce#2421
Since 1.26.2 was cut without any bug fixes, we can now undo the temporary reverts.
=> Revert "Revert "[Cherry pick #2402 -> 1.26] Add some validations for L4 multinetwork services.""

pkg/neg/controller.go, pkg/neg/controller_test.go
=> Cherry-pick Trigger node process when providerID populated to 1.27

pkg/neg/syncers/transaction_test.go, pkg/utils/zonegetter/fake.go
=> Add more unit tests for ZoneGetter change in NEG controller

pkg/neg/controller.go, pkg/neg/controller_test.go
=> Trigger node process when providerID populated

cmd/glbc/main.go, pkg/flags/flags.go
* The NEG controller will run if enable-neg-controller is enabled.
* Setting its default value as true so we won't break any existing tests.
* Flag-gate NEG controller and Svcneg CRD with enable-neg-controller.
=> Introduce enable-neg-controller flag, and flag-gate NEG controller and Svcneg CRD.

cmd/glbc/main.go
=> Refactor runNEGController

pkg/neg/controller.go
=> Remove duplicate shutdown log in NEG controller.

cmd/glbc/main.go, pkg/firewalls/controller.go, pkg/firewalls/controller_test.go, pkg/loadbalancers/features/l7rxlb.go
- We need to create firewall to allow traffic from proxy-subnet to nodes
=> Create proper firewall for Regional XLB Ingress

cmd/glbc/main.go, pkg/firewalls/controller.go, pkg/firewalls/controller_test.go
* Firewall controller should waits on stopCh so its shutdown() can be properly executed.
=> Make firewall controller waits on stopCh.

pkg/neg/manager.go
/assign @gauravkghildiyal @swetharepakula
=> Fix log params for new klog

cmd/glbc/app/handlers.go, cmd/glbc/main.go, pkg/controller/controller.go, pkg/flags/flags.go
=> Remove deleteAll option.

cmd/glbc/main.go, pkg/neg/controller.go, pkg/neg/controller_test.go
=> Enable L7 NEG by default.

hack/boskos.sh
* Update project type to `gce-project` as `ingress-project` does not exist in community clusters.
/assign @aojea 
=> Update project type to be gce-project.

cmd/glbc/main.go
=> Update logic on EnableNegController.

pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/loadbalancers/interfaces.go, pkg/loadbalancers/l7s.go, pkg/loadbalancers/l7s_test.go
1. Check if forwarding rule exists with previous lbScheme
2. If yes -- start garbage collection for the ingress
=> Add garbage collection when transitioning between ILB and RXLB

pkg/e2e/helpers.go
=> Don't return error if ingress already do not exist

pkg/firewalls/controller.go
/assign @spencerhance @swetharepakula 
printing all the ingresses is overkill
=> Remove useless big log

cmd/e2e-test/regional_xlb_test.go, pkg/fuzz/gcp.go
=> Fix VIP in params after transition

pkg/neg/syncers/transaction.go, pkg/neg/syncers/transaction_test.go
=> [Cherry-pick #2469 -> 1.28] Reset error state even when degraded mode is not enabled.

cmd/glbc/main.go, pkg/backends/ig_linker.go, pkg/backends/regional_ig_linker.go, pkg/controller/controller.go, pkg/instancegroups/manager.go, pkg/l4lb/l4controller.go, pkg/l4lb/l4netlbcontroller.go, pkg/loadbalancers/certificates.go, pkg/loadbalancers/l4.go, pkg/loadbalancers/l4netlb.go, pkg/sync/sync.go
=> Add context loggers to missing places

pkg/neg/syncers/endpoints_calculator.go, pkg/neg/syncers/endpoints_calculator_test.go
=> [Cherry-pick #2431 -> 1.26] Fix NEG degraded mode for L4 externalTrafficPolicy=Local services.

cmd/e2e-test/regional_xlb_test.go
=> Add more logs to e2e tests

cmd/e2e-test/regional_xlb_test.go
=> Increase timeout and explain rxlb transition e2e test problem

cmd/glbc/main.go
=> Add back lockName to logs related to lock availability metrics.

pkg/fuzz/validator.go
Reverts kubernetes/ingress-gce#2487
it broke tests because of the logic in here https://github.com/kubernetes/ingress-gce/blob/b6f6c795fc74d7b2a3fbbdf0ffd32bdb5d0ca3b5/pkg/fuzz/helpers.go#L38 for CDN Validator
/assign @swetharepakula @spencerhance
=> Revert "Add validating Default 404 service in e2e tests"

pkg/composite/composite.go, pkg/loadbalancers/target_proxies.go, pkg/translator/translator.go, pkg/translator/translator_test.go
- Regional HTTPS Proxy requires patch method, instead of setSslPolicy
=> Add support for sslPolicy for regional XLB ingress

pkg/neg/syncers/transaction.go
=> [release-1.28] Added user-facing log about degraded mode.

pkg/neg/syncers/transaction.go
* Emit events when error state is set and reset to notify error state status of the syncer.
* When error state is set, degraded mode calculation is used only if "--enableDegradedMode" flag is turned on. No behavioral change is triggered by error state if the flag is not turned on.
* Error state is reset only if "--enableDegradedMode" flag is on and there is no difference between normal and degraded mode calculation.
Example logs:
```
I1130 00:06:03.754769 3742241 event.go:307] "Event occurred" object="default/neg-demo-svc" fieldPath="" kind="Service" apiVersion="v1" type="Normal" reason="SetErrorState" message="Set error state for NEG default/neg-demo-svc-k8s1-89f6839e-default-neg-demo-svc-80-b0c7e439-http/80-9376-GCE_VM_IP_PORT-L7 due to endpoint information for attach operation is …
```
=> Added user-facing log about degraded mode.

pkg/loadbalancers/target_proxies.go, pkg/utils/utils_test.go
some partial link do not even have project set...
=> Fix comparison for partial and full resource urls

pkg/composite/composite.go, pkg/controller/controller.go, pkg/loadbalancers/target_proxies.go
- Before, sslPolicy was not deleted, if it was set and then removed.
=> Fix deleting sslPolicy by using NullFields

pkg/controller/controller.go, pkg/firewalls/firewalls_l4.go, pkg/healthchecksl4/healthchecksl4.go, pkg/healthchecksl4/interfaces.go, pkg/l4lb/l4controller.go, pkg/l4lb/l4controller_test.go, pkg/l4lb/l4netlbcontroller.go, pkg/l4lb/l4netlbcontroller_test.go, pkg/loadbalancers/address_manager.go, pkg/loadbalancers/forwarding_rules.go, pkg/loadbalancers/forwarding_rules_ipv6.go, pkg/loadbalancers/l4.go, pkg/loadbalancers/l4_test.go, pkg/loadbalancers/l4ipv6.go, pkg/loadbalancers/l4netlb.go, pkg/loadbalancers/l4netlbipv6.go, pkg/network/network.go, pkg/utils/common/finalizer.go
/cc @mmamczur 
/cc @cezarygerard
=> Enhance context logging

pkg/neg/metrics/metrics.go
=> [release-1.23] Add buckets for syncer staleness metrics

cmd/glbc/main.go
fixed a slow memleak in collectLockAvailabilityMetrics func
=> fix a slow leak

cmd/glbc/main.go
Cherry-pick #2516.
/cc @cezarygerard
=> [Cherry-pick #2516 -> 1.28] fix a slow leak

pkg/controller/controller.go, pkg/l4lb/l4controller.go, pkg/l4lb/l4netlbcontroller.go
- This is just informational id
- I found this to be very helpful while debugging, to understand where sync starts and ends, and also better filter for relevant logs
- Using math.rand as this does not require good crypto
/assign @swetharepakula @cezarygerard
=> Add tracking sync id to logger

cmd/glbc/main.go
=> [Cherry-pick #2519 -> 1.28] Do wg.Add before spawning a goroutine.

pkg/flags/flags.go
=> Add feature flag for Multi-Subnet Cluster.

pkg/backends/ig_linker_test.go, pkg/backends/integration_test.go, pkg/backends/regional_ig_linker_test.go, pkg/context/context.go, pkg/controller/controller_test.go, pkg/instancegroups/controller_test.go, pkg/instancegroups/manager_test.go, pkg/neg/controller.go, pkg/neg/controller_test.go, pkg/neg/manager_test.go, pkg/neg/syncers/endpoints_calculator.go, pkg/neg/syncers/endpoints_calculator_test.go, pkg/neg/syncers/transaction_test.go, pkg/neg/syncers/utils_test.go, pkg/neg/types/types_test.go, pkg/test/utils.go, pkg/utils/utils.go, pkg/utils/zonegetter/fake.go, pkg/utils/zonegetter/zone_getter.go, pkg/utils/zonegetter/zone_getter_test.go
Exclude non-default subnet nodes from zoneGetter.
=> Exclude non-default subnet nodes from zoneGetter

pkg/neg/syncers/utils_test.go, pkg/neg/types/fakes.go
* Consolidate L7 endpoint calculation into TestValidateEndpointFields where it tests for both calculations
=> Rename and add test cases related to L7 endpoint calculation

pkg/backends/backends.go, pkg/backends/backends_test.go, pkg/backends/regional_ig_linker_test.go, pkg/loadbalancers/l4.go, pkg/loadbalancers/l4_test.go, pkg/loadbalancers/l4netlb.go
Instead of lengthy list of args
=> Refactor EnsureL4BackendService to use params struct as an argument

pkg/backends/ig_linker_test.go, pkg/backends/integration_test.go, pkg/backends/regional_ig_linker_test.go, pkg/controller/controller_test.go, pkg/instancegroups/controller_test.go, pkg/instancegroups/manager_test.go, pkg/neg/controller.go, pkg/neg/controller_test.go, pkg/neg/manager_test.go, pkg/neg/readiness/poller_test.go, pkg/neg/readiness/reflector.go, pkg/neg/readiness/reflector_test.go, pkg/neg/readiness/utils_test.go, pkg/neg/syncers/endpoints_calculator_test.go, pkg/neg/syncers/transaction_test.go, pkg/neg/syncers/utils_test.go, pkg/neg/types/fakes.go, pkg/neg/types/types_test.go, pkg/utils/zonegetter/zone_getter.go, pkg/utils/zonegetter/zone_getter_test.go
=> L7 readiness reflector update for MSC.

cmd/glbc/main.go, pkg/annotations/service.go, pkg/backends/backends.go, pkg/backends/backends_test.go, pkg/context/context.go, pkg/flags/flags.go, pkg/l4lb/l4controller.go, pkg/l4lb/l4netlbcontroller.go, pkg/loadbalancers/l4.go, pkg/loadbalancers/l4_test.go, pkg/loadbalancers/l4netlb.go, pkg/loadbalancers/l4netlb_test.go
The feature sits behind the flags, separate flags for ILB and NetLB
=> Weighted Load Balancing for both ILB and NetLB

pkg/apis/svcneg/v1beta1/types.go, pkg/apis/svcneg/v1beta1/zz_generated.openapi.go
* Add two new fields: Subnet and State in SvcNeg.
/cc @mmamczur 
/hold Wait for confirmation on the design.
=> Update SvcNeg CR.

pkg/utils/utils.go
=> Update Node subnet label.

pkg/l4lb/l4controller.go, pkg/l4lb/l4netlbcontroller.go, pkg/l4lb/metrics/metrics.go
- Add panic recovery to syncWrapper, AddFunc, and UpdateFunc
- Log detailed error messages
- Emit metric on panic for monitoring
/assign @mmamczur @cezarygerard
=> Add panic recovery with error messages in L4Controller

pkg/instancegroups/manager.go, pkg/instancegroups/manager_test.go, pkg/utils/utils.go
- add debug log
- add proper unit tests
=> Amend error handling for error "400: memberAlreadyExists"

Makefile, go.mod
=> Build using Go 1.22.4

Makefile, go.mod
=> [release-1.30] Build using Go 1.22.4

pkg/flags/flags.go
=> Add the flag for Multi-Subnet cluster phase1 support.

pkg/common/operator/ingress.go, pkg/common/operator/ingress_test.go, pkg/controller/controller.go
=> Add event handler for SvcNeg on Ingress Controller. 

pkg/annotations/service.go, pkg/backends/backends.go, pkg/backends/backends_test.go, pkg/l4lb/l4lbcommon.go, pkg/loadbalancers/l4.go, pkg/loadbalancers/l4_test.go, pkg/loadbalancers/l4netlb.go, pkg/loadbalancers/l4netlb_test.go
=> L4 weighted LB backend locality policy

pkg/loadbalancers/l4.go
Implemented logic to check if the customer's project is allowlisted for Weighted Load Balancing on L4 Internal Load Balancers. If the project is not allowlisted:
- Emit a warning event to inform the user.
- Abandon the provisioning of the service to prevent unexpected behavior.
=> Handle ILB Weighted Load Balancing allowlisting

pkg/neg/manager.go, pkg/neg/manager_test.go
=> Cherry-pick #2622 to release-1.23 - fix: GCE_VM_IP NEGs should be synced on each Node change.

pkg/neg/manager.go, pkg/neg/manager_test.go
=> Cherry-pick #2622 to release-1.26 - fix: GCE_VM_IP NEGs should be synced on each Node change.

pkg/neg/manager.go, pkg/neg/manager_test.go
=> Cherry-pick #2622 to release-1.28 - fix: GCE_VM_IP NEGs should be synced on each Node change.

pkg/l4lb/l4controller.go, pkg/l4lb/l4controller_test.go, pkg/l4lb/l4netlbcontroller.go, pkg/l4lb/l4netlbcontroller_test.go
=> [Cherrypick #2635 into release-1.30] Add initial cache check sync

pkg/l4lb/l4controller.go, pkg/l4lb/l4controller_test.go, pkg/l4lb/l4netlbcontroller.go, pkg/l4lb/l4netlbcontroller_test.go
=> [Cherrypick #2635 into release-1.31] Add initial cache check sync

pkg/e2e/helpers.go
Neg status annotation is a best effort annotation that is not always accurate in regards to the zones. Therefore switch to using the SvcNEG CRs to determine which zones NEGs are currently in.
=> Determine zones by querying the SvcNEG CRs

pkg/e2e/helpers.go
=> Make WaitForNegCRs() wait for the SvcNEG to have the "Initialized" condition

pkg/backends/backends.go, pkg/backends/backends_test.go, pkg/loadbalancers/l4.go, pkg/loadbalancers/l4_test.go, pkg/loadbalancers/l4netlb_test.go
LocalityLBPolicy = MAGLEV requires allowlisting. Implement logic to make ILBs use default "" LocalityLBPolicy and use MAGLEV once WEIGHTED_MAGLEV or MAGLEV is used.
=> Use default LocalityLBPolicy for ILB

pkg/backends/backends.go, pkg/backends/backends_test.go
With new backendSvcEqual we never update the localityLbPolicy on existing services that do not use Weighted Load Balancers also now this invariant is true: backendSvcEqual(old, new) == backendSvcEqual(new, old)
Plus changed the naming of some variables as confusing names may have contributed to the problem
Original PR: https://github.com/kubernetes/ingress-gce/pull/2654
=> Cherry-pick #2654 Improve backendSvcEqual code for backend service creation

pkg/backends/ig_linker_test.go, pkg/backends/integration_test.go, pkg/backends/regional_ig_linker_test.go, pkg/context/context.go, pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/instancegroups/controller.go, pkg/instancegroups/controller_test.go, pkg/instancegroups/interfaces.go, pkg/instancegroups/manager.go, pkg/instancegroups/manager_test.go, pkg/l4lb/l4netlbcontroller.go
Improve logger of the instance group manager to take context from load balancer controller
=> [Cherry-pick #2636 -> 1.31]  Improve Instance Group manager logger

cmd/glbc/main.go, pkg/l4lb/l4controller.go, pkg/l4lb/l4netlbcontroller.go, pkg/neg/types/cloudprovideradapter.go, pkg/neg/types/fakes.go, pkg/neg/types/interfaces.go, pkg/network/network.go, pkg/network/network_test.go
Supporting cluster with network defined using network Id instead of network Name
=> Cluster with network id - fix

pkg/composite/gen.go, pkg/composite/gen/main.go, pkg/composite/meta/meta.go, pkg/forwardingrules/forwarding_rules.go, pkg/loadbalancers/forwarding_rules.go, pkg/loadbalancers/forwarding_rules_test.go, pkg/loadbalancers/interfaces.go, pkg/loadbalancers/l4_test.go
Patching forwarding rules instead of recreating them when updating only patchable fields.
Patchable fields:
AllowGlobalAccess
NetworkTier
=> ForwardingRule - Patch

pkg/neg/controller.go
=> Remove unused cloud field

pkg/neg/syncers/utils.go, pkg/neg/syncers/utils_test.go
=> Check PodIP against PodCIDR only when hostNetwork=false.

pkg/neg/syncers/utils.go, pkg/neg/syncers/utils_test.go
=> [Cherry-pick #2671 -> 1.31] Check PodIP against PodCIDR only when hostNetwork=false.

pkg/neg/syncers/utils.go, pkg/neg/syncers/utils_test.go
=> [Cherry-pick #2671 -> 1.30] Check PodIP against PodCIDR only when hostNetwork=false.

pkg/l4lb/l4controller.go, pkg/l4lb/l4controller_test.go, pkg/l4lb/l4netlbcontroller.go, pkg/l4lb/l4netlbcontroller_test.go
=> [Cherrypick #2635 into release-1.29] Add initial cache check sync

pkg/l4lb/l4controller.go, pkg/l4lb/l4controller_test.go, pkg/l4lb/l4netlbcontroller.go, pkg/l4lb/l4netlbcontroller_test.go
=> [Cherrypick #2635 into release-1.28] Add initial cache check sync

pkg/l4lb/l4controller.go, pkg/l4lb/l4controller_test.go, pkg/l4lb/l4netlbcontroller.go, pkg/l4lb/l4netlbcontroller_test.go
=> [Cherrypick #2635 into release-1.26] Add initial cache check sync 

cmd/glbc/main.go, pkg/common/operator/ingress_test.go, pkg/context/context.go, pkg/controller/controller_test.go, pkg/firewalls/controller_test.go, pkg/l4lb/l4controller_test.go, pkg/l4lb/l4netlbcontroller_test.go, pkg/psc/controller_test.go
=> Remove unused KubeConfig parameter

pkg/neg/manager.go, pkg/neg/manager_test.go
=> Fix the race condition that causes syncer missing in the syncerMap

pkg/backends/neg_linker.go, pkg/backends/neg_linker_test.go, pkg/context/context.go, pkg/controller/controller.go, pkg/neg/manager.go, pkg/neg/syncers/transaction.go, pkg/neg/syncers/transaction_test.go, pkg/neg/syncers/utils.go, pkg/neg/syncers/utils_test.go
Flag gate changes in #2604 and #2615. Ensure no behavior changes unless MultiSubnetClusterPhase1 is enabled.
=> Flag gate multi-subnet cluster changes related to NEG CR.

pkg/context/context.go, pkg/flags/flags.go
=> Make NodeTopologyInformer only looks for cluster-wide CR

pkg/utils/namer/l4_namer.go, pkg/utils/namer/l4_namer_test.go, pkg/utils/namer/namer.go, pkg/utils/namer/namer_test.go
=> Add naming schema for non default subnet NEGs.

pkg/neg/syncers/utils.go, pkg/neg/syncers/utils_test.go
=> [Cherry-pick #2671 -> 1.29] Check PodIP against PodCIDR only when hostNetwork=false.

pkg/neg/syncers/utils.go, pkg/neg/syncers/utils_test.go
=> [Cherry-pick #2671 -> 1.28] Check PodIP against PodCIDR only when hostNetwork=false.

pkg/flags/flags.go, pkg/multiproject/projectcrd/projectcrd.go
=> Add multi-project CRD, add flag for multi-project CRD namespace label

Makefile, go.mod
=>  Update Go version to 1.22.8

Makefile, go.mod
=> [release-1.30] 1.30 update go 1.22.8

Makefile, go.mod
=>  [release-1.31] Update go version to 1.22.8

Makefile, go.mod
=> [release-1.28] 1.28 go update 1.22.8

Makefile, go.mod
=> [release-1.26] Update Go Version 1.22.8

Makefile, go.mod
=> [release-1.23] Update Go version 1.22.8

pkg/flags/flags.go, pkg/multiproject/projectcrd/projectcrd.go
=> Use Object Label to identify Project, instead of Namespace, rename the flag

cmd/e2e-test/regional_xlb_test.go
=> Quick fix RXLB transition test by increasing sleep and moving sleep before getting ingress

cmd/e2e-test/cdn_test.go
=> Extend the timeout for CDN tests from 15 min to 30 min

cloudbuild.yaml
=> Use $_GIT_TAG for unique tag of e2e image

cmd/glbc/main.go, pkg/neg/controller.go, pkg/neg/syncers/endpoints_calculator.go, pkg/neg/syncers/syncer.go, pkg/neg/syncers/transaction.go
=> Logging improvements for NEG Controller

pkg/neg/syncers/transaction.go, pkg/neg/syncers/transaction_test.go, pkg/nodetopology/utils.go, pkg/utils/zonegetter/zone_getter.go
=> fix: Properly handle multi-network cases within multi-subnet implementation.

pkg/annotations/network_tier.go, pkg/annotations/network_tier_test.go, pkg/loadbalancers/forwarding_rules.go, pkg/loadbalancers/forwarding_rules_ipv6.go, pkg/loadbalancers/l4netlb_test.go, pkg/utils/utils.go
and add unit tests. This helps to follow Go guidelines https://go.dev/wiki/CodeReviewComments#package-names.
=> Move `GetNetworkTier` to `pkg/annotations`

pkg/composite/gen.go, pkg/composite/gen_test.go
=> Update copyright year from 2024 to 2025 in gen.go and gen_test.go files

pkg/l4lb/l4netlbcontroller.go, pkg/l4lb/l4netlbcontroller_test.go
Reverts kubernetes/ingress-gce#2760
=> Revert "[cherrypick #2747 to release-1.32] Trigger deletion of NEG based NetL…"

cmd/glbc/main.go
based on https://github.com/kubernetes/ingress-gce/pull/2789
Should be no-op, but it was just a bit hard to read and understand the logic before
=> Refactor leader elect main

pkg/recorders/manager.go
=> Fix importing correct scheme for recorders manager

pkg/neg/syncers/transaction.go, pkg/neg/syncers/transaction_test.go
=> Mark NEGs from removed subnets at TO_BE_DELETED

cmd/glbc/main.go, pkg/flags/flags.go, pkg/multiproject/controller/controller.go, pkg/multiproject/gce/fake.go, pkg/multiproject/gce/fake_test.go, pkg/multiproject/gce/gce.go, pkg/multiproject/manager/manager.go, pkg/multiproject/neg/neg.go, pkg/multiproject/start/start.go, pkg/multiproject/start/start_test.go, pkg/multiproject/testutil/providerconfigwebhook.go, pkg/neg/controller.go
=> ProviderConfig fixes and integration test

pkg/multiproject/gce/gce.go, pkg/multiproject/gce/gce_test.go
=> Support generating proper GCE conf when network and subnetwork of ProviderConfig are specified using URL

pkg/multiproject/gce/gce.go, pkg/multiproject/gce/gce_test.go
=> Change multiproject auth API to support per-provider-config token

pkg/neg/manager.go, pkg/neg/manager_test.go
This PR is dependent on the merging of https://github.com/kubernetes/ingress-gce/pull/2812.
=> Garbage collect TO_BE_DELETED NEGs

pkg/flags/flags.go, pkg/multiproject/gce/gce.go, pkg/multiproject/gce/gce_test.go, pkg/multiproject/start/start_test.go
=> Rework per-provider-config auth. Assume cluster project if no label set

pkg/apis/providerconfig/v1/types.go, pkg/multiproject/controller/controller_test.go, pkg/multiproject/finalizer/finalizer.go, pkg/multiproject/finalizer/finalizer_test.go, pkg/multiproject/manager/manager.go, pkg/multiproject/start/start_test.go, pkg/providerconfig/client/clientset/versioned/typed/providerconfig/v1/fake/fake_providerconfig.go, pkg/providerconfig/client/clientset/versioned/typed/providerconfig/v1/fake/fake_providerconfig_client.go, pkg/providerconfig/client/clientset/versioned/typed/providerconfig/v1/providerconfig.go, pkg/providerconfig/client/clientset/versioned/typed/providerconfig/v1/providerconfig_client.go, pkg/providerconfig/client/informers/externalversions/providerconfig/v1/interface.go, pkg/providerconfig/client/informers/externalversions/providerconfig/v1/providerconfig.go, pkg/providerconfig/client/listers/providerconfig/v1/expansion_generated.go, pkg/providerconfig/client/listers/providerconfig/v1/providerconfig.go, pkg/utils/patch/patch.go, pkg/utils/patch/patch_test.go
=> Regenerate ProviderConfig types to be Cluster scoped, not Namespace scoped

OWNERS
I've became a k8s community member:
https://github.com/orgs/kubernetes/people?query=TortillaZHawaii
=> Add TortillaZHawaii to Reviewers

hack/setup-local.sh
Fixed setup script, now working for both zonal and regional clusters
=> Fixed setup script for zonal cluster

pkg/utils/patch/patch.go
- StrategicMergePatch is not supported for custom resource, hence giving us errors
- Replace StrategicMergePatch with MergeMatch
=> Fix patching ProviderConfig resource

pkg/utils/patch/patch.go
- StrategicMergePatch is not supported for custom resource, hence giving us errors
- Replace StrategicMergePatch with MergeMatch
=> [Cherry-pick #2832 to release-1.34] Fix patching ProviderConfig resource

pkg/multiproject/manager/manager.go
/assign @gauravkghildiyal @swetharepakula
=> Add per-provider-config logger, that has ProviderConfig.Name value

pkg/utils/zonegetter/zone_getter.go, pkg/utils/zonegetter/zone_getter_test.go
This slightly increases the robustness with the handling of NodeTopology CR.
=> Return atleast the default subnet if the NodeTopology has empty subnets.

pkg/context/context.go, pkg/utils/zonegetter/zone_getter.go, pkg/utils/zonegetter/zone_getter_test.go
Create a mode in the ZoneGetter to properly handle legacy network based clusters
/assign @mmamczur 
/cc @ruixiansong
=> Zone getter legacy

pkg/utils/zonegetter/zone_getter.go
=> Update ListSubnets logging for legacy case

pkg/context/context.go, pkg/utils/zonegetter/zone_getter.go, pkg/utils/zonegetter/zone_getter_test.go
Create a mode in the ZoneGetter to properly handle legacy network based clusters
/assign @mmamczur 
/cc @ruixiansong
=> [Cherrypick #2865 into release-1.35] Legacy zone getter 1.35

cmd/404-server-with-metrics/server-with-metrics.go, cmd/check-gke-ingress/app/command/root.go, cmd/e2e-test/basic_test.go, cmd/workload-controller/main.go, pkg/address/manager_test.go, pkg/e2e/fixtures.go, pkg/e2e/helpers.go, pkg/neg/manager.go, pkg/neg/syncers/transaction_test.go, pkg/network/network_test.go, pkg/psc/controller_test.go, pkg/storage/configmaps_test.go, pkg/utils/gceurlmap.go
Each commit fixes errors caused by specific error code
=> Fix some of the golangci-lint staticcheck errors

pkg/controller/controller.go, pkg/instancegroups/controller.go, pkg/instancegroups/manager.go, pkg/l4lb/l4netlbcontroller.go, pkg/utils/zonegetter/zone_getter.go, pkg/utils/zonegetter/zone_getter_test.go
=> Add functions to list nodes/zones in the default subnet in the zoneGetter and apply those functions in instance group use cases

pkg/firewalls/controller_test.go, pkg/loadbalancers/loadbalancers_test.go, pkg/metrics/metrics_test.go, pkg/translator/translator_test.go, pkg/utils/utils.go
Since Go introduced generics there is no need to have type specialized util functions for creating pointers.
=> Use ptr.To

OWNERS
Reviewers are automatically added to every PR. This triggers a lot of notifications, even when the change doesn't touch L4LBs code. 
I can lgtm either way, but I don't want to receive so many notifications and mails.
=> Move TortillaZHawaii to approvers

pkg/flags/flags.go, pkg/loadbalancers/addresses.go, pkg/loadbalancers/l7.go, pkg/loadbalancers/loadbalancers_test.go
=> Deprecate --enable-delete-unused-frontends, consider always enabled

pkg/firewalls/controller.go, pkg/firewalls/controller_test.go, pkg/flags/flags.go
/assign @gauravkghildiyal @swetharepakula
=> Allow ability to override firewall source ranges

pkg/l4lb/l4netlbcontroller.go, pkg/l4lb/l4netlbcontroller_test.go
When determining which backend to use for a NetLB service in addition to the finalizers also check the actual backend service backends.
This is to work around the situations where the customers remove finalizers and can cause an unexpected move to NEG backends.
=> [Cherrypick #2880 to release-1.34] NetLB: workaround for the finalizer removal case

pkg/firewalls/equal.go, pkg/firewalls/equal_test.go
When comparing Firewall rules make sure the different ways of representing IPv6 addresses are taken into account.
For example "2600:2900:3070:be4:6000::" means the same address as "2600:2900:3070:BE4:6000:0:0:0" however these are not equal strings. When an existing FR is retrieved the address values may be shortened and so simple string comparison can result in unnecessary updates.
=> Fix FirewallRules unexpected patching for IPv6

pkg/context/context.go, pkg/utils/zonegetter/zone_getter.go, pkg/utils/zonegetter/zone_getter_test.go
=> Cherry pick the fix for legacy network in the zonegetter

pkg/utils/zonegetter/zone_getter.go
This reverts commit 526caa8e14e5740182db0a56686d4cc01763f140, reversing changes made to 1471e53ad7dc453fd19ec12ae6061d4e1e63684f.
This is to unblock the legacy network fix release
=> Revert "Merge pull request #2940 from panslava/release-1.34"

pkg/controller/errors/errors.go
=> chore: Make ErrBadSvcType more descriptive about not using NEGs

pkg/multiproject/neg/neg.go, pkg/multiproject/start/start_test.go
Previously, MultiProject NEG controller informers were started with a per-ProviderConfig stop channel. When the first ProviderConfig was deleted, its stopCh closed and killed the shared caches — leaving subsequent ProviderConfigs unprocessed until a new leader restart.
Fix by starting informers using global stopCh so they survive individual ProviderConfig lifecycles.
=> [Cherry-pick #2958 to 1.36] Keep shared informers alive across ProviderConfig shutdown

pkg/multiproject/start/start.go
=> Add more logs to multiproject start.go

pkg/multiproject/controller/controller.go
- Use client-go cache.WaitForCacheSync to wait for informer caches instead of polling every 5s
=> replace 5s poll with WaitForCacheSync

pkg/e2e/helpers.go
=> e2e: wait for NEG zones before returning from WaitForNegCRs

pkg/e2e/helpers.go
=> Increase NEG poll timeout to 10 mins in e2e tests
