- pkg/annotations/service.go
- pkg/l4/l4controller.go
- pkg/l4/l4controller_test.go
- pkg/l4/metrics/metrics.go
- pkg/loadbalancers/l4.go
- pkg/loadbalancers/l4_test.go
- pkg/metrics/metrics.go
- pkg/test/utils.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
The new metric will count the number of failed L4 ILB syncs along with the GCE resource that failed and the type of error that was thrown.
This PR has 3 changes:
1) Adding a new pkg/l4/metrics/metrics.go - for exporting L4 ILB sync metrics.
2) refactoring logic in l4controller.go to publish the new and existing ILB metrics.
3) Unit test changes.
Verified that errors are published correctly by creating 200 ILB services on a cluster and hitting quota errors.
cc @swetharepakula @skmatti 
> Add a new L4 ILB metric for sync errors

- pkg/backends/ig_linker_test.go
- pkg/backends/integration_test.go
- pkg/controller/controller.go
- pkg/controller/controller_test.go
- pkg/instances/instances.go
- pkg/instances/instances_test.go
- pkg/loadbalancers/loadbalancers_test.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
- removes dependency on legacy-cloud-provider for generating the
instance references/URLs
/cc @prameshj @spencerhance 
> Generate URL for GCE instances resource

- pkg/backends/backends.go
- pkg/backends/ig_linker.go
- pkg/backends/syncer.go
- pkg/healthchecks/healthchecks.go
- pkg/healthchecks/healthchecks_l4.go
- pkg/l4/l4controller.go
- pkg/loadbalancers/forwarding_rules.go
- pkg/neg/controller.go
- pkg/neg/manager.go
- pkg/neg/syncers/transaction.go
- pkg/neg/syncers/utils.go
This allows the errors to be unwrapped to classify it correctly without
having to do string matches - https://blog.golang.org/go1.13-errors#TOC_3.3.
> Cherrypick PR#1429 - Use %w to wrap errors.

- pkg/utils/gceurlmap.go
- pkg/utils/gceurlmap_test.go
The backend service synchronization triggers multiple times when multiple paths use the same backend service 
For example for this configuration  
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
name: test-ingress
spec:
rules:
- host: "example.com"
http:
paths:
- path: /alpha
pathType: ImplementationSpecific
backend:
service:
name: backend-service
port:
number: 80
- path: /beta
pathType: ImplementationSpecific
backend:
service:
name: backend-service
port:
number: 80
```
the backend synchronization (health checks, cdn, iap, ...) will run for each of the paths, and each sync triggers api call to the GCE, and I assume there is a quota and rate limiting because it takes lot of time just for one backend service.
Fix for #1447
> Fix duplicate service ports sync

- pkg/e2e/adapter/ingress.go
In v1beta1 Patch, old ingress is converted twice instead of the 
cc @prameshj @spencerhance 
> Fix adapter client patch

- pkg/apis/serviceattachment/v1alpha1/types.go
* allows creation of ServiceAttachments with null ConsumerForwardingRules list
> Add omitempty tag for ConsumerForwardingRules

- pkg/neg/controller.go
Cherrypicks #1456 & #1470 fix for Finalizer test and longer resync periods to release 1.12.
Description in #1470 includes details about the test fix.
> [Cherrypick #1470] into release-1.12: Process service if old ingress class was glbc

- pkg/neg/readiness/poller.go
- pkg/neg/readiness/poller_test.go
When ratelimiting kicks in and delays the NEG readiness reflector from getting health status via ListNetworkEndpoint GCE API call, the reflector may hit a nil pointer panic when trying to retrieve `p.pollMap[key].endpointMap` when key has been removed from pollMap.
The reason the key might be removed from pollMap is because NEG readiness condition timeout on the pod and all ednpoints/pods behind the NEG has been marked as ready. However, poller is still blocked by ratelimiter from issuing ListNetworkEndpoint API call.
> avoid panic when reflector under load and rate limited

- pkg/flags/flags.go
- pkg/ratelimit/ratelimit.go
- pkg/ratelimit/ratelimit_test.go
Adds flag --gce-ratelimit-scale
907fac5b5ecb7d5df6c53cedd7dcc0c7e76dcc32
> Cherrypick: Add rate limiting scaling parameter

- pkg/controller/controller.go
- pkg/flags/flags.go
- Decreases ingress sync time
Tested by batch creating 30 ingresses that use the same service and 5 workers
Before: ~20 minutes for all ingresses to sync
After: ~2 minutes for all ingresses to sync
- Note: There is a mutex around SyncBackends(), so that portion of the code is still effectively single-threaded.
- Configurable with `--num-ingress-workers` flag
> Update Ingress Sync Queue to use multiple workers

- pkg/psc/controller.go
- pkg/psc/controller_test.go
* If status has not changed, modified timestamp is not updated and the
CR will not be patched
/assign @freehan , @prameshj
> Only bump LastModifiedTimestamp for Status updates

- pkg/controller/controller.go
This is to help prevent multiple workers entering GC logic with conflicts as GC might walk thru shared resources.
> add lock to GC logic

- pkg/neg/controller.go
- pkg/neg/controller_test.go
- pkg/neg/syncers/endpoints_calculator.go
- pkg/neg/syncers/subsets.go
When a node changes state from Unschedulable or Unready to Ready, the NEG controller should Sync the NEGs to include this new node.
This is needed for Cluster trafficPolicy where nodes are selected at random. For Local Traffic Policy, the event of endpoint add/delete would be sufficient.
> Enqueue Node updates to VM_IP_NEG controller.

- pkg/instances/instances.go
* ensures that on delete, instance urls are properly formed with
`/projects` suffix on the basepath
Without the fix errors like the below are seen when removing a node:
```
2021-07-30T20:51:20.620095578Z stderr F I0730 20:51:20.619477       1 instances.go:354] Remove(<instance-group>, _) = RemoveInstances: [googleapi: Error 400: Invalid value for field 'instances[0].instance': '<url-without-projects-suffix>'. The URL is malformed., invalid] (took 40.291331ms); nodes = [<node-name>]
```
With the change logs show successful removal of node:
```
Removing 1, adding 0 nodes
2021-07-30T21:00:18.088782643Z stderr F I0730 21:00:18.088590       1 instances.go:296] Removing nodes [<node-name>] from <instance-group>in zone <zone>
2021-07-30T21:00:18.089973988Z stderr F I0730 21:00:18.089766       1 …
```
> Use local method to get instance references

- pkg/utils/utils.go
Current checks for both the alpha label and V1 label. Both were set to the same value. This PR fixes the V1 string to have the updater value.
The alpha check is not removed, in case this PR needs to be cherrypicked to k8s 1.18.
Previously we were checking the same string in 2 places - https://github.com/kubernetes/ingress-gce/blob/05c0e8b2a52fa225ee5908b9c10e497807a1b796/pkg/utils/utils.go#L381 and https://github.com/kubernetes/ingress-gce/blob/05c0e8b2a52fa225ee5908b9c10e497807a1b796/pkg/utils/utils.go#L385
> Updated the value of LabelNodeRoleExcludeBalancer to the V1 string.

- pkg/controller/translator/translator.go
- pkg/controller/translator/translator_test.go
This PR will separate the path type from the ingress class. That way path type can be enabled as ingress class continues to be developed.
> Always enable pathtype

- pkg/utils/utils.go
- pkg/utils/utils_test.go
Cherrypick of https://github.com/kubernetes/ingress-gce/pull/1537
> [1.12] Allow Unschedulable nodes to be part of the LB backends list.

- pkg/neg/readiness/poller.go
- pkg/neg/readiness/poller_test.go
Currently there are 4 types of healths a network endpoint can have:
* forwardingRule
* backendService
* healthCheck
* healthCheckService
Currently, the NEG controller explicitly checks for a backendService,
however if there is any of the other healths, rather than fast-failing
it will timeout waiting for a backendService to appear and become
healthy.
This is really just a workaround, and ideally the code would be
refactored to support all possible healths. For now, this will bring
back correctness to the fast-fail waiting on health iff
backendServices does not exist in healths.
See: https://cloud.google.com/compute/docs/reference/rest/v1/networkEndpointGroups/listNetworkEndpoints
> Skip unsupported healths during NEG polling

- pkg/neg/controller.go
- pkg/neg/syncers/endpoints_calculator.go
- pkg/neg/syncers/endpoints_calculator_test.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
Nodes that are about to be upgraded/scaled down/marked to exclude from LB backends should be skipped by Endpoints calculator in the Local mode. They are already skipped in the cluster mode.
> Remove nodes from LocalTrafficPolicy NEG if they are not a ready candidate

- pkg/l4/l4controller.go
- pkg/l4/l4controller_test.go
- pkg/loadbalancers/forwarding_rules.go
- pkg/loadbalancers/l4.go
- pkg/neg/controller.go
- pkg/neg/controller_test.go
- pkg/utils/utils.go
The 2 controllers identify what services they should work on via the finalizer value. V1 finalizer - service controller, v2 finalizer - subsetting controller.
If the service finalizer fields are manually reset(through a script, user intervention), the subsetting controller will add the v2 finalizer, thinking it is a new service.
The service controller will also add the v1 finalizer because the legacy forwarding rule still exists.
This results in unnecessary creation of NEGs and other LB resources for the legacy ILB. This change reduces the chance of this race.
> Mitigate race condition between service controller and subsetting controller for existing services.

- pkg/l4/l4controller.go
- pkg/neg/controller.go
Do not emit events about services being skipped. Events about one controller processing the service and another skipping it, will be confusing for users.
> Skip processing non-ILB services in NEG controller.

- pkg/l4/l4controller.go
- pkg/neg/controller.go
Do not emit events about services being skipped. Events about one controller processing the service and another skipping it, will be confusing for users.
Copy of https://github.com/kubernetes/ingress-gce/pull/1552
> [1.13] Skip processing non-ILB services in NEG controller.

- pkg/l4/l4controller.go
- pkg/l4/l4controller_test.go
If a legacy external Forwarding rule is found, ILB processing should continue.
Cherrypick of https://github.com/kubernetes/ingress-gce/pull/1554
> [1.13] Only skip ILB processing if legacy ILB FR is found.

- pkg/l4/l4controller.go
- pkg/l4/l4controller_test.go
If a legacy external Forwarding rule is found, ILB processing should continue.
> Only skip ILB processing if legacy ILB FR is found.

- pkg/neg/controller.go
- pkg/neg/syncers/endpoints_calculator.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
The predicate function used for Instance groups should not check this - to prevent race with service controller. Removing nodes that are about to be upgraded can cause disruption for existing traffic, since non-subsetting ILBs do not configure connectionDraining.
This is a follow up of  https://github.com/kubernetes/ingress-gce/pull/1532 where the annotation check was introduced.
> Look for UPGRADE_NODES annotation only for ILB Subsetting.

- pkg/context/context.go
This adds a new lock instead of reusing healthcheck lock. Healthcheck lock is taken before running all the healthcheck functions ( for neg, l7, l4 controllers).
Since this happens periodically, it would be wasteful for event recorder to wait for the same lock.
Context - the healthcheck lock was renamed in https://github.com/kubernetes/ingress-gce/pull/413, but I think it makes sense to rename it back to a specific name given the frequency of the lock usage.
Verified with `go test -race` - failed before fix, passed after.
@spencerhance
> Add a lock for the recorders map.

- pkg/neg/controller.go
- pkg/neg/syncers/endpoints_calculator.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
The predicate function used for Instance groups should not check this - to prevent race with service controller.
Cherrypick of https://github.com/kubernetes/ingress-gce/pull/1564
> [1.13] Look for UPGRADE_NODES annotation only for ILB Subsetting.

- pkg/backends/integration_test.go
- pkg/backends/syncer_test.go
- pkg/healthchecks/healthchecks.go
- pkg/healthchecks/healthchecks_test.go
- pkg/translator/healthchecks.go
- pkg/translator/healthchecks_test.go
- HealthCheck.merge() and ToAlphaComputeHealthCheck() now optionally return errors
- merge() now returns an error if the specified protocol is invalid
Example error:
```
Warning  Sync    1s (x3 over 3s)     loadbalancer-controller  Error syncing to GCP: error running backend syncing routine: error ensuring health check: Protocol "http" is not valid, must be one of ["HTTP","HTTPS","HTTP2"]
```
Old error:
```
Health check "k8s1-xxx-yyy" update error: googleapi: Error 400: Invalid value for field 'resource.httpHealthCheck': ''. HTTP healthCheck missing., invalid
```
> Add errors to healthcheck merge() func

- pkg/l4/l4controller.go
- pkg/l4/l4controller_test.go
- pkg/loadbalancers/forwarding_rules.go
- pkg/loadbalancers/l4.go
- pkg/neg/controller.go
- pkg/neg/controller_test.go
- pkg/utils/utils.go
Cherrypick of 3 PRs - https://github.com/kubernetes/ingress-gce/pull/1545, https://github.com/kubernetes/ingress-gce/pull/1552, https://github.com/kubernetes/ingress-gce/pull/1554
Main target is 1.11 branch, cherrypicking in 1.12 for completeness.
> [1.12] Prevent race conditions between service and subsetting controllers.

- pkg/annotations/service.go
- pkg/annotations/service_test.go
- pkg/l4/l4controller.go
This could indicate that a NEG was created in a new zone, which requires a backend service link update.
When the service is created for the first time, the addition of the NEG annotation will result in one extra round of processing. 
> Process ILB service when NEG annotation changes.

- docs/deploy/gke/non-gcp/README.md
- pkg/annotations/ingress.go
- pkg/e2e/fixtures.go
- pkg/test/utils.go
"failure-domain.beta.kubernetes.io/zone" is deprecated in favor of "topology.kubernetes.io/zone" - https://kubernetes.io/docs/reference/labels-annotations-taints/
> Skip using deprecated zone label for Nodes.

- pkg/controller/controller.go
- pkg/controller/translator/translator.go
- pkg/controller/utils_test.go
- pkg/instances/fakes.go
- pkg/instances/instances.go
- pkg/instances/interfaces.go
- pkg/l4/l4controller.go
- pkg/neg/controller.go
- pkg/neg/controller_test.go
- pkg/neg/manager.go
- pkg/neg/syncers/endpoints_calculator.go
- pkg/neg/syncers/transaction.go
- pkg/neg/syncers/transaction_test.go
- pkg/neg/syncers/utils.go
- pkg/neg/syncers/utils_test.go
- pkg/neg/types/fakes.go
- pkg/neg/types/interfaces.go
- pkg/neg/types/simple_zone_getter.go
- pkg/neg/types/simple_zone_getter_test.go
- pkg/neg/types/types.go
- pkg/neg/types/types_test.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
In case of NEG reconcile/removal or instance group removal, the controller
should check all zones where the cluster has nodes. The current implementation
only checks zones where the cluster has ready/schedulable nodes.
Some failure cases that this change addresses:
1) An L4 NEG can be created in 2 zones - zone1, zone2. Now all nodes in zone2 become unready. Then one node in zone2 becomes ready. NEG will not update the node in zone2 since it will not retrieve the zone2 NEG.
2) NEG/Instance group deletion will not delete the NEG/IG from the zone which only has unready nodes, even though the empty NEG/IG will still exist.
> Include zones with unready nodes when listing zones.

- pkg/e2e/fixtures.go
We're moving away from google.com gcp projects. These images are now on community-owned infra.
Note that the porter image has been centralized into the agnhost image.
Related: https://github.com/kubernetes/k8s.io/issues/1522
> Updates E2E test images registry

- pkg/utils/utils.go
- pkg/utils/utils_test.go
This was allowed in service controller in https://github.com/kubernetes/kubernetes/pull/90823
Cherrypick of https://github.com/kubernetes/ingress-gce/pull/1537
> [1.11] Allow Unschedulable nodes to be part of the LB backends list.

- pkg/l4netlb/l4netlbcontroller_test.go
- pkg/loadbalancers/forwarding_rules.go
- pkg/loadbalancers/l4netlb.go
- pkg/test/utils.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
In L4NetLB NodePort is used by namer to create BackendService name.
Previously NodePort was not set and by default its value was 0 so
all backends had the same name and we there were error in creating
multiple services
To test NodePort set multi-services test were written
Change port ranges calculation for creating forwarding rule.
Previously we assigned first continue port Range from service,
now it is calculated from service assigned ports to
create boundary range MINPORT-MAXPORT.
> Fix ports in L4NetLB

- pkg/neg/controller.go
- pkg/neg/manager.go
- pkg/neg/manager_test.go
- pkg/neg/syncers/transaction.go
- pkg/neg/syncers/transaction_test.go
- pkg/neg/types/fakes.go
* VmIpPort NEGs should be synced when node change results in a zone
being added or removed
> Trigger sync for certain node changes

- pkg/neg/controller.go
- pkg/neg/manager.go
- pkg/neg/manager_test.go
- pkg/neg/syncers/transaction.go
- pkg/neg/syncers/transaction_test.go
- pkg/neg/types/fakes.go
* VmIpPort NEGs should be synced when node change results in a zone
being added or removed
* Node informer event handlers are initialized in all cases
> [Cherrypick #1600 into 1.13]  Trigger sync for certain node changes

- pkg/neg/controller.go
- pkg/neg/manager.go
- pkg/neg/manager_test.go
- pkg/neg/syncers/transaction.go
- pkg/neg/syncers/transaction_test.go
- pkg/neg/types/fakes.go
* VmIpPort NEGs should be synced when node change results in a zone
being added or removed
* Node informer event handlers are initialized in all cases
Cherrypick #1600 into release-1.11
> [Cherrypick #1600 into 1.11] Trigger sync for certain node changes

- pkg/backendconfig/backendconfig.go
- pkg/context/context.go
- pkg/crd/crd.go
- pkg/crd/crd_test.go
- pkg/crd/meta.go
- pkg/e2e/adapter/psc.go
- pkg/e2e/adapter/psc_test.go
- pkg/e2e/fixtures.go
- pkg/e2e/framework.go
- pkg/e2e/helpers.go
- pkg/experimental/workload/workload.go
- pkg/frontendconfig/frontendconfig.go
- pkg/ingparams/ingparams.go
- pkg/psc/controller.go
- pkg/psc/controller_test.go
- pkg/serviceattachment/serviceattachment.go
- pkg/svcneg/svcneg.go
PSC controller uses v1 ServiceAttachment CRD and client to process and manage service attachments
> PSC uses V1 ServiceAttachment

- pkg/neg/syncers/endpoints_calculator_test.go
- pkg/neg/types/fakes.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
Stop using the previous annotation that is only set for some GKE operations(surge upgrade).
The new label will be set by all gke nodepool operations.
> Exclude nodes that have GKE drain operation label, from LB backends.

- pkg/neg/syncers/endpoints_calculator_test.go
- pkg/neg/types/fakes.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
Stop using the previous annotation that is only set for some GKE operations(surge upgrade).
The new label will be set by all gke nodepool operations.
Cherrypick of https://github.com/kubernetes/ingress-gce/pull/1615 into release-1.14
> [1.14] Exclude nodes that have GKE drain operation label, from LB backends.

- pkg/backends/backends.go
- pkg/firewalls/firewalls_l4.go
- pkg/healthchecks/healthchecks_l4.go
- pkg/healthchecks/healthchecks_l4_test.go
- pkg/l4netlb/l4netlbcontroller_test.go
- pkg/loadbalancers/forwarding_rules.go
- pkg/loadbalancers/l4.go
- pkg/loadbalancers/l4_test.go
- pkg/loadbalancers/l4netlb.go
- pkg/loadbalancers/l4netlb_test.go
- pkg/utils/utils.go
When External or Internal L4 LoadBalancer creates a shared health check
it should set description indicating that this resource is shared
among all L4 LoadBalancers despise their type.
> Unified  health check description for ILB and XLB resource

- cmd/e2e-test/cdn_test.go
* Ensures that the regex `CDN` only matches old CDN test and that all
new tests only match regex `Cdn`
> Change ExpandedCDN to Cdn

- pkg/loadbalancers/l4.go
- pkg/loadbalancers/l4_test.go
- pkg/loadbalancers/l4netlb.go
- pkg/loadbalancers/l4netlb_test.go
- pkg/test/gcehooks.go
When L4 LoadBalancer is deleted (Internal or External) firewall rule was deleted upfront.
But when ExternalTrafficPolicy is set to Cluster health check is shared
among all ILB or XLB services and removing firewall rule will make those
services unreachable. So in service deletion we need to check if health
check is not in use by another service,
> Fix firewall rule deletion in L4 LBs

- hack/setup-local.sh
hack/setup-local.sh was failing if clusterName is too long, cause instance names created by gke truncated up to 24 characters
Also, node-instance-prefix should start from "gke-" but it was not, fixed
> Fix setup-local.sh for long cluster names

- pkg/l4lb/l4controller_test.go
- pkg/l4lb/l4netlbcontroller_test.go
- pkg/loadbalancers/l4.go
- pkg/loadbalancers/l4_test.go
- pkg/loadbalancers/l4netlb.go
- pkg/loadbalancers/l4netlb_test.go
- pkg/neg/types/interfaces.go
- pkg/neg/types/types.go
- pkg/neg/types/types_test.go
- pkg/test/utils.go
- pkg/utils/namer/interfaces.go
- pkg/utils/namer/l4_namer.go
- pkg/utils/namer/l4_namer_test.go
- pkg/utils/namer/namer.go
- pkg/utils/serviceport.go
Function creating names for ILB aligning with k8s2 convention is
VMIPNEG.
Since we use the same name for neg, backend service and firewall rules I
rename this function to L4Backend. Now we can use the same function for
NetLB services and NetLB does not use NEG so VMIPNEG name is not
suitable here.
> External and Internal Load Balancers backend should use the same k8s2 name convention

- pkg/backends/ig_linker_test.go
- pkg/backends/integration_test.go
- pkg/backends/regional_ig_linker_test.go
- pkg/controller/controller_test.go
- pkg/firewalls/fakes.go
- pkg/instances/fakes.go
- pkg/instances/instances_test.go
- pkg/neg/types/fakes.go
- pkg/psc/controller_test.go
- pkg/test/utils.go
- pkg/utils/utils.go
We are using FakeInstanceGroups from `pkg/instances/fakes.go` as a mock for testing interactions with GCE instance groups api.  
This PR rewrites FakeInstanceGroups so it can support multiple instance groups in multiple zones
This PR does not involve any production code changes, only test code changes
> Add multiple zones support to fake instance groups

- pkg/loadbalancers/address_manager.go
- pkg/loadbalancers/address_manager_test.go
- pkg/loadbalancers/forwarding_rules.go
- pkg/loadbalancers/l4netlb.go
This change is needed because I would like to add metric for IP addresses which are managed by controller and this metric will be collected in L4NetLb controller.
> Refactor Address Manager to return if address is managed by controller

- pkg/metrics/workqueue_metrics.go
This PR enables by default workqueue prometheus metric
for all controllers that run NamedQueue: Ingress, L4 and L4 RBS controllers.
> Enable workqueue metrics

- pkg/l4lb/l4controller.go
- pkg/l4lb/l4netlbcontroller.go
This is required to correctly track availability SLO when L4 NetLB Controller get's stuck
> Make L4 NetLB Cpntroller Healthcheck return error

- pkg/l4lb/l4netlbcontroller.go
- pkg/l4lb/l4netlbcontroller_test.go
In L4 RBS load balancer controller
1) remove service annotations, for  correct XLB->ILB transition when customer changes service annotations
2) try to delete the instance group to cleanup the instance group, this will
  - succeed when the last Service/LB using the instance group is deleted
  - fail if other L4/L7 load balancer is using the instance group
otherwise the IG can lea
> Improve RBS service deletion

- pkg/context/context.go
- pkg/flags/flags.go
- pkg/metrics/l4metrics_test.go
- pkg/metrics/metrics.go
- pkg/metrics/metrics_test.go
- pkg/neg/controller_test.go
- Add new flag for configuring metrics export.
- Modify tests to use naive fake for controller metrics 
This will allow us to increase export frequency to comply with sampling theorem: https://en.wikipedia.org/wiki/Nyquist%E2%80%93Shannon_sampling_theorem
> Add new flag for configuring metrics export frequency

- pkg/l4lb/l4controller.go
- pkg/l4lb/l4netlbcontroller.go
- pkg/l4lb/metrics/metrics.go
Do not restart controller after L4 healthcheck failure, publish metrics instead
After discussion offline we decide that restarting controller on single healthckeck failure may be too invasive and reduce the reliability. 
This PR undoes the https://github.com/kubernetes/ingress-gce/pull/1683 and replaces healthcheck failure error with metric to count the errors.
> Do not restart controller after L4 healthcheck failure, publish metrics instead

- docs/faq/README.md
link for cluster-setup.md in https://github.com/kubernetes/ingress-gce/tree/master/docs/faq#an-ingress-controller-e2e-is-failing-what-should-i-do section was broken
> corrected link for cluster-setup.md

- pkg/loadbalancers/target_proxies.go
- pkg/loadbalancers/url_maps.go
* Fixes a bug preventing the disabling and deletion of HttpsRedirects
due to UrlMap Ensure happening before the TargetProxy Ensure
* EnsureRedirectUrlMap() now does not return an error if deletion fails
* Prevents premature removal of the `redirect-url-map` annotation (which prevented deletion)
Our e2e test does not catch this because it wipes out the annotation on ingress update().  This will be fixed in a follow-up.
> Fix HttpsRedirects Lifecycle

- pkg/backends/ig_linker.go
- pkg/backends/ig_linker_test.go
- pkg/backends/regional_ig_linker.go
- pkg/backends/regional_ig_linker_test.go
- pkg/test/gcehooks.go
We should update backend service with ig llinks
only when ig links changed.
> Fix for backend service update

- pkg/l4lb/l4netlbcontroller_test.go
- pkg/loadbalancers/address_manager.go
- pkg/loadbalancers/address_manager_test.go
- pkg/loadbalancers/forwarding_rules.go
- pkg/loadbalancers/l4netlb.go
- pkg/loadbalancers/l4netlb_test.go
- pkg/metrics/features.go
- pkg/metrics/l4metrics_test.go
- pkg/metrics/metrics.go
- pkg/metrics/types.go
- pkg/test/gcehooks.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
There are errors related to Network Tier that are caused by User misconfigurations and they should be filtered out from ServicesInError metrics.
This errors are:
1. Ip address and forwarding rule Network Tier mismatch
2. User created service in Standard Tier and deleted the annotation, this action will changed desired service Network Tier to PREMIUM but IP address and forwarding rule should be tear down first because we cannot update Network Tier in this resources. We can tear down resources only when Network Tier from annotation mismatch with network tier in IP address or forwarding rule.
> Do not include User Errors in L4NetLBInError metric

- pkg/composite/metrics/metrics.go
Define Buckets in gce_api_request_duration_seconds metric to cover latencies from 5ms to 5 minutes+ 
The default buckets: `	DefBuckets = []float64{.005, .01, .025, .05, .1, .25, .5, 1, 2.5, 5, 10}`
defined in, github.com/prometheus/client_golang/prometheus/histogram.go
do not cover long running requests, e.g. backend service update takes 30-40 seconds.
> Add buckets to gce_api_request_duration_seconds metric

- pkg/instances/fakes.go
- pkg/instances/instances.go
- pkg/instances/instances_test.go
- pkg/l4lb/l4netlbcontroller.go
- pkg/l4lb/l4netlbcontroller_test.go
- pkg/test/utils.go
This fixes a bug for clusters bigger than instance group max size, cause we were trying to add more than allowed number of nodes to instance group and gcp api returned an error
> Truncate nodes list to maximum instance group size (1000) before adding to instance group

- pkg/context/context.go
- pkg/flags/flags.go
- pkg/l4lb/l4netlbcontroller.go
- pkg/loadbalancers/l4netlb.go
- pkg/metrics/l4metrics_test.go
- pkg/metrics/metrics.go
- pkg/metrics/types.go
Add resync timestamp to service metric state
When service sync ends with an error we wants to try to resync it for
some period of time and after that time if result is still error we will
increment L4NetLBSInError metric.
Retry period is fixed 20min. It is becasue resync period is 10min.
> Modify reporting error metrics from L4 RBS services -  only report service in error if resync deadline elapsed

- pkg/l4lb/l4netlbcontroller.go
- pkg/l4lb/l4netlbcontroller_test.go
- pkg/loadbalancers/l4netlb.go
- pkg/metrics/types.go
FirstSyncErrorTime was not set for failed synchronisation and while MetricController was exporting the metrics then it crashed because it tried to use nil value.
> Init first sync error time with transation start time

- docs/deploy/gke/README.md
Corrected broken link for gke-self-managed.sh in https://github.com/kubernetes/ingress-gce/tree/master/docs/deploy/gke#important-prerequisites
#1702
> corrected link for gke-self-managed.sh

- pkg/utils/endpointslices/index.go
- pkg/utils/endpointslices/index_test.go
* Service key may not be possible if EndpointSlice does not have all
the expected labels set, namely the service label. This is a valid
EPS and should be ignored when indexing. Returning an error causes
the store to panic. Instead return empty list of keys and no error,
so that the EPS is ignored.
> [Cherrypick #1733 into release-1.15] Do not return error if EndpointSlicesServiceKey func errors

- pkg/utils/endpointslices/index.go
- pkg/utils/endpointslices/index_test.go
* Service key may not be possible if EndpointSlice does not have all
the expected labels set, namely the service label. This is a valid
EPS and should be ignored when indexing. Returning an error causes
the store to panic. Instead return empty list of keys and no error,
so that the EPS is ignored.
> [Cherrypick #1733 into release-1.14] Do not return error if EndpointSlicesServiceKey func errors

- pkg/utils/endpointslices/index.go
- pkg/utils/endpointslices/index_test.go
* Service key may not be possible if EndpointSlice does not have all
the expected labels set, namely the service label. This is a valid
EPS and should be ignored when indexing. Returning an error causes
the store to panic. Instead return empty list of keys and no error,
so that the EPS is ignored.
> [Cherrypick #1733 into release-1.16] Do not return error if EndpointSlicesServiceKey func errors

- pkg/utils/endpointslices/index.go
- pkg/utils/endpointslices/index_test.go
* Service key may not be possible if EndpointSlice does not have all
the expected labels set, namely the service label. This is a valid
EPS and should be ignored when indexing. Returning an error causes
the store to panic. Instead return empty list of keys and no error,
so that the EPS is ignored.
> [Cherrypick #1733 in release-1.17] Do not return error if EndpointSlicesServiceKey func errors

- cmd/e2e-test/affinity_test.go
* tests are flaky because GCLB is taking over 10 minutes to apply the new
configuration
> Extend transition timeout to 15 min

- pkg/l4lb/l4lbcommon.go
- pkg/l4lb/l4netlbcontroller.go
- pkg/l4lb/l4netlbcontroller_test.go
- pkg/test/gcehooks.go
Fixing bug introduces in PR #1740: RBS annotation was not deleted from Target Pool services
> Fix preventTargetPoolToRBSMigration. Properly delete annotation

- pkg/firewalls/firewalls_l4.go
- pkg/l4lb/l4controller.go
- pkg/l4lb/l4lbcommon.go
- pkg/l4lb/l4netlbcontroller.go
- pkg/l4lb/l4netlbcontroller_test.go
- pkg/l4lb/metrics/metrics.go
- pkg/loadbalancers/l4syncresult.go
Clean up RBS resources if we found rbs finalizer and target pool
attached to the service
This expected to only happen during service creation, if user quickly adds rbs annotation after creating the legacy service, before target pool was provisioned
> Handle L4 ELB RBS controller race with legacy on service creation

- pkg/l4lb/l4netlbcontroller.go
Deleting annotations updates service configuration and other controllers
see this update. We should delete annotation last, so other controllers
see updated service with all other fields (especially finalizer) removed
> Delete RBS annotations as a last step on garbage collection

- pkg/firewalls/firewalls_l4.go
- pkg/loadbalancers/l4_test.go
- pkg/loadbalancers/l4netlb_test.go
L4 firewall's DestinationRanges was not being updated when the forwardingrule's IP was updated.
> Fix DestinationRanges update when IP changes

- cmd/glbc/main.go
- pkg/backends/ig_linker_test.go
- pkg/backends/integration_test.go
- pkg/backends/regional_ig_linker_test.go
- pkg/context/context.go
- pkg/controller/controller_test.go
- pkg/flags/flags.go
- pkg/instances/fakes.go
- pkg/instances/instances.go
- pkg/instances/instances_test.go
- pkg/l4lb/l4netlbcontroller_test.go
This is refactoring of NodePool, following from this https://github.com/kubernetes/ingress-gce/pull/1707
> Add maxIGSize to NodePool constructor, instead of using global flag

- pkg/l4lb/l4netlbcontroller.go
- pkg/l4lb/l4netlbcontroller_test.go
- pkg/loadbalancers/l4netlb.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
This is mostly copied from here https://github.com/kubernetes/ingress-gce/pull/1773
> Fix RBS crash, when getting NodePorts for Services without ports

- pkg/l4lb/l4netlbcontroller.go
- pkg/l4lb/l4netlbcontroller_test.go
- pkg/loadbalancers/l4netlb.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
Fix RBS crash, when getting NodePorts for Services without ports
> [Cherrypick #1774 in release-1.19]  Fix RBS crash, when getting NodePorts for Services without ports

- pkg/backends/features/securitypolicy.go
- pkg/backends/features/securitypolicy_test.go
Fix [issue](https://github.com/kubernetes/ingress-gce/issues/1706) #1706 BackendConfig.securityPolicy is not removed after config updates
> Fix BackendConfig.securityPolicy is not removed after config updates

- cmd/glbc/main.go
[issue #1713 ](https://github.com/kubernetes/ingress-gce/issues/1713) Migrate gce-ingress to LeasesResourceLock from ConfigMapsLeases
> Migrate gce-ingress to LeasesResourceLock from ConfigMapsLeases

- cmd/e2e-test/draining_test.go
- pkg/e2e/helpers.go
* Extend NEG GC timeout since regional cluster GC loops take longer
* Extend draining timeout as propagation latency can be greater than 10
minutes
* Create a ServiceAttachment specific timeout since ServiceAttachment
requires load balancer to come up as well as a service attachment and
may take longer than the NEG timeout
> Increase timeouts to reflect GCE API

- pkg/l4lb/l4netlbcontroller.go
- pkg/loadbalancers/forwarding_rules.go
- pkg/loadbalancers/l4.go
- pkg/loadbalancers/l4_test.go
- pkg/loadbalancers/l4netlb.go
- pkg/loadbalancers/l4netlb_test.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
Return values are independent, and there is no reason to do it in single function
> Split GetPortsAndProtocol function to 4 separate functions

- pkg/forwardingrules/forwarding_rules.go
- pkg/forwardingrules/forwarding_rules_test.go
- pkg/l4lb/intefaces.go
- pkg/l4lb/l4controller.go
- pkg/l4lb/l4netlbcontroller.go
- pkg/loadbalancers/forwarding_rules.go
- pkg/loadbalancers/interfaces.go
- pkg/loadbalancers/l4.go
- pkg/loadbalancers/l4netlb.go
- vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
- vendor/github.com/google/go-cmp/cmp/cmpopts/errors_go113.go
- vendor/github.com/google/go-cmp/cmp/cmpopts/errors_xerrors.go
- vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
- vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
- vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
- vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
- vendor/golang.org/x/xerrors/LICENSE
- vendor/golang.org/x/xerrors/PATENTS
- vendor/golang.org/x/xerrors/README
- vendor/golang.org/x/xerrors/adaptor.go
- vendor/golang.org/x/xerrors/codereview.cfg
- vendor/golang.org/x/xerrors/doc.go
- vendor/golang.org/x/xerrors/errors.go
- vendor/golang.org/x/xerrors/fmt.go
- vendor/golang.org/x/xerrors/format.go
- vendor/golang.org/x/xerrors/frame.go
- vendor/golang.org/x/xerrors/go.mod
- vendor/golang.org/x/xerrors/internal/internal.go
- vendor/golang.org/x/xerrors/wrap.go
- vendor/modules.txt
This separates "business" logic of creating forwarding rules for our controllers, from interacting with forwarding rules in google cloud
This removes copy pasted code between l4 ilb and l4 elb
> Create Forwarding Rules provider

- pkg/loadbalancers/l4_test.go
> cleanup l4 tests

- pkg/healthchecks/healthchecks_l4.go
- pkg/l4lb/l4controller_test.go
- pkg/l4lb/l4netlbcontroller_test.go
- pkg/loadbalancers/l4_test.go
- pkg/loadbalancers/l4netlb_test.go
- pkg/utils/namer/interfaces.go
- pkg/utils/namer/l4_namer.go
- pkg/utils/namer/l4_namer_test.go
Before we used single function to get L4 Health Check and L4 Health Check Firewall name
It is better to split it to separate functions
> Extract to separate function L4HealthCheckFirewall from L4 namer L4HealthCheck

- pkg/backends/ig_linker.go
- pkg/backends/neg_linker.go
- pkg/loadbalancers/addresses.go
- pkg/loadbalancers/certificates.go
- pkg/loadbalancers/forwarding_rules.go
- pkg/loadbalancers/l4.go
- pkg/loadbalancers/l4_test.go
- pkg/loadbalancers/l4netlb.go
- pkg/loadbalancers/l4netlb_test.go
- pkg/loadbalancers/l7.go
- pkg/loadbalancers/l7s.go
- pkg/loadbalancers/target_proxies.go
- pkg/loadbalancers/url_maps.go
- pkg/neg/syncers/transaction.go
- pkg/ratelimit/ratelimit.go
Cleanup code:
- get rid of one letter variables named 'L/l/I/|/!/1'
- removed unused parameters from assert func in l4 tests
- split l4//l7 neg endpoint calculators into separate files
- refactor l4 neg calculator
no business logic or test logic has been changed in this commit
> Cleanup code

- pkg/neg/controller.go
- pkg/neg/manager.go
- pkg/neg/manager_test.go
- pkg/neg/types/types.go
* Propagate node update events for both NEG types (GCE_VM_IP_PORT + GCE_VM_IP)
* Configure separate zoneMaps for the NEG types (`vmIpZoneMap` and `vmIpPortZoneMap`). These zoneMaps will be updated using the same predicate function that is eventually used inside `transactionSyncer.isZoneChange()` for the respective NEG types.
* Introduce a new function `NodePredicateForNetworkEndpointType` that will be the source of truth for the type of predicate function to be used for a given NEG type.
For future reference, here's another related PR: https://github.com/kubernetes/ingress-gce/pull/1600
> Fix creation of NEGs in the new zone when cluster spans to the new zone

- pkg/loadbalancers/l4netlb.go
We were deleting address with the name of backend service, but actually,
address will have a name of forwarding rule
> Fix deleting address in RBS

- cmd/e2e-test/readme.md
Adds more information on running the ILB e2e tests and update some of args information.
> Update e2e-test README

- pkg/forwardingrules/forwarding_rules.go
- pkg/forwardingrules/forwarding_rules_test.go
Move createKey to the bottom, change tests variable names
This fixes are taken from health checks provider review comments https://github.com/kubernetes/ingress-gce/pull/1763
> Reformat forwarding rules provider

- cmd/glbc/main.go
- pkg/healthchecks/interfaces.go
- pkg/healthchecksl4/healthchecksl4.go
- pkg/healthchecksl4/healthchecksl4_test.go
- pkg/healthchecksl4/interfaces.go
- pkg/healthchecksprovider/healthchecksprovider.go
- pkg/healthchecksprovider/healthchecksprovider_test.go
- pkg/l4lb/l4controller_test.go
- pkg/l4lb/l4netlbcontroller_test.go
- pkg/loadbalancers/l4.go
- pkg/loadbalancers/l4_test.go
- pkg/loadbalancers/l4netlb.go
- pkg/loadbalancers/l4netlb_test.go
This separates business logic of managing L4 HealthChecks and interacting with Google Cloud API
We want to achieve following layered level logic
l4controller (handles workqueue for l4 services) -> l4 (for single service) -> l4healthchecks (health checks business logic) -> healthchecksprovider (no business logic, only interaction with gcp)
This makes composition better, testing and mocking should be also easier in the long run
> Create Health Checks Provider to interact with Google Cloud

- pkg/loadbalancers/l4_test.go
Split assertInternalLbResourcesDeleted function in l4_test to smaller functions which separately check that forwarding rule, health check, firewall etc were deleted
> Refactor l4_test assertInternalLbResourcesDeleted function

- pkg/loadbalancers/l4.go
- pkg/loadbalancers/l4_test.go
- pkg/utils/namer/interfaces.go
- pkg/utils/namer/l4_namer.go
- pkg/utils/namer/l4_namer_test.go
Currently, we using everywhere L4Backend() as a name for Firewall. It is a bit confusing, and can be handled on the level of namer, so this PR adds L4Firewall which returns result from L4Backend
I can not easily find and fix all the places in the test, where we still use L4Backend as name for Firewall, but I think it is not a big problem, and we will gradually fix it
> Add L4Firewall to namer, instead of using L4Backend

- pkg/healthchecksl4/healthchecksl4.go
- pkg/healthchecksl4/interfaces.go
- pkg/l4lb/l4netlbcontroller_test.go
- pkg/loadbalancers/l4.go
- pkg/loadbalancers/l4_test.go
- pkg/loadbalancers/l4netlb.go
1) Moved functions to be defined in order of execution
2) Renamed EnsureHealthCheck -> EnsureHealthCheckWithFirewall, DeleteHealthCheck -> DeleteHealthCheckWithFirewall
No functional changes, just small refactoring
This is needed for Dual-Stack https://github.com/kubernetes/ingress-gce/pull/1782, but doing this in separate PR
> Refactor healthchecksl4, change functions order, rename functions

- build/test.sh
This flag was deprecated, and does not seam to give any improvement https://github.com/golang/go/issues/41696
> Remove go test command with -i flag, cause it was deprecated

- .golangci.yaml
- cmd/404-server-with-metrics/server-with-metrics.go
- cmd/echo/app/handlers.go
- cmd/fuzzer/fuzzer.go
- cmd/glbc/app/handlers.go
- cmd/workload-daemon/main.go
Add handling errors where it was missing
> Fix errcheck linter for all non-test files

- pkg/healthchecksl4/healthchecksl4.go
This improves debugging and logging
Some health checks are intended to be shared and will fail on deletion, but some can fail in the same way, even they were not intended to be shared, but user misconfigured it and attached to some resources, so it is useful to log if health check was intended to be shared
> Log if health check intended shared on deletion

- pkg/loadbalancers/l4_test.go
Instead of checking that len(firewall.SourceRanges) != 0 check that it actually has expected ranges
> Add checking for firewall source ranges in l4_test

- pkg/loadbalancers/forwarding_rules.go
- pkg/loadbalancers/l4.go
- pkg/loadbalancers/l4_test.go
We were trying to delete address with backend service name, but we only reserve address with forwarding rule name
> Fix deletion of address in l4

- pkg/l4lb/l4controller_test.go
This is removing bool parameter expectStatus, and instead splitting function `validateSvcStatus` into 2 functions `verifyILBServiceProvisioned` and `verifyILBServiceNotProvisioned`
This will also help to write Dual-Stack tests
> Small refactor of l4controller_test assertions 

- cmd/e2e-test/customresponseheaders_test.go
- pkg/fuzz/helpers.go
> Add Custom response header e2e test

- cmd/glbc/main.go
- pkg/context/context.go
- pkg/flags/flags.go
- pkg/l4lb/l4controller.go
- pkg/l4lb/l4netlbcontroller.go
- pkg/l4lb/l4netlbcontroller_test.go
Before this change there was only one flag "num-l4-workers" to keep a count of internal and external L4 load balancer goroutines. It's better to have 2 separate flags so the new "num-net-l4-workers" flag was added.
> Add a new NetL4LB flag

- pkg/loadbalancers/l4_test.go
- pkg/loadbalancers/l4netlb.go
- pkg/loadbalancers/l4netlb_test.go
- pkg/loadbalancers/l4testutils.go
- Split l4netlb_test assertions by functions
- Move common l4_test, l4netlb_test assertions to l4testutils
This will also make it easier to add dual-stack tests to l4netlb in the future
/assign @kl52752
> Refactor l4 tests

- pkg/l4lb/l4netlbcontroller.go
- pkg/loadbalancers/l4netlb.go
- pkg/loadbalancers/l4netlb_test.go
It is better to have single source of naming, which is L4Namer in l4netlb
This PR changes getting Backend Service name and Firewall name with using namer, instead of ServicePort
This PR also helps to add DualStack implementation 
/assign @kl52752
> Use namer.L4Firewall and namer.L4Backend instead of servicePort

- cmd/e2e-test/ilb_test.go
- pkg/e2e/fixtures.go
- pkg/loadbalancers/l7.go
- pkg/loadbalancers/loadbalancers_test.go
Previously this was not allowed by the L7-ILB, but now it is. Sharing the same VIP can be used only when specifying a static VIP.
> Add Ingress Support for L7-ILB HTTP+HTTPS on same LB

- cmd/glbc/main.go
- pkg/healthchecksl4/healthchecksl4.go
- pkg/l4lb/l4controller_test.go
- pkg/l4lb/l4netlbcontroller_test.go
- pkg/loadbalancers/l4.go
- pkg/loadbalancers/l4_test.go
- pkg/loadbalancers/l4netlb.go
- pkg/loadbalancers/l4netlb_test.go
Removed shared global struct, instead only use shared mutex 
for fake, return healthchecks instance with independent mutex
I also want to make our package pass go test -race, and current fake approach makes it fail
> Change healthchecksl4 sync mechanism

- pkg/healthchecksl4/healthchecksl4.go
- pkg/healthchecksl4/healthchecksl4_test.go
According to l4 healthcheck constants
the default set up has timeout = 8 seconds
and threshold = 3 times. As result it can
lead to 24 (8*3) seconds of lost requests.
This change is supposed to decrease this
time to only 6 seconds.
> Change l4 healthcheck timeout

- pkg/healthchecksl4/healthchecksl4_test.go
The deleted test was duplicating
other 2 tests:
* TestHealthcheckInterval
* TestHealthcheckUnhealthyThreshold
> Delete L4LB healthcheck test

- pkg/l4lb/metrics/metrics.go
Current buckets definitions are too high, all events fall before first bucket.
> Add more L4 latency metrics

- pkg/healthchecks/healthchecks_l4.go
- pkg/healthchecks/healthchecks_l4_test.go
This change cherry-picks functionality from master to the v1.14.8 to create a new patch v1.14.9 with changed healthcheck constants 
According to l4 healthcheck constants
the default set up has timeout = 8 seconds
and threshold = 3 times. As result it can
lead to 24 (8*3) seconds of lost requests.
This change is supposed to decrease this
time to only 6 seconds for sharedHc=false.
> [Cherrypick #1828] l4 healthcheck timeouts change

- pkg/neg/controller_test.go
In general, I want to make all unit tests pass with -race, this is 1 step towards 
Current approach with `ports` variable in neg tests has race, cause we use global variable, and we modify it from different tests
/assign swetharepakula
/cc code-elinka
/cc aojea
> Fix ports read/write races in neg tests

- pkg/healthchecksl4/healthchecksl4_test.go
This just exercise the new thresholds added depending on the shared value (local/cluster)
Lot of boilerplate instead of making the test dynamic for simplicity
> increase test coverage

- pkg/backends/backends.go
- pkg/backends/regional_ig_linker_test.go
- pkg/healthchecksl4/healthchecksl4.go
- pkg/instances/instances.go
- pkg/l4lb/l4lbcommon.go
- pkg/l4lb/l4netlbcontroller.go
- pkg/loadbalancers/forwarding_rules.go
- pkg/loadbalancers/l4.go
- pkg/loadbalancers/l4_test.go
- pkg/loadbalancers/l4netlb.go
This should not introduce any change in logic, but involves some refactoring
I've tried to split it by multiple commits
> Add more logs to L4 NetLB

- cmd/404-server-with-metrics/server-with-metrics.go
Add to 404 server with metrics the functionality to return status code. The status code to return is given in the URL path of request in the format of /statuscode/<code>, e.g. /statuscode/500 .
> Add statusCodeHandler to 404-server-with-metrics which serves status code given in URL path

- pkg/l4lb/l4netlbcontroller.go
I've added this event in https://github.com/kubernetes/ingress-gce/pull/1845 thinking it will give more info,
but I found out that proper update event is emitted in needsUpdate function, emitting event on top level will spam events even on periodic enqueues, which we don't want
> Remove emitting Update event on top-level in L4 NetLB

- cmd/glbc/main.go
- pkg/backends/ig_linker.go
- pkg/backends/ig_linker_test.go
- pkg/backends/integration_test.go
- pkg/backends/regional_ig_linker.go
- pkg/backends/regional_ig_linker_test.go
- pkg/context/context.go
- pkg/controller/controller.go
- pkg/controller/controller_test.go
- pkg/controller/utils.go
- pkg/controller/utils_test.go
- pkg/instancegroups/controller.go
- pkg/instancegroups/controller_test.go
- pkg/instancegroups/fakes.go
- pkg/instancegroups/interfaces.go
- pkg/instancegroups/manager.go
- pkg/instancegroups/manager_test.go
- pkg/l4lb/l4netlbcontroller.go
- Rename instances package -> instancegroups. This package controls instance groups, not "instances" themselves, similar to "neg" package
- Move controller/node.go out of l7 controller, but to instancegroups package (cause it is used not only for l7, but also for l4)
- Unexport only internal methods, rename functions for clarity
> Refactor instances package, move node controller out of l7

- pkg/l4lb/l4controller.go
- pkg/loadbalancers/l4.go
- pkg/metrics/l4metrics_test.go
- pkg/metrics/metrics.go
- pkg/metrics/types.go
This PR adds counting service per ipFamilies, ipFamilyPolicy and Status for L4 ILB DualStack
Count will be stored in a map where key is struct 
```
type L4ILBDualStackServiceState struct {
// IPFamilies stores spec.ipFamilies of Service
IPFamilies string
// IPFamilyPolicy specifies spec.IPFamilyPolicy of Service
IPFamilyPolicy string
// Status specifies status of L4 ILB DualStack
Status L4ILBDualStackServiceStateStatus
}
```
> Add L4 ILB Dual-Stack Metrics

- pkg/crd/crd.go
- pkg/crd/crd_test.go
The glbc component needs to get a CRD and have permission to read it, this is not inmidiate when bootstrapping a cluster so, instead of crashing and depending on a external component to restart the pod, we can active poll on this conditions before crashing.
This has the benefit of reducing the noise on the logs with panics, that may be misinterpreted by external tools processing the logs. It also improves the bootstrap latency.
We can observe this behavior in any of the jobs
```
F1112 06:42:03.275192       1 main.go:115] Failed to ensure BackendConfig CRD: failed to verify the existence of BackendConfig CRD: customresourcedefinitions.apiextensions.k8s.io "backendconfigs.cloud.google.com" is forbidden: User "system:controller:glbc" cannot get resource "customresourcedefinitions" in API …
```
> wait on startup to get permissions

- cmd/e2e-test/ilb_test.go
- pkg/e2e/fixtures.go
In addition to fixing the e2e func, the following fixes are included in the addl. commits:
* Fix TestILBStaticIP bug where the annotations were not being applied by using the newly fixed EnsureIngress() func instead.
* Fix a missing negAnnotation in the ILB e2e test.
> Update e2e.EnsureIngress() to check Annotations in addition to Spec

- pkg/neg/syncers/endpoints_calculator.go
- pkg/neg/syncers/endpoints_calculator_test.go
- pkg/neg/syncers/transaction.go
- pkg/neg/syncers/transaction_test.go
- pkg/neg/syncers/utils.go
- pkg/neg/syncers/utils_test.go
- pkg/neg/types/interfaces.go
Add check to make sure the total number of endpoints from EndpointDataequals to the number of endpoints from endpointPodMap. If not, the syncer will enter the error state. 
EndpointData may contain duplicated endpoint, but endpointPodMap removes the duplicated endpoints, and dupCount stores the number of duplicated it removed. We compare the endpoint counts with duplicates.
Change the function definition of NetworkEndpointsCalculator.CalculateEndpoints() to return another variable that represents the count of duplicated endpoints.
> Add check for endpoint counts equal

- cmd/e2e-test/main_test.go
- cmd/e2e-test/run.sh
- pkg/e2e/fixtures.go
- pkg/e2e/framework.go
This is an optional field that is necessary for ILB tests running in clusters that are not using the "default" network and subnet.
Tested in an example VM.
> Adds Subnet field to e2e-test

- pkg/neg/syncers/transaction.go
- pkg/neg/syncers/transaction_test.go
Check if EndpointSlice has missing or invalid data zone/nodeName. If so, the syncer will enter the error state.
> Add check for invalid or missing data in EPS

- pkg/neg/syncers/transaction.go
- pkg/neg/syncers/transaction_test.go
Add check to make sure neither the total number of endpoints from EPS or the one from calculated endpoint list is 0. If not, the syncer will enter the error state.
> Add check for endpoint count is zero

- pkg/neg/syncers/transaction.go
- pkg/neg/syncers/transaction_test.go
Add check to make sure attach/detach endpoint operations are not failed due to invalid endpoint batch information. If so, the syncer will enter the error state.
> Add check for attach/detach API error

- pkg/e2e/fixtures.go
This is a fix for a bug triggered by this PR: https://github.com/kubernetes/ingress-gce/pull/1867
The subnet needs to be provided as a full resource path.
```
--- PASS: TestILBStaticIP (2287.03s)
--- PASS: TestILBStaticIP/ilb-static-ip (2287.03s)
--- PASS: TestILBStaticIP/ilb-static-ip/Transition-0 (270.95s)
--- PASS: TestILBStaticIP/ilb-static-ip/Transition-1 (31.01s)
--- PASS: TestILBStaticIP/ilb-static-ip/Transition-2 (30.99s)
```
> Change e2e regional address to use full subnet path

- pkg/l4lb/l4netlbcontroller.go
- pkg/l4lb/l4netlbcontroller_test.go
NetLB RBS Controller: Change needsDeletion and shouldProcessService logic 
1) only process if old or new version of the service was/is RBS
2) only delete if service has RBS annotation/finalizer/forwarding rule, even if the type changed from LoadBalacer to other type
This will make controller cleanup RBS resources in case service type changed.
This PR builds on top of pull/1879 from @panslava
> NetLB controller: cleanup RBS resources in case service type changed

- pkg/l4lb/l4netlbcontroller.go
- pkg/l4lb/l4netlbcontroller_test.go
This fixes issue, that on switching Service Type from LoadBalancer to ClusterIP or NodePort, RBS resources were not cleaned up
> Fix L4 NetLB RBS cleanup when Service Type changed

- pkg/l4lb/l4netlbcontroller.go
- pkg/l4lb/l4netlbcontroller_test.go
[Cherrypick #1879] cherry pick service type transision fix to release 1.20
NetLB RBS Controller: Change needsDeletion and shouldProcessService logic
1) only process if old or new version of the service was/is RBS 2) only delete if service has RBS annotation/finalizer/forwarding rule, even if the type changed from LoadBalacer to other 3) added 2 test cases for service type change (external name, empty value)
> [Cherrypick #1879] cherry pick service type transision fix to release 1.20

- pkg/instancegroups/manager.go
Fixing the mess I created
This reverts commit 21a9e0a79473032a434a120ce99ff5aab56e5a95.
> Revert "Don't log all node names"

- pkg/loadbalancers/address_manager.go
- pkg/loadbalancers/address_manager_test.go
- pkg/loadbalancers/forwarding_rules.go
- pkg/loadbalancers/forwarding_rules_test.go
- pkg/test/gcehooks.go
- pkg/utils/utils.go
Change the errors caused by user misconfiguring the Load Balancer IP in cases where:
- the requested LB external IP is not reserved in the project
- attempting to use an IP already used by another LB
- attempting to use a reserved IP of another type (internal IP).
This will affect numbers reported in the metrics, marking the above errors as user errors.
> NetLB: Treat LoadBalancer IP setup errors as user errors.

- pkg/loadbalancers/address_manager.go
- pkg/loadbalancers/address_manager_test.go
- pkg/loadbalancers/forwarding_rules.go
- pkg/loadbalancers/forwarding_rules_test.go
- pkg/test/gcehooks.go
- pkg/utils/utils.go
[Cherrypick #1890] Cherrypick metric user errors fix to release 1.20
NetLB: Treat LoadBalancer IP setup errors as user errors.
(cherry picked from commit 810ebc9d33fa89d8a68a9adda0499087bfd38667)
> [Cherrypick #1890] Cherrypick metric user errors fix to release 1.20

- pkg/loadbalancers/l4.go
- pkg/loadbalancers/l4_test.go
- pkg/loadbalancers/l4netlb.go
- pkg/loadbalancers/l4netlb_test.go
- pkg/utils/sourceranges.go
- pkg/utils/sourceranges_test.go
- pkg/utils/utils.go
- Introduce custom error type, to identify user errors
- Cover with unit tests (was not done in old helper)
- Needed to add IPv6 support later (in next PR)
> Reimplement getting load balancer source ranges

- pkg/loadbalancers/l4.go
- pkg/loadbalancers/l4_test.go
- pkg/loadbalancers/l4ipv6.go
- pkg/loadbalancers/l4netlb.go
- pkg/loadbalancers/l4netlb_test.go
- pkg/utils/sourceranges.go
- pkg/utils/sourceranges_test.go
Continuing https://github.com/kubernetes/ingress-gce/pull/1896
This adds support for IPv6 values in loadBalancerSourceRanges
We will filter out only IPv4 CIDRs for IPv4 source ranges, and IPv6 CIDRs for IPv6 source ranges
> Add support for IPv6 values in loadBalancerSourceRanges

- pkg/instancegroups/manager.go
- pkg/l4lb/l4netlbcontroller.go
- pkg/l4lb/l4netlbcontroller_test.go
NodePorts are not needed for NetLB RBS and were copied from legacy implementation. They were also slowing down our controller, because we were updating same instance group with node port for every service
> Remove using node ports for L4 NetLB RBS Services

- pkg/utils/utils.go
If user tries to create IPv6 ILB in subnetwork, which does not have internal IPv6 addresses, this call https://github.com/panslava/ingress-gce/blob/master/pkg/loadbalancers/forwarding_rules_ipv6.go#L67 will return following error
ensureIPv6Resources: Failed to ensure ipv6 forwarding rule - googleapi: Error 400: Invalid value for field 'resource.subnetwork': 'https://www.googleapis.com/compute/v1/projects/.../regions/us-west3/subnetworks/v6-ext-subnet'. Subnetwork does not have an internal IPv6 IP space which is required for IPv6 L4 ILB forwarding rules., invalid
We should count such errors as user ones
I also not really sure, if the approach I did is good -- checking string matching on the very end of sync loop. 
Alternatively, we could do this string matching checking straight after …
> Add IsSubnetworkMissingIPv6GCEError to User Errors

- pkg/neg/syncers/transaction.go
- pkg/neg/syncers/transaction_test.go
- pkg/neg/syncers/utils.go
Consolidate EndpointSlice nodeName and zone check, and flip checking logic for better readability.
Return error if nodeName or zone is missing when CalculateEndpoints, and check for error state based on the returned error. Add check for case when nodeName is set to be empty string. Flip invalid check to valid check.
> Clean up error state checking

- hack/verify-all.sh
- hack/verify-gofmt.sh
- hack/verify-govet.sh
- hack/verify-lint.sh
otherwise the scripts fails because `pipefail` is a bash only thing
```
hack/verify-all.sh
hack/verify-all.sh: 19: set: Illegal option -o pipefail
make: *** [Makefile:68: verify] Error 2
+ EXIT_VALUE=2
```
> use bash for verify scripts

- pkg/l4lb/l4controller.go
- pkg/l4lb/l4controller_test.go
- pkg/metrics/types.go
Currently all dual stack errors are not distinguished between user errors and controller failure. This is required to set up proper alerts
At first we should merge this https://github.com/kubernetes/ingress-gce/pull/1897
> Add UserError Status to ILB DualStack metrics

- pkg/annotations/gce_annotations.go
- pkg/annotations/service.go
Remove the dependency on legacy-cloud-providers for pkg/annotations/service.go
to facilitate import into google3 as this library does not exist in google3.
> Inline dependency on legacy-cloud-providers

- cmd/e2e-test/neg_test.go
- pkg/e2e/fixtures.go
With this commit, you can run the NEG tests for Windows with: -test.run=TestWindowsNEG.
> NEG: Add wrappers for NEG Windows test.

- pkg/l4lb/l4controller.go
- pkg/l4lb/l4controller_test.go
Currently, updating ipFamilies do not trigger L4 ILB service update. This is a bug fix
/assign mmamczur
> Trigger updating DualStack ILB Service if ipFamilies changed

- pkg/flags/flags.go
With short resync period, when running locally, it is easy to miss bugs, when service update is not triggered, but service is quickly updated due to resync period (example https://github.com/kubernetes/ingress-gce/pull/1928) 
/assign aojea
> Change resync period to 10 minutes

- pkg/neg/readiness/poller.go
- pkg/neg/readiness/poller_test.go
This change introduces delay for health checks in NEG polling to avoid busy waiting and quota exceeded errors.
> Add delay for retrying NEG polling for unhealthy pods

- Makefile
- build/build.sh
- build/rules.mk
- build/test.sh
Alpine image doesn't have gcc installed, that is required if we want to test with the race detector.
It also uses muslc instead of libc, that use to be conflictive with network features.
Switching to the ubuntu images, we have to explicitly use `bash`, since ubuntu defaults `sh` to `dash`, that doesn't support some bashism like `set -o pipefail`
In addition, remove the BASEIMAGE variable that doesn't seem to be used anywhere, a `grep` with current state doesn't show any match.
> don't use alpine for testing

- pkg/neg/controller.go
- pkg/neg/controller_test.go
> Remove Services.Get() from syncNegStatusAnnotation()

- pkg/neg/controller.go
- pkg/neg/controller_test.go
Cherry pick from #1926
Optimize Neg Controller
Note:
I have created this cherry pick MANUALLY  from PR/1926 as it is almost impossible to use merge tools after code has diverged so far
> [Cherry pick #1926] Remove Services.Get() from syncNegStatusAnnotation()

- pkg/instances/instances.go
- pkg/l4lb/l4netlbcontroller.go
- pkg/l4lb/l4netlbcontroller_test.go
[Cherry pick #1907] to release 1.20 Remove using node ports for L4 NetLB RBS Services
NodePorts are not needed for NetLB RBS and were copied from legacy implementation. They were also slowing down our controller, because we were updating same instance group with node port for every service
> [Cherry pick #1907] to release 1.20 Remove using node ports for L4 NetLB RBS Services

- pkg/cmconfig/controller.go
Instead of doing a Get to the apiserver use the informer cache
> configmapcontroller use the informer cache

- cmd/glbc/main.go
- pkg/context/context.go
- pkg/flags/flags.go
- pkg/healthchecksl4/healthchecksl4.go
- pkg/l4lb/l4lbcommon.go
- pkg/l4lb/l4netlbcontroller.go
- pkg/l4lb/l4netlbcontroller_test.go
- pkg/loadbalancers/forwarding_rules.go
- pkg/loadbalancers/forwarding_rules_ipv6.go
- pkg/loadbalancers/forwarding_rules_test.go
- pkg/loadbalancers/l4.go
- pkg/loadbalancers/l4_test.go
- pkg/loadbalancers/l4ipv6.go
- pkg/loadbalancers/l4netlb.go
- pkg/loadbalancers/l4netlb_test.go
- pkg/loadbalancers/l4netlbipv6.go
- pkg/loadbalancers/l4netlbipv6_test.go
- pkg/loadbalancers/l4syncresult.go
- pkg/test/utils.go
- pkg/utils/namer/l4_namer.go
Add support for `spec.ipFamilies` and `spec.ipFamiliyPolicy` in L4 NetLB
- Add new feature-flag `--enable-l4netlb-dual-stack`, all the new logic is hidden behind it
- Support all the transitions between ipFamilies, controller sync will provide resources for required ipFamily and clean resources for not required, but only if they exist in annotations
- On service deletion, clean up all the resources, no matter if they exist in annotations
> Add Dual-Stack support to L4 NetLB

- Dockerfile.e2e-test
To support multiarch, e2e-test dockerfile
should have non-arch dependant packages.
> Change e2e-test dockerfile

- pkg/neg/metrics/metrics.go
- pkg/neg/syncers/transaction.go
Added metrics to track the sync staleness of NEG syncers, where staleness is defined as how long since the syncer last syncs.
> Add metrics to track syncer staleness

- pkg/neg/metrics/metrics.go
- pkg/neg/syncers/transaction.go
Added metrics to track the sync staleness of endpointslices, where staleness is defined as how long since it has been last processed.
> Add metrics to track endpointslice staleness

- pkg/neg/metrics/neg_metrics_collector.go
- pkg/neg/types/sync_results.go
Define NegSyncResult to store the result of sync and the error encountered.
> Define sync results

- pkg/l4lb/l4controller.go
- pkg/l4lb/l4netlbcontroller.go
- pkg/loadbalancers/l4.go
- pkg/loadbalancers/l4netlb.go
- pkg/metrics/l4metrics_test.go
- pkg/metrics/metrics.go
- pkg/metrics/types.go
This PR adds counting service per ipFamilies, ipFamilyPolicy and Status for L4 NetLB DualStack
As ILB and NetLB DualStack metrics store the same data, I changed type L4ILBDualStackServiceState to be just general L4DualStackServiceState
I will add PersistentError (status to report after 20 mins of errors) in the next PR for both ILB and NetLB
> Add L4 NetLB Dual-Stack Metrics

- pkg/neg/syncers/transaction.go
- pkg/neg/syncers/transaction_test.go
- pkg/neg/types/sync_results.go
Add a waitgroup that waits for the completeness of all NEG operations.
> Refactor syncNetworkEndpoints

- pkg/neg/syncers/transaction.go
Initialize one waitGroup for each sync now to avoid race condition due to multiple syncs all work on the same waitGroup.
> Fix waitGroup race condition bug

- pkg/l4lb/l4controller.go
- pkg/l4lb/l4netlbcontroller.go
do no report multiple times the same case of late sync
> improve L4FailedHealthCheckCount metric 

- pkg/l4lb/l4controller_test.go
- pkg/loadbalancers/l4.go
- pkg/loadbalancers/l4netlb.go
- pkg/metrics/l4metrics_test.go
- pkg/metrics/metrics.go
- pkg/metrics/types.go
Report PersistentError if service is in Error after 20 minutes of
retries
Should be merged after NetLB Metrics https://github.com/kubernetes/ingress-gce/pull/1937
> Add new metric status PersistentError for L4 DualStack

- pkg/l4lb/l4controller.go
- pkg/l4lb/l4netlbcontroller.go
- pkg/l4lb/metrics/metrics.go
Add a new metric, similar to L4 ILB, NetLB Latency, which will report latencies if L4 DualStack enabled, with ipfamilies as a new label
Should be merged after https://github.com/kubernetes/ingress-gce/pull/1937
> Add L4 DualStack Sync Latency metrics

- pkg/neg/metrics/neg_metrics_collector.go
- pkg/neg/types/endpoint_stat.go
Define SyncerEPStat to store the count of endpoint and endpoint slices in different states. Define the states for endpoint and endpoint slices.
> Define endpoint state

- pkg/loadbalancers/target_proxies.go
If you delete the FrontendConfig before the redirectUm is cleaned up, the FrontendConfig will be nil and l7.redirectUm will not be, leading to an "unrecoverable" crash loop. The only fix is to manually update the target proxy's link to the original urlmap.
> Add nil check for FrontendConfig in checkProxy()

- pkg/neg/controller.go
- pkg/neg/metrics/neg_metrics_collector.go
- pkg/neg/syncers/transaction.go
- pkg/neg/syncers/transaction_test.go
- pkg/neg/syncers/utils.go
- pkg/neg/types/sync_results.go
Created sync metrics collector to collect sync related metrics. Added metrics to collect the cumulative count of sync results. Specified metrics emit interval in flags.go.
> Add metrics for sync result

- pkg/neg/metrics/neg_metrics_collector.go
Added metrics to collect the current count of syncers in each status.
> Add metrics for syncer states

- pkg/neg/controller.go
- pkg/neg/metrics/neg_metrics_collector.go
- pkg/neg/syncers/transaction.go
- pkg/neg/syncers/transaction_test.go
- pkg/neg/syncers/utils.go
> Revert "Add metrics for sync result"

- pkg/metrics/workqueue.go
Some events related to NEG workqueues take subsecond time for completion. Having more buckets within the 1 second duration should help estimate us better if the NEG Controller is working as expected -- even a slight increase on these <1 second processing times could drastically effect the overall performance when the NEG Controller is managing too many events.
> Add smaller bucket sizes for workqueue metrics

- pkg/flags/flags.go
This is a boolean feature flag to enable Transparent Health Checks (THC).
The purpose of the THC feature is to implement integration of
* health checks in GCE called Unified Health Checks (UHC) and
* health check mechanism in K8s,
so we can reflect K8s readiness status in UHC healthy status. The goal is to provide consistent health check results for GKE and UHC, showing the same status and operating on the same probers results.
K8s readiness status is a signal to enable the traffic flow for the POD. For GSLB, the health information is stored in the UHC configured for the BackendService. When those two signals are synchronized, there will be no disruption on traffic when the Backend will be marked as healthy. 
**Naming:** The THC health check mechanism is “transparent” from Kubernetes …
> Add flag for Transparent Health Check

- pkg/healthchecksl4/healthchecksl4.go
/assign @code-elinka 
one more time to remind that linters are needed...
> Fix log wrong format argument

- cmd/glbc/main.go
- pkg/flags/flags.go
- pkg/neg/controller.go
- pkg/neg/controller_test.go
- pkg/neg/manager.go
- pkg/neg/manager_test.go
- pkg/neg/types/testing.go
> Concurrently process deletion candidates within NEG Garbage Collector

- pkg/neg/syncers/utils.go
- pkg/neg/syncers/utils_test.go
Create skeleton code for degraded mode procedure. Implementation for filling missing information and filter invalid pod will come in separate PRs.
> Create skeleton code for degraded mode procedure

- pkg/neg/syncers/transaction.go
Fix error caused by unhashable error aggregation in getErrorStateReason()
> Fix error caused by unhashable error list

- pkg/neg/syncers/utils.go
- pkg/neg/syncers/utils_test.go
Filter terminal pods, which are pods with failed or succeeded phase.
> Filter terminal pods in degraded mode

- pkg/neg/syncers/utils.go
When we encounter duplicate endpoints, we would always choose the one with an alphabetically lower name so we have a consistent and reliable way to break the tie.
> Update duplicate endpoint handling

- cmd/glbc/main.go
- pkg/flags/flags.go
- pkg/neg/controller.go
- pkg/neg/controller_test.go
- pkg/neg/manager.go
- pkg/neg/manager_test.go
- pkg/neg/types/testing.go
> [Cherry pick #1976] Concurrently process deletion candidates within NEG Garbage Collector

- pkg/l4lb/l4controller.go
- pkg/l4lb/l4netlbcontroller.go
Order of execution was wrong, function was fast returned  
and some small logs improvements 
/assign aojea
> Fix PublishL4NetLBDualStackSyncLatency

- pkg/healthchecks/healthcheck.go
- pkg/healthchecks/healthchecks_test.go
- pkg/translator/healthchecks.go
This is the first preparatory PR in a series of two. The intention of the second PR is to detect the removal of `BackendConfig` CRD and to update health check configuration according to the existing input (rather than keep the existing configuration from `BackendConfig`).
The present PR updates the health check `Description` when `BackendConfig` is used. Additionally, test cases are modified to verify health check `Description`s.
> Adjust health check Description when BackendConfig used

- pkg/neg/syncers/utils.go
- pkg/neg/syncers/utils_test.go
- pkg/neg/types/types.go
- pkg/neg/types/types_test.go
This PR moves the logic of skipping IPv6 endpoints to the individual endpoint calculators. This allows L4 to use the ipv6 endpoints and l7 to ignore them.
> Process IPv6 Endpoints 

- pkg/ratelimit/ratelimit.go
It appears that there's yet another rate limiter that has to be updated due to https://github.com/GoogleCloudPlatform/k8s-cloud-provider/pull/77
In my testing, this is the last patch needed to build ingress with the newest k8s-cloud-provider
/assign @aojea
> Add Observe() func to internal GCERateLimiter

- go.mod
- go.sum
- vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/context.go
- vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/gce_projects.go
- vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/gen.go
- vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/meta/meta.go
- vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/observe.go
- vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/ratelimit.go
- vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/service.go
- vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/utils.go
- vendor/modules.txt
This is needed to pull in https://github.com/GoogleCloudPlatform/k8s-cloud-provider/pull/79
> Bump k8s-cloud-provider to v1.22.0

- cmd/e2e-test/e2e-test.yaml
I tried to run e2e tests on ARM and it does not work because I left this file unchanged in previous PRs
> Change e2e-test.yaml to support ARM

- pkg/loadbalancers/forwarding_rules.go
- pkg/loadbalancers/forwarding_rules_test.go
This fixes bug in RBS that forwarding rule is not getting updated on port updates
> Add comparing PortRange in forwarding rules Equal function

- cmd/glbc/main.go
- pkg/neg/controller.go
- pkg/neg/controller_test.go
- pkg/neg/manager.go
- pkg/neg/manager_test.go
- pkg/neg/syncers/endpoints_calculator.go
- pkg/neg/syncers/endpoints_calculator_test.go
- pkg/neg/syncers/labels/labels.go
- pkg/neg/syncers/transaction.go
- pkg/neg/syncers/transaction_test.go
- pkg/neg/syncers/utils.go
- pkg/neg/syncers/utils_test.go
1. Remove `PodLabelPropagationConfig` from `EndpointsCalculator` related code since we will no longer calculate label propagation in `EndpointsCalculator`.
2.  Add `PodLabelPropagationConfig` to NEG `TransactionSyncer`
> Refactor code related to PodLabelPropagationConfig

- pkg/neg/syncers/transaction.go
Remove set error state from calculateEndpoints and instead set it during syncInternal, otherwise, the error state will be overwritten and error state won't be found.
> Update set error state for CalculateEndpoints()

- cmd/glbc/main.go
- pkg/flags/flags.go
- pkg/neg/controller.go
- pkg/neg/controller_test.go
- pkg/neg/manager.go
- pkg/neg/manager_test.go
- pkg/neg/syncers/endpoints_calculator.go
- pkg/neg/syncers/endpoints_calculator_test.go
- pkg/neg/syncers/transaction.go
- pkg/neg/syncers/transaction_test.go
- pkg/neg/types/testing.go
> Add feature flag for IPv6 NEGs support

- pkg/neg/syncers/labels/label_test.go
- pkg/neg/syncers/labels/labels.go
- pkg/neg/types/types.go
Add EndpointAnnotationMap to negtypes
Add getPodLabelMap function and truncateLabel function for label propagation 
Add unit tests
> Add getPodLabelMap function for NegLabelPropagation and add unit test for it

- pkg/neg/metrics/neg_metrics_collector.go
- pkg/neg/syncers/endpoints_calculator.go
- pkg/neg/syncers/endpoints_calculator_test.go
- pkg/neg/syncers/transaction.go
- pkg/neg/syncers/transaction_test.go
- pkg/neg/syncers/utils.go
- pkg/neg/syncers/utils_test.go
- pkg/neg/types/interfaces.go
- pkg/neg/types/sync_results.go
Refactor syncInternalImpl, toZoneNetworkEndpointMap, and toZoneNetworkEndpointMapDegradedMode.
1. Refactor syncInternalImpl. 
- Create convertUntypedToEPS for converting endpointslice, and computeEPSStaleness for compute EPS staleness metrics.
- Create getEndpointsCalculation() to account for endpoint calculation for error state and enableDegradedMode.
2. Refactor toZoneNetworkEndpointMap. 
- Reduce the number of return values by wrapping them in a struct ZoneNetworkEndpointMapResult
- Create helper function getEndpointPod(), getEndpointZone() to simplify endpoint node, pod, and zone checking,
- Refactor endpoint node, pod, and zone checking
3. Refactor toZoneNetworkEndpointMapDegradedMode. 
- Reduce the number of return values by wrapping them in a struct ZoneNetworkEndpointMapResult
- …
> Refactor syncInternalImpl and toZoneNetworkEndpointMap

- pkg/backends/ig_linker.go
- pkg/backends/ig_linker_test.go
- pkg/backends/regional_ig_linker.go
- pkg/backends/regional_ig_linker_test.go
Tried to make it so that whatever exists in the backends list is preserved instead of overwriting with 'wantIGs'.
> Support IG backends removal in regional_ig_linker.go.

- pkg/neg/syncers/transaction.go
- pkg/neg/syncers/utils.go
- pkg/neg/syncers/utils_test.go
> Filter out migrating endpoints in NEG controller

- pkg/neg/metrics/label_propagation_metrics.go
- pkg/neg/metrics/metrics_test.go
- pkg/neg/metrics/neg_metrics_collector.go
> Add label propagation metrics

- pkg/neg/controller.go
- pkg/neg/metrics/label_propagation_metrics.go
- pkg/neg/metrics/metrics.go
- pkg/neg/metrics/metrics_test.go
- pkg/neg/metrics/neg_metrics_collector.go
- pkg/neg/syncers/labels/labels.go
- pkg/neg/syncers/transaction.go
- pkg/neg/syncers/transaction_test.go
- pkg/neg/syncers/utils.go
- pkg/neg/syncers/utils_test.go
> Add label propagation metrics calculation logic

- pkg/neg/syncers/utils.go
- pkg/neg/syncers/utils_test.go
- pkg/neg/types/sync_errors.go
Update validatePod to return error so we can get more context on the failing reason.
Change errors from get zone to ErrEPZoneMissing, and raise NodeNotFound error when we validate endpoint's node resource.
Addressing comment https://github.com/kubernetes/ingress-gce/pull/2044#discussion_r1158984260.
> Update endpoint checking return

- pkg/neg/syncers/transaction_test.go
Error state should be checked with syncLock, and we should return false and nil if we are not in the desired state.
We should also check errorState within waitPoll because seeing update in NEG does not guarantee we have also set the syncer's error state.
> Fix wait.PollImmediate in TestEnableDegradedMode

- pkg/servicemetrics/servicemetrics.go
in the debug log after metrics export
> Use time.Duration.String func to print duration

- pkg/backends/integration_test.go
- pkg/backends/syncer_test.go
- pkg/controller/controller.go
- pkg/controller/translator/translator.go
- pkg/healthchecks/fakes.go
- pkg/healthchecks/healthcheck.go
- pkg/healthchecks/healthchecks.go
- pkg/healthchecks/healthchecks_test.go
- pkg/healthchecks/interfaces.go
- pkg/translator/healthchecks.go
Since https://github.com/kubernetes/ingress-gce/pull/2008, the health check description is modified if the service health check is configured with a BackendConfig CRD. The purpose of the present PR is to emit an event on the service on this occasion.
The changes are guarded with the flag `flags.F.EnableUpdateCustomHealthCheckDescription` from https://github.com/kubernetes/ingress-gce/pull/2018/.
> Emit event on Description-only healthcheck update

- cmd/gke-diagnoser/app/util/report.go
Add report structs for gke-diagnoser CLI
Add json utils for the output report
> Add report utils for gke-diagnoser to support json output

- pkg/neg/controller.go
- pkg/neg/controller_test.go
- pkg/neg/manager.go
- pkg/neg/manager_test.go
- pkg/neg/syncers/transaction.go
- pkg/neg/syncers/transaction_test.go
- pkg/neg/syncers/utils.go
- pkg/neg/syncers/utils_test.go
- pkg/neg/types/types.go
- pkg/neg/types/types_test.go
- pkg/network/network.go
This struct holds the networking URLs that are now used when creating GCE resources (this commit contains changes for NEGs).
Currently only the default network information is always populated but it will be different for multi-networked services.
Why adding to PortInfo/ServicePort:
1. The controller creates syncers per service port. On update a diff is made with already used Ports vs the ones from the update. Adding the network to PortInfo will make the diff recognize any network change, so it will be possible to shut down the syncers for old network. Updating network for a running syncer would be difficult
2. there can be only one network set for the service so it could make sense to keep it on a service level but this introduced more complicated logic of handling syncers. It is possible …
> Add network package containing the NetworkInfo struct

- pkg/neg/syncers/syncer_test.go
Add lock to syncerTest to protect read and write for fields in syncerTest.
> Fix race condition in syncer test

- cmd/e2e-test/neg_test.go
> Change label propagation e2e test to align with label propagation config

- cloudbuild.yaml
This is the canonical and supported way to build images in kubernetes
https://github.com/kubernetes/test-infra/tree/master/config/jobs/image-pushing#image-pushing-jobs
> use cloudbuild to build container images

- cmd/glbc/main.go
- go.mod
- go.sum
- pkg/healthchecks/healthchecks.go
- pkg/healthchecks/healthchecks_test.go
- pkg/psc/controller.go
- pkg/psc/controller_test.go
- pkg/translator/healthchecks.go
- pkg/utils/healthcheck/healthcheckdesc.go
- pkg/utils/healthcheck/healthcheckdesc_test.go
- vendor/k8s.io/cloud-provider-gcp/providers/gce/gce.go
- vendor/k8s.io/cloud-provider-gcp/providers/gce/gce_fake.go
- vendor/modules.txt
Replace a plain string with a JSON string as the health check Description when the health check is configured with a BackendConfig CRD. The longer plan is to similarly JSONify all health check Descriptions, irrespective of the health check configuration.
> JSONify healthcheck Description for BackendConfig

- pkg/neg/metrics/metrics.go
- pkg/neg/syncers/transaction.go
Add metrics that reports the number of endpoints differ between current endpoint calculation and degraded mode calculation. It is not emitted when current endpoint calculation returns any errors because the returned map will be empty, while in degraded mode calculation, errors are handled and a non-empty map is returned.
> Degraded mode correctness metrics

- pkg/neg/syncers/endpoints_calculator.go
- pkg/neg/syncers/transaction_test.go
- pkg/neg/syncers/utils.go
- pkg/neg/syncers/utils_test.go
- pkg/neg/types/sync_errors.go
Filter pods have IPs outside of the corresponding nodes' IP ranges.
> Filter pods that have out of range IP

- pkg/neg/manager.go
- pkg/neg/syncers/endpoints_calculator.go
- pkg/neg/syncers/endpoints_calculator_test.go
- pkg/neg/syncers/transaction.go
- pkg/neg/syncers/transaction_test.go
- pkg/neg/syncers/utils.go
- pkg/neg/syncers/utils_test.go
- pkg/neg/types/sync_errors.go
Filter pods that don't have labels match to its service label selector.
> Filter pods that don't belong to the service in question

- cmd/gke-diagnoser/app/kube/clientset.go
Add general k8s clientsets
Add BackendConfig clientsets
Add FrontendCondif clientsets
> Add clientsets to gke-diagnoser tool

- cmd/gke-diagnoser/app/ingress/rule.go
- cmd/gke-diagnoser/app/ingress/rule_test.go
- cmd/gke-diagnoser/app/report/report.go
Rename util package in gke-diagnoser to report
Add CheckServiceExistence rule for gke-ingress-checker
Add unit test for CheckServiceExistence rule
> Add CheckServiceExistence Rule for gke-ingress-checker

- pkg/neg/syncers/transaction.go
- pkg/neg/syncers/transaction_test.go
- pkg/neg/syncers/utils.go
- pkg/neg/syncers/utils_test.go
- pkg/neg/types/types.go
This is required to support new IPv6 fields within that are currently only present in Alpha APIs
> Use Alpha NEG API when DualStackNEG feature is enabled

- pkg/annotations/service.go
- pkg/backends/integration_test.go
- pkg/backends/syncer_test.go
- pkg/context/context.go
- pkg/controller/controller.go
- pkg/controller/translator/translator.go
- pkg/controller/translator/translator_test.go
- pkg/firewalls/controller.go
- pkg/healthchecks/healthcheck.go
- pkg/healthchecks/healthchecks.go
- pkg/healthchecks/healthchecks_test.go
- pkg/translator/healthchecks.go
- pkg/translator/healthchecks_test.go
- pkg/utils/serviceport.go
Configure UHC with THC defaults when the THC annotation is present for the service. Flag-gated with `flags.F.EnableTransparentHealthChecks`.
> Read THC annotation and configure UHC accordingly

- pkg/neg/controller.go
- pkg/neg/readiness/poller.go
- pkg/neg/readiness/poller_test.go
- pkg/neg/readiness/reflector.go
- pkg/neg/readiness/reflector_test.go
Before: Only IPv4 Health status was used to decide if NEG endpoint is ready
Now: Both IPv4 and IPv6 health statuses will be used to decide if NEG endpoint is ready.
> Consume IPv6 Health status for NEG pod readiness

- cloudbuild.yaml
It seems that 30 mins is just on the edge for building multi-arch images, since this is a postsubmit job we can afford to wait for 60 mins to be on the safe side
https://testgrid.k8s.io/sig-network-ingress-gce-e2e#post-ingress-gce-push-image
> bump timeout for building images

- docs/deploy/resources/glbc.yaml
- pkg/controller/translator/translator.go
- pkg/controller/translator/translator_test.go
- pkg/firewalls/controller.go
- pkg/firewalls/controller_test.go
- pkg/healthchecks/healthchecks.go
- pkg/healthchecks/healthchecks_test.go
After this PR is merged, the next steps (with some soak time in between as appropriate) are:
* remove the flag `--enable-backendconfig-healthcheck` from config files (internal),
* remove the flag `--enable-backendconfig-healthcheck` from `pkg/flags/flags.go`.
~This is a child PR dependent on https://github.com/kubernetes/ingress-gce/pull/2088. Please review only the last commit `Remove the flag EnableBackendConfigHealthCheck`.~
> Remove the flag EnableBackendConfigHealthCheck

- pkg/neg/metrics/endpoint_metrics.go
- pkg/neg/metrics/neg_metrics_collector.go
- pkg/neg/metrics/syncer_metrics.go
Rename metrics name and key to match monarch definition.
> Rename syncer and endpoint metrics to match Monarch

- pkg/neg/metrics/metrics.go
- pkg/neg/metrics/neg_metrics_collector.go
- pkg/neg/metrics/neg_metrics_collector_test.go
- pkg/neg/syncers/dualstack/migrator.go
- pkg/neg/syncers/dualstack/migrator_test.go
- pkg/neg/syncers/transaction.go
- pkg/neg/types/states.go
> Add new metrics for NEG DualStack Migrator

- cmd/check-gke-ingress/app/ingress/rule.go
- cmd/check-gke-ingress/app/ingress/rule_test.go
> Add CheckBackendConfigExistence to check-gke-ingress

- cloudbuild.yaml
If I run an image: gcr.io/k8s-ingress-image-push/ingress-gce-e2e-test
I see an error: 
```
==============================================================================
E2E TEST
./run.sh: line 113: /e2e-test: No such file or directory
```
It means it doesn't have binaries that were supposed to be copied. 
This change adds a line that builds those binaries (make all-build).
> Build binaries for docker images in cloudbuild.yaml

- cloudbuild.yaml
The last cloudbuild.yaml change was merged with VERBOSE variable and it leads to postsubmit jobs to fail. This change removes duplicate mentionings of VERBOSE and uses direct list of architectures instead of overhead with ALL_ARCH.
> Remove verbose arg from cloudbuild.yaml

- Dockerfile.e2e-test
Install gcloud cli in e2e-test image
based on architecture to support multiarch.
> Change e2e-test dockerfile run cmds

- Dockerfile.e2e-test
The google-cloud-cli:debian_component_based image has all needed binaries and certificates preinstalled, in addition to that it works with arm64 that makes it possible to run e2e test on different architectures.
>  Use gcloud base image for e2e-test container

- pkg/neg/types/types.go
> Switch Compute API to beta for NEG IPv6 fields when DualStackNEG feature flag is enabled

- pkg/neg/syncers/dualstack/migrator.go
- pkg/neg/syncers/dualstack/migrator_test.go
- pkg/neg/syncers/transaction.go
> Use degraded mode results in NEG DualStack migration heuristics

- cmd/check-gke-ingress/app/ingress/rule.go
- cmd/check-gke-ingress/app/ingress/rule_test.go
> Add CheckHealthCheckConfig rule to check-gke-ingress

- cloudbuild.yaml
- hack/push-multiarch.sh
The e2e image needs to be built with docker buildx because it may be built in a cross-compiled way
and it has not only pre-copied binaries but also
some dependencies (sh script, curl, gcloud-cli).
> Use hack script for e2e test image building

- docs/deploy/gke/README.md
- docs/deploy/resources/glbc.yaml
- docs/deploy/resources/rbac.yaml
> Make minimal modifications to make dual-stack-negs work with self-managed controller

- cmd/check-gke-ingress/app/ingress/rule.go
- cmd/check-gke-ingress/app/ingress/rule_test.go
> Add CheckIngressRule to check-gke-ingress

- pkg/servicemetrics/servicemetrics.go
otherwise deleted services will appear in metrics forever it their label combination was unique
this is small iprovement over PR#2136
- comment
- reset gauges just int time to reduce reace risk (scrape between reset and setting new values)
> Reset gauges when collecting service metrics

- Dockerfile.e2e-test
- cloudbuild.yaml
- hack/push-multiarch.sh
1) Docker buildx cmd can build a multiarch image
in one run. Use it instead of many commands
2) The hack/push-multiarch.sh script is used for e2e build
via docker buildx (/root/.docker/cli-plugins/docker-buildx).
It requires to specify HOME=/root so buildx works as expected.
See:
[github.com/kubernetes/test-infra/tree/master/config/jobs/image-pushing
](https://github.com/kubernetes/test-infra/tree/master/config/jobs/image-pushing#simple-build-example)
> Use only one buildx command for e2e-test

- pkg/l4lb/l4lbcommon.go
- pkg/l4lb/l4netlbcontroller.go
- pkg/l4lb/l4netlbcontroller_test.go
- pkg/loadbalancers/l4syncresult.go
- Delete only if service has finalizer or rbs forwarding rule, meaning it was provisioned by RBS controller at some point
- Don't delete RBS annotation on garbage collection
/assign @cezarygerard @aojea
> Change logic of deleting RBS service

- build/test.sh
We have too many logs in all tests
/assign @aojea @swetharepakula @gauravkghildiyal
> Remove running tests with verbose mode

- pkg/neg/metrics/neg_metrics_collector.go
- pkg/neg/syncers/endpoints_calculator.go
1. Fix metrics emit issue. Metrics should be emitted when error is nil.
2. Remove unneeded parameter in computeEndpointStateMetrics.
3. Add endpoint and endpoint slice count to the emit metrics log.
> Endpoint State metrics Cleanup

- Makefile
Patches of golang could differ and
make the debugging process harder.
To demolish that problem we should
pin not only major.minor versions
but also patch one.
@cezarygerard I decided to proceed with patch, not sha because it's more readable and can be used in any basic image.  
see: https://hub.docker.com/_/golang
> Pin golang patch version in Makefile

- cmd/e2e-test/neg_test.go
- pkg/e2e/adapter/ingress.go
- pkg/e2e/fixtures.go
- pkg/e2e/fixtures_test.go
- pkg/e2e/framework.go
- pkg/e2e/helpers.go
Create e2e test for degraded mode.
When an endpointslice contains endpoint with missing or empty nodeName, this should be filled during degraded mode. When an endpointslice contains endpoint with invalid pod information, or the endpoint has an IP that doesn't correspond to any podIP, this endpoint should be filtered out.
> Degraded mode e2e

- pkg/neg/controller.go
- pkg/neg/manager.go
- pkg/neg/metrics/metrics.go
- pkg/neg/readiness/poller.go
- pkg/neg/readiness/reflector.go
- pkg/neg/readiness/utils.go
- pkg/neg/syncers/endpoints_calculator.go
- pkg/neg/syncers/syncer.go
- pkg/neg/syncers/transaction.go
- pkg/neg/syncers/utils.go
- pkg/utils/utils.go
Define `NegControllerErrorCount` that tracks both internal sync error and API server errors(GCE/K8s).
> Track GCE/K8s server error

- pkg/l4lb/l4netlbcontroller.go
- pkg/l4lb/l4netlbcontroller_test.go
As we removed deleting RBS annotation in garbageCollectRBSNetLB we now need to remove annotation explicitly, otherwise service will not be handled by legacy controller
/assign @cezarygerard
> Delete RBS annotation explicitly in preventTargetPoolRaceWithRBSOnCreation

- hack/push-multiarch.sh
We have 3 registries for images:
* multiarch
* amd64
* arm64
Even we can keep everything in the first one,
we still want to support last two registries
for users who may need that.
> Push arch specific images

- cmd/check-gke-ingress/app/command/root.go
- cmd/check-gke-ingress/app/ingress/ingress.go
- cmd/check-gke-ingress/app/ingress/rule.go
- cmd/check-gke-ingress/app/ingress/rule_test.go
> Integrate checks for check-gke-ingress

- pkg/neg/metrics/metricscollector/metrics.go
- pkg/neg/metrics/metricscollector/metrics_collector.go
- pkg/neg/syncers/transaction.go
Add syncer in error state metrics
> Add syncer in error state metrics

- pkg/annotations/service.go
- pkg/controller/controller.go
- pkg/controller/translator/translator.go
- pkg/controller/translator/translator_test.go
- pkg/firewalls/controller.go
- pkg/healthchecks/healthchecks.go
- pkg/healthchecks/healthchecks_test.go
- pkg/translator/healthchecks.go
- pkg/utils/serviceport.go
The purpose of the PR is to emit Events on Service/Ingress objects when the UHC health check for the Service has been successfully configured with the Transparent Health Checks (THC) feature or such a configuration has been attempted.
> Emit Events on THC (mis)configuration

- pkg/neg/metrics/metricscollector/metrics.go
- pkg/neg/metrics/metricscollector/metrics_collector.go
- pkg/neg/syncers/transaction.go
- pkg/neg/types/sync_errors.go
1. We should update state of syncers after we check for error state. In syncInternal(), we update after checking, but in operationInternal(), we update before checking. On the other hand, it doesn't make sense to have a syncer not in error state while it triggers an error state error.
2. When publishing metrics, export all possible states otherwise we might have states that currently don't exist but are not updated during metrics collection. For example, we have a syncer in error state before, so we set errorCount=1 in metrics. When it now succeeds, we set successCount=1, but we haven't reset the errorCount, so we end up with sucessCount=1 and errorCount=1.
> Update syncer count metrics emit

- pkg/neg/syncers/transaction.go
- pkg/neg/syncers/transaction_test.go
- pkg/neg/syncers/utils.go
- pkg/neg/syncers/utils_test.go
Add TestParseEndpointBatchErr to verify invalid endpoint batch error state. Add TestValidateEndpointFields to verify invalid endpoint information error state.
> Add unit tests to validate error states are detected

- pkg/neg/syncers/utils.go
Update logging in endpoint calculation.
The way to trigger this is by constructing a custom endpoint slice so that we contains two endpoints from EPS that share the same pod but contains different endpointIP. The reason we are seeing this is because for this endpoint, the IP we use for network endpoint(and used for this check) is different from the IP from the endpoint in EPS. 
The first IP we have is the endpoint IP from EPS, and the later one is the one we used for network endpoint.
> Update logging in endpoint calculation.

- pkg/loadbalancers/l4.go
- pkg/loadbalancers/l4_test.go
- pkg/loadbalancers/l4ipv6.go
- pkg/loadbalancers/l4netlb.go
- pkg/loadbalancers/l4netlbipv6.go
There was an omission in the code for multinet and some firewall rules were created in the incorrect VPC.
> Fix firewalls for L4 ILBs.

- pkg/common/typed/service.go
Fixes #2135 
/assign @aojea @cezarygerard
> Deep copy service after getting from informer

- pkg/annotations/service.go
- pkg/loadbalancers/forwarding_rules_ipv6.go
- pkg/loadbalancers/l4.go
- pkg/loadbalancers/l4_test.go
- pkg/loadbalancers/l4netlb_test.go
- Add new annotation networking.gke.io/load-balancer-subnet which adds support to specify custom subnet for external IPv6 forwarding rule
- Use new annotation instead of old "networking.gke.io/internal-load-balancer-subnet" for ILB, but fallback to old annotation
> Add support for Custom Subnet for IPv6 NetLB

- go.mod
- go.sum
- pkg/loadbalancers/address_manager.go
- pkg/loadbalancers/address_manager_test.go
- pkg/loadbalancers/forwarding_rules.go
- pkg/loadbalancers/forwarding_rules_ipv6.go
- pkg/loadbalancers/l4.go
- pkg/loadbalancers/l4_test.go
- pkg/loadbalancers/l4ipv6.go
- vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/mock/mock.go
- vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/observe.go
- vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/utils.go
- vendor/github.com/kr/pretty/diff.go
- vendor/github.com/kr/pretty/formatter.go
- vendor/github.com/rogpeppe/go-internal/LICENSE
- vendor/github.com/rogpeppe/go-internal/fmtsort/mapelem.go
- vendor/github.com/rogpeppe/go-internal/fmtsort/mapelem_1.11.go
- vendor/github.com/rogpeppe/go-internal/fmtsort/sort.go
- vendor/modules.txt
This will prevent losing address while recreating forwarding rule
Tested running locally with real cluster
> Reserve Static IPv6 address before syncing L4 ILB

- pkg/neg/metrics/metrics.go
- Update k8s/gce server request metrics to count server error
- For NEG controller error count metrics, count server error with ignore=True as server error instead of ignored error. Ignore=True means we are okay with these errors, but we do care if the failure is due to server error.
> update k8s/gce server request metrics to count server error

- pkg/neg/metrics/metricscollector/metrics.go
- pkg/neg/metrics/metricscollector/metrics_collector.go
- pkg/neg/metrics/metricscollector/metrics_collector_test.go
- pkg/neg/syncers/transaction.go
- pkg/neg/types/sync_errors.go
Add a new managed neg count metric that will track the count of negs by zone and endpoint type. This is different from the neg count in the usage metrics which only counts syncers. The usage metrics can be an undercount as it does not account for regional clusters where a neg is created per zone. Syncers' locations can point to regions for regional clusters which does not give an accurate picture of the distribution of negs across zones.
A followup commit is also included that cleans up the syncerState metric so that the different states no longer need to be hardcoded.
/cc @sawsa307
> Neg count metrics

- pkg/loadbalancers/forwarding_rules_ipv6.go
- pkg/loadbalancers/l4netlb_test.go
This will prevent losing address while recreating forwarding rule
> Reserve Static IPv6 address before syncing L4 NetLB

- pkg/loadbalancers/forwarding_rules_ipv6.go
- pkg/loadbalancers/l4netlbipv6.go
This is another discrepancy in gcp api, fixing it
> Add /96 suffix to static addresses for IPv6 external forwarding rules

- pkg/loadbalancers/features/l7ilb.go
> Include proxy-only subnet with purpose=REGIONAL_MANAGED_PROXY when generating firewall rules for Ingress

- pkg/loadbalancers/features/l7ilb.go
> Cherry-pick #2186: Include proxy-only subnet with purpose=REGIONAL_MANAGED_PROXY when generating firewall rules for Ingress

- pkg/healthchecks/healthchecks.go
- pkg/healthchecks/healthchecks_test.go
In https://github.com/kubernetes/ingress-gce/pull/2008 and https://github.com/kubernetes/ingress-gce/pull/2068, we guarantee that the health check Description is updated when a BackendConfig is added to the Service (behind the flag --enable-update-hc-description). When a BackendConfig is removed, typically a health check update is triggered, which includes resetting the Description. However, under some circumstances the health check parameters update won't happen on BackendConfig removal, but it is still desirable to reset the Description to reflect the lack of BackendConfig. This reset is added in the present PR.
The changes are behind the abovementioned flag --enable-update-hc-description. This is a temporary fix and corresponding code will be removed with the subsequent planned …
> Update healthcheck Description on BackendConfig removal

- pkg/loadbalancers/forwarding_rules.go
- pkg/loadbalancers/forwarding_rules_test.go
This fixes bug in RBS that forwarding rule is not getting updated on port updates
> [Cherry-pick #2042] Add comparing PortRange in forwarding rules Equal function

- Makefile
- build/build.sh
- build/rules.mk
- cmd/check-gke-ingress/README.md
>  Add instructions for check-gke-ingress and updated makefile

- pkg/l4lb/l4controller_test.go
- pkg/l4lb/l4netlbcontroller_test.go
- pkg/loadbalancers/forwarding_rules_ipv6.go
- pkg/loadbalancers/l4.go
- pkg/loadbalancers/l4_test.go
- pkg/loadbalancers/l4ipv6.go
- pkg/loadbalancers/l4netlb.go
- pkg/loadbalancers/l4netlb_test.go
- pkg/loadbalancers/l4netlbipv6.go
- pkg/test/utils.go
- pkg/utils/utils.go
- Before syncing IPv6 Services, verify if Service subnet has required IPv6 ranges (INTERNAL for ILB and EXTERNAL for NetLB)
- Add unit tests
> Add explicit verification for External/Internal IPv6 subnet

- pkg/annotations/l4_static_address.go
- pkg/annotations/l4_static_address_test.go
- pkg/loadbalancers/forwarding_rules.go
- pkg/loadbalancers/forwarding_rules_ipv6.go
- pkg/loadbalancers/l4.go
- pkg/loadbalancers/l4_test.go
- pkg/loadbalancers/l4netlb_test.go
- Introduce new annotation "networking.gke.io/load-balancer-ip-addresses", which
will store comma-separated list of address names
- Add logic to identify address with matching IP family from new
annotation
> Add support for static DualStack IPs

- pkg/metrics/features.go
- pkg/metrics/metrics.go
- pkg/metrics/metrics_test.go
The present PR adds a label for ServicePort metrics counting ServicePorts with Transparent Health Checks enabled.
> Add metrics for Transparent Health Checks

- cmd/glbc/main.go
- pkg/annotations/service.go
- pkg/annotations/service_test.go
- pkg/backends/backends.go
- pkg/backends/backends_test.go
- pkg/backends/regional_ig_linker_test.go
- pkg/context/context.go
- pkg/flags/flags.go
- pkg/l4lb/l4netlbcontroller.go
- pkg/l4lb/l4netlbcontroller_test.go
- pkg/loadbalancers/l4.go
- pkg/loadbalancers/l4_test.go
- pkg/loadbalancers/l4netlb.go
- pkg/loadbalancers/l4netlb_test.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
The change allows users to create a NetLB service with strong session affinity. 
What was added: 
* flag to enable strong session affinity feature
* annotation for the strong session affinity in the service specs
* functions to check all requirements and configurations for strong session affinity, session affinity type, and session affinity config
* unit tests
Commits are only for reviewing purposes, it will be squashed into one big commit before the merge. Or maybe two commits: changes & unit tests
> Strong Session Affinity for L4NetLB

- pkg/loadbalancers/l4netlb.go
Strong Session Affinity has a possibility to specify much longer IdleTimeout. This parameter didn't work properly for some time and now it works as expected, we may use it.
> Populate IdleTimeout for L4NetLB Session Affinity

- pkg/loadbalancers/features/l7ilb.go
Reverts kubernetes/ingress-gce#2190
> Revert "[Cherry-pick #2186 -> 1.21] Include proxy-only subnet with purpose=REGIONAL_MANAGED_PROXY when ge…"

- pkg/loadbalancers/features/l7ilb.go
Reverts kubernetes/ingress-gce#2187
> Revert "Cherry-pick #2186 -> 1.20: Include proxy-only subnet with purpose=REGIONAL_MANAGED_PROXY when generating firewall rules for Ingress"

- cmd/glbc/main.go
- pkg/context/context.go
- pkg/healthchecksl4/healthchecksl4.go
- pkg/healthchecksl4/interfaces.go
- pkg/l4lb/l4controller.go
- pkg/l4lb/l4netlbcontroller.go
- pkg/l4lb/l4netlbcontroller_test.go
- pkg/loadbalancers/l4.go
- pkg/loadbalancers/l4_test.go
- pkg/loadbalancers/l4netlb.go
- pkg/loadbalancers/l4netlb_test.go
- pkg/loadbalancers/l4testutils.go
- pkg/neg/controller.go
- pkg/neg/controller_test.go
- pkg/network/network.go
- pkg/network/network_test.go
Push network resolution down to `EnsureLB` functions so that the sync result can be returned consistently. Add Resolver interface to avoid passing down network and gkenetworkparamset listers and allow to use fake resolver in tests.
> Refactor multinetwork resolution.

- pkg/backends/backends.go
- pkg/backends/backends_test.go
- pkg/loadbalancers/l4netlb.go
There are two changes:
* Session Affinity Tracking Policy shouldn't
be updated if the flag for it wasn't set.
* Backend should be updated when
ConnectionTrackingPolicy has changed.
> Change logic of L4 Strong Session Affinity

- pkg/context/context.go
- pkg/l4lb/l4controller.go
- pkg/l4lb/l4controller_test.go
- pkg/l4lb/l4netlbcontroller.go
- pkg/l4lb/l4netlbcontroller_test.go
- pkg/loadbalancers/l4.go
- pkg/loadbalancers/l4netlb.go
- pkg/loadbalancers/l4netlb_test.go
- pkg/metrics/l4_dualstack_metrics.go
- pkg/metrics/l4_dualstack_metrics_test.go
- pkg/metrics/l4_legacy_metrics.go
- pkg/metrics/l4_legacy_metrics_test.go
- pkg/metrics/l4_metrics.go
- pkg/metrics/l4_metrics_test.go
- pkg/metrics/metrics.go
- pkg/metrics/types.go
- vendor/github.com/prometheus/client_golang/prometheus/testutil/lint.go
- vendor/github.com/prometheus/client_golang/prometheus/testutil/promlint/promlint.go
- vendor/github.com/prometheus/client_golang/prometheus/testutil/testutil.go
- vendor/modules.txt
The existing L4 metrics are now regarded as legacy and have been renamed as such.
The new L4 metric will follow and share state with DualStack metrics.
this also includes multinet metric label.
> Refactor L4 metrics reporting

- pkg/l4lb/l4controller.go
- pkg/l4lb/l4netlbcontroller.go
Move deleting the finalizer to the very last part of the sync
Otherwise deleting annotations may result in error and retry
to reviewers:
wait for internal approval on this cherry pick
> [Cherry-pick #2134]  Delete finalizer last in L4 RBS controller

- pkg/utils/utils.go
- pkg/utils/utils_test.go
* Remove infinite for loop since errors.As finds the relevant error
* Add tests to validate the functions work for multi-wrapped errors
/assign @bowei 
/cc @gauravkghildiyal
> Refactor ServerErrror helper functions

- pkg/metrics/metrics.go
- pkg/metrics/metrics_test.go
The feature `transparentHealthChecks` was not been added to `initializeCounts()` in `pkg/metrics/metrics.go` within https://github.com/kubernetes/ingress-gce/pull/2195. This resulted in a buggy behaviour as in the comment to the `initializeCounts()` function.
> Fix thc metric invisible when zero and not decreasing to 0

- pkg/l4lb/l4controller.go
- pkg/l4lb/l4netlbcontroller.go
Reverts kubernetes/ingress-gce#2225
It does not have a approval and I think the problem is the annotation removal, if we are going to delete the Service we don't need to remove the annotations first AFAIK
> Revert "[Cherry-pick #2134]  Delete finalizer last in L4 RBS controller"

- docs/contrib/testing.md
- docs/faq/README.md
**What type of PR is this?**
/kind cleanup
**What this PR does / why we need it:**
Fixes a broken link to testgrid dashboard.
**Which issue(s) this PR fixes:**
This is related to an umbrella issue and fixes a task of the same:
https://github.com/kubernetes/test-infra/issues/30370
> fix: Broken links to testgrid dashboard

- pkg/flags/flags.go
The flag `--enable-backendconfig-healthcheck` was made void in https://github.com/kubernetes/ingress-gce/pull/2099, and the present PR removes it altogether.
> Remove unused flag --enable-backendconfig-healthcheck

- pkg/loadbalancers/features/l7ilb.go
Reverts kubernetes/ingress-gce#2206
/hold
> Cherry-pick #2186 -> 1.20: Include proxy-only subnet with purpose=REGIONAL_MANAGED_PROXY when generating firewall rules for Ingress

- pkg/loadbalancers/features/l7ilb.go
Reverts kubernetes/ingress-gce#2205
/hold
> [Cherry-pick #2186 -> 1.21] Include proxy-only subnet with purpose=REGIONAL_MANAGED_PROXY when generating firewall rules for Ingress

- pkg/loadbalancers/features/l7ilb.go
Reverts kubernetes/ingress-gce#2204
/hold
> [Cherry-pick #2186 -> 1.22] Include proxy-only subnet with purpose=REGIONAL_MANAGED_PROXY when generating firewall rules for Ingress

- pkg/loadbalancers/features/l7ilb.go
Cherry-pick of https://github.com/kubernetes/ingress-gce/pull/2186
/hold
> [Cherry-pick #2186 -> 1.19] Include proxy-only subnet with purpose=REGIONAL_MANAGED_PROXY when generating firewall rules for Ingress

- pkg/loadbalancers/l4.go
- pkg/loadbalancers/l4netlb.go
- pkg/metrics/l4_metrics.go
- pkg/metrics/l4_metrics_test.go
- pkg/metrics/types.go
Strong Session Affinity (SSA) is a parameter of NetLB service that could be enabled and should be presented in metrics to report:
* amount of services with SSA
* diffirentiate UserError from other ones for such services.
> Add Strong Session Affinity for L4 Metric State

- pkg/loadbalancers/l4netlb.go
Backend Service has a leftover comment about
Strong Session Affinity check that should be removed.
The checkStrongSessionAffinityRequirements was run in EnsureFrontend() before that
> Clean leftover comment for Strong Session Affinity

- pkg/annotations/ingress.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
- Add "gce-regional" ingress class annotation
- Add GceL7XLBRegionalIngressClass that checks if ingress has
gce-regional annotation class, and if regional external ingress is
enabled
- Should be no-op
> Add gce-regional ingress class annotation

- pkg/neg/metrics/metrics.go
- pkg/neg/syncers/transaction.go
- pkg/neg/syncers/transaction_test.go
* Add additional logging for degraded mode behavior.
* Update logging bucket so we can distinguish endpoint diff 0 from endpoint diff 1 in degraded mode correctness metric.
* Update error checking in checkEndpointBatchErr.
> Update metrics bucket to distinguish 0 and 1.

- pkg/controller/translator/translator.go
- pkg/controller/translator/translator_test.go
- In the same manner as for L7 ILB, always enable NEGs on ServicePort
for L7XLB Regional Ingress
- This is flag-gated, because L7XLBRegionalEnabled is flag-gated
> Enable ServicePort NEGs for L7 RXLB 

- pkg/healthchecks/healthchecks.go
- This will reduce getRegional to do only 1 simple thing -- getting
health check
- This will allow us to set ForRegionalXLB later
- Should not change any behaviour
> Move setting healthcheck ForNEG, ForILB to upper functions

- pkg/utils/utils.go
- pkg/utils/utils_test.go
- IsGCEIngress is used in different controllers to filter ingresses that ingress-gce should handle
- Return true only if flag is enabled. Adding dependency on the global flag
I don't like being dependent on the global flag, but this looks not extremely bad here. But if you ask, I can refactor, just I would need to pass this flag to different controllers
> Add L7 Regional XLB to IsGCEIngress, depending on the flag

- pkg/backends/interfaces.go
- pkg/backends/neg_linker.go
- pkg/backends/neg_linker_test.go
- pkg/neg/manager.go
- pkg/neg/manager_test.go
- pkg/neg/readiness/poller.go
- pkg/neg/readiness/poller_test.go
- pkg/neg/readiness/utils.go
- pkg/neg/readiness/utils_test.go
- pkg/neg/syncers/endpoints_calculator.go
- pkg/neg/syncers/syncer.go
- pkg/neg/syncers/transaction.go
- pkg/neg/syncers/transaction_test.go
- pkg/neg/syncers/utils.go
- pkg/neg/syncers/utils_test.go
- pkg/neg/types/cloudprovideradapter.go
- pkg/neg/types/cloudprovideradapter_test.go
- pkg/neg/types/fakes.go
- pkg/neg/types/interfaces.go
This PR is the continuation of https://github.com/kubernetes/ingress-gce/pull/1746(contextual logging for components
in NEG controller).
* Functions will accept a logger object from its caller, so the prefix will be determined based on the caller objects.
> Replace klog with context logging for NEG Controller

- pkg/healthchecks/healthchecks.go
- Now we use getRegional also for Regional External HealthChecks
> Fix log to say "Regional" instead of "ILB"

- cmd/e2e-test/regional_xlb_test.go
- pkg/fuzz/features/neg.go
- pkg/fuzz/gcp.go
- pkg/fuzz/helpers.go
- Extend e2e helpers to support verifications for external regional LBs
- New test is almost a full copy of ilb_test.go
> Add simple e2e creation/deletion test for gce-regional-external ingress

- pkg/backends/backends.go
- pkg/backends/backends_test.go
- pkg/backends/regional_ig_linker_test.go
- pkg/l4lb/l4netlbcontroller.go
- pkg/loadbalancers/l4.go
- pkg/loadbalancers/l4_test.go
- pkg/loadbalancers/l4netlb.go
Use `enableStrongSessionAffinity` flag to close access to Strong Session Affinity feature if not needed. 
This change includes: 
* @mmamczur commit 
* my changes to use excisting flag for SSA
Both of commits will be squashed together just before merging. 
That approach is called feature flagging. 
I found an article with more info about it: https://arxiv.org/pdf/1907.06157.pdf
> Hide Strong Session Affinity code behind a flag (fully) 

- pkg/backendconfig/validation.go
- pkg/backendconfig/validation_test.go
- pkg/controller/translator/translator.go
- This adds validation for backend config to return error if user specifies IAP or CDN with Regional External Ingress
> Disable IAP and CDN BackendConfig for Regional External Ingress

- pkg/neg/syncers/utils_test.go
* Add instance2 to nodeLister. It is a missing but necessary setup. We injected error to endpoint using instance2(invalid IP), but if instance2 is not added to nodeLister, it also be filtered for nodeNotFound regardless of whether the IP is invalid.
* Use same ipv6 podCIDR in TestDegradedModeValidateEndpointInfo by updating the ipv6 podCIDR for instance1. Its ipv6 CIDR value does not matter because it is a node for single stack endpoints, whereas instance3 and instance4 are for dual stack endpoints and their ipv6 CIDR do matter. In addition, using different podCIDRs creates unnecessary confusions.
> Use same ipv6 podCIDR, and add instance2 to nodeLister.

- cmd/e2e-test/redirects_test.go
- pkg/fuzz/gcp.go
- Add test implementation, almost a full copy of the TestHttpsRedirects
- Add to regional utils handling https redirect map, which was not expected for ILB (which was the only user of regional utils)
> Add HTTPs redirects e2e test for RXLB Ingress

- .golangci.yaml
- Sometimes CI fails timing out on golangci-lint
- Increase timeout to 3 minutes (1 minute is default, used before)
Failure example: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/ingress-gce/2357/pull-ingress-gce-verify/1725606439445073920
> Increase golangci-lint timeout

- pkg/composite/gen.go
- pkg/composite/gen/main.go
Right now, metrics for some GCE API calls are not exported (e.g. ListNetworkEndpoints). This PR adds `Observe` call to some missing places in the generated client API.
> Add Observe to all paths of generated client API

- pkg/e2e/helpers.go
- Reduce polling time to 10 minutes if ExpectUnreachable
> Reduce e2e test polling time for Unreachable

- pkg/flags/flags.go
- pkg/neg/syncers/transaction.go
* To avoid changes in code logic, we don't handle degradedMode calculation error outside, but only collect metrics when degraddedModeErr is nil.
* Log if we are using degraded mode endpoint calculation.
> New flag for degraded mode metrics collection, and add logging for the selection of endpoint calculation.

- pkg/e2e/helpers.go
Reverts kubernetes/ingress-gce#2370
The timeout is still short for this test. Even though we are testing unreachable, the load balancer needs more than 10 minutes in order for all the relevant resources to be created.
Right now tests are failing because they never reach [here](https://github.com/kubernetes/ingress-gce/blob/master/pkg/e2e/helpers.go#L170-L173) within 10 minutes which can only happen when the Ingress stabilizes.
> Revert "Reduce e2e test polling time for Unreachable"

- build/test.sh
* The linter on this branch is returning errors but the same code on other branches do not produce lint errors.
* Since this branch will not have any more feature development and will only contain bug fixes, disable the linter for this branch only
/cc @bowei
> Disable go linter for 1.20 branch

- pkg/neg/syncers/syncer.go
* Put PublishNegControllerErrorCountMetrics in its own goroutine because it is running on critial path in syncer.go.
> Make PublishNegControllerErrorCountMetrics run in its own goroutine

- pkg/neg/syncers/syncer.go
> [Cherry pick #2359 -> 1.26] Make PublishNegControllerErrorCountMetrics run in its own goroutine

- pkg/neg/syncers/syncer.go
Reverts kubernetes/ingress-gce#2403
Temporarily reverting the bug fixes on 1.26
> Revert "[Cherry pick #2359 -> 1.26] Make PublishNegControllerErrorCountMetrics run in its own goroutine"

- pkg/network/network.go
- pkg/network/network_test.go
Reverts kubernetes/ingress-gce#2405
Temporarily reverting bug fixes on release-1.26
> Revert "[Cherry pick #2402 -> 1.26] Add some validations for L4 multinetwork services."

- pkg/neg/syncers/syncer.go
Reverts kubernetes/ingress-gce#2420
Since 1.26.2 was cut without any bug fixes, we can now undo the temporary reverts.
> Revert "Revert "[Cherry pick #2359 -> 1.26] Make PublishNegControllerErrorCountMetrics run in its own goroutine""

- pkg/neg/metrics/metricscollector/features.go
- pkg/neg/metrics/metricscollector/metrics.go
- pkg/neg/metrics/metricscollector/metrics_collector.go
- pkg/neg/metrics/metricscollector/metrics_collector_test.go
- pkg/neg/metrics/metricscollector/types.go
* NEG usage metrics will be pulled from pkg/metrics to pkg/neg/metrics, and emit via NEG metrics collector.
* In this PR, only dependencies are replicated. No behavior change is introduced.
* Existing types and constants will be cleaned up in #2407.
> Replicate dependencies for neg usage metrics migration.

- pkg/neg/syncers/endpoints_calculator.go
- pkg/neg/syncers/endpoints_calculator_test.go
Whenever the NEG controller would go into the degraded mode for L4 LB service with externalTrafficPolicy=Local, the controller would ignore endpoint slice data for NEG endpoints calculation. This would result in detachment of all endpoints and broken LB.
> Fix NEG degraded mode for L4 externalTrafficPolicy=Local services.

- pkg/neg/syncers/endpoints_calculator.go
- pkg/neg/syncers/endpoints_calculator_test.go
Whenever the NEG controller would go into the degraded mode for L4 LB service with externalTrafficPolicy=Local, the controller would ignore endpoint slice data for NEG endpoints calculation. This would result in detachment of all endpoints and broken LB.
(cherry picked from commit 6ed11af3d7e2388449fac50bfc649c8354cecd28)
> [Cherry pick #2431 -> 1.27] Fix NEG degraded mode for L4 externalTrafficPolicy=Local services.

- cmd/glbc/main.go
- pkg/controller/controller.go
- pkg/controller/controller_test.go
- pkg/loadbalancers/interfaces.go
- pkg/loadbalancers/l7s.go
- pkg/loadbalancers/loadbalancers_test.go
- pkg/sync/interfaces.go
- pkg/sync/sync.go
- pkg/utils/common/common.go
- pkg/utils/common/common_test.go
- pkg/utils/common/finalizer.go
* Initialize a logger instance in cmd/glbc/main.go.
* All ingress controller log messages will be prefixed by `IngressController`. 
Example:
```
I0111 19:55:55.582574  873925 controller.go:170] "IngressController: Ingress added, enqueuing" ingressKey="default/neg-demo-ing" 
I0111 19:55:55.583044  873925 controller.go:585] "IngressController/preSyncGC: Running preSyncGC" ingressKey="default/neg-demo-ing"
I0111 19:55:55.583458  873925 controller.go:406] "IngressController/SyncBackends: Skip syncing instance groups" ingressKey="default/neg-demo-ing"    
```
* Logging for sub-components like HealthChecker will be added in separate PRs.
> Add contextual logging for ingress controller.

- cmd/glbc/main.go
- pkg/flags/flags.go
* The IG controller will run if enable-ig-controller is enabled.
* Setting its default value as true so we won't break any existing tests.
* Flag-gate IG controller with enable-ig-controller.
> Introduce enable-ig-controller flag, and flag-gate IG controller.

- pkg/backends/syncer.go
- pkg/backends/syncer_test.go
- pkg/healthchecks/healthchecks.go
- pkg/healthchecks/healthchecks_test.go
- pkg/healthchecks/interfaces.go
- pkg/translator/healthchecks.go
- pkg/translator/healthchecks_test.go
- pkg/utils/healthcheck/healthcheckdesc.go
- pkg/utils/healthcheck/healthcheckdesc_test.go
* Add contextual logging for L7 Health Checker functions.
* Functions will take the logger from higher level so contexts can be preserved and embedded. 
Exmaple:
```
I0131 20:02:32.530192 1904521 healthchecks.go:146] "SyncServicePort" servicePortID="default/neg-demo-svc/&ServiceBackendPort{Name:,Number:80,}" nodePort=0 portNumber=80 portName
="http" THCOptInOnSvc=false enableTHC=false                                                                                                                                      
I0131 20:02:32.530259 1904521 healthchecks.go:307] "DefaultNEGHealthCheck()" servicePortID="default/neg-demo-svc/&ServiceBackendPort{Name:,Number:80,}" protocol="HTTP"          
I0131 20:02:32.530292 1904521 healthchecks.go:553] "Getting Health Check" …
```
> Add contextual logging L7 Health Checker.

- pkg/backends/backends.go
- pkg/backends/backends_test.go
- pkg/backends/features/iap.go
- pkg/backends/ig_linker.go
- pkg/backends/ig_linker_test.go
- pkg/backends/integration_test.go
- pkg/backends/interfaces.go
- pkg/backends/neg_linker_test.go
- pkg/backends/regional_ig_linker.go
- pkg/backends/regional_ig_linker_test.go
- pkg/backends/syncer.go
- pkg/backends/syncer_test.go
- pkg/composite/composite.go
- pkg/controller/controller.go
- pkg/loadbalancers/l4.go
- pkg/loadbalancers/l4_test.go
- pkg/loadbalancers/l4netlb.go
- pkg/loadbalancers/l7.go
* BackendSyncer works like the manager for backends, while backend.go
contains functions working on individual backends.
* We will do context embedding in backendSyncer when we process each
backend.
Exmaple:
```
I0131 20:02:35.890028 1904521 syncer.go:62] Sync: backend {ID:default/neg-demo-svc/&ServiceB(14 results) [2237/2826]
80,} NodePort:0 Port:80 PortName:http Protocol:HTTP TargetPort:{Type:0 IntVal:9376 StrVal:} NEGEnabled:true VMIPNEGE
nabled:false L4RBSEnabled:false L7ILBEnabled:false L7XLBRegionalEnabled:false THCConfiguration:{THCOptInOnSvc:false
THCEvents:{THCConfigured:false BackendConfigOverridesTHC:false THCAnnotationWithoutFlag:false THCAnnotationWithoutNE
G:false}} BackendConfig:<nil> BackendNamer:0xc00043d940 MaxRatePerEndpoint:<nil> CapacityScaler:<nil>}
I0201 …
```
> Add contextual logging for Backend pools. 

- cmd/glbc/main.go
- pkg/context/context.go
- pkg/firewalls/controller.go
- pkg/instancegroups/controller.go
- pkg/l4lb/l4controller.go
- pkg/l4lb/l4netlbcontroller.go
- pkg/neg/controller.go
- pkg/neg/controller_test.go
- pkg/psc/controller.go
- pkg/psc/controller_test.go
- pkg/servicemetrics/servicemetrics.go
* We require all controllers follow the same pattern for their Run functions as in they cannot take any parameters. NEG controller and PSC controller are updated to accomodate this.
> Make all controllers follow the same Run() pattern.

- cmd/glbc/app/handlers.go
- cmd/glbc/main.go
- pkg/controller/controller.go
- pkg/flags/flags.go
* Pull out SIGTERM Handler so it is independent from the ingress controller and only closes closeCh when TERM signal is received.
* Run ingress controller in its own goroutine.
* Add a waitgroup to ensure cleanups are properly executed after close.
* Exit when cleanups are finished or 30 seconds timeout is reached. Instead of waiting on cleanup indefenitely, this avoids possible hanging of the program.
* Flag-gate ingress and firewall controller using runIngressController flag.
> Pull out SIGTERMHandler, flag-gate ingress and firewall controller, and run L7 NEG as default

- pkg/instancegroups/controller.go
* Variables in defer are evaluated at the time we reach defer. In this case, it is evaluated at the beginning of the function. To fix this, the log line should be wrapped in function so the whole function is evaluated at the end.
> time.Since with defer should be wrapped in function.

- cmd/glbc/main.go
- pkg/flags/flags.go
* NEG controller should not have logic to understand which controllers are running.
* Introduce enable-l4-neg to flag-gate L4 NEG processing. Its value will be determined from the manifest level.
> Introduce enable-l4-neg flag and use it to flag-gate L4 NEGs.

- cmd/glbc/app/metrics.go
- cmd/glbc/main.go
* Add lock availability metrics.
* NEG controller leader election will run separately if leader election is enabled.
* For now, NEG controller leader election only does metrics collection.
> Add lock availability metrics.

- cmd/glbc/main.go
- pkg/flags/flags.go
* If EnableNEGControllerLeaderElection is true, then we will not only collect metrics on NEG lock, but also run NEG Controller with it.
* NEG Controller will also listen to stopCh, and terminate if stopCh is closed.
> Update NEG controller run behavior based on GateNEGByLock flag.

- pkg/backends/neg_linker.go
- pkg/backends/neg_linker_test.go
- pkg/fuzz/features/neg.go
- pkg/healthchecks/healthchecks_test.go
- pkg/utils/namer/interfaces.go
- pkg/utils/namer/namer.go
- pkg/utils/namer/namer_test.go
- pkg/utils/serviceport.go
- pkg/utils/serviceport_test.go
- This is required to share the same service between RXLB and ILB. Frontend resources already have separate names (they depend on the ingress)
> Introduce separate backend naming scheme for RXLB Ingress

- pkg/controller/controller.go
`StartLogging` actually expects logging function that supports formatting string, which is not the case with a context logger
> Fix broadcasting events

- pkg/neg/syncers/transaction.go
- pkg/neg/syncers/transaction_test.go
* Make sure error state is reset when there is no change in normal and degraded mode calculation.
* This allows errorState to be cleared when enableDegradedMode is false.
> Reset error state even when degraded mode is not enabled.

- cmd/e2e-test/regional_xlb_test.go
- Some resources are not ready, even if the traffic is flowing.
- This is not the best, but quick hack, that fixes the failures.
> Add sleep after transitioning in e2e test

- pkg/l4lb/l4controller.go
- pkg/l4lb/l4controller_test.go
- pkg/loadbalancers/forwarding_rules.go
We should create ILB if legacy forwarding rule does not exists (404) or has a different scheme than expected
Plus tiny panic fix
> Make sure we don't create ILBs if reading legacy forwarding rule failed

- cmd/e2e-test/regional_xlb_test.go
- pkg/l4lb/l4controller.go
- pkg/l4lb/l4netlbcontroller.go
- pkg/l4lb/metrics/metrics.go
The metric was proposed by our SRE when we discussed  improvements in the component.
This metric gives better observability than l4_failed_healthcheck_count / l4_controller_healthcheck
> Add metric with timestamp of last sync item by l4 controllers

- pkg/fuzz/validator.go
- Before, if Ingress.Spec didn't specify default backend -- we wouldn't check it at all
- Add a verification, that will check that if DefaultBackend is not specified -- we get a 404 error
> Add validating Default 404 service in e2e tests

- go.mod
- go.sum
- vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/gen.go
- vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/meta/compute_services.go
- vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/service.go
- vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/utils.go
- vendor/modules.txt
- This will add Patch Methods for HttpsTargetProxy which are needed for RXLB
> Update k8s-cloud-provider to 1.27

- pkg/l4lb/l4controller.go
- pkg/l4lb/l4controller_test.go
- pkg/loadbalancers/forwarding_rules.go
We should create ILB if legacy forwarding rule does not exist (404) or has a different scheme than expected
Plus tiny panic fix
> [Cherry-pick #2480 -> 1.28] Make sure we don't create ILBs if reading legacy forwarding rule failed

- cmd/glbc/main.go
* wg.Add(1) when the counter is zero must execute before wg.Wait(). This is to ensure wg.Wait() does wait instead of finishing before the counter is incremented.
> Do wg.Add before spawning a goroutine.

- pkg/instancegroups/controller.go
- pkg/instancegroups/controller_test.go
Sync function should not enqueue every node separately when we need to update the IGs in controller.
Just add a request to update with a dummy node as a key.
> Simplify InstanceGroup.Sync()

- pkg/psc/controller.go
- pkg/psc/controller_test.go
NOTES:
```
Previously, we used to see less of 403 forbidden errors because we
always used to look for subnets in the same project as the GKE clusters
project, in which case the service-account always had permissions. This
meant that for Shared VPC use cases, we used to incorrectly look for the
subnet in the service project and not in the host project.
After the changes introduced in commit
https://github.com/kubernetes/ingress-gce/commit/12ee6f29c07f6542a49e4abd82a36a8046999612#diff-aacf8e53dbfd73dd635a4d6615f52725b9f2b1ebcdbb25efae5a6bae20201fd7
within the file vendor/k8s.io/cloud-provider-gcp/providers/gce/support.go, we
now corrected the behaviour for Shared VPC where we now start looking for the
subnet in the host project. But this often leads to 403 forbidden …
```
> Do not consider forbidden errors within the PSC controllers sync metrics

- pkg/firewalls/fakes.go
- pkg/firewalls/firewalls.go
- pkg/firewalls/firewalls_test.go
- pkg/test/utils.go
GetFirewall could fail for reasons other than notFound, and treating them all as notFound could lead to error during CreateFirewall(StatusConflict).
> Create firewall if it doesn't exist during periodic resync.

- pkg/l4lb/l4controller.go
- pkg/l4lb/l4lbcommon.go
- pkg/l4lb/l4lbcommon_test.go
- pkg/l4lb/l4netlbcontroller.go
- pkg/l4lb/metrics/metrics.go
- pkg/utils/common/finalizer.go
Sometimes users remove finalizers and it affects
garbage collection. We want to emit a warning event in that case and record it within a new metric l4LBRemovedFinalizers.
> Add a check for removed l4 finalizers

- pkg/l4lb/l4controller.go
- pkg/l4lb/l4lbcommon.go
- pkg/l4lb/l4netlbcontroller.go
- pkg/l4lb/updatetype.go
Enhance context logging for ILB controller.
Avoid duplicated context logging by using root logger with name/namespace context.
/assign @cezarygerard @code-elinka @mmamczur @08volt
> Unify context logging across L4 LB

- pkg/neg/readiness/reflector.go
- pkg/neg/readiness/reflector_test.go
* For pods in non-default subnet, it is possible for them to share the same labels with the pods in default subnets. As a result, the list of neg will not be empty in the NEG lookup, so they will not be marked as ready for not in default subnet.
> Update readiness check for non-default subnet nodes.

- pkg/instancegroups/manager.go
- pkg/utils/utils.go
this will also prevent requeing of the same service
> ignore errors if adding a node results in "400: memberAlreadyExists"

- pkg/neg/readiness/reflector.go
- pkg/neg/readiness/reflector_test.go
- pkg/neg/syncers/utils.go
- pkg/neg/syncers/utils_test.go
- pkg/neg/types/fakes.go
- pkg/neg/types/states.go
- pkg/neg/types/sync_errors.go
- pkg/utils/zonegetter/zone_getter.go
- pkg/utils/zonegetter/zone_getter_test.go
* If nodeName is empty on the Pod, it means the Pod hasn't been scheduled. We will mark it as unready, and when the Pod is scheduled, it will trigger another Pod update.
* If we ever encounter a persistent issue when checking node subnet during pod readiness, we mark the pod as ready if the timeout is reached.
* An endpoint corresponds to a node without PodCIDR should be considered as an error-state condition. A new error-state error is added to ensure we can correctly trigger this, and we will exclude this endpoint in degraded mode.
> Skip marking NEG readiness gate as ready until nodeName is set for msc, and add new error state for Node without PodCIDR

- pkg/neg/readiness/reflector.go
- pkg/neg/readiness/reflector_test.go
- pkg/neg/syncers/utils.go
- pkg/neg/syncers/utils_test.go
- pkg/neg/types/fakes.go
- pkg/neg/types/states.go
- pkg/neg/types/sync_errors.go
- pkg/utils/zonegetter/zone_getter.go
- pkg/utils/zonegetter/zone_getter_test.go
> [Cherry-pick #2599 -> 1.30] Skip marking NEG readiness gate as ready until nodeName is set for msc, and add new error state for node without PodCIDR.

- cmd/e2e-test/upgrade/neg.go
- cmd/e2e-test/upgrade_test.go
Replace obsolete test based on neg-status with one based on NEG CR for Standalone NEGs.
- neg-status is not guaranteed to be accurate and a has race condition with the Node Becoming ready and the NEG Controller processing the Service.
- Make the test based on NEG CR the standard one and remove the old test based on NEG status (which is way past the supported version)
> Replace obsolete test based on neg-status with one based on NEG CR for Standalone NEGs.

- pkg/instancegroups/manager.go
- pkg/instancegroups/manager_test.go
- pkg/l4lb/l4netlbcontroller_test.go
the is an error in truncating to 1000 nodes before iterating over zones when adding/removing instances from instance group
plus unit tests for multizonal case
> Fix instance group sizes

- pkg/instancegroups/manager.go
- pkg/instancegroups/metrics/metrics.go
Add instance group resize metrics.
- An histogram that tracks how many nodes we are adding or removing.
- A counter that tracks the number of adds and removes we are attempting.
> Add instance group resize metrics

- pkg/loadbalancers/addresses.go
- pkg/translator/translator.go
- pkg/translator/translator_test.go
- Apparently Premium tier became available for RXLB https://cloud.google.com/network-tiers/docs/overview#resources
- Verified with locally running controller, and it indeed works
> Use Premium Network Tier for RXLB

- pkg/instancegroups/manager.go
- pkg/instancegroups/manager_test.go
- pkg/instancegroups/metrics/metrics.go
- pkg/l4lb/l4netlbcontroller_test.go
- pkg/utils/utils.go
Fix instance group sizes and related metrics
Includes:
- Improve error handling "400: memberAlreadyExists": https://github.com/kubernetes/ingress-gce/commit/8995ac3657a330be42d8c55be9a677fcf5abf4ec
- Fix instance group size bug https://github.com/kubernetes/ingress-gce/pull/2582
- Add metrics to track instance group size https://github.com/kubernetes/ingress-gce/pull/2610
> Release v1.30 -[Cherry-pick #2582 #2610 -> 1.30] Fix instance group size bug and add 2 new metrics to monitor resize events

- pkg/flags/flags.go
- pkg/l4lb/l4netlbcontroller_test.go
- pkg/loadbalancers/forwarding_rules.go
- pkg/loadbalancers/forwarding_rules_ipv6.go
- pkg/loadbalancers/forwarding_rules_test.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
GCE forwarding rules have a limit of 5 forwarded ports. In the external L4 load balancer, we currently turn a set of exposed ports into a port range from minPort to maxPort and forward all ports in the range, which needlessly forwards traffic for ports that are not supposed to be exposed.
With this change, if 5 or less ports are exposed, we expose each distinct, otherwise we use the old mechanism of exposing a port range. This is similar to have the Internal Load Balancer is setup, except the ILB exposes all ports if more than 5 ports need to be exposed.
To avoid recreating forwarding rules when code logic is updated, we treat port ranges and distinct ports that fall into the same port range as equivalent.
> Forward individual ports for NetLB with 5 or less service ports

- pkg/neg/manager.go
- pkg/neg/manager_test.go
This reverts the behaviour to what existed prior to https://github.com/kubernetes/ingress-gce/pull/1754.
This is also logical, since for GCE_VM_IP NEGs, the endpoints are the nodes themselves. So similar to the behavior for GCE_VM_IP_PORT negs which get synced on EndpointSlice changes, it makes sense to sync GCE_VM_IP NEGs on Node changes.
> fix: GCE_VM_IP NEGs should be synced on each Node change.

- pkg/flags/flags.go
- pkg/l4lb/l4netlbcontroller_test.go
- pkg/loadbalancers/forwarding_rules.go
- pkg/loadbalancers/forwarding_rules_ipv6.go
- pkg/loadbalancers/forwarding_rules_test.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
GCE forwarding rules have a limit of 5 forwarded ports. In the external L4 load balancer, we currently turn a set of exposed ports into a port range from minPort to maxPort and forward all ports in the range, which needlessly forwards traffic for ports that are not supposed to be exposed.
With this change, if 5 or less ports are exposed, we expose each distinct, otherwise we use the old mechanism of exposing a port range. This is similar to have the Internal Load Balancer is setup, except the ILB exposes all ports if more than 5 ports need to be exposed
> [Cherry-pick #2575 -> 1.30] Forward individual ports for NetLB with 5 or less service ports

- pkg/l4lb/l4controller.go
- pkg/l4lb/l4controller_test.go
- pkg/l4lb/l4netlbcontroller.go
- pkg/l4lb/l4netlbcontroller_test.go
This pull request introduces a delay mechanism to ensure cache synchronization before the L4NetLBController and L4Controller commence operation. This is accomplished by incorporating a 10-minute wait period with 5-second polling intervals, ensuring that all required informers have been duly updated.
* **Unit Tests:** Existing unit tests should continue to pass without modifications.
> Add initial cache sync check

- pkg/backends/ig_linker_test.go
- pkg/backends/integration_test.go
- pkg/backends/regional_ig_linker_test.go
- pkg/context/context.go
- pkg/controller/controller.go
- pkg/controller/controller_test.go
- pkg/instancegroups/controller.go
- pkg/instancegroups/controller_test.go
- pkg/instancegroups/interfaces.go
- pkg/instancegroups/manager.go
- pkg/instancegroups/manager_test.go
- pkg/l4lb/l4netlbcontroller.go
**Instance Group Manager Logger Context Enhancement**
This pull request addresses a missing context issue within the Instance Group Manager logger. When the manager is called by 'client' structs, certain log fields lacked essential contextual information. 
To resolve this, the following changes were made:
* **Public function modification:** The public function of the Instance Group Manager now explicitly takes a logger as an argument.
* **Logger field removal:** The redundant logger field within the manager has been removed.
These adjustments ensure that logs generated when the manager interacts with 'client' structs contain comprehensive contextual details, facilitating improved troubleshooting and analysis.
> instance group logger

- pkg/backends/backends.go
- pkg/backends/backends_test.go
With new backendSvcEqual we never update the localityLbPolicy on existing services that do not use Weighted Load Balancers also now this invariant is true: backendSvcEqual(old, new) == backendSvcEqual(new, old)
Plus changed the naming of some variables as confusing names may have contributed to the problem
> Improve backendSvcEqual code for backend service creation

- cmd/glbc/main.go
- pkg/context/context.go
- pkg/flags/flags.go
- pkg/l4lb/l4controller.go
- pkg/l4lb/l4netlbcontroller.go
- pkg/loadbalancers/l4.go
- pkg/loadbalancers/l4_test.go
- pkg/loadbalancers/l4ipv6.go
- pkg/loadbalancers/l4netlb.go
- pkg/loadbalancers/l4netlb_test.go
- pkg/loadbalancers/l4netlbipv6.go
Added `disable-l4-lb-fw` flag to disable _only_ the ingress -> node firewalls for L4 ILB and NetLB to remove conflicts with firewall policies.
/assign @cezarygerard 
> Add flag to disable L4 LB ingress firewalls 

- pkg/loadbalancers/l4.go
- pkg/loadbalancers/l4netlb.go
- pkg/metrics/l4_metrics.go
- pkg/metrics/l4_metrics_test.go
- pkg/metrics/types.go
If Weighted Load Balancing is enabled on a service by pods-per-node annotation, export it as part of the usage metrics for both ILB and NetLB.
> Cherry-pick #2657 Add metrics to track services using Weighted LB

- pkg/instancegroups/manager.go
- pkg/instancegroups/manager_test.go
- pkg/l4lb/l4netlbcontroller.go
With this change, the code to ensure IGs will use AllNodesFilter to determine which zones to create IGs in. The goal is to avoid detaching groups which become temporarily unready, for example after master upgrade. This change should be fine since creating and using an IG that could be empty is ok from the LB perspective. On the other hand removing a temporarily unready group can cause 10 minutes of no traffic.
> Use all zones when creating the shared IG for an RBS service.

- pkg/neg/syncers/transaction.go
- pkg/neg/syncers/transaction_test.go
- pkg/neg/syncers/utils.go
- pkg/utils/negdescription.go
* When there is conflict in NEG description, if the conflict occurs within the same cluster, skip update since that CR is owned by a different syncer. Otherwise, set initialize condition to false.
* Always update negObjRef in updateInitStatus to make sure the information is up-to-date.
> Update NEG Status update logic when there is conflict in NEG desc.

- pkg/l4lb/l4controller.go
- pkg/l4lb/l4netlbcontroller.go
- pkg/l4lb/metrics/metrics.go
If Weighted Load Balancing is enabled on a service by pods-per-node annotation, export its sync latency metrics for both ILB and NetLB. Include label for weighted load balancing in error count metric
> L4 Weighted Load Balancing sync latency and error count metrics

- pkg/backends/neg_linker.go
- pkg/backends/neg_linker_test.go
- pkg/backends/syncer_test.go
- pkg/controller/controller_test.go
- pkg/l4lb/l4controller_test.go
- pkg/l4lb/l4netlbcontroller_test.go
- pkg/test/utils.go
* Query NEGs from Svcneg Status, and only do GCE query as a fallback.
> Query NEGs from Svcneg when linking BackendServices.

- pkg/neg/manager.go
- pkg/neg/manager_test.go
- pkg/neg/syncers/transaction.go
- pkg/neg/syncers/transaction_test.go
- pkg/neg/syncers/utils.go
- pkg/neg/syncers/utils_test.go
- pkg/neg/types/types.go
* Populate Subnet in NEG CR based on the subnet on the NEG.
* Populate State as ACTIVE for newly created NEGs. For NEGs in the zones which don't have any nodes, set their state as INACTIVE.
* Remove deleted NEG reference during NEG GC.
> Update NEG reference in NEG CR

- pkg/instancegroups/manager.go
- pkg/instancegroups/manager_test.go
- pkg/l4lb/l4netlbcontroller_test.go
- pkg/utils/utils.go
there is an error in truncating to 1000 nodes before iterating over zones when adding/removing instances from instance group.
The instance group management logic should be following:
- For each zone add up to #m.maxIGSize number of nodes to the instance group
- If there is more then truncate last nodes (in alphabetical order)
- the logic should be consistent with cloud-provider-gcp's Legacy L4 ILB Controller: https://github.com/kubernetes/cloud-provider-gcp/blob/fca628cb3bf9267def0abb509eaae87d2d4040f3/providers/gce/gce_loadbalancer_internal.go#L606C1-L675C1
- the  production value for m.maxIGSize should be set to 1000 as is in the cloud-provider-gcp.
> [Cherrypick #2582 into release-1.28] Fix instance group sizes

- cmd/glbc/main.go
- pkg/flags/flags.go
- pkg/neg/controller.go
- pkg/neg/controller_test.go
- pkg/neg/manager.go
- pkg/neg/manager_test.go
- pkg/neg/syncers/endpoints_calculator.go
- pkg/neg/syncers/endpoints_calculator_test.go
- pkg/neg/syncers/subsets.go
- pkg/neg/syncers/transaction.go
- pkg/neg/syncers/transaction_test.go
- pkg/neg/types/types.go
- pkg/neg/types/types_test.go
- pkg/utils/common/finalizer.go
- pkg/utils/utils.go
This PR contains changes for the NEG controller to support L4 NetLB services.
The NEG controller will be triggered for NetLBs with the presence of the new netlb V3 finalizer
Also the PortInfo had to be extended to contain the type of L4 LB since the calculators need this info in order to pick the right subset sizes. NetLBs will use larger subsets than ILB. Also this allows to differentiate a NEG syncer for ILB vs one for NetLB, when the service moves between ILB and NetLB the syncer for the old service spec will be stopped and a new one created for the changed service.
> NEG controller part - L4 RBS External LB NEG support

- pkg/backends/neg_linker.go
- pkg/backends/neg_linker_test.go
> Remove NEGs in to-be-deleted state after merging Backends.

- pkg/l4lb/l4netlbcontroller.go
- pkg/l4lb/metrics/metrics.go
- pkg/loadbalancers/l4.go
- pkg/loadbalancers/l4netlb.go
- pkg/metrics/l4_metrics.go
- pkg/metrics/l4_metrics_test.go
- pkg/metrics/types.go
This extends the L4 NetLB metrics with `backend_type` field that will allow tracking the adoption and performance of NEG backed LBs vs IG ones.
> Add backend_type label to l4_netlbs_count and the L4_netlb latency metrics

- pkg/loadbalancers/l4.go
- pkg/loadbalancers/l4_test.go
- pkg/loadbalancers/l4netlb_test.go
LocalityLBPolicy = MAGLEV requires allowlisting. Implement logic to make ILBs use default "" LocalityLBPolicy and use MAGLEV once WEIGHTED_MAGLEV or MAGLEV is used.
> [Cherry-pick #2652 -> 1.31] Use default LocalityLBPolicy for ILB

- pkg/loadbalancers/forwarding_rules_ipv6.go
- pkg/loadbalancers/l4netlb_test.go
- pkg/utils/utils.go
BUG FIX:
NetLB does not support IPv6 on standard tier network.
Whenever this config was used the real setup was silently using premium tier.
> IPv6 NetLB - disallow using on standard tier network

- pkg/instancegroups/manager.go
- pkg/l4lb/l4netlbcontroller_test.go
- pkg/neg/manager_test.go
- pkg/neg/metrics/metricscollector/metrics_collector.go
- pkg/neg/metrics/metricscollector/metrics_collector_test.go
- pkg/neg/syncers/dualstack/migrator.go
- pkg/neg/syncers/dualstack/migrator_test.go
- pkg/neg/syncers/endpoints_calculator.go
- pkg/neg/syncers/endpoints_calculator_test.go
- pkg/neg/syncers/subsets.go
- pkg/neg/syncers/subsets_test.go
- pkg/neg/syncers/transaction.go
- pkg/neg/syncers/transaction_table.go
- pkg/neg/syncers/transaction_table_test.go
- pkg/neg/syncers/transaction_test.go
- pkg/neg/syncers/utils.go
- pkg/neg/syncers/utils_test.go
- pkg/neg/types/interfaces.go
- pkg/neg/types/types.go
- pkg/utils/zonegetter/zone_getter.go
- pkg/utils/zonegetter/zone_getter_test.go
* Use endpointGroupInfo instead of string(zone) when mapping NEGs since now endpoints shall be partitioned based on the zone and the subnet they are in.
* Nodes in non-default subnets will be filtered when enableMultiSubnetCluster=true and enableMultiSubnetClusterPhase1=false. When enableMultiSubnetClusterPhase1=true, we will include endpoints
and nodes from non-default subnets.
> Moving from string(zone) to endpointGroupInfo when mapping NEGs, and populate subnet values for nodes in zoneGetter and NEG syncers.

- pkg/loadbalancers/forwarding_rules_ipv6.go
- pkg/loadbalancers/l4netlb_test.go
- pkg/utils/utils.go
GCE NetLB does not support IPv6 and Network Tier standard
Added user error when ensuring NetLB with Dualstack and Network Tier Standard Added tests to verify that the LB won't be provisioned in this specific case.
> [Cherry-pick #2700 -> 1.31] Not ensuring NetLb when Dualstack and Network Tier forced to Standard

- pkg/address/manager.go
- pkg/address/manager_test.go
- pkg/loadbalancers/forwarding_rules.go
- pkg/loadbalancers/forwarding_rules_ipv6.go
- pkg/loadbalancers/l4.go
- pkg/loadbalancers/l4_test.go
- pkg/loadbalancers/l4netlb.go
This change shrinks the size of the `pkg/loadbalancers` by moving address related utilities to another package.
> Refactor AddressManager into pkg/address

- pkg/flags/flags.go
Adds `EnableL4MixedProtocol` flag for mixed protocol feature. 
Also auto reformatted the `var ( F = ... )` to `var F = ...`.
> Add flag for L4 Mixed Protocol feature

- hack/run-local-glbc.sh
File `run-local.sh` does not exist. It should be set to `setup-local.sh` as docs suggest.
See: [docs/contrib/dev-setup.md](https://github.com/kubernetes/ingress-gce/blob/master/docs/contrib/dev-setup.md)
> Fix small typo in `hack/run-local-glbc.sh`

- pkg/firewalls/equal.go
- pkg/firewalls/equal_test.go
- pkg/firewalls/firewalls_l4.go
- pkg/firewalls/firewalls_l4_test.go
- pkg/healthchecksl4/healthchecksl4.go
- pkg/healthchecksl4/healthchecksl4_test.go
- pkg/loadbalancers/l4.go
- pkg/loadbalancers/l4_test.go
- pkg/loadbalancers/l4ipv6.go
- pkg/loadbalancers/l4netlb.go
- pkg/loadbalancers/l4netlb_test.go
- pkg/loadbalancers/l4netlbipv6.go
Changes the L4 Firewall to allow for the future multi protocol LB feature.
`compute.Firewall` struct allows to pass multiple allow rules of `compute.FirewallAllowed` type. Previously we only used one allow rule per service, but that will change with a multi protocol support feature where we will need to pass one rule for TCP and one for UDP.
There might be issues with casing, as the protocol is either UPPERCASE or lowercase. I want to make sure this doesn't trigger unnecessary updates to GCP, hopefully E2E tests will catch that.
> Firewall Rules - multi protocol support

- pkg/forwardingrules/ports.go
- pkg/forwardingrules/ports_test.go
Mixed protocol feature cannot rely on existing utils.GetPorts as it returns all ports in the spec, ignoring protocol. 
Part of the https://github.com/kubernetes/ingress-gce/pull/2734
> Add protocol aware GetPorts function

- pkg/backends/backends.go
- pkg/backends/ig_linker.go
- pkg/backends/integration_test.go
- pkg/backends/interfaces.go
- pkg/backends/neg_linker.go
- pkg/backends/regional_ig_linker.go
- pkg/backends/regional_ig_linker_test.go
- pkg/backends/syncer.go
- pkg/backends/syncer_test.go
- pkg/controller/controller.go
- pkg/l4lb/l4controller.go
- pkg/l4lb/l4netlbcontroller.go
- pkg/loadbalancers/l4.go
- pkg/loadbalancers/l4netlb.go
- pkg/loadbalancers/l7.go
As per [Go Wiki](https://go.dev/wiki/CodeReviewComments#interfaces) interfaces should generally belong in the package that uses values of the interface type, not the package that implements these values. In this case there is no real added value of using interfaces instead of concrete types. We can safely remove them and get rid of boilerplate.
> Remove unnecessary interfaces in pkg/backends

- pkg/loadbalancers/l4.go
- pkg/loadbalancers/l4_test.go
- pkg/utils/utils.go
If non-existent subnetwork for internal load balancer specified using `networking.gke.io/internal-load-balancer-subnet` annotation mark resulting error as user one
> ILB - if wrong subnet specified mark as user error

- pkg/l4lb/l4netlbcontroller.go
- pkg/l4lb/l4netlbcontroller_test.go
RBS controller can have only V3 finalizer (without V2), so it should be also checked to infer if service is RBS based.
> Fix checks if service provisioned by RBS controller

- cmd/glbc/main.go
- pkg/backends/protocol.go
- pkg/backends/protocol_test.go
- pkg/context/context.go
- pkg/l4lb/l4controller.go
- pkg/loadbalancers/l4.go
Similar to https://github.com/kubernetes/ingress-gce/pull/2733, but this one only looks at the service definitions, for single protocol it won't change anything, so for example TCP will still have TCP backend, but when both TCP and UDP services are used it will use L3 backend service.
> Add backends.GetProtocol func for mixed protocol

- cmd/glbc/app/clients.go
- go.mod
- go.sum
- pkg/multiproject/gce/gce.go
- pkg/multiproject/gce/gce_test.go
- pkg/multiproject/sharedcontext/sharedcontext.go
- vendor/github.com/go-ini/ini/.editorconfig
- vendor/github.com/go-ini/ini/.gitignore
- vendor/github.com/go-ini/ini/.golangci.yml
- vendor/github.com/go-ini/ini/LICENSE
- vendor/github.com/go-ini/ini/Makefile
- vendor/github.com/go-ini/ini/README.md
- vendor/github.com/go-ini/ini/codecov.yml
- vendor/github.com/go-ini/ini/data_source.go
- vendor/github.com/go-ini/ini/deprecated.go
- vendor/github.com/go-ini/ini/error.go
- vendor/github.com/go-ini/ini/file.go
- vendor/github.com/go-ini/ini/helper.go
- vendor/github.com/go-ini/ini/ini.go
- vendor/github.com/go-ini/ini/key.go
- vendor/github.com/go-ini/ini/parser.go
- vendor/github.com/go-ini/ini/section.go
- vendor/github.com/go-ini/ini/struct.go
- vendor/modules.txt
- Still uses default gce.conf to get most of the info
- If project info not specified will use default config values, which corresponds to cluster-project
- Overrides TokenURL and TokenBody and Network info if project is specified
> Add code for multiproject GCE Client creation

- pkg/forwardingrules/protocol.go
- pkg/forwardingrules/protocol_test.go
- pkg/loadbalancers/forwarding_rules.go
Used behind MixedProtocol feature flag for ILBs only. Requires #2743 to be merged as well.
> Add forwardingrules.GetILBProtocol func for mixed protocol

- cmd/glbc/main.go
- pkg/context/context.go
- pkg/firewalls/allowed.go
- pkg/firewalls/allowed_test.go
- pkg/l4lb/l4netlbcontroller.go
- pkg/loadbalancers/l4netlb.go
When specifying multi protocol service NetLB Controller needs to update firewall rules to allow traffic to flow on both TCP and UDP ports. This PR introduces `firewalls.AllowedForService` which adds that functionality, and invokes the function if the EnableL4MixedProtocol flag is enabled.
> Firewall Allowed for NetLB mixed protocol

- pkg/annotations/service.go
- pkg/loadbalancers/l4.go
- pkg/loadbalancers/l4syncresult.go
- Adds L3 forwarding rules annotations to the ILB service.
- Adds missing code to use L3 protocol inside `GetFRName()`.
- Updates `getOldIPv4ForwardingRule()` to allow for deletion of L3 Forwarding rules. This isn't behind the feature flag to allow users to delete L3 Forwarding rule even after opting out of  `--enable-l4-mixed-protocol`.
I've tested it manually with various transitions including: from nothing to mixed, mixed to nothing, tcp to mixed to udp to nothing, various port changes while staying in L3. I also created the mixed protocol service when using `--enable-l4-mixed-protocol` and then after disabling the flag I've verified that the service has been recreated based on the first protocol (legacy) while still using the same IP.
> Add L3 forwarding rules annotations and fix transitions

- pkg/loadbalancers/l4.go
When specifying multi protocol service ILB Controller needs to update firewall rules to allow traffic to flow on both TCP and UDP ports. Used only when the mixed protocol feature flag is enabled.
Similar to #2740, but for ILB.
> Firewall Allowed for ILB mixed protocol

- pkg/backends/ig_linker_test.go
- pkg/backends/integration_test.go
- pkg/backends/regional_ig_linker_test.go
- pkg/context/context.go
- pkg/controller/controller_test.go
- pkg/instancegroups/controller_test.go
- pkg/instancegroups/manager_test.go
- pkg/l4lb/l4controller_test.go
- pkg/l4lb/l4netlbcontroller_test.go
- pkg/neg/controller.go
- pkg/neg/controller_test.go
- pkg/neg/manager.go
- pkg/neg/manager_test.go
- pkg/neg/readiness/reflector_test.go
- pkg/neg/syncers/endpoints_calculator_test.go
- pkg/neg/syncers/transaction.go
- pkg/neg/syncers/transaction_test.go
- pkg/neg/syncers/utils_test.go
- pkg/neg/types/fakes.go
- pkg/neg/types/interfaces.go
- pkg/neg/types/types.go
- pkg/neg/types/types_test.go
- pkg/utils/namer/interfaces.go
- pkg/utils/namer/l4_namer.go
- pkg/utils/namer/l4_namer_test.go
- pkg/utils/namer/namer.go
- pkg/utils/zonegetter/fake.go
- pkg/utils/zonegetter/zone_getter.go
- pkg/utils/zonegetter/zone_getter_test.go
* Query Node Topology CR for the current set of NEGs in the cluster.
* When ensureNetworkEndpointGroups(), ensure NEGs are properly provisioned in the non-default subnets as well.
> Create additional NEGs based on subnets in Node Topology CR.

- cloudbuild.yaml
- hack/push-multiarch.sh
* Add one more tag for e2e-test images
> Add ability to push images with multiple tags

- cloudbuild.yaml
* Quotes literal are interpreted as quote characters which error during tag creation
> Remove quotes literal

- pkg/neg/syncers/subsets.go
- pkg/neg/syncers/transaction.go
- pkg/neg/syncers/transaction_test.go
- pkg/neg/syncers/utils.go
- pkg/neg/syncers/utils_test.go
> Extend retrieve current NEG endpoints to also look for NEGs in non-default subnets.

- pkg/neg/syncers/transaction.go
- pkg/neg/syncers/transaction_test.go
> Ensure NEG Readiness Reflector commits endpoints from non-default subnets.

- pkg/neg/syncers/transaction.go
- pkg/neg/syncers/transaction_test.go
> Update endpoints for NEGs from non-default subnet.

- cmd/glbc/main.go
- pkg/context/context.go
- pkg/flags/flags.go
- pkg/l4lb/l4controller.go
- pkg/l4lb/l4netlbcontroller.go
Since the implementation for ILB is ready it makes sense to separate the flag to enable ILBs in e2e tests, while having currently WIP NetLB be disabled. 
It uses the same naming convention as DualStack:
```
EnableL4ILBDualStack:          flags.F.EnableL4ILBDualStack,
EnableL4NetLBDualStack:        flags.F.EnableL4NetLBDualStack,
````
> Split the enable-mixed-protocol flag into ILB and NetLB

- pkg/instancegroups/manager.go
- pkg/instancegroups/manager_test.go
If no nodes for certain zone were provided to Sync, then all existing ones are removed.
Issue: https://github.com/kubernetes/ingress-gce/issues/2724
> Fix excluding of nodes from NetLBs for last node in zone

- pkg/loadbalancers/forwarding_rules_ipv6.go
- pkg/loadbalancers/l4.go
- pkg/loadbalancers/l4_mixed_test.go
- pkg/loadbalancers/l4_test.go
- pkg/loadbalancers/l4ipv6.go
- pkg/loadbalancers/mixedprotocoltest/annotations.go
- pkg/loadbalancers/mixedprotocoltest/consts.go
- pkg/loadbalancers/mixedprotocoltest/ingress.go
- pkg/loadbalancers/mixedprotocoltest/resources.go
- pkg/loadbalancers/mixedprotocoltest/spec.go
- Adds IPv6 and Dual Stack support for mixed protocol ILBs
- Adds test data in `pkg/loadbalancers/mixedprotocoltest` for {TCP, UDP, Mixed} x {IPv4, IPv6, DualStack}, including:
-  annotations
-  consts for names of nodes, services, namespaces, ip addresses
- Kubernetes Ingress definitions
- Cloud resources (fakeGCE): forwarding rules, backend services, firewalls, health checks
- Adds TestEnsureMixedILB:
- Tests for {IPv4, IPv6, DualStack} x {TCP, UDP, Mixed}
- create
- transitions
- delete
- Fixes forwarding rule resource leak when switching both protocol and stack f.e. IPv4 UDP to IPv6 TCP, by deleting all potential forwarding rules for a service. This leak will be created because the delete logic tries to create forwarding rule name for the old state stack based on the new protocol. So …
> Add Ensure tests for mixed protocol ILB

- pkg/forwardingrules/needs.go
- pkg/forwardingrules/needs_test.go
This will be used by NetLB controller to determine whether to use a mixed forwarding rule manager or an already existing one.
Part of #2764
> Add NeedsMixed helper function

- pkg/multiproject/finalizer/finalizer.go
- pkg/multiproject/finalizer/finalizer_test.go
- pkg/utils/common/finalizer.go
- pkg/utils/patch/patch.go
- pkg/utils/patch/patch_test.go
- Added general functions to patch ClusterSlice ObjectMetadata
- Added functions to add/delete neg cleanup finalizer on ClusterSlice.
This will allow to properly clean neg controllers when cluster slice
is deleted
> Add funcs to add/delete finalizer on ClusterSlice 

- pkg/neg/metrics/metricscollector/metrics_collector.go
- pkg/neg/metrics/metricscollector/metrics_collector_test.go
- pkg/neg/syncers/dualstack/migrator.go
- pkg/neg/syncers/dualstack/migrator_test.go
- pkg/neg/syncers/endpoints_calculator.go
- pkg/neg/syncers/endpoints_calculator_test.go
- pkg/neg/syncers/subsets.go
- pkg/neg/syncers/subsets_test.go
- pkg/neg/syncers/transaction.go
- pkg/neg/syncers/transaction_test.go
- pkg/neg/syncers/utils.go
- pkg/neg/syncers/utils_test.go
- pkg/neg/types/interfaces.go
- pkg/neg/types/types.go
The idea we're trying to represent is that NEGs will be created in this zone and subnet. These two parameters combined are defining the location for that NEG, hence the name NEGLocation.
> Rename EndpointGroupInfo to NEGLocation for a better representation of the concept

- pkg/address/hold.go
- pkg/address/hold_test.go
- pkg/loadbalancers/forwarding_rules.go
This commit moves pieces of code responsible for picking, holding and releasing IP addresses from single protocol ensureIPv4ForwardingRule to a separate function, so that the logic can be reused in mixed protocol implementation as well. It also adds a suite of unit tests for this shared functionality.
> Add HoldExternalIPv4 func

- pkg/forwardingrules/netlb_mixed_manager.go
- pkg/forwardingrules/netlb_mixed_manager_test.go
MixedManagerNetLB will be run inside the L4NetLB loadbalancer.
* EnsureIPv4 will be used manage forwarding rules when the mixed protocol flag is enabled and service has both TCP and UDP ports defined.
* DeleteIPv4 will be used when either service is deleted or there will be conversion from mixed to single protocol.
* AllRules will be used in single protocol implementation to hold address from mixed protocol forwarding rules.
> Add forwardingrules.NetLBMixedManager

- hack/setup-local.sh
When trying to filter clusters with "key=value" gcloud returns a warning:
```
WARNING: --filter : operator evaluation is changing for consistency across Google APIs.  name=kluster currently does not match but will match in the near future.  Run `gcloud topic filters` for details.
```
Based on the `gcloud topic filters` it is enough to replace `=` with `:`. Context:
```
key :( simple-pattern ... )
True if key matches any simple-pattern in the (space, tab, newline,
comma) separated list.
key = value
True if key is equal to value, or [deprecated] equivalent to : with
the exception that the trailing * prefix match is not supported.
For historical reasons, this operation currently behaves
differently for different Google APIs. For many APIs, this is True
if key is equal to value. For a few …
```
> Replace depracated filter expression in setup-local.sh

- pkg/multiproject/neg/neg.go
- Will be used with ProviderConfig Controller, starting NEG controller as
ProviderConfig EventHandler
based on other PR https://github.com/kubernetes/ingress-gce/pull/2755
> Add function that starts NEG controller per ProviderConfig

- pkg/multiproject/manager/manager.go
- pkg/multiproject/neg/neg.go
> Add multiproject manager which will be responsible for starting and tracking controllers per ProviderConfig

- cmd/glbc/app/handlers.go
- cmd/glbc/main.go
- pkg/context/context.go
- pkg/controller/controller.go
- pkg/l4lb/l4controller.go
- pkg/l4lb/l4netlbcontroller.go
- pkg/systemhealth/systemhealth.go
- Move Health checks out of context to systemhealth package. Context is already doing too much and systemhealth is self-sufficient struct that can live in separate package, which makes code less entangled
- Modify existing calls for AddHealthCheck to use new struct
- This will also allow to run healthchecks when controller is not initialising full context (for example in multiproject mode)
also I could've added this into L4 and L4netlb controller and add health check inside their constructor. Buuut. It would need to change too much of the test code to add everywhere new argument....
> Refactor context health check implementation

- pkg/context/context.go
- pkg/recorders/manager.go
- Add a new package "recordersmanager"
- This will allow to reuse the logic, if we don't have full controller
context (for example for multiproject mode)
based on previous PRs, should be reviewed after them
> Move recorders manager out of context for reusability

- pkg/flags/flags.go
- pkg/neg/controller.go
- pkg/neg/controller_test.go
This PR adds a flag for IPV6 only NEG's. If the flag is false, then the NEG Controller will still error if an IPV6 only service is configured.
The plan is to flag flip in a patch release once IPV6 NEG support is available in production (requires GCP LB support for IPV6 only NEG's).
> Add flag for IPV6 only NEG's

- pkg/neg/syncers/transaction.go
- pkg/neg/syncers/transaction_test.go
Multi-networking and multi subnet clusters are currently incompatible features and approach neg naming differently. Therefore, ensure that the neg syncer understands which naming scheme to use and how to detect multi-networking versus multi subnet clusters correctly
> Look for correct neg when using multi-networking

- pkg/neg/manager.go
- pkg/neg/manager_test.go
* NEG CRs should be updated with current state of NEGs. This provides the most accurate picture of the NEG and allows the CR to be consumed by other downstream clients
* Remove flag gating as this change is not specific to the multi subnet clusters feature.
> Enable CR updates after NEG GC always

- hack/verify-all.sh
The linter is still enabled by the make test run which runs inside the build image. This ensures that the go version matches what we expect the code to run in. hack/verify-all.sh runs with the host go version which may not always be compatible.
Temporarily disable the linters in hack/verify-all.sh due to a bump in go image for kubekinsv2 image
(https://github.com/kubernetes/test-infra/commit/6d1f25d314508c3968c6c15cd586086fe0a50540). This image is used in our GH testing which caused our linters to fail as our build is still on Go 1.22 but the image is now in Go 1.24.
> Disable linter in hack/verify-all.sh

- pkg/neg/syncers/subsets.go
Match the max subset size with IG per zone for NEG backed NetLB.
> Increase max number of subsets NetLB for ETP:local

- cmd/glbc/main.go
- pkg/flags/flags.go
This is the first part of Phase 1 of the effort to split L4 from ingress-gce.
> Introduce a new lock for L4 and related controllers.

- hack/setup-local.sh
Fixes a bug that prevented the script from working with regional clusters. 
Previously, the script incorrectly used the cluster's region as the instance group zone. This change now extracts the correct zone from the instance group's URL, ensuring compatibility with regional clusters.
> script: Use instance zone instead of cluster location in setup-local script

- hack/setup-local.sh
This PR introduces a bash script (setup-local-regional.sh) to simplify GLBC configuration for regional GKE clusters.
The script automates the process of gathering necessary information about a regional cluster, with logic to find a running instance in the cluster's instance groups. including:
- Network name    
- Subnetwork name    
- Project ID    
- Node tags    
- Instance zone    
It then generates a gce.conf file containing these parameters, which is required for running GLBC.
> Setup script for GLBC configuration on regional clusters

- pkg/neg/syncers/endpoints_calculator.go
- pkg/neg/syncers/subsets_test.go
- pkg/neg/syncers/syncer.go
- pkg/neg/syncers/transaction.go
- pkg/neg/syncers/transaction_test.go
- pkg/neg/syncers/utils.go
- pkg/neg/syncers/utils_test.go
This includes fixing:
* error strings should not end with punctuation or newlines (ST1005)
* redundant type from array, slice, or map composite literal
* simplify range expression
* duplicate imports
* deprecated sets.Strings
* package "xxx" is being imported more than once (ST1019)
* redundant return statement
Doesn't touch logic.
> Fix linter warnings for pkg/neg/syncers

- pkg/neg/syncers/endpoints_calculator.go
- pkg/neg/syncers/endpoints_calculator_test.go
- pkg/neg/syncers/subsets.go
- pkg/utils/zonegetter/fake.go
* Calculate the number of NEGs created linearly based on the actual Pod count.
* It also takes into account other factors. It will provision at least 3 NEGs for each Zone/Subnet pair. It also maxes out on Node count or limits set by passthrough LBs.
* In scalability tests with a large number of small LBs it reduces time to provision and delete LB by around 30%.
Also:
* Makes sorting zones "stable". This is done by taking also zone name into account when count is the same. This should prevent moving single NEG between zones when sort determines different order. It also makes testing easier.
* Clean up unused "networkEndpointType" from TestClusterGetEndpointSet.
> Improve NEG performance provision/deletion for small NetLBs

- pkg/multiproject/gce/gce.go
- pkg/multiproject/gce/gce_test.go
Also, Support multiple lines with the same keys in gce.conf for MultiProject. For example, there could be multiple alpha-features
> Fix replacing TokenBody for quoted jsons for MultiProject

- cmd/glbc/main.go
- pkg/backends/backends.go
- pkg/backends/backends_test.go
- pkg/context/context.go
- pkg/flags/flags.go
- pkg/l4lb/l4controller.go
- pkg/loadbalancers/l4.go
- pkg/loadbalancers/l4_test.go
This PR implements zonal affinity capabilities for L4 Internal Load Balancers, allowing traffic to stay within zones when possible for improved performance and reduced cross-zone data transfer costs.
- Add zonal affinity flag for L4 ILB controllers
- Implement backendService zonal affinity control logic
- Add backendService minimum API version control for zonal features
- Update backendService tests to include zonal affinity cases with expected NetworkPassThroughLbTrafficPolicy
- Add handler for service spec Spec.TrafficDistribution change events
- Add L4 TestZonalAffinity integration tests
Users can enable zonal affinity by configuring their service with `Spec.TrafficDistribution=PreferClose`.
- Added unit tests for backendService with zonal affinity configurations
- Added L4 …
> Add zonal affinity support

- pkg/l4lb/l4controller.go
- pkg/l4lb/metrics/metrics.go
- pkg/loadbalancers/l4.go
- pkg/loadbalancers/l4netlb.go
- pkg/metrics/l4_metrics.go
- pkg/metrics/l4_metrics_test.go
- pkg/metrics/types.go
This PR adds support for tracking zonal affinity usage in L4 load balancer metrics. The zonal affinity feature allows users to configure traffic distribution policies for L4 ILB by setting `spec.trafficDistribution` to `PreferClose` which creates load balancers that prefer routing traffic to backends in the same zone.
- Added `zonal_affinity` label to both L4 metrics
- Updated metric initialization to capture zonal affinity status
- Added zonal affinity verification to metric test functions
- Updated unit tests to verify proper reporting of zonal affinity metrics
> Add zonal affinity to L4 load balancer metrics

- pkg/l4lb/metrics/metrics.go
Zonal affinity label was wrongly including "L4_ILB" which is not needed since it is already included in the metric name
> Renaming ILB Metric label Zonal Affinity

- .gitignore
This ignores any binary produced by the delve debugger.
When running the controller using VSCode debugger, the debugger creates a temporary binary in cmd/glbc:
This change ignores the binary.
> Add __debug_bin* to .gitignore

- pkg/multiproject/gce/gce.go
- pkg/multiproject/gce/gce_test.go
Also, Support multiple lines with the same keys in gce.conf for MultiProject. For example, there could be multiple alpha-features
> [Cherry-pick #2836 to release-1.34] Fix replacing TokenBody for quoted jsons for MultiProject

- go.mod
- go.sum
- vendor/golang.org/x/net/http2/frame.go
- vendor/golang.org/x/net/http2/server.go
- vendor/modules.txt
https://github.com/advisories/GHSA-vvgc-356p-c3xw
> Update golang.org/x/net dependency to v0.38.0 to fix a CVE.

- pkg/neg/syncers/transaction.go
- pkg/neg/syncers/transaction_test.go
When multi-subnet-cluster feature flag is enabled, ensure that the endpoints under multi-networking are correctly attached to the right NEG name. NEGs in Multi-network still use the default NEG name (unlike the name for the additional subnets in MSC)
> fix: Corrently handle endpoint attachment overlap between MSC and MN

- pkg/neg/controller.go
- pkg/neg/readiness/poller_test.go
- pkg/neg/readiness/reflector.go
- pkg/neg/readiness/reflector_test.go
- pkg/neg/readiness/utils_test.go
Previously, when we didn't create NEGs for the additinoal subnets, we had the logic in place to make sure that the pods which exist in nodes from the additional subnet are always marked ready for the NEG readiness gate. This was done since the pod will never get added to a NEG and hence won't have it's readiness gate ready in a natural way.
But now that we DO have NEGs in additional subnets, we no longer need this explicit handling.
> fix: NEG Readiness gate for MSC is no longer prematurely marked ready

- pkg/l4lb/l4controller.go
- pkg/l4lb/l4lbcommon.go
- pkg/l4lb/l4netlbcontroller.go
- pkg/loadbalancers/l4_test.go
- pkg/loadbalancers/l4netlb.go
- pkg/loadbalancers/l4netlb_test.go
- pkg/loadbalancers/user_error.go
- pkg/loadbalancers/user_error_test.go
- pkg/utils/sourceranges.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
Since utils package is dependend upon practicaly everywhere, it causes import cycles when trying to add additional `error.As` there. Since I don't want to grow this black hole pkg this commit moves IsUserError to pkg/loadbalancers as we actually use it there.
Also adds tests which were missing for that method.
> Check for FirewallXPNError in IsUserError

- pkg/utils/namer/l4_namer.go
- pkg/utils/namer/l4_namer_test.go
New naming convention suffixes "-{num}" to the end of Forwarding Rule name or "-{num}-ipv6" for IPv6 ones. We use base36 to limit the space used up by num.
Also refactors some of the existing TestL4Namer to simplify repetetive code. Personally I'm not a huge fan of having to check each field's length, as the `want`ed result tests that as well, but for sanity check we can leave it there.
> Add new namer funcs for Forwarding Rule sets

- cmd/glbc/main.go
- pkg/multiproject/neg/neg.go
- pkg/neg/controller.go
- pkg/neg/controller_test.go
- pkg/neg/manager.go
#cleanup Clean up Neg controller code
Removed unnecessary checks in the code for checking whether svcNegClient is null or not. It is initialized properly in the main function at ingress-gce/blob/master/cmd/glbc/main.go#L176, if initialization fails it causes the program to exit.
It is safe to assume in the other parts of code that it is fully initialized and value is not null.
> Clean up Neg controller code

- pkg/neg/controller.go
- pkg/neg/controller_test.go
When deciding if a NetLB requires NEGs rely on the presence of the V3 finalizer and not of the RBS annotation.
Sometimes customers create an RBS service but then remove annotations and/or finalizers. In that case the L4 NetLB can detect it is an RBS service and restore the V3 finalizer. The NEG controller always expected the RBS annotation, so it could result in missing NEGs.
> [Cherrypick #2882 to release-1.35] NEGController: rely on the presence of the V3 finalizer vs the RBS annotation

- pkg/l4lb/l4netlbcontroller.go
- pkg/l4lb/l4netlbcontroller_test.go
When determining which backend to use for a NetLB service in addition to the finalizers also check the actual backend service backends.
This is to work around the situations where the customers remove finalizers and can cause an unexpected move to NEG backends.
> NetLB: workaround for the finalizer removal case

- pkg/backends/backends.go
- pkg/composite/gen.go
- pkg/composite/gen/main.go
- pkg/loadbalancers/certificates.go
- pkg/loadbalancers/l7s.go
- pkg/loadbalancers/loadbalancers_test.go
- pkg/neg/types/cloudprovideradapter.go
This updates the code generator to include the filter argument. We also run codegen and fill in a new missing argument with filter.None.
> Add filter argument in composite List generator

- pkg/address/hold_test.go
- pkg/address/to_use_test.go
- pkg/backends/backends_test.go
- pkg/forwardingrules/netlb_mixed_manager_test.go
- pkg/loadbalancers/l4_mixed_test.go
- pkg/loadbalancers/l4_test.go
- pkg/loadbalancers/l4netlb_mixed_test.go
I've found my tests from the past that don't capture testcases, potentially leading to some unexpected results. This fixes all of the t.Parallel table driven tests that didn't capture test case.
> Fix test using t.Parallel() not capturing test cases

- pkg/neg/syncers/endpoints_calculator.go
- pkg/neg/syncers/endpoints_calculator_test.go
- pkg/neg/syncers/utils_test.go
NEG Controller, when generating desired endpoints in the endpoints calculator for Multi Networking service, use the MN network as as the NEG subnet instead of the subnet of the node.
This is to make sure the location from the calculator matches the 'current' state calculated before and also so that the location actually matches the actual subnet the NEG will reside in.
Without this change the NEG controller calculation will be different for current state and for desired, so the controller will think it has to detach and attach endpoints. This will result in the controller issuing constant detach calls, exhausting the quota in the project for the NEG API.
> NEG Controller: fix the multinet NEG location to prevent constant NEG detach calls

- pkg/neg/controller.go
- pkg/neg/readiness/poller_test.go
- pkg/neg/readiness/reflector.go
- pkg/neg/readiness/reflector_test.go
- pkg/neg/readiness/utils_test.go
- pkg/utils/zonegetter/zone_getter.go
- pkg/utils/zonegetter/zone_getter_test.go
This includes a revert (first commit) of changes made in https://github.com/kubernetes/ingress-gce/pull/2860 that involved removing special handling for NEG readiness gates for non-default subnet pods. (The first commit is a pure-revert)
The new fix being made is that only when MSC Phase 1 is enabled will we disable special handling for non-default subnets. This is done because when MSC Phase 1 is enabled, we will create NEGs in non-default subnet and no longer need special handling for the non-default-subnet-pods
In summary, this change introduces the following logic in `pkg/neg/controller.go` file:
```
markNonDefaultSubnetPodsReady = flags.F.EnableMultiSubnetCluster && !flags.F.EnableMultiSubnetClusterPhase1
```
where
- `flags.F.EnableMultiSubnetCluster ` = MSC Phase 0
- …
> Properly handle NEG readiness gate when transitioning between MSC Phase 0 and Phase 1

- pkg/neg/controller.go
- pkg/neg/readiness/poller_test.go
- pkg/neg/readiness/reflector.go
- pkg/neg/readiness/reflector_test.go
- pkg/neg/readiness/utils_test.go
- pkg/utils/zonegetter/zone_getter.go
- pkg/utils/zonegetter/zone_getter_test.go
Cherry-pick of https://github.com/kubernetes/ingress-gce/pull/2906
> Cherry-pick #2906 -> 1.36: Properly handle NEG readiness gate when transitioning between MSC Phase 0 and Phase 1

- cmd/e2e-test/logging_test.go
Problem was, we had `err := verifyLogging` but should be `err = verifyLogging`
/assign @swetharepakula @gauravkghildiyal
> Fix shadowing error in tests

- pkg/firewalls/firewalls_l7_cr.go
- pkg/firewalls/firewalls_test.go
While testing gcpfirewalls cr creation inside ingress-gce we encountered an issue when Allow - TPC:all rule is requested.
The former implementation would create a cr with Allow:all instead, which is a violation of the specification:
https://cloud.google.com/kubernetes-engine/docs/concepts/firewall-rules#ingress-fws
> Fix firewall cr creation

- pkg/neg/syncers/endpoints_calculator.go
- pkg/neg/syncers/endpoints_calculator_test.go
- pkg/neg/syncers/utils_test.go
NEG Controller, when generating desired endpoints in the endpoints calculator for Multi Networking service, use the MN network as as the NEG subnet instead of the subnet of the node.
This is to make sure the location from the calculator matches the 'current' state calculated before and also so that the location actually matches the actual subnet the NEG will reside in.
Without this change the NEG controller calculation will be different for current state and for desired, so the controller will think it has to detach and attach endpoints. This will result in the controller issuing constant detach calls, exhausting the quota in the project for the NEG API.
> [Cherrypick #2903 -> release-1.34] NEG Controller: fix the multinet NEG location to prevent constant NEG detach calls

- pkg/backends/backends.go
- pkg/backends/backends_test.go
- pkg/loadbalancers/l4.go
- pkg/loadbalancers/l4netlb.go
Unset the Locality LB Policy of the backend service when an internal LoadBalancer service disables Weighted Load Balancing. Now it is possible to move from `WEIGHTEDMAGLEV` to unset ` ` instead of using `MAGLEV`.
> Disable Weighted Load Balancing by unsetting localityLBPolicy field

- cmd/glbc/main.go
- pkg/context/context.go
- pkg/l4lb/l4controller.go
- pkg/l4lb/l4controller_test.go
- pkg/l4lb/l4netlbcontroller.go
- pkg/l4lb/l4netlbcontroller_test.go
- pkg/l4lb/metrics/collector.go
- pkg/l4lb/metrics/dualstack_metrics.go
- pkg/l4lb/metrics/dualstack_metrics_test.go
- pkg/l4lb/metrics/features.go
- pkg/l4lb/metrics/ipv4_metrics.go
- pkg/l4lb/metrics/ipv4_metrics_test.go
- pkg/l4lb/metrics/legacy_metrics.go
- pkg/l4lb/metrics/legacy_metrics_test.go
- pkg/l4lb/metrics/metrics.go
- pkg/l4lb/metrics/types.go
- pkg/loadbalancers/l4.go
- pkg/loadbalancers/l4netlb.go
- pkg/loadbalancers/l4netlb_test.go
- pkg/metrics/features.go
- pkg/metrics/metrics.go
- pkg/metrics/types.go
This commit moves all of the L4 releated metrics to another package. It also creates a separate Collector to export those metrics and adds missing comments.
<details>
<summary>Logs from LB after the change</summary>
```log
I0415 12:20:36.369684  433963 ipv4_metrics.go:146] "Exporting L4 ILB usage metrics for services" logger="ControllerContext.L4MetricsCollector" serviceCount=0
I0415 12:20:36.369781  433963 ipv4_metrics.go:156] "L4 ILB usage metrics exported" logger="ControllerContext.L4MetricsCollector"
I0415 12:20:36.369806  433963 ipv4_metrics.go:162] "Exporting L4 NetLB usage metrics for services" logger="ControllerContext.L4MetricsCollector" serviceCount=1
I0415 12:20:36.369848  433963 metrics.go:244] "Exporting ingress usage metrics" logger="ControllerContext.ControllerMetrics" …
```
> Separate L4 specific metrics from `pkg/metrics` to `pkg/l4lb/metrics`

- pkg/utils/zonegetter/zone_getter.go
Changed logger.Info calls to use appropriate verbosity levels (V(2), V(3), V(4)) to prevent excessive logging that can overflow disk space in large clusters with thousands of services and nodes.
- V(4): Debug-level logs for frequently called operations (per service/node)
- V(3): Verbose logs for filtered node summaries
- V(2): Info-level logs for listing operations and error conditions
This prevents disk space issues while maintaining debug capability with --v flags.
/assign @gauravkghildiyal @mmamczur
> [Cherry-pick #2938 to 1.36] Reduce zone_getter log spam by adjusting log levels

- pkg/utils/zonegetter/zone_getter.go
Adjusted log levels in zone_getter.go to prevent excessive logging that overflows disk space in large clusters with thousands of services/nodes.
Changed frequently called logger.Info to V(2)/V(3)/V(4) based on call frequency.
> Reduce zone_getter log spam by adjusting log levels

- pkg/l4lb/metrics/ipv4_metrics.go
- pkg/l4lb/metrics/ipv4_metrics_test.go
- pkg/l4lb/metrics/types.go
We want to monitor the mixed protocol services separately, as they differ a bit in implementation. The new label has 4 potential values: "TCP", "UDP", "MIXED" or "" (empty).
Results from cluster that runs an external tcp, external mixed and internal mixed:
```
...
l4_ilbs_count{multinet="false",protocol="MIXED",status="Success",weighted_lb_pods_per_node="false",zonal_affinity="false"} 1
...
l4_netlbs_count{backend_type="NEG",multinet="false",protocol="MIXED",status="Success",strong_session_affinity="false",weighted_lb_pods_per_node="false"} 1
l4_netlbs_count{backend_type="NEG",multinet="false",protocol="TCP",status="Success",strong_session_affinity="false",weighted_lb_pods_per_node="false"} 1
...
```
SYNC time metrics will be in a separate PR.
> Add Protocol Label to existing COUNT metrics

- pkg/flags/flags.go
When set to true, this flag will configure the L4 ILB and NetLB controllers to operate in a strict IPv6-only mode. This involves disabling all IPv4-related logic and resource management.
> Add --enable-l4-ipv6-only-mode flag

- pkg/flags/flags.go
- pkg/l4lb/l4controller.go
- pkg/l4lb/l4controller_test.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
Introduces a wait and re-fetch mechanism when a service has no L4 ILB finalizers (v1 or v2) through a flag `L4ILBLegacyHeadStartTime`. This prevents race conditions between controllers during initial service creation, ensuring the L4 controller processes the most recent service state and avoids conflicting operations. This to prevent race during cluster update when enabling GKE subsetting.
This will only be applied to regional clusters since zonal clusters don't have the issue.
> Prevent L4 ILB controller race conditions on service creation

- pkg/crd/validation.go
- pkg/crd/validation_test.go
New codegen CRDs include metadata, these must be removed to pass 
validation. See Kubernetes commit d74a9a9da658e1cb9ae23ae0622089fe09d65564.
This fixes the reverted PR: https://github.com/kubernetes/ingress-gce/pull/2957
> Remove .metadata from CRD

- pkg/backends/backends.go
- pkg/backends/backends_test.go
- pkg/loadbalancers/l4.go
- pkg/loadbalancers/l4_test.go
- pkg/loadbalancers/l4netlb_test.go
This change introduces WEIGHTED_GCP_RENDEZVOUS as the locality LB policy for weighted ILB services. It also adds awareness for the upcoming RENDEZVOUS default policy to prevent unnecessary backend service recreation during reconciliation.
The controller now correctly differentiates between NetLB (Maglev) and ILB (Rendezvous) policies, ensuring stability and proper configuration for weighted load balancing. This aligns the controller with backend infrastructure updates for internal load balancers.
> Add Rendezvous hashing for ILB weighted load balancing

- cmd/glbc/main.go
- pkg/multiproject/start/start.go
- Scope: changes are confined to the multiproject leader-election flow.
- Controllers & informers now inherit the leader-election context, exiting immediately when the lease is lost or on SIGTERM.
- ReleaseOnCancel=true enables instant lease hand-off for smoother rollouts.
> Multiproject: stop controllers when leadership ends

- cmd/glbc/main.go
- pkg/flags/flags.go
Acquiring the L4 lock will no longer happen 'inside' the Ingress lock. With this change the controllers can be run as separate containers/pods.
> [Cherrypick #2970 to release-1.37] Move to independent locks for L4 and Ingress controllers.

- pkg/multiproject/start/start_test.go
- pkg/multiproject/testutil/providerconfigwebhook.go
Previously, the reactor manually called tracker.Add and returned handled=true, short-circuiting the chain and sometimes causing double-add/AlreadyExists. Now we only label the object and return handled=false so the default ObjectReaction persists it, reducing flakes.
Also initialize the labels map and remove the unused FakeTracker parameter.
> Let ReactionChain continue in EmulateProviderConfigLabelingWebhook

- pkg/context/context.go
- pkg/utils/zonegetter/README.md
- pkg/utils/zonegetter/zone_getter.go
- pkg/utils/zonegetter/zone_getter_test.go
Legacy networks do not have the concept of subnets and naturally are not compatible with the multi subnet feature. Therefore zonegetter must be able to handle legacy networks and not error out. Legacy mode zonegetter still validates that the Nodes have the pod cidr and the provider ID set before using it for any calculation
Legacy Network Assumptions:
* All Nodes are considered part of the default network
* The subnetwork is always empty
Adds a readme on what the zonegetter does at a high level
> Implement a legacy mode for the zonegetter

- cmd/glbc/main.go
- pkg/context/context.go
- pkg/controller/controller_test.go
* BackendConfig and FrontendConfig are only used by Ingress and do not need to be ensured by other controllers.
> Ensure Ingress CRDS only when Ingress ctrl is enabled

- pkg/flags/flags.go
- pkg/l4lb/l4controller.go
- pkg/loadbalancers/l4.go
- pkg/loadbalancers/l4_test.go
- pkg/loadbalancers/l4netlb.go
- pkg/loadbalancers/l4netlb_test.go
- pkg/neg/syncers/subsets.go
- pkg/neg/syncers/subsets_test.go
- pkg/neg/syncers/utils.go
- pkg/neg/syncers/utils_test.go
- pkg/utils/utils.go
This change adds support to the controller to provision L4 LoadBalancers configured as IPv6-only.
> Enable IPv6-only L4 LoadBalancer 
