instances/instances.go, instances/instances_test.go
Found an issue regarding the recent change to setting named ports. The wrong list was used when being appended to the instance group's existing list of ports. If you run the added test case, the unit test shows that ports get duplicated.
=> Fix issue when setting instance group named ports

backends/backends.go, controller/cluster_manager.go, controller/utils_test.go, instances/instances.go, instances/instances_test.go, instances/interfaces.go, instances/utils.go
Changes
- Fixed log line which was previously printing a slice of memory addresses instead of port numbers.
https://github.com/kubernetes/ingress-gce/blob/ef0e824a0250c97298b65b87fbf573898d456642/instances/instances.go#L119
- Renamed "AddInstanceGroup" to "EnsureInstanceGroupsAndPorts" to actually reflect the actions of the func
- Split "EnsureInstanceGroups" and created "EnsureInstanceGroupAndPorts" for the actions on a single instance group.
- Removed unused return variable of nodeports from "EnsureInstanceGroupsAndPorts"
=> Minor cleanup to instance group management

Makefile
We no longer should invoke 'godeps' after the recent shuffling of repos (ingress -> ingress-gce/ingress-nginx split) and Makefiles.
=> Fix the glbc build by removing 'godeps' from command.

Makefile, README.md, cmd/glbc/main.go, rc.yaml
Test Cases
- @nikhiljindal Found an issue with interop between service controller and MC but it's not a release blocker.
Test Clusters
Areas to check
- Named ports of instance groups
- Instances in instance groups
- URL Map matches ingress rules
- Backend health
- Firewall rule update
- GLBC Log for errors
Temporary image for testing
*nicksardo/glbc:0.9.7*
=> Release 0.9.7

pkg/backends/backends.go
This variable name looked wrong, so I'm fixing it.
=> Rename local var to reflect what it is.

pkg/backends/fakes.go, pkg/healthchecks/fakes.go
Updating `pkg/backends/fakes.go` to return 404 when object does not exist.
Verified that all other packages (`pkg/firewalls`, `pkg/healthchecks` and `pkg/instances`) return 404s in the same way.
Updated `pkg/healthchecks/fakes.go` to use the same util method as all other packages.
cc @nicksardo @bowei
=> Updating backends/fakes to return 404 in the same way as all other fakes

pkg/annotations/annotations.go, pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/controller/utils.go, pkg/controller/utils_test.go
Extracting out annotations related code from `pkg/controller/utils.go` into a separate `pkg/annotations` package. This will allow reusing annotation keys rather than duplicating them everywhere.
cc @bowei @nicksardo @csbell @G-Harmon
=> Extracting out annotations to a separate package to allow reuse

pkg/loadbalancers/fakes.go
Same as https://github.com/kubernetes/ingress-gce/pull/56.
Missed `pkg/loadbalancers/fakes.go` in that PR.
=> Updating loadbalancer/fakes.go to return 404

pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/tls/tls.go
TlsLoader is the interface used to load TLSCerts for an ingress.
cc @bowei @nicksardo @csbell @G-Harmon @madhusudancs
=> Extracting tlsloader into a separate package to enable reuse

pkg/controller/controller_test.go, pkg/loadbalancers/fakes.go, pkg/loadbalancers/loadbalancers_test.go
Removing loadbalancer package's dependency on testing.
Without this change, any binary that depends on loadbalancer package also starts exposing test flags.
cc @nicksardo @bowei
=> Removing non code test's dependency on testing package

pkg/backends/backends.go, pkg/backends/backends_test.go, pkg/controller/cluster_manager.go, pkg/controller/fakes.go, pkg/instances/instances.go, pkg/instances/instances_test.go, pkg/loadbalancers/loadbalancers_test.go, pkg/utils/namer.go, pkg/utils/namer_test.go, pkg/utils/utils.go, pkg/utils/utils_test.go
- Split off unit tests for namer into namer_test.go
=> Move GetNamedPort to Namer

cmd/glbc/main.go, pkg/backends/backends_test.go, pkg/controller/cluster_manager.go, pkg/controller/controller_test.go, pkg/controller/fakes.go, pkg/healthchecks/healthchecks_test.go, pkg/instances/fakes.go, pkg/instances/instances_test.go, pkg/loadbalancers/fakes.go, pkg/loadbalancers/loadbalancers.go, pkg/loadbalancers/loadbalancers_test.go, pkg/utils/namer.go, pkg/utils/namer_test.go
- This allows the multicluster code to share use of the Namer.
- Add more unit testing
- Coverage is now ~90% of namer code.
=> Add ability to change prefix in the Namer

pkg/loadbalancers/fakes.go, pkg/loadbalancers/interfaces.go
I have an upcoming commit in the k8s-multicluster-ingress repo where I will use this.
cc @bowei @nicksardo @nikhiljindal
=> Add ListGlobalForwardingRules to the LoadBalancers interface.

examples/websocket/README.md, examples/websocket/deployment.yaml, examples/websocket/server.go
Changes:
- Fixes occasional panics due to concurrent writing
- Adds html page for connecting to the websocket
- Adds copyright header
Fixes #77
=> Update websocket example

examples/tls-termination/gce/README.md
The example ingress name is `test` and not `gce-test`.
Also need to run the `curl` command without `-k` to get the SSL self signed cert error.
=> Fixing typos in gce-tls example readme

examples/websocket/server.go
Fixes:
- Slashes in URL were being escaped when hydrating template.
- Use correct func for printing error message.
=> Minor fixes to example JS

Makefile
Adds a new rule to the Makefile which pushes an image of glbc for e2e testing. This target basically does the same thing as a regular build and push but we need it for two reasons:
1. Modify the CONTAINER_PREFIX so that it is clear that image is for e2e testing.
2. In test-infra/kubetest, we need to build an image of glbc for testing and having a target called e2e so that we kubetest can just say "make e2e" makes it clearer what we are doing.
=> Add e2e make rule

cmd/glbc/app/clients.go, cmd/glbc/app/flags.go, cmd/glbc/app/handlers.go, cmd/glbc/main.go, pkg/utils/namer.go
- Includes some minor logging cleanups
=> Deprecate --use-real-cloud and --verbose flags

README.md
As what we had for [kubernetes/dns](https://github.com/kubernetes/dns). The coverage result should be available at the next build.
=> Add build, coverage and report badges

Makefile
Fixes push-e2e make rule to push the containers to a registry it is allowed to push to. 
Specifically, kubetest does not have permissions to push to google_containers.
=> Fix push-e2e make rule

Makefile
Using latest as the tag for our e2e testing image will allow the e2e jobs in Prow to simply pull using the tag "latest".  This is not ideal but it fixes our jobs for now.
=> Modify VERSION to use "latest" in push-e2e target

Makefile
We now pass these vars through inside of the e2e job config so they are no longer needed in the Makefile.
/assign @bowei
=> Remove some vars from make push-e2e target

pkg/loadbalancers/loadbalancers_test.go
There was a bug when transitioning from a pre-shared certificate to a secret-based certificate. The controller deletes the pre-shared certificate when it really should ignore it (quote https://github.com/kubernetes/ingress-nginx/pull/639). This PR adds an unit test for that.
Ref https://docs.google.com/document/d/1E2ufxZGujFCYKYOsvBjb4VMNjBy8CM-MMycoT_UVwIs/edit#heading=h.djafujeypqcp.
/assign @nicksardo @rramkumar1
=> Add unit test to verify pre-shared cert retention

cmd/glbc/main.go, pkg/backends/backends_test.go, pkg/context/context.go, pkg/controller/cluster_manager.go, pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/controller/fakes.go, pkg/controller/node.go, pkg/controller/translator/translator.go, pkg/controller/translator/translator_test.go, pkg/controller/utils.go, pkg/controller/utils_test.go, pkg/firewalls/firewalls.go, pkg/loadbalancers/l7.go, pkg/loadbalancers/l7s.go, pkg/loadbalancers/loadbalancers_test.go, pkg/neg/controller.go, pkg/neg/controller_test.go, pkg/neg/fakes.go, pkg/neg/interfaces.go, pkg/neg/manager.go, pkg/neg/manager_test.go, pkg/neg/syncer.go, pkg/neg/syncer_test.go
A bunch of patches:
* A lot of clean up and movement
* Sync one ingress (as opposed to all) in Checkpoint
* Call GC explicitly when an Ingress is deleted
* Shutdown() firewall when there are no more Ingresses
=> Sync one ingress

cmd/glbc/main.go
We will remove this when a release can be cut to support logging to
stderr.
=> Always set -logtostderr (this matches the original behavior)

pkg/controller/controller.go, pkg/controller/translator/translator.go
- Backend service pool only syncs the list of service ports used for the respective ingress.
- Consolidate all ingress references to a single object which was deep copied.
- Changing log level of a frequently printed line from 4->5.
- Minor modifications to event handlers
Before
```
I0205 23:03:18.031082       1 backends.go:216] Sync: backends [{30466 HTTP testing/my-echo-svc {1 0 my-http-port}} {32349 HTTP default/my-echo-svc {1 0 my-http-port}}]
```
After
```
I0205 22:59:43.566574       1 backends.go:224] Sync: backends [{32349 HTTP default/my-echo-svc {1 0 my-http-port} 80 false}]
I0205 22:59:45.215794       1 backends.go:224] Sync: backends [{30466 HTTP testing/my-echo-svc {1 0 my-http-port} 80 false}]
```
=> Sync ingress-specific backends and minor logging changes

cmd/glbc/app/init.go, pkg/backends/backends.go, pkg/backends/backends_test.go, pkg/controller/cluster_manager.go, pkg/controller/fakes.go, pkg/controller/translator/translator.go, pkg/controller/translator/translator_test.go, pkg/controller/utils.go, pkg/loadbalancers/l7s.go, pkg/loadbalancers/loadbalancers_test.go
In order to prevent confusion with the `SvcPort` and `SvcTargetPort`, I suggest we be more specific by renaming `Port` to `NodePort`
=> Rename Port to NodePort

pkg/controller/controller.go
From https://github.com/kubernetes/kubernetes/pull/58643, found that no event is emitted when glbc fails to retrieve TLS cert. It might be helpful to make this visible to users.
=> Emit event on TLS errors

pkg/controller/controller.go
Periodic resync behavior was inadvertently removed in previous PR: https://github.com/kubernetes/ingress-gce/pull/123/files#diff-3c862eb54a8e0e161b534e0c67e5379eL143
=> Periodic resync

cmd/glbc/app/handlers.go
This endpoint currently prints the version and current verbosity level. You can also change the verbosity during runtime with a simple PATCH.  
```
curl -X PATCH http://localhost:8080/flag?v=10
```
More information can be added later.
=> Introduce flag endpoint

pkg/controller/controller.go
Follow up of https://github.com/kubernetes/ingress-gce/pull/112. Emit error event separately for now.
=> Emit event on RuntimeInfo error

cmd/glbc/main.go
V=3 for 0.9.8 is more or less equivalent to v=4 for 0.9.7. This change will allow us to change the glbc.manifest to use `--verbose` and be backwards compatible with the 0.9.7 image.
cc @rramkumar1
=> Verbose flag: set v=3

README.md
Updating the documentation so that it clearly states the 2 options that users have to store their certs: as k8s secrets or as GCP SSL certs.
cc @csbell @G-Harmon @nicksardo @bowei
=> Adding information about using GCP SSL certs for frontend HTTPS

README.md, deploy/glbc/README.md, deploy/glbc/gce.conf, deploy/glbc/script.sh, deploy/glbc/yaml/default-http-backend.yaml, deploy/glbc/yaml/glbc.yaml, deploy/glbc/yaml/rbac.yaml, docs/README.md
=> Add instructions and a tool for people who want to try out a new version of the ingress controller before it is released.

cmd/glbc/app/clients.go, pkg/flags/flags.go, pkg/ratelimit/ratelimit.go, pkg/ratelimit/ratelimit_test.go, vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/gce/gce.go
This PR adds support for rate limiting certain GCE API call's that are made by the controller. Currently, the cloud provider layer does not rate limit any standard controller calls (such as BackendService Get). As a result, in some cases when API calls are frequent, we are blowing through project quota and getting rate limited on the GCE side. This could also cause the controller to slow down. By allowing for customization of what calls can be rate limited, we can prevent blowing through project quota and we can intelligently rate limit so that we do not experience slowdown.  
Will add unit tests once the overall approach is LGTM'd.
/assign @nicksardo @bowei
=> Initial implementation for ingress rate limiting

docs/README.md
=> Fix formatting error in docs/README.md

pkg/loadbalancers/fakes.go
This is what we do for all other resources like forwarding rule, target proxies, etc.
UrlMap is the only resource for which we use namer again.
Fixing this inconsistency.
Found while writing a test for https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/issues/145 for kubemci. We pass a nil namer while instantiating FakeLoadBalancers in our tests.
cc @bowei @nicksardo @G-Harmon
=> Use given name rather than regenerating it in UrlMap fake

pkg/loadbalancers/fakes.go
Ref https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/issues/155
Fakes should return NotFound as the real code does.
This will help us catch issues like https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/issues/155 in our unit tests.
cc @G-Harmon @nicksardo @bowei @MrHohn
=> Updating FakeLoadBalancers.Delete to return NotFound when appropriate

deploy/glbc/script.sh
I get the following error:
```
sed: can't read default-http-backend.yaml: No such file or directory
```
Thanks.
=> Fix path default-http-backend.yaml

pkg/controller/cluster_manager.go, pkg/controller/controller.go, pkg/firewalls/firewalls.go, pkg/firewalls/firewalls_test.go
Fixes #182
Also fixes an pre-existing issue of keeping around backend services if MCI and normal ingresses shared backend services. If the normal ingress was deleted, the backend service wouldn't be GC'd until MCI was deleted.
The logic for syncing MCI vs GCE-ingress was not easily distinguishable. I've re-ordered the sync logic and broke down `Checkpoint` into something I think is more clear. 
Checkpoint is broken up into three separate funcs and are called in the following order:
1. `EnsureInstanceGroupsAndPorts()`
- MCI updates annotations and early returns.
2. `EnsureLoadBalancer()`
3. `EnsureFirewall()`
cc @nikhiljindal @csbell @bowei  @MrHohn  @rramkumar1
=> Fix sync of multi-cluster ingress

pkg/annotations/service.go, pkg/annotations/service_test.go, pkg/backends/backends.go, pkg/backends/backends_test.go, pkg/backends/fakes.go, pkg/backends/interfaces.go, pkg/controller/cluster_manager.go, pkg/controller/controller_test.go, pkg/controller/fakes.go, pkg/healthchecks/healthchecks.go, pkg/healthchecks/healthchecks_test.go, pkg/instances/fakes.go, pkg/loadbalancers/l7s.go, pkg/loadbalancers/loadbalancers_test.go
- Adds HTTP2 annotation to Service
- Creates alpha HealthCheck and BackendService resources when the protocol is HTTP/2, by using a composite BackendService type
- Tests for HealthCheck/BackendServices using HTTP/2
=> Ingress HTTP/2 Support

docs/dev/post-release-steps.md
This is mainly for keeping track of things we need to do when a new release is cut. 
/assign @nikhiljindal
=> Add some documentation on post-release TODO's

build/rules.mk
Patch from https://github.com/kubernetes/contrib/pull/2877. Local test (`make test`) is failing without this:
```
Checking go vet: FAIL                                                                         
go: disabling cache (/.cache/go-build) due to initialization failure: mkdir /.cache: permission denied
```
=> Ensure .go/cache in build

pkg/controller/controller.go, pkg/controller/translator/translator.go
I might be missing something, but it seems `ensureInstanceGroupAndPorts()` is already doing what we need --- ensuring given ports are included in instance group, so the change is tiny?
@rramkumar1 @nicksardo
=> Ensure only needed nodeports on instance group on ingress sync

pkg/loadbalancers/l7.go, pkg/loadbalancers/l7s.go, pkg/loadbalancers/loadbalancers_test.go, pkg/utils/namer.go, pkg/utils/namer_test.go
Changes
- Rename SSL certs from `k8s-ssl-{nameHash}--{clusterId}-{secretHash}` to `k8s-ssl-{nameHash}-{secretHash}--{clusterId}` to be consistent with other resources.
- Get rid of `sslCertPrefix` for simplification.
=> Change naming of SSL certs

cmd/glbc/app/namer.go, pkg/controller/cluster_manager.go, pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/controller/translator/translator.go, pkg/controller/translator/translator_test.go, pkg/loadbalancers/l7.go, pkg/loadbalancers/loadbalancers_test.go, pkg/utils/gceurlmap.go, pkg/utils/utils.go, pkg/utils/utils_test.go
/assign @nicksardo @MrHohn 
Will update tests once approach is LGTM'd.
=> Refactor translator.ToURLMap to not re-fetch backend services

pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/utils/taskqueue.go
Splitting up sync so we no longer have the defer statement.
Fixing controller tests so we know when the sync func fails.
=> Split sync up 

pkg/loadbalancers/l7.go, pkg/loadbalancers/loadbalancers_test.go
Sometimes we hit timeouts in the e2e test: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-ingress-gce-e2e/1719
The controller is leaking an SSL Certificate and the test cleanup gives the controller a lot of time to clean it... Though, it never does.
```log
...
I0412 10:38:57.917] Apr 12 10:38:57.917: INFO: No backend services found
I0412 10:38:59.195] Apr 12 10:38:59.194: INFO: Monitoring glbc's cleanup of gce resources:
I0412 10:38:59.195] k8s-ssl-350024a07559f009-83697e1b6f4cfc12--b4d5aa05f1df8c87 (ssl-certificate)
I0412 10:38:59.195] 
I0412 10:39:07.635] Apr 12 10:39:07.634: INFO: No backend services found
I0412 10:39:08.924] Apr 12 10:39:08.924: INFO: Monitoring glbc's cleanup of gce resources:
I0412 10:39:08.925] …
```
=> Fix multiple secrets with same certificate

Gopkg.lock, Gopkg.toml, pkg/backends/utils.go, pkg/backends/utils_test.go, pkg/controller/utils.go, pkg/mapper/fakes.go, pkg/mapper/interfaces.go, pkg/mapper/mapper.go, pkg/mapper/mapper_test.go, vendor/github.com/hashicorp/errwrap/LICENSE, vendor/github.com/hashicorp/errwrap/README.md, vendor/github.com/hashicorp/errwrap/errwrap.go, vendor/github.com/hashicorp/go-multierror/.travis.yml, vendor/github.com/hashicorp/go-multierror/LICENSE, vendor/github.com/hashicorp/go-multierror/Makefile, vendor/github.com/hashicorp/go-multierror/README.md, vendor/github.com/hashicorp/go-multierror/append.go, vendor/github.com/hashicorp/go-multierror/flatten.go, vendor/github.com/hashicorp/go-multierror/format.go, vendor/github.com/hashicorp/go-multierror/multierror.go, vendor/github.com/hashicorp/go-multierror/prefix.go
A followup PR will modify the controller to use this code rather than the code in pkg/translator.
=> Code to setup removal of ServicePort logic out of translator 

pkg/loadbalancers/l7.go, pkg/loadbalancers/loadbalancers_test.go
Cherrypick fix https://github.com/kubernetes/ingress-gce/pull/213 for release 1.1
=> Cherrypick: Fix multiple secrets with same certificate

Makefile, build/build.sh, build/rules.mk, cmd/glbc/main.go, pkg/version/version.go
This will make it easier for us during debugging e2e test failures. Specifically, we now do not need to cross-reference with the latest e2e image push job run to find out the commit used in the test.
=> Add support for logging latest commit hash of GLBC build being used

cmd/glbc/main.go, pkg/context/context.go, pkg/controller/controller.go, pkg/mci/controller.go
Tested this locally and it worked. Stood up a cluster registry with a couple cluster inside of it and then deleted one of the clusters. Logs showed that all ingresses in the cluster registry host were enqueued.
=> Add ability for MCI controller to enqueue ingresses

pkg/mapper/fakes.go, pkg/mapper/interfaces.go, pkg/mapper/mapper.go, pkg/utils/utils.go
This PR adds a new method to the interface. Specifically, now the list of expected services can be overwritten with a call to SetExpectedServices. 
=> Small addition to ClusterServiceMapper interface

pkg/informer/informer.go, pkg/informer/interfaces.go
This interface will allow for easy management of service and ingress informers for target clusters.
=> First pass at an interface to manage informers

pkg/context/context.go, pkg/mci/controller.go
This PR does a lot of things:
1. Add a helper for creating a kubernetes client given a Cluster spec. This code is really hacky but it will  suffice for now. 
2. Add a helper for doing some work when the "add" and "delete" event handlers fire for a cluster. Specifically, this creates the client, informer managers, and service mappers for each cluster. 
Note: I will probably add testing for all of this code in a separate PR.
=> Add code for building cluster client and other resources.

pkg/target/interfaces.go, pkg/target/target.go, pkg/target/utils.go, pkg/utils/utils.go
Next PR will hopefully tie everything together in the sync loop.
=> Add an interface to manage target resources

cmd/glbc/main.go, pkg/annotations/ingress.go, pkg/backends/backends.go, pkg/context/context.go, pkg/controller/cluster_manager.go, pkg/controller/controller.go, pkg/controller/translator/translator.go, pkg/controller/translator/translator_test.go, pkg/controller/utils.go, pkg/controller/utils_test.go, pkg/firewalls/firewalls.go, pkg/firewalls/firewalls_test.go, pkg/firewalls/interfaces.go, pkg/informer/informer.go, pkg/mci/controller.go, pkg/mci/utils.go, pkg/target/interfaces.go, pkg/target/target.go, pkg/target/utils.go, pkg/utils/utils.go, pkg/utils/utils_test.go
Final changes to make the MCI controller work end-to-end. 
A cleanup PR will follow this one to improve naming and add relevant tests.
=> Final changes to make MCI controller work 

pkg/annotations/service.go, pkg/annotations/service_test.go
=> Add util functions for backendConfig annotation

pkg/backends/fakes.go, pkg/controller/controller_test.go, pkg/controller/translator/translator.go, pkg/loadbalancers/fakes.go, pkg/loadbalancers/l7.go, pkg/loadbalancers/loadbalancers_test.go, pkg/utils/gceurlmap.go, pkg/utils/gceurlmap_test.go, pkg/utils/namer.go, pkg/utils/utils.go
Will fix tests once approach looks good.
=> Refactor gceurlmap to a struct representation

cmd/glbc/app/init.go, pkg/backends/backends.go, pkg/backends/backends_test.go, pkg/backends/fakes.go, pkg/backends/interfaces.go, pkg/controller/cluster_manager.go, pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/controller/fakes.go, pkg/controller/translator/translator.go, pkg/controller/translator/translator_test.go, pkg/controller/utils.go, pkg/loadbalancers/fakes.go, pkg/loadbalancers/l7.go, pkg/loadbalancers/l7s.go, pkg/loadbalancers/loadbalancers_test.go, pkg/utils/gceurlmap.go, pkg/utils/gceurlmap_test.go, pkg/utils/serviceport.go
This PR attempts to merge the logic of two function in the translator. Right now, ToUrlMap() and IngressToNodePorts() both iterate over an Ingress spec in very similar ways. In order to reduce complexity of having two similar code paths being executed at different times, we can merge these two functions together to ensure easier testing and maintainability. 
This also gives us the opportunity to store all config in one place (GCEURLMap). Now, this struct uses a ServicePort to denote a backend rather than the backend's name. (credit to @nicksardo  for this idea)
If this approach looks reasonable, I will add tests for it (there are no tests for any of this currently). 
This PR is a prerequisite for condensing backend pool's (#242).
=>  Merge the logic of ToUrlMap() and IngressToNodePorts() [WIP]

examples/health-checks/README.md
=> Update healthcheck docs regarding containerPort

pkg/backendconfig/backendconfig.go, pkg/backendconfig/backendconfig_test.go
/assign @rramkumar1 @nicksardo 
cc @bowei
=> Add utils for retrieving backendconfigs for service (and reversely)

pkg/controller/cluster_manager.go, pkg/controller/controller.go, pkg/controller/translator/translator.go, pkg/controller/translator/translator_test.go, pkg/loadbalancers/interfaces.go, pkg/loadbalancers/l7s.go, pkg/loadbalancers/loadbalancers_test.go, pkg/ratelimit/ratelimit_test.go
=> Small aesthetic fixes to code base.

pkg/backends/backends.go, pkg/backends/backends_test.go, pkg/backends/fakes.go, pkg/backends/interfaces.go, pkg/controller/cluster_manager.go, pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/healthchecks/healthchecks.go, pkg/healthchecks/healthchecks_test.go, pkg/healthchecks/interfaces.go, pkg/loadbalancers/fakes.go, pkg/loadbalancers/l7.go, pkg/loadbalancers/l7s.go, pkg/utils/namer.go, pkg/utils/namer_test.go, pkg/utils/serviceport.go
Continuation of https://github.com/kubernetes/ingress-gce/pull/239
More changes:
- Neg suffix hash uses the UID truncated to 8 chars.
- Neg suffix hash input fields are separated by a delimiter
- ServicePort now has an extension function to return the correct name. 
- `namer.Backend` is renamed to `namer.IGBackend` to prevent confusion between IG/NEG.
TODO in another PR:
Rewrite unit tests to not care what kind of serviceport their given.
=> BackendService naming for NEG backend services & healthchecks

cmd/glbc/main.go, pkg/backends/backends.go, pkg/backends/backends_test.go, pkg/controller/cluster_manager.go, pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/controller/fakes.go, pkg/flags/flags.go, pkg/healthchecks/healthchecks.go, pkg/healthchecks/healthchecks_test.go, pkg/healthchecks/interfaces.go
This PR should wait on #262
TODOs before merge:
1. Manually test case of ingress using system default backend w/ other backends and verify health checks.
2. Verify that users can still modify health check settings for all backends and that the controller will not reconcile. 
=> Condense health checkers into one health checker for all backends.

cmd/glbc/app/init.go, cmd/glbc/main.go, pkg/backends/backends.go, pkg/backends/backends_test.go, pkg/controller/cluster_manager.go, pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/controller/fakes.go, pkg/controller/translator/translator.go, pkg/controller/translator/translator_test.go, pkg/flags/flags.go, pkg/healthchecks/healthchecks.go, pkg/utils/serviceport.go, pkg/utils/utils.go, pkg/utils/utils_test.go
Changes:
- Users can now configure the default backend service **port** by flag - defaults to "http".
- Controller checks that the default backend service exists and has the specified port name.
- Now only the ServicePortID is passed to the LBC - the nodeport is no longer cached.
- TranslateIngress may now return an error. This will occur if the default backend service does not exist at sync-time.
=> Pass service/port tuple separate from ServicePort

pkg/annotations/service.go
Sorry I missed this in https://github.com/kubernetes/ingress-gce/pull/271.
=> Fix BackendConfigKey to use beta

pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/controller/errors/errors.go, pkg/controller/translator/testdata/ingress-missing-multi-svc.json, pkg/controller/translator/testdata/ingress-missing-multi-svc.yaml, pkg/controller/translator/testdata/ingress-missing-rule-svc.json, pkg/controller/translator/testdata/ingress-missing-rule-svc.yaml, pkg/controller/translator/testdata/ingress-multi-empty.json, pkg/controller/translator/testdata/ingress-multi-empty.yaml, pkg/controller/translator/testdata/ingress-multi-paths.json, pkg/controller/translator/testdata/ingress-multi-paths.yaml, pkg/controller/translator/testdata/ingress-no-host.json, pkg/controller/translator/testdata/ingress-no-host.yaml, pkg/controller/translator/testdata/ingress-single-host.json, pkg/controller/translator/testdata/ingress-single-host.yaml, pkg/controller/translator/testdata/ingress-two-hosts.json, pkg/controller/translator/testdata/ingress-two-hosts.yaml, pkg/controller/translator/translator.go, pkg/controller/translator/translator_test.go, pkg/controller/utils.go, pkg/loadbalancers/l7.go, pkg/loadbalancers/loadbalancers_test.go, pkg/neg/fakes.go, pkg/test/utils.go, pkg/utils/gceurlmap.go, pkg/utils/utils.go
**Changes**
- Stop gracefully falling back on system default backend if specified backend is not found - no longer need EventRecorder in translater
- Return list of errors from TranslateIngress
- ensureIngress will error if TranslateIngress hits any errors. `ToSvcPorts` iterates all ingresses (for now) and will continue to collect all known service ports
- Deleted a lot of tests in controller_test.go. Some of them should be re-created in different packages (tests that check GCE resource config), and new tests should be made for the controller that assert controller logic such as garbage collection, k8s object lifecycle edge cases.
- Re-wrote tests for controller and created tests for TranslateIngress.
=> TranslateIngress changes

pkg/backends/backends.go, pkg/backends/backends_test.go, pkg/backends/interfaces.go, pkg/controller/cluster_manager.go, pkg/controller/controller.go, pkg/utils/utils.go
Right now, BackendPool.Ensure takes in a list of compute.InstanceGroup. However, the backend pool does not use any field of the IG other than its link. Therefore, it's cleaner to just pass in a list of IG links rather than the full object.
=> Ensure Load Balancer using IG links instead of IG compute object

pkg/backends/backends_test.go, pkg/backends/fakes.go, pkg/controller/fakes.go
- Have FakeBackendServices save Alpha BackendServices by default. GA methods convert the object to alpha version. This is to avoid converting an Alpha object to GA, and potentially losing data present on fields that are only in Alpha but not GA.
- Use `alphaErrFunc` to throw error if not alpha whitelisted (currently only used for HTTP/2)
=> fake backendservices save alpha objects by default

README.md
=> Update documentation to include multiple-TLS support.

pkg/crd/validation.go
This will ensure that if a user pushes a spec like below, that an error will be returned to them:
```
spec:
iap:
```
=> Make sure structs in OpenAPI spec are serialized with 'type: object'

pkg/controller/controller.go, pkg/controller/translator/translator.go, pkg/controller/translator/translator_test.go, pkg/utils/serviceport.go
Thinking it might be great to separate this out of the actual backend service feature implementation. @rramkumar1 Feel free to close this if you have code changes ready, I remembered you were doing something similar...
@bowei
=> Bake backend config into ServicePort

pkg/backends/backends.go, pkg/backends/backends_test.go
This PR fixes the logical OR flow in ensureBackendService to ensure that no short-circuiting occurs. Because of this short circuit, when a BackendService was being ensured only the protocol would be ensured, not the health check or description. However, on subsequent syncs, health check and description would eventually get ensured. Regardless, it makes the code clearer to fix this.
Finally, this PR also ensures that we only get a legacy health check if the BackendService is pointing to one. Previously, we would always get it. This addresses nicksardo@'s comment in #269
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubernetes/ingress-gce/288)
=> Fix bug with ensuring BackendService settings + health checks

cmd/glbc/main.go, pkg/context/context.go, pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/controller/translator/translator.go, pkg/controller/translator/translator_test.go, pkg/neg/controller_test.go, pkg/neg/manager_test.go, pkg/neg/syncer_test.go
This ensures that all of our switches are maintained in the controller context. It also makes some parts of the code easier to read.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubernetes/ingress-gce/299)
=> Slight refactor of controller context to include both NEG & BackendConfig switches

pkg/backends/backends.go, pkg/backends/backends_test.go, pkg/healthchecks/fakes.go, pkg/instances/fakes.go, pkg/instances/instances.go, pkg/loadbalancers/certificates.go, pkg/loadbalancers/fakes.go, pkg/loadbalancers/forwarding_rules.go, pkg/loadbalancers/l7.go, pkg/loadbalancers/loadbalancers_test.go, pkg/loadbalancers/target_proxies.go, pkg/loadbalancers/url_maps.go, pkg/neg/fakes.go, pkg/neg/syncer.go, pkg/utils/utils.go, pkg/utils/utils_test.go
Removes the plethora of helper functions which all perform the same basic action:
- `retrieveObjectName`
- `comparableGroupPath`
- `getResourceNameFromLink`
- `CompareLinks`
- `BackendServiceComparablePath`
- `retrieveName`
Replacing them with a few utility functions which depend on on the [cloud package](https://godoc.org/k8s.io/kubernetes/pkg/cloudprovider/providers/gce/cloud).
=> Use cloud ResourceID for URL parsing and generation

pkg/backends/composite.go, pkg/backends/composite_test.go, vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/gce/cloud/gen.go, vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/gce/cloud/meta/meta.go, vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/gce/gce_backendservice.go
=>  Add beta backend service support to composite type

pkg/backendconfig/backendconfig.go, pkg/backendconfig/utils.go, pkg/backendconfig/utils_test.go, pkg/controller/translator/translator.go, pkg/controller/translator/utils.go, pkg/controller/translator/utils_test.go
The motivation behind this change is to be able to reuse these new utility functions in our new testing framework. Also, breaking these functions out make them easier to test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubernetes/ingress-gce/318)
=> Break out some helper functions for better testing + reuse

cmd/e2e-test/basic_test.go, pkg/fuzz/features/allow_http_test.go, pkg/fuzz/helpers.go, pkg/fuzz/helpers_test.go, pkg/fuzz/validator_test.go
- Get Ingress definition from builder with method Build() rather than
direct access to the object.
- Fix line breaks to make invocations more readable.
=> Make Ingress builder reusable

cmd/glbc/main.go, pkg/apis/backendconfig/v1beta1/types.go, pkg/apis/backendconfig/v1beta1/zz_generated.openapi.go, pkg/backendconfig/backendconfig_test.go, pkg/backends/backends.go, pkg/backends/backends_test.go, pkg/backends/features/cdn.go, pkg/backends/features/cdn_test.go, pkg/backends/features/iap.go, pkg/backends/features/iap_test.go, pkg/composite/composite.go, pkg/controller/cluster_manager.go, pkg/controller/controller.go, pkg/controller/fakes.go, pkg/controller/translator/translator.go, pkg/utils/utils.go
This is the last PR for IAP + CDN integration.
TODO's in separate PR's:
1. Need to write an e2e test using new test framework.
2. Need to add more unit tests to verify behavior.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubernetes/ingress-gce/301)
=> IAP + CDN 

pkg/metrics/util.go, pkg/neg/controller.go, pkg/neg/metrics.go, pkg/neg/syncer.go
promethues dump:
```
neg_controller_neg_sync_count{key="k8s1-84a1883c1680fcf8-default-hostname-9376-d05afea4",result="success",type="attach"} 3
neg_controller_neg_sync_duration_seconds_bucket{key="k8s1-84a1883c1680fcf8-default-hostname-9376-d05afea4",result="success",type="attach",le="0.005"} 0
neg_controller_neg_sync_duration_seconds_bucket{key="k8s1-84a1883c1680fcf8-default-hostname-9376-d05afea4",result="success",type="attach",le="0.01"} 0
neg_controller_neg_sync_duration_seconds_bucket{key="k8s1-84a1883c1680fcf8-default-hostname-9376-d05afea4",result="success",type="attach",le="0.025"} 0
neg_controller_neg_sync_duration_seconds_bucket{key="k8s1-84a1883c1680fcf8-default-hostname-9376-d05afea4",result="success",type="attach",le="0.05"} 0 …
```
=> NEG Metrics

cmd/e2e-test/basic_test.go, pkg/e2e/fixtures.go, pkg/fuzz/helpers.go
/assign @bowei
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubernetes/ingress-gce/331)
=> Add fixtures and helpers in e2e framework for BackendConfig

pkg/backendconfig/utils_test.go, pkg/backends/features/cdn_test.go, pkg/backends/features/iap_test.go, pkg/composite/composite_test.go, pkg/controller/translator/translator_test.go, pkg/controller/translator/utils_test.go, pkg/test/utils.go
This PR makes test improvements and additions in numerous packages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubernetes/ingress-gce/339)
=> Testing improvements

pkg/fuzz/gcp.go
Should be `backendService` instead of `urlMap`?
@rramkumar1
=> Minor fix for retrieving backendService resource

pkg/backends/backends.go, pkg/backends/backends_test.go, pkg/backends/features/doc.go, pkg/backends/features/features.go, pkg/backends/features/features_test.go, pkg/utils/description.go, pkg/utils/description_test.go, pkg/utils/serviceport.go
=> Store feature names in backend service description

pkg/backends/backends.go, pkg/backends/backends_test.go, pkg/healthchecks/fakes.go, pkg/instances/fakes.go, pkg/instances/instances.go, pkg/loadbalancers/certificates.go, pkg/loadbalancers/fakes.go, pkg/loadbalancers/forwarding_rules.go, pkg/loadbalancers/l7.go, pkg/loadbalancers/loadbalancers_test.go, pkg/loadbalancers/target_proxies.go, pkg/loadbalancers/url_maps.go, pkg/neg/fakes.go, pkg/neg/syncer.go, pkg/utils/gceurlmap_test.go, pkg/utils/taskqueue_test.go, pkg/utils/utils.go, pkg/utils/utils_test.go
Removes the plethora of helper functions which all perform the same basic action:
- `retrieveObjectName`
- `comparableGroupPath`
- `getResourceNameFromLink`
- `CompareLinks`
- `BackendServiceComparablePath`
- `BackendServiceRelativeResourcePath`
- `retrieveName`
Replacing them with a few utility functions which depend on on the [cloud package](https://godoc.org/k8s.io/kubernetes/pkg/cloudprovider/providers/gce/cloud).
=> Use cloud ResourceID for URL parsing, generation, and comparison

cmd/e2e-test/run.sh
Retry on metadata curl with explicit error out if it cannot be
contacted.
Capture more information about the project resources so
it is easier to do post-mortem debugging.
=> Retry on getting PROJECT, dump out project resources

pkg/backends/features/cdn.go, pkg/backends/features/cdn_test.go, pkg/backends/features/iap.go, pkg/backends/features/iap_test.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubernetes/ingress-gce/345)
=> Modify IAP + CDN support to not touch settings if section in spec is missing

pkg/controller/translator/translator.go
This ensures that when someone dereferences a BackendConfig from the annotation, that we don't touch their settings,
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubernetes/ingress-gce/347)
=> On removal of backend config name from service annotaion, ensure no existing settings are affected

pkg/backends/backends.go, pkg/backends/features/features.go, pkg/backends/features/features_test.go, pkg/backends/features/securitypolicy.go, pkg/backends/features/securitypolicy_test.go
<s>The first commit is for updating vendor. I will soon split that into another PR.</s> Updated vendor in https://github.com/kubernetes/ingress-gce/pull/293.
/assign @rramkumar1 @bowei
=> Add support for security policy

pkg/fuzz/default_validator_env.go, pkg/fuzz/features/cdn.go, pkg/fuzz/features/features.go, pkg/fuzz/features/iap.go, pkg/fuzz/helpers.go, pkg/fuzz/validator.go
Note that this PR also contains some small changes to the validator:
1.  In order to prevent the http client in the validator from following redirects, I implemented the 
CheckRedirect hook. 
2.  Move the pathToDefaultBackend variable up higher so that other files can use it.
Ref: #301
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubernetes/ingress-gce/319)
=> IAP + CDN e2e testing implementation

pkg/annotations/service.go, pkg/backendconfig/backendconfig.go, pkg/controller/errors/errors.go, pkg/controller/translator/translator.go
=> Minor fix to backend config errors

pkg/controller/controller.go, pkg/controller/utils.go
Given that setting backend config with system default backend is valid, update on system default backend should trigger ingress sync as well.
=> Trigger ingress sync on system default backend update

pkg/fuzz/features/features.go, pkg/fuzz/features/security_policy.go
Implement mostly an empty fuzzer for security policy. There isn't much we can check from the response. The actual e2e test and validation logic will be in a separate PR.
=> Implement fuzzer for feature security policy

pkg/annotations/service.go, pkg/annotations/service_test.go, pkg/neg/controller.go, pkg/neg/controller_test.go, pkg/neg/utils.go, pkg/neg/utils_test.go
Follow-up to https://github.com/kubernetes/ingress-gce/pull/284 .
- Merges the Expose NEG and Ingress NEG annotations into a single key. Example: `{"ingress": true,"exposed_ports":{"3000":{},"4000":{}}}`
- Use kubeClient to actually update the Kubernetes Service in addition to updating it in serviceLister.
- Additional cleanup of documentation.
=> merge Ingress NEG annotation and Expose NEG annotation

pkg/backends/backends_test.go, pkg/healthchecks/fakes.go, pkg/healthchecks/healthchecks.go, pkg/healthchecks/healthchecks_test.go, pkg/healthchecks/interfaces.go, pkg/utils/serviceport.go
=> Swtich to use beta HealthCheck for NEG

cmd/e2e-test/basic_test.go, cmd/e2e-test/security_policy_test.go, pkg/e2e/helpers.go, pkg/fuzz/gcp.go, pkg/fuzz/helpers.go, pkg/utils/description.go
This e2e test mostly checks if security policy is properly set on the relevant backend service resource upon ingress creation/update.
/assign @rramkumar1 @bowei
=> Implement e2e test for security policy

cmd/e2e-test/cdn_test.go, cmd/e2e-test/iap_test.go, pkg/e2e/fixtures.go
I still need to add a test to verify the state transitions
/assign @bowei
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubernetes/ingress-gce/367)
=> Add simple e2e test for CDN & IAP 

cmd/e2e-test/cdn_test.go, cmd/e2e-test/iap_test.go
Sorry, the signature of `WaitForGCLBDeletion()` was changed by https://github.com/kubernetes/ingress-gce/pull/360 but new callers were added in https://github.com/kubernetes/ingress-gce/pull/367 so codes can't built at the moment.
=> Fix WaitForGCLBDeletion() callers

cmd/e2e-test/backend_config_test.go
This test creates a set of Ingress & Service that references a not exist BackendConfig and waits for a warning event being emitted. 
/assign @rramkumar1 @bowei
=> Add a negative test case for referencing not exist BackendConfig

pkg/neg/manager.go, pkg/neg/utils.go, pkg/neg/utils_test.go
=> cherrypick #377 into release-1.2

pkg/backends/backends_test.go, pkg/backends/features/doc.go, pkg/backends/features/features.go, pkg/backends/features/features_test.go, pkg/utils/serviceport.go
`func (sp ServicePort) Version() meta.Version ` is deprecated, new feature version logic should be added to features.go instead. 
Still working on fixing the unit test.
/assign @freehan @agau4779
=> Patch NEG version into features.go and add more docs for features package

cmd/e2e-test/security_policy_test.go
If this test runs in multiple clusters, then we will see failures since the security policy created will not be unique to that clusters. Adding the sandbox namespace to the end of the name ensures we don't see these errors.
/assign @bowei 
/cc @MrHohn
=> Modify security policy e2e test to create unique GCP resources.

cmd/e2e-test/backend_config_test.go, pkg/backendconfig/backendconfig.go
=> Add more negative test cases for backend config

pkg/fuzz/features/security_policy.go, pkg/fuzz/helpers.go
This PR teaches security policy validator to actually check for response's status code.
/assign @rramkumar1 @bowei
=> Implement security policy validator for real

cmd/glbc/app/clients.go, pkg/flags/flags.go, pkg/ratelimit/ratelimit.go, pkg/ratelimit/ratelimit_test.go
Example ingress creation: https://pastebin.com/raw/HApszAgu
=> Pace operation polling

cmd/glbc/main.go, pkg/context/context.go, pkg/controller/cluster_manager.go, pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/controller/fakes.go, pkg/controller/translator/translator_test.go, pkg/neg/controller_test.go, pkg/neg/manager_test.go, pkg/neg/syncer_test.go
This PR is one of many that aim to eliminate the need for ClusterManager. In this PR, I introduce ControllerContextConfig which simply encapsulates the values for some command line flags, most notably the default backend service port ID. This eliminates the need for ClusterManager to keep track of it.
=> Introduce ControllerContextConfig and move some command-line tunable stuff there

pkg/controller/cluster_manager.go, pkg/controller/controller.go
Yet another PR to slowly remove ClusterManager from existence. This PR inlines the EnsureLB call into the controller itself.
=> Remove EnsureLB from ClusterManager

pkg/controller/controller.go, pkg/controller/translator/testdata/ingress-missing-multi-svc.json, pkg/controller/translator/testdata/ingress-missing-rule-svc.json, pkg/controller/translator/testdata/ingress-multi-empty.json, pkg/controller/translator/testdata/ingress-multi-paths.json, pkg/controller/translator/testdata/ingress-no-host.json, pkg/controller/translator/testdata/ingress-single-host.json, pkg/controller/translator/testdata/ingress-two-hosts.json, pkg/controller/translator/translator_test.go, pkg/loadbalancers/fakes.go, pkg/loadbalancers/l7.go, pkg/loadbalancers/l7s.go, pkg/loadbalancers/loadbalancers_test.go, pkg/loadbalancers/target_proxies.go, pkg/loadbalancers/url_maps.go, pkg/loadbalancers/url_maps_test.go, pkg/utils/gceurlmap.go, pkg/utils/gceurlmap_test.go, pkg/utils/serviceport.go
Changes
- `UpdateUrlMap()` mostly turned into static func `toComputeURLMap()`. It's sync logic moved to `ensureComputeURLMap()`.
- `L7s.Sync()` calls `ensureComputeURLMap()` to assert the URLMap's existence and correctness instead of making a separate, later call to `UpdateUrlMap()` 
- `utils.GCEURLMap` used a map for hostname->path rules which made the generated URLMap's order non-deterministic (presumably this caused unnecessary API calls). It now uses a slice and maintains uniqueness.
Bulk of this PR is in tests or related datafiles.
=> URLMap sync

pkg/context/context.go
Makes it easier for other stuff to use the lock :)
=> Rename context's hcLock to lock

pkg/controller/translator/translator.go, pkg/utils/utils.go
Addresses #292 
Use the same node selection logic as the kubernetes service controller:
- filter out master nodes
- filter out non-ready node
- filter out nodes with label `alpha.service-controller.kubernetes.io/exclude-balancer`
In the kubernetes service controller, the service node exclusion is a feature gate but there is no feature gate on this controller, so I removed the feature gate test (it seems unlikely that this label would be applied to a node that doesn't require exclusion). If you think it's not a good call I can revisit this.
I have a custom build available on dockerhub for testing: `lbernail/glbc:v0.2`
=> Align node filtering with kubernetes service controller

pkg/annotations/service.go, pkg/annotations/service_test.go
=> Introduce cloud.google.com/app-protocols to eventually replace existing annotation

pkg/backends/backends.go, pkg/backends/ig_linker_test.go, pkg/backends/interfaces.go, pkg/backends/neg_linker_test.go, pkg/backends/syncer.go, pkg/controller/controller.go
Introduced by #424. Looks like we can't create a BackendService without a health check. Fixed the BackendPool.Create implementation to now take in a health check link.
/assign @bowei
=> Fix bug in backend syncer where backend service was being created without health check

pkg/loadbalancers/url_maps.go
The previous code could potentially have a NPE if l.um = nil.  Modified the code to use the Name field of the L7 struct instead, which we know will always be non-nil.
Example error log:
```I0814 11:19:06.891594       1 l7s.go:66] Creating l7 e2e-tests-ingress-ckx44-hostname--bd7d411a662def7f
E0814 11:19:07.199597       1 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/go/src/k8s.io/ingress-gce/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/go/src/k8s.io/ingress-gce/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go/src/k8s.io/ingress-gce/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:573 …
```
=> Fix null-pointer exception in url map ensure logic

pkg/backends/backends.go, pkg/backends/syncer.go
Makes it easier to not make a mistake of forgetting to set version when calling Update(). All logic is now encapsulated in Update() implementation itself.
/assign @bowei
=> BackendPool Update() should set backend service version

pkg/controller/controller.go
In the current logic, it appears that errors during garbage collection at the end of a sync were being suppressed. Now, any errors during GC should be logged properly.
=> Fix error handling in controller sync()

pkg/apis/backendconfig/v1beta1/types.go, pkg/apis/backendconfig/v1beta1/zz_generated.openapi.go
This is for fixing an incompatibility issue with https://github.com/kubernetes/features/issues/571.
/assign @rramkumar1 
cc @Liujingfang1
<s>Note: The `Description` entry is manually removed, as adding `omitempty` doesn't seem to stop generating it.</s> Fixed by removing struct comment.
=> Remove 'Description' and 'Required' from OpenAPI schema root layer

pkg/instances/instances.go, pkg/instances/instances_test.go
=> Remove unused named ports from instance group's 

pkg/apis/backendconfig/v1beta1/types.go, pkg/apis/backendconfig/v1beta1/zz_generated.openapi.go
Cherrypicking https://github.com/kubernetes/ingress-gce/pull/442 so it can make the next patch release.
=> Cherrypick #442 into release-1.3

pkg/controller/controller.go, pkg/controller/utils.go, pkg/controller/utils_test.go
ref: https://github.com/kubernetes/ingress-gce/issues/433
=> do not create instance group with NEG backends

Gopkg.lock, pkg/utils/finalizer.go, pkg/utils/finalizer_test.go, vendor/k8s.io/apimachinery/pkg/util/rand/rand.go, vendor/k8s.io/kubernetes/pkg/util/slice/BUILD, vendor/k8s.io/kubernetes/pkg/util/slice/slice.go
Adding some functions needed to support finalizers. This code can easily be reused by other modules.
Much of this code was adapted from https://github.com/kubernetes/kubernetes/pull/54569
/assign @bowei @MrHohn
=> Add some utility functions to support finalizers

pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/sync/interfaces.go, pkg/sync/sync.go
This PR introduces one high level sync interface and an interface for controllers to implement the sync. 
The benefit of this PR is that it enforces a simple contract for controllers to follow and makes creating controller mocks much easier. For example, the existing controller in pkg/controller/controller.go would be modified to implement the Controller interface. 
Note that this PR works at a layer above #424. A controller would potentially implement SyncBackends using the new interfaces defined in pkg/backends.
Also note that this abstraction will make it easier to parallelize syncs although the current implementation would need to be rewired a bit.
The second commit attempts to use the new interfaces in pkg/controller the way the code is currently structured.
/assign @bowei
=> Introduce a new interface to encapsulate Ingress sync and controller implementation of the sync

pkg/controller/controller.go, pkg/controller/types.go, pkg/sync/interfaces.go, pkg/sync/sync.go
This PR tries to eliminate the Ingress type from being referenced in the Controller and Syncer interfaces in pkg/sync. This ensures that implementations of the Controller interface can use any Ingress implementation.
/assign @bowei
=> Slight refactor of Controller interface to eliminate Ingress type specifically

pkg/annotations/service.go, pkg/annotations/service_test.go, pkg/controller/translator/translator.go, pkg/neg/controller.go, pkg/neg/utils.go, pkg/neg/utils_test.go
Refactor NEG annotation handling
Fix a problem where NEG annotation mal format errors are eaten. 
cc: @agau4779
=> fix and refactor on NEG annotation handling

pkg/crd/crd.go, pkg/crd/meta.go
For example, "kubectl get backendconfig" could be "kubectl get bcfg"
=> Support short names in CRD Meta. Allows for abbreviating CRD's in kubectl

pkg/loadbalancers/certificates.go, pkg/loadbalancers/fakes.go, pkg/loadbalancers/loadbalancers_test.go, pkg/tls/tls.go
Hardcoding limit means more changes in ingress when targetproxy limit is increased.
=> Do not truncate tls certs based on target proxy limit

pkg/backends/backends.go, pkg/instances/instances.go
Reverts kubernetes/ingress-gce#458
This is causing e2e tests to fail because it depends on #460. Will submit this later.
=> Revert "Refactor some uses of snapshotter.Add() to use bool rather than real object"

pkg/controller/controller.go
This is a follow up/in relation to my comment made here: https://github.com/kubernetes/ingress-gce/pull/112#issuecomment-394784727
This switches ingress-gce back to the previous behaviour of 'soft failing' if the specified TLS secret exists. Without this change, we've had many users complain that auto-TLS using cert-manager (and also kube-lego) is broken.
Please see the discussion in #112 and https://github.com/jetstack/cert-manager/issues/606 for more detail.
The one notable difference, is instead of simply logging a warning using `glog` (which on GKE is not visible to end users), we now fire a Warning event, but importantly **still continue afterwards**. This is essential for something like cert-manager, as without it users would need to create some kind of self-signed placeholder …
=> Fire warning event instead of hard failing if TLS certificate is not present

cmd/glbc/main.go, pkg/flags/flags.go, pkg/neg/controller.go, pkg/neg/controller_test.go, pkg/neg/manager.go
Modified 2 things:
- make NEG GC more frequent
- delay initial NEG GC to allow services to be fully processed.
=> Harden NEG GC

pkg/controller/controller.go
=> Cherrypick #388 on release 1.3 branch

CONTRIBUTING.md
This PR updates the link that currently point to the [Google Groups Kubernetes Mailing List](https://groups.google.com/forum/#!forum/kubernetes-users) to the new [discuss.kubernetes.io](https://discuss.kubernetes.io) forum. 
The mailing list has been archived and set to read only. For more information on this, see issue https://github.com/kubernetes/community/issues/2492
/cc @castrojo
=> Replace kubernetes-users mailing list link with discuss forum link

pkg/backends/neg_linker_test.go, pkg/neg/cloudprovideradapter.go, pkg/neg/controller.go, pkg/neg/controller_test.go, pkg/neg/manager.go, pkg/neg/manager_test.go, pkg/neg/metrics/metrics.go, pkg/neg/syncer/batch.go, pkg/neg/syncer/batch_test.go, pkg/neg/types/fakes.go, pkg/neg/types/interfaces.go, pkg/neg/types/types.go, pkg/utils/utils.go
No functional changes. Only refactoring: 
- Created sub-package for `/metrics` and `/syncer`
- Move common types and interfaces into `/types`
- Rename `syncer` to `batchSyncer`
cc: @agau4779
=> Restructure NEG controller

deploy/glbc/yaml/default-http-backend.yaml, docs/troubleshooting.md, examples/deployment/gce-ingress-controller.yaml
**What this PR does / why we need it**:
Update docker image for default backend service (render 404 page)
**Release note**:
```release-note
Update defaultbackend image to 1.5.
```
@bowei @timstclair
=> Update defaultbackend image to 1.5

Dockerfile.fuzzer, Dockerfile.glbc
Alpine fixed a RCE vulnerability in apk in 3.8.1 (https://alpinelinux.org/posts/Alpine-3.8.1-released.html)
Update the base image used for ingress-gce.
=> Bump Alpine base image version

pkg/neg/syncer/batch.go
This fix a nil pointer exception, when an endpoint does not have an associated node. 
This usually happens when the endpoints object is manually created.
cc: @agau4779
=> Fix a potential nil pointer exception

pkg/neg/controller.go
This makes the informer processing lockless. It used to depend on SyncerManager internal locks.
cc:  @agau4779
=> add work queue to process endpoint changes

pkg/utils/namer.go, pkg/utils/namer_test.go
Follow up of #494
Repush #495
cc: @agau4779
=> merge negBelongsToCluster into IsNEG

Gopkg.lock, cmd/e2e-test/main_test.go, cmd/fuzzer/app/validate.go, cmd/fuzzer/fuzzer.go, cmd/glbc/app/clients.go, pkg/controller/controller.go, vendor/k8s.io/client-go/plugin/pkg/client/auth/oidc/OWNERS, vendor/k8s.io/client-go/plugin/pkg/client/auth/oidc/oidc.go
controller.go changes transformed ingress spec errors from Kubernetes Events to simple logs:
https://github.com/kubernetes/ingress-gce/blob/master/pkg/controller/controller.go#L455  is returning.
So we never hit https://github.com/kubernetes/ingress-gce/blob/master/pkg/controller/controller.go#L461 .
As a consequence, some e2e tests, waiting for those events, bails out
(ie. https://github.com/kubernetes/ingress-gce/blob/master/cmd/e2e-test/backend_config_test.go#L114 ).
Notifying those errors as events -as they did previously- seems the proper course of action,
and generaly useful beyond testing.
Unrelated: end users may authenticate to GCP using OpenID Connect (at least I do);
linking in client-go's plugin/pkg/client/auth/oidc allow them to run tests on their
machines.
=> Fix events-based e2e tests

deploy/glbc/yaml/glbc.yaml, deploy/glbc/yaml/rbac.yaml
Not sure if BackendConfig support was intentionaly left out of the deployment
example (ie. after all it's still off by default, that feature is possibly not
yet considered ready for usage outside GKE?), or this example was just forgotten.
If the later, including it would be nice as those GKE users having already
defined BackendConfigs and willing to try ingress-gce git HEAD would be up
for a suprise.
Otherwise, let's just drop this PR.
=> Update deploy/glbc yaml files for BackendConfig

pkg/fuzz/gcp.go
`CheckResourceDeletion()` appends pointer of the key to `resources` while detecting un-deleted resources, which would likely be pointing to a wrong key as the for loop goes. This PR changes it to append value of the key instead.
=> [e2e test] append key value to resources instead of pointer

cmd/e2e-test/basic_test.go, cmd/e2e-test/cdn_test.go, cmd/e2e-test/iap_test.go, cmd/e2e-test/security_policy_test.go
=> In e2e tests, always skip checking for deletion of default backend service

cmd/glbc/main.go, pkg/controller/controller.go, pkg/controller/node.go, pkg/firewalls/controller.go, pkg/utils/taskqueue.go, pkg/utils/taskqueue_test.go
Originally, PeriodicTaskQueue has 2 loops:
- wait.Until managed by stopCh
- for loop in worker() managed by workqueue
Shutdown only exits the second loop. Failing to close stopCh before
calling Shutdown will cause panic because of double close workDone
channel.
=> Fix the issue where Shutdown doesn't shutdown taskqueue

cmd/glbc/main.go, pkg/context/context.go, pkg/controller/controller.go
This should fix the current failures in the OSS CI:
Ref: https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-ingress-gce-e2e/3251
=> Managed Certs integration: Fix code so that informers are not instantiated if managed certs is not enabled

pkg/annotations/ingress.go, pkg/firewalls/controller.go
Tested using debug output. 
```
I1002 00:52:00.732636       1 firewalls.go:129] Could not create L7 firewall on XPN cluster. Raising event for cmd: "gcloud compute firewall-rules create k8s-fw-l7--f55c729d54843f52 --network shared-net --description \"GCE L7 firewall rule\" --allow tcp:30000-32767 --source-ranges 130.211.0.0/22,209.85.152.0/22,209.85.204.0/22,35.191.0.0/16 --target-tags gke-xpn-test-5a5694fa-node --project yankaiz-xpn-host"
I1002 00:52:00.732948       1 controller.go:178] >>>>>>>>>>>>> Emitting event for FirewallXPNError <<<<<<<<<<<<<<<
I1002 00:52:00.733404       1 controller.go:149] Syncing firewall
I1002 00:52:00.734304       1 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"default", Name:"ing-web", UID:"ac329930-c5da-11e8-a4db-42010af0009b", …
```
=> Add annotation to suppress XPN firewall events

pkg/annotations/ingress.go, pkg/firewalls/controller.go
Cherrypick https://github.com/kubernetes/ingress-gce/pull/506 into release-1.4
Add annotation to suppress XPN firewall events when failed to manipulate firewall due to XPN and permission error.
=> Add gke.io/suppress-firewall-xpn-error annotation to suppress XPN firewall events

README.md, docs/annotations.md
README.md is light on details related to recent features (NEGs,
BackendConfig, etc.). That may be material for an other PR ?
For now, let's just edit so the content remains correct (ie. not
assuming instance groups exclusively, when NEG is an option).
=> README.md: don't assume instance groups where NEG is an option

pkg/neg/syncers/backoff.go, pkg/neg/syncers/backoff_test.go, pkg/neg/syncers/retry_handler.go, pkg/neg/syncers/retry_handler_test.go
Extract the backoff retry logic from `batchSyncer` and write 2 util package that can be reused by different syncers, plus unit testing:
- `backoffHandler` calculates exponential backoff delays
- `backoffRetryHandler` triggers `retryFunc` after back off delay.
These utils are building blocks for the new `transactionSyncer`
cc: @agau4779
=> Add a Backofff Handler utils

cmd/e2e-test/draining_test.go, cmd/e2e-test/timeout_test.go, pkg/fuzz/helpers.go
As suggested by @MrHohn 
Those are simple tests checking that the settings from BackendConfig propagates well
to the live BackendService.
Let me know if you'd rather me to write fuzz http reqs testing real timeouts expirations
(that's much more involved -esp. the connection draining part- so it'll take more time though).
=> e2e tests for timeout and draining timeout

pkg/neg/syncers/batch.go, pkg/neg/syncers/transaction.go, pkg/neg/syncers/transaction_test.go, pkg/neg/syncers/utils.go, pkg/neg/syncers/utils_test.go
This PR introduces transaction NEG syncer. This syncer is non blocking. It will not wait for batches of NEG operation to finish before trigger more NEG operations. 
PR prerequistes:
#528
#509
#499
TODOs:
- add a flag to switch between batch syncer and transaction syncer
- add more unit test
- make this more readable
=> Transaction Syncer

cmd/e2e-test/draining_test.go
While polling for the connection draining transition, the test calls t.Errorf() instead of t.Logf(). This causes the test to fail rather than perform the poll-loop again, as intended.
/assign @bowei
=> Connection Draining E2E: Fix test log message level

pkg/backendconfig/backendconfig.go, pkg/backendconfig/backendconfig_test.go, pkg/backendconfig/utils.go, pkg/common/operator/backendconfig.go, pkg/common/operator/backendconfig_test.go, pkg/common/operator/doc.go, pkg/common/operator/ingress.go, pkg/common/operator/ingress_test.go, pkg/common/operator/service.go, pkg/common/operator/service_test.go, pkg/common/typed/backendconfig.go, pkg/common/typed/ingress.go, pkg/common/typed/service.go, pkg/context/context.go, pkg/controller/controller.go, pkg/firewalls/controller.go, pkg/utils/utils.go
/assign @bowei 
PR is broken up into 3 commits for easier review.
=> Add pkg/common/operator & pkg/common/typed to make resource joins much cleaner.

cmd/e2e-test/affinity_test.go, cmd/e2e-test/basic_test.go, cmd/e2e-test/basic_upgrade_test.go, cmd/e2e-test/cdn_test.go, cmd/e2e-test/draining_test.go, cmd/e2e-test/iap_test.go, cmd/e2e-test/security_policy_test.go, cmd/e2e-test/timeout_test.go, pkg/e2e/framework.go, pkg/e2e/helpers.go, pkg/e2e/sandbox.go, pkg/e2e/status.go
Continuation of https://github.com/kubernetes/ingress-gce/pull/392 .
=> Ingress Upgrade Testing

pkg/controller/controller.go, pkg/controller/controller_test.go
=> do not leak LB when ingress class is changed

examples/static-ip/README.md
Fixed a misspell in annotation name. 
Now readme is correct and matching .yml files.
=> Fixed misspell (annotation name) i README.md

pkg/controller/controller.go, pkg/controller/node.go, pkg/firewalls/controller.go, pkg/utils/taskqueue.go, pkg/utils/taskqueue_test.go
=> Create task queues with a name so that usage metrics can be tracked by Prometheus

pkg/e2e/helpers.go
Hoping this will mitigate some of the errors we are seeing. We need to figure out a way to maybe increase/decrease the timeout based on the environment (e.g how many ingresses are being synced)
=> Increase deletion timeout for e2e tests

cmd/e2e-test/upgrade_test.go, pkg/e2e/status.go
- Start and stop ConfigMap informer based on k8s master state
- Delete Ingress and break loop upon test finish
=> Ingress e2e test cleanup

pkg/controller/translator/translator.go, pkg/controller/translator/translator_test.go, pkg/neg/controller.go
fixes: https://github.com/kubernetes/ingress-gce/issues/541
=> reflect readiness probe in health check for NEG enabled ClusterIP service backend

cmd/e2e-test/run.sh
In certain cases to reduce the noise in the logs, we may want to not dump all the network resources in the project.
/assign @bowei
=> [E2E] In run.sh, add option to disable the resource dump at the end of the test.

cmd/e2e-test/upgrade_test.go
=> Upgrade Test: Ignore connection refused errors when WaitForIngress() is called.

pkg/controller/translator/translator.go
This is small part of fix for #50 (fixes this log messages https://github.com/kubernetes/ingress-gce/issues/50#issuecomment-335960715)
GetNodeConditionPredicate filtered nodes with conditions different from "Ready", and we're getting this messages when node is deleting from instance group.
=> do not use condition predicate while getting zone for node

pkg/instances/instances.go, pkg/instances/instances_test.go
This reverts commit fbe88aa88b961ab683af8486da6e040cbd75584c.
Cherry pick onto 1.4 branch
/assign @bowei
=> [1.4 Cherry pick] Revert "Remove unused named ports from instance group's"

.github_changelog_generator, CHANGELOG.md
=> Add changelog for v1.4.1 + Add config file for github-changelog-generator

pkg/loadbalancers/l7s.go, pkg/loadbalancers/loadbalancers_test.go, pkg/utils/namer.go
Addresses https://github.com/kubernetes/ingress-gce/issues/606
Fixes the Garbage Collection routine in l7s. GC takes in `names` as an argument, where `names` comes from the garbage collection state, which is a list of Ingress names which are formatted something like `something-a/something-b`. We derive the loadbalancer name from the `something-a` portion, by affixing the clusterid to it.
=> standardize loadbalancer naming for GC

pkg/backends/features/cdn.go, pkg/backends/features/cdn_test.go
Fixes #599
Currently verifying whether this works and other existing state transitions still hold.
=> [BackendConfig] CDN default cache key policy should be true instead of false.

pkg/neg/syncers/retry_handler.go, pkg/neg/syncers/retry_handler_test.go
Use FakeClock to make unit test run faster.
=> make backoff retry handler unit test faster

pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/controller/types.go, pkg/flags/flags.go, pkg/utils/finalizer.go
The finalizer `ingress.finalizer.cloud.google.com` will be applied to the Ingress upon update if it does not have a finalizer yet. It will be removed only after the resources related to the Ingress have been deleted first. Absence of a finalizer means the Ingress itself can be safely deleted.
If a resource used for this ingress fails to be deleted because it’s ‘in use’ by another resource, then the resource will be skipped. If it cannot be deleted for another reason, the controller will attempt deletion at a later attempt.
=> Add Finalizers for Ingress

pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/flags/flags.go, pkg/utils/finalizer.go
Cherry-pick 2nd commit in #613
=> Cherry-pick #613 onto 1.4 branch

pkg/controller/translator/translator.go, pkg/controller/translator/translator_test.go, pkg/neg/controller.go
bug fix: correctly reflect readiness probe in health check for NEG enabled ClusterIP service backend
=> Cherrypick #582 into release-1.4 branch

pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/flags/flags.go, pkg/utils/finalizer.go
Reverts kubernetes/ingress-gce#628. This did not pick back cleanly. 
=> Revert "Cherry-pick #613 onto 1.4 branch"

pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/controller/types.go, pkg/utils/finalizer.go
Reverts kubernetes/ingress-gce#627. This also did not pick back cleanly.
=> Revert "Cherry-pick #613 onto 1.4, part 1"

pkg/loadbalancers/certificates.go, pkg/loadbalancers/fakes.go, pkg/loadbalancers/loadbalancers_test.go
This should allow for a no-downtime migration from secret-based to pre-shared certs, as the secret-based cert will be still used until the secret is removed.
=> Support secret-based and pre-shared certs at the same time

pkg/e2e/framework.go
Shortening the name of the namespace will allow us to not hit the name truncation bug that currently exists.
This is a temporary measure until we have a concrete design on how to fix the bug.
=> Shorten the name of the namespace for test sandboxes

pkg/utils/namer.go, pkg/utils/namer_test.go
=> Modify NameBelongToCluter to tolerate truncated cluster name suffix

pkg/e2e/framework.go
Reverts kubernetes/ingress-gce#648
#650 is the permanent solution.
=> Revert "Shorten the name of the namespace for test sandboxes"

cmd/e2e-test/upgrade_test.go
Because the created Ingress previously specified a default backend, it was possible that the new path we add post-upgrade could fail but we still pass the test. This happens because the service being used for the default backend and the service being used for the new path are the same.
=> Fix upgrade test to create an Ingress with no default backend

cmd/e2e-test/upgrade_test.go
This is a follow up to #654. Since we removed usage of a default backend in the Ingress spec, the system default backend service (404 server) will also be created.
=> Update upgrade_test.go to look for 2 backend services in whitebox test

Dockerfile.404-server, Dockerfile.fuzzer, Dockerfile.glbc
[Kubernetes issue/70249
](https://github.com/kubernetes/kubernetes/issues/70249)
Internal Doc: go/rebase-gke-image-to-distroless
Test: Tested the Dockerfile files validation via "make build bin".
=> Rebase base images from scratch and alpine to distroless

pkg/firewalls/firewalls.go
Currently the error from gce cloud is thrown away. Need this error to be in the log for better troubleshooting.
=> Add exact error to the log when firewall operation fails

cmd/e2e-test/upgrade_test.go
Since we add a new host to the Ingress, some amount of 404's are expected.
=> [Upgrade Test] After path addition to Ingress post-upgrade, do not error out if we receive 404's.

cmd/glbc/main.go, pkg/annotations/service.go, pkg/annotations/service_test.go, pkg/backends/integration_test.go, pkg/backends/syncer.go, pkg/backends/syncer_test.go, pkg/context/context.go, pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/controller/translator/translator.go, pkg/controller/translator/translator_test.go, pkg/firewalls/controller_test.go, pkg/flags/flags.go, pkg/neg/controller_test.go, pkg/neg/manager_test.go, pkg/neg/syncers/batch_test.go, pkg/neg/syncers/syncer_test.go, pkg/neg/syncers/transaction_test.go
Remove feature flags for both NEG and BackendConfig. Both these features are stable and about to go GA soon so there is no reason to flag gate them.
Any further improvements to both these features will have their own flag-gate, if necessary.
=> Clean up unused feature flags for NEG and BackendConfig

Dockerfile.404-server, Dockerfile.fuzzer, Dockerfile.glbc
Reverts kubernetes/ingress-gce#655.
Since this was merged, our CI has been failing [1] with the following error:
oci runtime error: container_linux.go:247: starting container process caused "exec: \"sh\": executable file not found in $PATH"
[1] https://k8s-testgrid.appspot.com/sig-network-ingress-gce-e2e
=> Revert "Rebase base images from scratch and alpine to distroless"

pkg/e2e/framework.go
Every so often, we see that the same namespace is generated for different tests. Since rand.Rand is apparently not safe concurrent use, this is expected. Adding a lock around random number generation should fix the issue.
=> [E2E Test] Add lock around random number generation for sandbox namespace

Dockerfile.404-server, Dockerfile.fuzzer, Dockerfile.glbc
Since Rohit has updated all the glog to klog, it's safe to move forward and revert back the distroless PR.
=> Revert "Revert "Rebase base images from scratch and alpine to distroless""

pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/loadbalancers/certificates.go
Secret-based certs were skipped during loadbalancer runtime info update when pre-shared certs were specified.
Changed to always include secret-based certs and added a test to document this change.
This is a followup to #641
=> Fix supporting secret-based and pre-shared certs at the same time

pkg/healthchecks/healthchecks.go
=> examine nil pointer before applying backend protocol configurations

pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/loadbalancers/certificates.go
#687 was directly on the 1.5 branch but we need this change on master as well. 
FYI @michallowicki
=> Add #687 onto master

pkg/healthchecks/healthchecks.go
=> Cherrypick #678 into release-1.5

cmd/e2e-test/basic_test.go
Corresponding e2e test for #688
=> Add e2e test for Ingress that has long namespace+name

cmd/e2e-test/basic_test.go
This ensures that a regex filter of "Basic" does not include this test.
=> TestBasicEdge -> TestEdge

pkg/e2e/status.go
If the status manager does not shut down correctly, the config map will still exist the next time a test starts and prevent the test from running until you delete it via kubectl. This deletes and replaces the config map if it already exists.
=> e2e StatusManager init() handle existing config map

cmd/e2e-test/affinity_test.go, cmd/e2e-test/backend_config_test.go, cmd/e2e-test/basic_test.go, cmd/e2e-test/cdn_test.go, cmd/e2e-test/draining_test.go, cmd/e2e-test/iap_test.go, cmd/e2e-test/neg_test.go, cmd/e2e-test/security_policy_test.go, cmd/e2e-test/timeout_test.go, cmd/e2e-test/upgrade_test.go, pkg/annotations/service.go, pkg/annotations/service_test.go, pkg/controller/translator/translator.go, pkg/e2e/fixtures.go, pkg/e2e/helpers.go, pkg/fuzz/features/features.go, pkg/fuzz/features/iap.go, pkg/fuzz/features/neg.go, pkg/fuzz/features/security_policy.go, pkg/fuzz/gcp.go, pkg/fuzz/helpers.go, pkg/neg/controller.go, pkg/neg/types/types.go, pkg/neg/types/types_test.go, pkg/neg/utils_test.go
Related Issue: https://github.com/kubernetes/ingress-gce/issues/667
Adds a basic NEG test "TestNEGBasic" that tests the functionality of enabling/disabling NEG for ingress, and verifying that the corresponding actions/GC are correct.
Adds NEG as a component to the fuzz validator framework
Adds helper functions:
- pkg/annotations/service.go: 
- NegAnnotation.String()
- Service.NEGAnnotation()
- Service.NEGStatus()
- pkgg/e2e/helpers.go
- WaitForNEGDeletion()
- WaitForNEGConfiguration()
- pkg/e2e/fixtures.go
- EnsureEchoService()
- EnsureIngress()
- pkg/fuzz/gcp.go
- GCLB.CheckNEGDeletion()
- pkg/neg/types/types.go
- ParseNegStatus()
- pkg/fuzz/features/neg.go
- verifyNegBackend()
- pkg/fuzz/helpers.go
- ServiceForPath()
=> Port basic NEG test from k/k

cmd/e2e-test/run.sh
This makes it easier for an external framework to distinguish between an error with the bootstrapping or an error due to the test failing (test failures return error code 1)
=> In E2E runner script, exit with error code 2 if encountered error with bootstrapping

cmd/e2e-test/basic_test.go, cmd/e2e-test/neg_test.go, pkg/e2e/fixtures.go, pkg/e2e/helpers.go, pkg/fuzz/features/neg.go
EnsureEchoService() now creates a deployment instead of a single pod (existing tests use 1 replica).  This will be useful for e2e tests that test the creation of multiple NEGs.
Also includes some fixes from comments made on https://github.com/kubernetes/ingress-gce/pull/679, mainly refactoring some common checks into checkGCLB().
=> Refactor EnsureEchoService() for e2e tests to use a deployment

cmd/e2e-test/neg_test.go, pkg/e2e/fixtures.go
Also:
- Removes the Protocol and ServicePort fields from EnsureEchoService() since using non-default values only makes the service invalid.
- Fix EnsureEchoService() to also update deployment scale
=> Add ClusterIP test case to NEG e2e tests

cmd/e2e-test/app_protocols_test.go, cmd/echo/app/handlers.go, pkg/e2e/fixtures.go, pkg/fuzz/features/app_protocol.go, pkg/fuzz/features/features.go, pkg/fuzz/helpers.go
The PR is split into two commits:
1. Extract echoheaders response body into public struct so it can be used elsewhere
2. Porting of tests
Note that the PR to remove the tests from k/k is https://github.com/kubernetes/kubernetes/pull/75143
=> Move tests for app protocols from k/k to Ingress-GCE repo

cmd/e2e-test/basic_https_test.go, pkg/e2e/cert.go, pkg/e2e/fixtures.go, pkg/e2e/framework.go, pkg/e2e/helpers.go, pkg/fuzz/helpers.go
Porting from k/k
This PR is already pretty big so I'll add transition tests in a followup
=> Add tests for HTTPS 

pkg/fuzz/features/allow_http.go
Currently, the feature validator only turns off the HTTPS path check but we also need to verify that the HTTPS resources are cleaned up. It is actually a known bug that we do not do this so once we fix the bug, we will need to add the corresponding validation here.
=> Add TODO in allow_http feature to verify that HTTPS resources are cleaned up

cmd/e2e-test/neg_test.go, pkg/fuzz/default_validator_env.go, pkg/fuzz/features/neg.go, pkg/fuzz/validator.go
In NEGTransition test, for every test case, after applying the new setup, it waits for ingress to stablize by calling https://github.com/kubernetes/ingress-gce/blob/master/cmd/e2e-test/neg_test.go#L90
However, if ingress-gce controller is under load, it takes more time to configure the LB based on the new config. Then the old LB setup will stays the same. And `WaitForIngress` will not block because the old setup is already working.
This PR makes the NEG feature validator to validate the reverse case (IG backends). So that `WaitForIngress` will block when NEG is disabled and wait for the ingress-gce to adjust backend service to use IG
=> make NEGTransition test unflakey under load

cmd/e2e-test/neg_test.go
Log the test case description for the NEG transition tests since they're all run within one sandbox.  Should make debugging more transparent.
=> Log description for NEG transition e2e tests

pkg/annotations/service_test.go, pkg/fuzz/features/neg.go, pkg/neg/controller.go, pkg/neg/controller_test.go, pkg/neg/manager.go, pkg/neg/manager_test.go, pkg/neg/types/interfaces.go, pkg/neg/types/types.go, pkg/neg/types/types_test.go, pkg/neg/utils.go, pkg/neg/utils_test.go
- No functional changes
- Split `PortNameMap` type into
- `PortNegMap`   (used by NEG Status Annotation)
- `SvcPortMap`   (Internal plumbing)
- `PortInfoMap`   (Syncer Manager interface)
- Include NEG name in PortInfo, so that no need to recalculate NEG name at multiple places. 
This is prerequisite for Readiness Reflector
cc: @spencerhance
=> Refactor NEG Type

cmd/glbc/app/namer.go, pkg/fuzz/default_validator_env.go
Use this new function in our e2e test framework as opposed to the namer which dynamically changes its naming policy. 
Reason is that during a master upgrade, the previous function would spit out a klog.Errorf() every time it could not read the ConfigMap which is expected since the master is upgrading. Since we know the uid will not change during our tests (for now), we would prefer to not have the error log showing up repeatedly in our test logs.
=> Introduce function to create a static namer that does not change naming policy

pkg/fuzz/validator.go
This is a readability thing because it makes it easier to diagnose which validator failed.
/assign @bowei
=> Return name of validator in error from CheckResponse()

pkg/tls/tls.go
Addresses a portion of #713. We may decide to cherry-pick this back to the 1.5 branch as well depending on the urgency.
=> Do not load secret from Ingress spec if provided name is empty

cmd/e2e-test/run.sh
There is no reason not to increase this since goroutines are cheap. Plus, as we add more test cases, we don't want the corresponding goroutine to be completely blocked from starting. This might cause the overall test to take longer than it really should. 
=> Increase number of max goroutines for e2e test from 10 to 100

cmd/echo/app/handlers.go
This is nice to have but will also help in debugging #493 
Verified with following request:
```
$ curl -i -H "Accept-Encoding: gzip" localhost:8080
HTTP/1.1 200 OK
Content-Encoding: gzip
Content-Type: application/json
Date: Tue, 16 Apr 2019 21:33:33 GMT
Content-Length: 10
Warning: Binary output can mess up your terminal. Use "--output -" to tell 
Warning: curl to output it to your terminal anyway, or consider "--output 
Warning: <FILE>" to save to a file.
```
=> Add support for response compression in echoserver

pkg/neg/types/shared/types.go
This is to make it easier for other repo to import this. 
cc: @cadmuxe
=> Add NegReadinessGate in a shared package

pkg/neg/syncers/transaction.go, pkg/neg/syncers/transaction_table.go, pkg/neg/syncers/transaction_table_test.go, pkg/neg/syncers/transaction_test.go, pkg/neg/syncers/utils.go, pkg/neg/syncers/utils_test.go, pkg/neg/types/network_endpoint.go, pkg/neg/types/network_endpoint_test.go
- Introduce a NetworkEndpoint Type to represent the meta information contained in NE.
- Introduce NetworkEndpointSet Type to support fast Get, Insert and DIfference calculation
- Adjust Transaction table to use NetworkEndpoint Type as key
- Adjust Transaction Syncer to use NetworkEndpoint and NetworkEndpointSet Type for internal plumbing. 
- Completely remove use of sets.String type for endpoint calculation.
=> Refactor Transaction NEG syncer to use strong type instead of string

pkg/neg/controller.go, pkg/neg/controller_test.go, pkg/neg/manager.go, pkg/neg/manager_test.go, pkg/neg/readiness/interface.go, pkg/neg/readiness/poller.go, pkg/neg/readiness/reflector.go, pkg/neg/readiness/utils.go, pkg/neg/syncers/batch.go, pkg/neg/syncers/batch_test.go, pkg/neg/syncers/syncer.go, pkg/neg/syncers/syncer_test.go, pkg/neg/syncers/transaction.go, pkg/neg/syncers/transaction_test.go, pkg/neg/syncers/utils.go, pkg/neg/syncers/utils_test.go, pkg/neg/types/types.go, pkg/neg/types/types_test.go
- initial commit of readiness reflector
- the readiness reflector will check if the pods has NEG readiness gate.
- if so, then will poll NEG health status and patch the pod NEG readiness condition when the endpoint became ready. 
- Refactoring: 
- modify common NEG types to accomendate readiness gate
- move NegSyncerKey to pkg/neg/types
- Adapt NEG controller for readiness reflector:
- include non-terminating pods to add in NEG
- This will make sure if a pod is not ready due to the NEG readiness gate will be added into NEG
- adapt NEG controller and Syncer Manager to take readiness gate into account. 
- adapt transaction NEG syncer to feedback into readiness reflector
=> readiness reflector

docs/deploy/resources/rbac.yaml
This is for issue #755. Straightforward fix for the invalid syntax. I tested the script with this change.
Given that the invalid syntax should have prevented anyone from using the script, it is rather concerning. Implies no tests for this. But creating a meaningful test for it is quite non-trivial, so not doing that here.
=> Deploying to GKE self managed has invalid YAML

cmd/e2e-test/main_test.go, cmd/fuzzer/app/validate.go, pkg/e2e/framework.go
(don't need to touch https://github.com/kubernetes/ingress-gce/blob/master/cmd/e2e-test/run.sh#L38-L42 since it can be passed in as an arg)
=> Add option to override gce endpoint in test

cmd/e2e-test/main_test.go, pkg/e2e/framework.go
Unfortunately this flag has to be the same as https://github.com/kubernetes/kubernetes/blob/8765fa2e48974e005ad16e65cb5c3acf5acff17b/staging/src/k8s.io/legacy-cloud-providers/gce/gce.go#L421-L429
=> Parse the gce endpoint flag the same way as k8s

.gitignore, docs/deploy/gke/README.md, docs/deploy/gke/gke-self-managed.sh, docs/deploy/resources/gce.conf, docs/deploy/resources/glbc.yaml
For issue #758.
This does several things to make this setup much easier. But in short, it allows a single command to be used to setup for the vast majority of cases (with just `./gke-self-managed.sh -n CLUSTER_NAME -z ZONE`).
1. The CLI flags are updated to actually work (ie, represent those used by the GLBC now).
2. The gce.conf file is automatically populated from querying the cluster. All options can be instead provided as CLI flags if the querying gets them wrong or to speed things up slightly (the time to query is pretty negligible compared to the time to restart the cluster to turn off the default GLBC, though).
3. The `glbc.yaml` file is automatically setup with the image instead of letting users create an invalid deployment that won't be caught till runtime.
4. The script defaults …
=> Updates for usability of GKE self managed setup script

pkg/loadbalancers/forwarding_rules.go, pkg/loadbalancers/l7.go, pkg/loadbalancers/loadbalancers_test.go, pkg/loadbalancers/target_proxies.go
This is for issue #661.
The description are the [same values as AWS uses in their Ingress](https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/ingress/annotation/#resource-tags).
Unit tests were updated. Can be viewed by creating an ingress and in Cloud Console, go to Network services > Load balancing > advanced view (description column). Note that the cluster name field is probably not the actual cluster name, but does identify the cluster (and instance group, etc).
=> GCP forwarding rule/target proxy description field populated

cmd/glbc/main.go, pkg/flags/flags.go, pkg/neg/controller.go, pkg/neg/controller_test.go
- Turn on readiness reflector by default for now for soaking
- Consider turning it off before release.
=> flag gate readiness reflector

pkg/neg/controller.go, pkg/neg/controller_test.go, pkg/neg/manager.go, pkg/neg/manager_test.go, pkg/neg/readiness/poller_test.go, pkg/neg/readiness/reflector_test.go, pkg/neg/readiness/utils.go, pkg/neg/readiness/utils_test.go, pkg/neg/syncers/batch_test.go, pkg/neg/syncers/retry_handler_test.go, pkg/neg/syncers/transaction_test.go, pkg/neg/syncers/utils.go, pkg/neg/syncers/utils_test.go, pkg/neg/types/types_test.go
- minor bug fixes
- add tons of unit tests.
=> Follow up on Readiness Reflector

pkg/fuzz/gcp.go
(would this work for the unions?)
=> add explicit logs when fail to get a cloud resource

pkg/fuzz/gcp.go
I feel like we can just change all `ForwardingRule` to `GlobalForwardingRule`... but, anyway, let me try to fix test first...
Still unsure why it works for prod though.
```
// Get: Returns the specified GlobalForwardingRule resource. Gets a list
// of available forwarding rules by making a list() request.
// For details, see https://cloud.google.com/compute/docs/reference/latest/globalForwardingRules/get
func (r *GlobalForwardingRulesService) Get(project string, forwardingRule string) *GlobalForwardingRulesGetCall {
c := &GlobalForwardingRulesGetCall{s: r.s, urlParams_: make(gensupport.URLParams)}
c.project = project
c.forwardingRule = forwardingRule
return c
}
```
=> use GlobalForwardingRules().Get() when detected a global fw rule

go.mod, go.sum, pkg/controller/controller_test.go, pkg/loadbalancers/addresses.go, pkg/loadbalancers/fakes.go, pkg/loadbalancers/interfaces.go, pkg/loadbalancers/l7.go, pkg/loadbalancers/l7s.go, pkg/loadbalancers/l7s_test.go, pkg/loadbalancers/loadbalancers_test.go, vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/mock/mock.go, vendor/modules.txt
Reverts kubernetes/ingress-gce#781 as it was not finished yet.
=> Revert "Remove Loadbalancer interface and use k8s-cloud-provider mocks"

pkg/neg/manager.go, pkg/neg/manager_test.go, pkg/neg/readiness/poller_test.go, pkg/neg/types/mock.go
Addressing https://github.com/kubernetes/ingress-gce/pull/774#discussion_r293940618
Unit test coverage up a little bit https://github.com/kubernetes/ingress-gce/pull/774#issuecomment-502868951
```
$ go test -coverprofile=coverage.out ./...
ok  	k8s.io/ingress-gce/pkg/neg	2.463s	coverage: 64.1% of statements
?   	k8s.io/ingress-gce/pkg/neg/metrics	[no test files]
ok  	k8s.io/ingress-gce/pkg/neg/readiness	0.315s	coverage: 73.0% of statements
ok  	k8s.io/ingress-gce/pkg/neg/syncers	2.316s	coverage: 72.2% of statements
ok  	k8s.io/ingress-gce/pkg/neg/types	0.423s	coverage: 28.0% of statements
?   	k8s.io/ingress-gce/pkg/neg/types/shared	[no test files]
```
=> Follow up on #774

pkg/backends/backends.go, pkg/composite/composite.go, pkg/composite/composite_test.go, pkg/composite/gen/main.go, pkg/composite/manual.go, pkg/composite/meta/meta.go, pkg/composite/utils.go, pkg/composite/utils_test.go, pkg/controller/controller.go
- Add SSLCertificate to composites
- Add Delete() and List() to composites
- Add hand generated functions
A follow up PR will be added to rename the files in pkg/composite to be more clear
=> Composite updates for integration

pkg/composite/composite.go, pkg/composite/gen.go, pkg/composite/gen/main.go, pkg/composite/utils.go, pkg/composite/utils_test.go
/assign bowei
blocking https://github.com/kubernetes/ingress-gce/pull/788
=> More composite updates for integration

pkg/utils/utils.go, pkg/utils/utils_test.go
This PR fixes https://github.com/kubernetes/ingress-gce/issues/595.
It searches for a taint with effect NoSchedule on GetNodeConditionPredicate. This way, the Load Balancer Sync can filter out nodes with taints such as ToBeDeletedByClusterAutoscaler. 
Notice that, on [Kubernetes Autoscaler](https://github.com/kubernetes/autoscaler/blob/e7dd38375165997b057967259b0d577ca253eebb/cluster-autoscaler/utils/deletetaint/delete.go#L76), the node is only tainted, it doesn't look like the `node.Spec.Unschedulable` is set anywhere.
=> Added NoSchedule effect to GetNodeConditionPredicate

cmd/glbc/main.go, pkg/backends/backends.go, pkg/backends/features/features.go, pkg/backends/ig_linker.go, pkg/backends/ig_linker_test.go, pkg/backends/interfaces.go, pkg/backends/neg_linker.go, pkg/backends/syncer.go, pkg/backends/syncer_test.go, pkg/composite/gen/main.go, pkg/composite/utils.go, pkg/composite/utils_test.go, pkg/controller/controller.go, pkg/firewalls/controller.go, pkg/firewalls/firewalls.go, pkg/healthchecks/healthchecks.go, pkg/healthchecks/interfaces.go, pkg/loadbalancers/certificates.go, pkg/loadbalancers/features/doc.go, pkg/loadbalancers/features/features.go, pkg/loadbalancers/features/features_test.go, pkg/loadbalancers/forwarding_rules.go, pkg/loadbalancers/interfaces.go, pkg/loadbalancers/l7.go, pkg/loadbalancers/l7s.go, pkg/loadbalancers/loadbalancers_test.go, pkg/loadbalancers/target_proxies.go, pkg/loadbalancers/url_maps.go, pkg/loadbalancers/url_maps_test.go
Just when you thought I couldn't possibly have another XL PR up my sleeves... :eyes: 
Replaces most resources with their composite version to enable L7-ILB and additional work.
Notable exceptions are health checks and firewall rules which will require some more careful changes.  I've tried to use as few constants as possible, but there are still cases where we need to just to default to GA-Global since we don't use any other types yet.
Additionally, basic e2e tests pass but I'll probably run more of them overnight to see if there are any regressions.
blocked by https://github.com/kubernetes/ingress-gce/pull/790
=> Integrate composite types into controller

docs/contrib/cluster-setup.md
The previous instructions were missing the fact that the pod is in the kube-system namespace
=> Update cluster-setup.md with the right instructions for deleting the ingress-gce pod

pkg/e2e/framework.go, pkg/e2e/sandbox.go
Dumps events at the end of each test. Make it easier to debug e2e failure.
=> dump events in sandbox

pkg/e2e/framework.go
Deferred function will be executed after t.Fatal.  https://golang.org/pkg/testing/#B.FailNow
=> make SandboxEventDump a deferred function to avoid being skipped by t.Fatal

docs/deploy/gke/gke-self-managed.sh
As using sed for appending a line doesn't work on macOS, changed to use awk.
```sh
$ sed "/name: http/a \ \ \ \ nodePort: ${NODE_PORT}" ../resources/default-http-backend.yaml
sed: 1: "/name: http/a \ \ \ \ n ...": extra characters after \ at the end of a command
```
=> Get gke-self-managed.sh working on macOS

pkg/backends/integration_test.go, pkg/backends/neg_linker.go, pkg/backends/neg_linker_test.go, pkg/backends/syncer.go, pkg/controller/controller.go
Remove BackendPool downcast by adding a cloud pointer to the neg linker and backend syncer
=> Add cloud pointer to neg linker and backend syncer

pkg/healthchecks/healthchecks.go, pkg/loadbalancers/certificates.go, pkg/loadbalancers/features/features.go, pkg/loadbalancers/features/features_test.go, pkg/loadbalancers/features/l7ilb.go, pkg/loadbalancers/forwarding_rules.go, pkg/loadbalancers/l7.go, pkg/loadbalancers/loadbalancers_test.go, pkg/loadbalancers/target_proxies.go, pkg/loadbalancers/url_maps.go
Features are now defined with structs instead of nested maps
=> Refactor loadbalancer features

pkg/composite/gen.go, pkg/composite/gen/main.go
This will be necessary to use L7-ILB Beta
=> Add beta regional resources to composite

pkg/neg/types/cloudprovideradapter.go
Will send a follow up PR to switch to use meta.scope as key. 
This PR is mostly for simple cherry-pick
=> tolerate non zonal NEG included in the AggregatedList API response

cmd/e2e-test/affinity_test.go, cmd/e2e-test/app_protocols_test.go, cmd/e2e-test/backend_config_test.go, cmd/e2e-test/basic_https_test.go, cmd/e2e-test/basic_test.go, cmd/e2e-test/cdn_test.go, cmd/e2e-test/draining_test.go, cmd/e2e-test/iap_test.go, cmd/e2e-test/security_policy_test.go, cmd/e2e-test/timeout_test.go, cmd/e2e-test/upgrade_test.go, pkg/e2e/fixtures.go, pkg/e2e/framework.go, pkg/e2e/helpers.go, pkg/e2e/legacy.go, pkg/e2e/legacy_test.go, pkg/e2e/sandbox.go, pkg/e2e/status.go
Make the e2e framework use an adapter so it can use both the old (extensions) and new (networking) APIs
=> Legacy api e2e

pkg/neg/types/cloudprovideradapter_test.go, pkg/neg/types/mock.go
=> follow up for #820

pkg/backends/backends.go, pkg/backends/interfaces.go, pkg/backends/syncer.go, pkg/backends/syncer_test.go, pkg/healthchecks/healthchecks.go, pkg/loadbalancers/loadbalancers_test.go
Refactor backends GC so that we don't need ListAllBackendServices() anymore.  That way, if one of the api calls fails, it won't block the others.
=> Refactor Backend GC

cmd/e2e-test/neg_test.go, cmd/echo/app/env.go, pkg/e2e/fixtures.go, pkg/e2e/helpers.go, pkg/fuzz/gcp.go
migrate part of the test from OSS k8s
=> add more neg tests

pkg/e2e/fixtures.go
=> fix a typo

cmd/e2e-test/ilb_test.go, pkg/e2e/helpers.go, pkg/fuzz/features/features.go, pkg/fuzz/features/ilb.go, pkg/fuzz/features/neg.go, pkg/fuzz/helpers.go, pkg/fuzz/validator.go
Replaces #824 
Updates the e2e test framework to have basic support for ILB (e.g. Supports path checking but doesn't support GCE whitebox or GC testing)
A follow up PR will be added to support those things
=> Update e2e framework for ILB - Part 1

pkg/common/operator/ingress.go, pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/controller/types.go, pkg/sync/interfaces.go, pkg/sync/sync.go
Fixes https://github.com/kubernetes/ingress-gce/issues/836
Existing GC workflow deletes instance groups as soon all GCE ingresses are deleted. But, instance groups should be retained as they are shared by multi-cluster ingresses as well.
=> Bugfix: don't GC instance groups while multi-cluster ingresses exist

pkg/firewalls/controller.go, pkg/firewalls/firewalls.go, pkg/firewalls/firewalls_test.go
- Fixes a bug where ILB subnet range is added multiple times
- Fixes a bug where empty ilb subnet is added to firewall
=> De-dupe additional source ranges for firewall

cmd/e2e-test/finalizer_test.go
This fixes a bug with finalizer e2e test. 
The test verifies the old ingress to ensure GCLB, it should be using updated ingress instead.
=> Bugfix: Pass updated ingress for validation

pkg/backends/backends.go
In the first sync for an ingress, this log line usually gets emitted:
```
E0924 13:25:09.946149   83693 l7.go:325] Error syncing backend status for k8s-be-31890--68d8bd3f6b43351f - ga - global: error getting health for backend "k8s-be-31890--68d8bd3f6b43351f": <nil>     
```
Usually shortly after Backends are attached to Backend-Services, there is no health status. Hence result in the log line.
=> split the error message in backend syncer health processing

cmd/e2e-test/main_test.go, cmd/e2e-test/run.sh, pkg/e2e/fixtures.go, pkg/e2e/framework.go
Adds support for creating and deleting ilb subnets to the e2e test framwork
Also adds optional "region" CLI flag to e2e binary which is needed for the subnet
Region will also be necessary for part 2 of the e2e test framework changes
=> e2e test framework add support for ilb subnet

cmd/glbc/app/clients.go
Cherrypick of https://github.com/kubernetes/ingress-gce/pull/847
/assign @bowei @freehan
=> Cherrypick to 1.6 branch: Use protobufs for communication with apiserver

cmd/e2e-test/ilb_test.go
This will ensure that all the tests have an ILB subnet in their region.  Later, we can add tests which delete or migrate the subnet and test that behavior.
=> Add CreateILBSubnet() call to all ilb e2e tests

cmd/e2e-test/ilb_test.go
Change the names of the resources in the ilb e2e tests to make debugging easier
=> Update ILB e2e test resource names

pkg/e2e/helpers.go
Our e2e tests need a longer timeout since we are creating more ingresses.  We should ideally lower this back down a bit later on if we can.
=> Update IngressPollTimeout to 45 minutes

pkg/backends/backends.go
Provides more specific errors in the logs
=> Separate out health check errors for Backends

pkg/e2e/fixtures.go
We should also expect to see 400s when attempting to create the subnet after the first time.
=> Update CreateILBSubnet() to catch 400s as well

pkg/fuzz/whitebox/num_backend_services.go
When there is no default backend set in the Ingress specification, the controller creates a 404 backend service. This was previously not taken into account. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubernetes/ingress-gce/878)
=> Fix backend services whitebox test to take into account the default backend

cmd/e2e-test/ilb_test.go, pkg/fuzz/helpers.go
Set the AllowHttp annotation to false for all L7-ILB HTTPS e2e tests since allowing both
HTTP and HTTPS on the same VIP is not currently supported.
=> Disable Http on ILB Https e2e tests

cmd/e2e-test/ilb_test.go
Accidentally left this out of #871 
Without this change, the basic tests fail since the service name is incorrect
=> Fix basic ilb test service name

pkg/controller/controller.go, pkg/neg/controller.go, pkg/utils/namer/utils.go, pkg/utils/utils.go
Fixes https://github.com/kubernetes/ingress-gce/issues/879
=> BugFix: Update ingress key function used for GC

cmd/e2e-test/ilb_test.go
Another bug from #871 :frowning_face: 
The update tests need to use the same same for the ingresses.
=> Fix Ingress names for ILB e2e update test

pkg/composite/gen.go, pkg/composite/gen/main.go, pkg/composite/gen_test.go, pkg/composite/meta/meta.go
Current usecase is for using NetworkEndpointGroups.
=> Add support for composite types for zonal resources

docs/deploy/gke/csm/default-http-backend.yaml, docs/deploy/resources/default-http-backend.yaml
user space default backend service.
With this annotation, the backend service will be deleted if created with kubectl apply -f
=> remove "addonmanager.kubernetes.io/mode: Reconcile" annotation from

pkg/backends/backends.go, pkg/backends/ig_linker.go, pkg/backends/ig_linker_test.go, pkg/backends/integration_test.go, pkg/backends/neg_linker.go, pkg/backends/neg_linker_test.go, pkg/backends/syncer.go, pkg/backends/syncer_test.go, pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/controller/translator/translator.go, pkg/controller/translator/translator_test.go, pkg/firewalls/controller.go, pkg/healthchecks/healthchecks.go, pkg/healthchecks/healthchecks_test.go, pkg/instances/instances.go, pkg/loadbalancers/loadbalancers_test.go, pkg/loadbalancers/url_maps.go, pkg/loadbalancers/url_maps_test.go, pkg/utils/namer/interfaces.go, pkg/utils/serviceport.go
This is part 2 of V2 Namer Migration:https://github.com/kubernetes/ingress-gce/issues/858 .
This does not change naming policy for backend resources. A light weight back-end namer interface is stubbed into each service port to retrieve back-end resource names. The current workflow passes in namer object to retrieve backend resources. This is not required anymore with new workflow.
=> Cleanup backend namer workflow

cmd/e2e-test/main_test.go, pkg/e2e/fixtures.go, pkg/e2e/framework.go
We need this to create the ILB subnet in the right network
=> Add -network flag to e2e test framework for ILB subnet creation

pkg/loadbalancers/features/l7ilb.go
Previously, we might accidentally pick a subnet in another VPC
I'm working on unit testing this in another branch. fakeGCE doesn't have a networkURL which makes testing this potentially more complicated.
This will need to be cherry-picked into release-1.7
=> Fix ILB subnet discovery to check for VPC as well

cmd/e2e-test/ilb_test.go
@skmatti discovered that some of our ingress test names + sandbox name exceed the GC leak limit.  Shortening the names here to avoid resource leaking.
=> Shorten ILB e2e ingress names to less than 20 characters to avoid leaks

cmd/e2e-test/ilb_test.go
Turns out our beautifully crafted names are still too long.  We have a total of 40 characters for namespace + name and the sandbox takes up 30 of those.  Now I understand why everything else is called "ingress-1" 
:grin: 
=> Shorten all ILB e2e ingress test names again since we actually only have 10 characters

pkg/controller/controller.go
Cherry pick #881 [BugFix: Update ingress key function used for GC] into release-1.7
=> Cherry pick #881 into 1.7

pkg/neg/controller.go
Fixing the NEG creation slowness for default-backend. 
cc: @spencerhance
=> enqueue default backend for NEG processing

go.mod
cmp module is used in tests for comparing two go types.
=> Add go-cmp to dependencies 

pkg/loadbalancers/features/l7ilb.go, pkg/loadbalancers/forwarding_rules.go
Adds cluster subnet to l7 ilb forwarding rule when the cluster network is in
custom mode
=> Fix ILB forwarding rule bug

pkg/loadbalancers/features/l7ilb.go, pkg/loadbalancers/forwarding_rules.go
=> Cherry Pick #906 (Fix ILB forwarding rule bug) to release-1.7

pkg/e2e/helpers.go, pkg/fuzz/features/neg.go, pkg/fuzz/validator.go, pkg/fuzz/validator_test.go
Previously, region was hardcoded to us-central1
=> Plumb region to neg validator for e2e testing

pkg/loadbalancers/l7.go, pkg/loadbalancers/loadbalancers_test.go
Create a WillNotConfigureFrontend event warning the user if they set up an internal https ingress without the allow-http annotation set to false, since that functionality is currently not supported.
=> Check for invalid L7-ILB HTTPS configuration

cmd/e2e-test/affinity_test.go
We are sometimes hitting this timeout, bumping it up to avoid flakes
=> Bump TestAffinity transition timeout from 5 to 10 minutes

pkg/controller/controller.go
Handle cache.DeletedFinalStateUnknown in backend/frontend config delete event handlers
Currently, we just panic since the interface conversion fails.
=> Handle cache.DeletedFinalStateUnknown

pkg/controller/controller.go
=> Cherry pick #912 [Handle cache.DeletedFinalStateUnknown] to release-1.7

pkg/flags/flags.go, pkg/neg/manager.go, pkg/neg/manager_test.go, pkg/neg/syncers/transaction.go, pkg/neg/syncers/transaction_test.go, pkg/neg/syncers/utils.go, pkg/neg/syncers/utils_test.go, pkg/neg/types/types.go
With '--enable-non-gcp-mode', NEG controller will create NEGs of type NON_GCP_PRIVATE_IP_PORT instead of GCE_VM_IP_PORT.
=> Add a flag for Non-GCP mode NEG controller.

pkg/neg/manager.go, pkg/neg/manager_test.go, pkg/neg/syncers/transaction.go, pkg/neg/syncers/transaction_test.go, pkg/neg/syncers/utils_test.go, pkg/neg/types/types.go
follow up of https://github.com/kubernetes/ingress-gce/pull/920
=> move neg type into syncerKey

pkg/composite/gen.go, pkg/composite/gen/main.go, pkg/composite/gen_test.go, pkg/composite/meta/meta.go
Existing neg utils require ListNetworkEndpoints and AggregatedListNetworkEndpointGroup. This PR adds those 2 methods to composite types.
=> Support more methods in composite NEGs.

pkg/loadbalancers/features/l7ilb.go, pkg/loadbalancers/forwarding_rules.go
Use network and subnetwork fields for l7-ilb all forwarding rules
instead of only custom-mode networks.  It turns out that the GCE API assumes the default network when no network or subnet is provided.
This also saves us from having to do a network lookup from the GCE API. (cc: @bowei)
=> Update forwarding rule logic for l7-ilb

pkg/neg/syncers/transaction.go, pkg/neg/syncers/transaction_table.go, pkg/neg/syncers/transaction_table_test.go, pkg/neg/syncers/transaction_test.go
This PR removes the reconciliation for transactions since it is no longer needed. 
Before, transaction syncer only triggers resync if any transaction requires reconciliation.
However, after some change, transaction syncer ALWAYS triggers resync. Hence, reconciliation handling is no longer needed. https://github.com/kubernetes/ingress-gce/blob/release-1.7/pkg/neg/syncers/transaction.go#L320
=> remove transaction syncer reconciliation

pkg/neg/controller.go, pkg/neg/controller_test.go, pkg/neg/manager.go, pkg/neg/manager_test.go, pkg/neg/readiness/poller_test.go, pkg/neg/readiness/utils_test.go, pkg/neg/syncers/syncer_test.go, pkg/neg/syncers/transaction.go, pkg/neg/syncers/transaction_test.go, pkg/neg/syncers/utils.go, pkg/neg/syncers/utils_test.go, pkg/neg/types/types.go, pkg/neg/types/types_test.go, pkg/neg/utils.go, pkg/neg/utils_test.go
Fixes: #832 
- Introduce Port Tuple for service port
- Refactor NegSyncerKey to include portTuple
- Use service port name to retrieve wanted endpoints instead of target port. 
- adjust all existing unit test to work with it
=> NEG Namedport Fix

pkg/backends/interfaces.go, pkg/backends/neg_linker.go, pkg/backends/neg_linker_test.go, pkg/composite/gen.go, pkg/composite/gen/main.go, pkg/neg/manager.go, pkg/neg/manager_test.go, pkg/neg/readiness/poller.go, pkg/neg/readiness/poller_test.go, pkg/neg/syncers/transaction.go, pkg/neg/syncers/transaction_test.go, pkg/neg/syncers/utils.go, pkg/neg/syncers/utils_test.go, pkg/neg/types/cloudprovideradapter.go, pkg/neg/types/cloudprovideradapter_test.go, pkg/neg/types/fakes.go, pkg/neg/types/interfaces.go, pkg/neg/types/mock.go, pkg/neg/types/types.go, pkg/utils/serviceport.go
Verified that the existing NEG creation/endpoint add works.
=> Modify NEG libraries to use composite types.

cmd/glbc/main.go, docs/deploy/resources/configmap-based-config.yaml, pkg/cmconfig/config.go, pkg/cmconfig/config_test.go, pkg/cmconfig/controller.go, pkg/cmconfig/controller_test.go, pkg/context/context.go, pkg/controller/controller_test.go, pkg/controller/translator/translator_test.go, pkg/firewalls/controller_test.go, pkg/flags/flags.go, pkg/neg/controller.go, pkg/neg/controller_test.go, pkg/neg/manager.go, pkg/neg/manager_test.go, pkg/neg/readiness/reflector_test.go, pkg/neg/syncers/syncer_test.go, pkg/neg/syncers/transaction_test.go, pkg/neg/syncers/utils.go
Reviewed in https://github.com/kubernetes/ingress-gce/pull/928
=> add configmap based config

pkg/neg/controller.go, pkg/neg/controller_test.go
This bus would be triggered in the following scenario:
Service A has the following 2 ports:
Port1 has name="80" and port=9999
Port2 has name="foo" and port=80
Ingress B references Service A with port name "80". Ingress controller picks port 9999, while NEG controller pickes port 80.
This PR makes NEG controller follow the same processing util for service references.
=> Fix a bug in NEG controller namedport handling

pkg/annotations/ingress.go, pkg/flags/flags.go, pkg/loadbalancers/addresses.go, pkg/loadbalancers/l7.go, pkg/loadbalancers/l7s_test.go, pkg/loadbalancers/loadbalancers_test.go
Fixes: https://github.com/kubernetes/ingress-gce/issues/32, https://github.com/kubernetes/ingress-gce/issues/465, https://github.com/kubernetes/ingress-gce/issues/764
/assign @bowei @freehan 
The Ensure workflow of Loadbalancer pool is modified in order to delete unused GCE resources.
This looks at user specified ingress options/annotations to determine if we need to delete specific frontend resources. 
- AllowHTTP is set to false:
if existing ingress annotations has http resources, then those will be deleted.
- SSL is not configured:
if existing ingress annotations has https resources, then those will be deleted.
- If User specifies an IP:
We try to delete Ingress managed static IP if exists. This is performed only when both http and https are enabled.
Note that the existing behavior of …
=> Bugfix: Delete unused GCE load-balancer resources on ingress spec change

pkg/neg/controller.go, pkg/neg/readiness/poller.go, pkg/neg/readiness/poller_test.go, pkg/neg/readiness/reflector.go, pkg/neg/readiness/reflector_test.go, pkg/neg/types/mock.go
Enable Pod Readiness Gate for Standalone NEG
=> enable readiness reflector for Standalone NEG

cmd/e2e-test/affinity_test.go, cmd/e2e-test/app_protocols_test.go, cmd/e2e-test/basic_https_test.go, cmd/e2e-test/basic_test.go, cmd/e2e-test/cdn_test.go, cmd/e2e-test/customrequestheaders_test.go, cmd/e2e-test/draining_test.go, cmd/e2e-test/finalizer_test.go, cmd/e2e-test/iap_test.go, cmd/e2e-test/ilb_test.go, cmd/e2e-test/neg_test.go, cmd/e2e-test/security_policy_test.go, cmd/e2e-test/timeout_test.go, cmd/e2e-test/upgrade_test.go, cmd/fuzzer/app/validate.go, pkg/fuzz/feature.go, pkg/fuzz/gcp.go
Add support for regional resources to gcp.go with minimal changes to the existing fuzzer logic
This allows for whitebox and GC testing of l7-ilb
=> Update e2e framework for ILB - Part 2

cmd/glbc/main.go, pkg/context/context.go, pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/controller/translator/translator_test.go, pkg/firewalls/controller_test.go, pkg/flags/flags.go, pkg/loadbalancers/interfaces.go, pkg/loadbalancers/l7s.go, pkg/loadbalancers/l7s_test.go, pkg/loadbalancers/loadbalancers_test.go, pkg/loadbalancers/url_maps_test.go, pkg/neg/controller_test.go, pkg/neg/manager_test.go, pkg/neg/readiness/reflector_test.go, pkg/neg/syncers/syncer_test.go, pkg/neg/syncers/transaction_test.go, pkg/sync/interfaces.go, pkg/sync/sync.go, pkg/test/utils.go, pkg/utils/common/common.go, pkg/utils/common/finalizer.go, pkg/utils/namer/frontendnamer.go, pkg/utils/namer/frontendnamer_test.go, pkg/utils/namer/utils.go, pkg/utils/namer/utils_test.go, pkg/utils/utils.go, pkg/utils/utils_test.go
This part4 of V2 Namer Migration: https://github.com/kubernetes/ingress-gce/issues/858. 
Fixes: https://github.com/kubernetes/ingress-gce/issues/537
This PR introduces a new naming scheme for for the following frontend resources:
- Forwarding Rule
- Target Proxy
- URL Map
- SSL Certificates
- Ingress managed Static IP
This should resolve frontend resource naming collision issues. 
The changes made in v2 naming scheme:
- New naming scheme:
`k8s{version-id}-{resource-prefix}-{kube-system-uid}-{namespace}-{name}-{8-char-hash}`
Example http target proxy: `k8s2-tp-ksuid123-namespace-name-wddys49o`
- Resource names will include an 8 character kube-system uid instead of cluster uid. This makes the new naming policy immune to config map(which tracks cluster uid) changes.
Frontend  GC workflow …
=> Add V2 frontend namer

cmd/glbc/main.go, pkg/controller/controller.go, pkg/sync/sync.go, pkg/utils/common/finalizer.go
This fixes the following two things
- Naming scheme on Ingress Creation
When controller ensures a finalizer for a new ingress being created, the load-balancer pool requires ingress latest finalizer annotation for creating ingress frontend resources based on corresponding naming scheme. This fix makes sure that finalizer annotation is updated before passing the ingress for sync.
- Kube-system UID needs to populated for all cases
Imagine a case where an ingress is created using v2 naming scheme and ingress controller is restarted with `--enable-v2-frontend-namer` disabled. We expect the ingress controller handle existing ingresses with v2 namer properly. We need kube-system uid to retrieve/delete load-balancer frontend resources in this case.
=> Fix naming scheme on creation

pkg/loadbalancers/l7.go, pkg/loadbalancers/loadbalancers_test.go
Refer: https://github.com/kubernetes/ingress-gce/pull/905#discussion_r348098467
=> Error out on invalid ingress frontend configuration

pkg/loadbalancers/l7.go, pkg/loadbalancers/loadbalancers_test.go
Cherrypick https://github.com/kubernetes/ingress-gce/pull/950 [Error out on invalid ingress frontend configuration] into v1.8.0
=> Cherrypick #950 into release 1.8

cmd/e2e-test/basic_test.go, pkg/e2e/fixtures.go, pkg/e2e/helpers.go, pkg/fuzz/gcp.go, pkg/fuzz/helpers.go, pkg/fuzz/whitebox/num_target_proxies.go, pkg/fuzz/whitebox/whitebox_tests.go
This adds tests for https://github.com/kubernetes/ingress-gce/pull/894. This test asserts that frontend resources existence is in agreement with user specified ingress configuration.
=> Add e2e tests for frontend resource leak fix

cmd/e2e-test/basic_https_test.go, cmd/e2e-test/basic_test.go, cmd/e2e-test/finalizer_test.go, cmd/e2e-test/neg_test.go, cmd/e2e-test/upgrade/basic_http.go, cmd/e2e-test/upgrade/neg.go, cmd/e2e-test/upgrade_test.go, pkg/e2e/helpers.go, pkg/e2e/interfaces.go
/assign @rramkumar1 @MrHohn 
cc: @freehan
=> Migrate upgrade tests to use the upgrade framework

cmd/e2e-test/finalizer_test.go, cmd/e2e-test/upgrade/finalizer.go, pkg/e2e/helpers.go
After adding new finalizer (V2 Finalizer), update finalizer upgrade tests to validate against either of v1 or v2 finalizers.
=> Update finalizer tests to validate against an ingress finalizer

pkg/composite/gen.go, pkg/composite/gen_test.go, pkg/composite/meta/meta.go, pkg/neg/readiness/poller_test.go, pkg/neg/syncers/transaction_test.go, pkg/neg/syncers/utils_test.go, pkg/neg/types/mock.go
This enables creation of NEGs in unit tests using Alpha or GA api. The transactions test has been modified to create both VM_IP_PORT as well as PRIMARY_VM_IP negs.
=> Add NEG mocks for alpha API and a new transactions test

cmd/glbc/app/init.go, pkg/context/context.go
Fixes a bug where we create a neg for the default backend with the wrong port
cc @freehan 
=> Fix default backend port bug for ilb neg

pkg/controller/controller.go
The existing flow panics when GC fails on `nil` ingress as we try to retrieve ingress namespace for emitting an event. 
=> Emit events only for non-nil ingresses

cmd/e2e-test/ilb_test.go, cmd/e2e-test/main_test.go, pkg/e2e/fixtures.go, pkg/e2e/framework.go
Now used in addition to -network since all ilb tests will need -network
for GCLBForVIP()
=> Add createIlbSubnet flag to ilb e2e tests

cmd/e2e-test/main_test.go, cmd/e2e-test/run.sh
Parse the network name from the metadata server and pass it along to e2e tests
blocked by #970 
/hold
=> e2e test run.sh add network

cmd/e2e-test/ilb_test.go, cmd/e2e-test/run.sh, pkg/fuzz/gcp.go
Fixes a bug where the ilb e2e test helper function may confuse multiple forwarding rules
from different VPCs with the same VIP
Will require another PR first to add the network flag to internal tests
/hold 
Blocked by #971
=> RegionalGCLBForVIP() Fix

docs/faq/README.md
Signed-off-by: Dominic Yin yindongchao@inspur.com
The folder structure of `test/e2e/framework` has changed since this PR (https://github.com/kubernetes/kubernetes/issues/66649), and `ingress_utils.go` was moved to `ingress/ingress_utils.go`
=> fix broken link

pkg/utils/namer/namer.go
We are using {prefix}{version}-{clusterid}-{namespace}-{name}-{service port}-{destination rule subset}-{hash}
as the NEG name for ASM NEGs. This is using one more hypen connector
compared to {prefix}{version}-{clusterid}-{namespace}-{name}-{service
port}-{hash}.
=> Fix the TrimField max length for ASM NEG name.

go.mod, go.sum, vendor/modules.txt
The change in https://github.com/kubernetes/ingress-gce/pull/975/commits/7550fb74e5efb00d05c6041556b3c34ea50c770c updated the dependency version, but did not update the timestamp.
The correct version was pulled in and build succeeded, but subsequent "go mod vendor" fails with timestamp mismatch error. This change fixes that error.
=> Fix timestamp of legacy-cloud-providers dependency

pkg/context/context.go, pkg/controller/controller.go, pkg/metrics/features.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, pkg/metrics/types.go
This exports the following ingress related usage metrics at a periodic interval(currently set to 10 mins),
1. Count of ingresses for each feature.
2. Count of service-port pairs for each feature.
=> Add Ingress usage metrics

pkg/fuzz/gcp.go
=> Skip checking delete for default NEG

pkg/metrics/features.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, pkg/metrics/types.go, pkg/neg/controller.go
=> add neg usage metrics

pkg/composite/gen.go, pkg/composite/gen/main.go
The existing change calls the global API in the GA version, this change adds a check and calls the Regional API if the Regional Key is specified.
@spencerhance
=> Use the Regional Service API in composite types

pkg/loadbalancers/forwarding_rules.go
=> Cherrypick #994[Use Static IP to create forwarding rule when available] into release 1.8

cmd/e2e-test/asm_test.go, cmd/e2e-test/main_test.go, cmd/e2e-test/neg_test.go, cmd/e2e-test/upgrade/neg.go, pkg/e2e/fixtures.go, pkg/e2e/framework.go, pkg/e2e/helpers.go
The e2e tests will test the configmap based asm mode on/off logic and
the DestinationRule/Serivce NEG creation logic in the asm mode.
=> Add e2e tests for NEG asm mode.

cmd/glbc/main.go, pkg/annotations/service.go, pkg/flags/flags.go, pkg/neg/controller.go, pkg/neg/controller_test.go, pkg/neg/manager.go, pkg/neg/manager_test.go, pkg/neg/syncers/endpoints_calculator.go, pkg/neg/syncers/endpoints_calculator_test.go, pkg/neg/syncers/subsets.go, pkg/neg/syncers/subsets_test.go, pkg/neg/syncers/transaction.go, pkg/neg/syncers/transaction_test.go, pkg/neg/types/fakes.go, pkg/neg/types/interfaces.go, pkg/neg/types/network_endpoint.go, pkg/neg/types/types.go, pkg/neg/types/types_test.go, pkg/utils/common/finalizer.go, pkg/utils/namer/namer.go, pkg/utils/serviceport.go, pkg/utils/utils.go, pkg/utils/utils_test.go, vendor/k8s.io/kubernetes/pkg/util/node/BUILD, vendor/k8s.io/kubernetes/pkg/util/node/node.go, vendor/modules.txt
This change adds support in transaction syncer to create GCE_VM_PRIMARY_IP NEGs.
The neg controller has 2 new flags - one for  watching ingress and one for services.
LoadBalancer services will be processed only if the second flag is enabled. This is disabled by default and can be enabled by adding "ILBSubsets" Alpha feature gate.
/assign @freehan @bowei
=> Support creation of GCE_VM_PRIMARY_IP NEGs for L4 ILB Services.

cmd/e2e-test/basic_test.go
Extends existing e2e test to cover bug: https://github.com/kubernetes/ingress-gce/issues/993
=> Make frontend resource deletion test verify that ingress VIP is unchanged 

pkg/backends/syncer.go, pkg/healthchecks/healthchecks.go
This does the following,
1. Removes the code block that is never reached, because the case is handled in upstream. 
2. Ignore 'resource being used by' error on healthcheck deletion because the associated backend service still uses it.
=> Ignore 'resource being used by' error

cmd/glbc/main.go, pkg/backends/integration_test.go, pkg/backends/syncer_test.go, pkg/context/context.go, pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/controller/translator/translator_test.go, pkg/healthchecks/healthchecks.go, pkg/healthchecks/healthchecks_test.go
All uses of this parameter come from the default flag value.
This reduces the surface area of the health checker.
=> Remove `DefaultBackendHealthCheckPath` as a parameter

pkg/neg/syncers/endpoints_calculator.go, pkg/neg/syncers/endpoints_calculator_test.go, pkg/neg/syncers/subsets.go, pkg/neg/syncers/subsets_test.go
The current logic for subsetting picks atmost (limit/numZones) number of nodes per zone. If some zones have a large number of nodes and other zones have only couple of nodes, the total endpoint size will be less than the desired limit, even when it is possible to pick upto the limit.
This PR fixes the behavior to select as many nodes as possible in all cases.
=> Handle zones with non-uniform node count in L4 ILB Subsetting

pkg/metrics/metrics.go
prometheus-to-sd requires the labels to named in snake case format.
=> Make metrics label Snake case compliant 

cmd/e2e-test/basic_test.go, pkg/e2e/fixtures.go
added test case TestBasicWindows that tests basic ingress for windows sever
=> added test case TestBasicWindows

pkg/context/context.go, pkg/controller/controller.go, pkg/metrics/features.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, pkg/metrics/types.go, pkg/neg/controller.go
=> Cherrypick #976, #984, #990 and #1012 [Ingress Usage metrics] into release 1.8

pkg/backends/syncer.go, pkg/healthchecks/healthchecks.go, pkg/healthchecks/healthchecks_test.go, pkg/healthchecks/interfaces.go
- Remove unused variable isLegacy
- Sync is now package private
- SyncServicePort encapsulates Sync and Probe override logic
- applyProbeSettingsToHC is now package private
=> Reduce surface area of healthchecks

pkg/loadbalancers/loadbalancers_test.go, pkg/loadbalancers/target_proxies.go, pkg/utils/utils.go
This is the main feature PR for SslPolicies
This relies on a few other PRs, but can be reviewed in parallel
=> Implement SslPolicies for TargetHttpsProxy

go.sum, pkg/apis/backendconfig/v1/types.go, pkg/apis/backendconfig/v1/zz_generated.openapi.go, pkg/apis/backendconfig/v1beta1/types.go, pkg/apis/backendconfig/v1beta1/zz_generated.openapi.go, pkg/healthchecks/healthchecks.go, pkg/healthchecks/healthchecks_test.go, pkg/utils/utils.go, pkg/utils/utils_test.go
```
Take healthcheck configuration overrides from the backendconfig
This enables taking the healthcheck configuration from a backendconfig
associated with the given Service.
As part of this PR, we also clean up the override handling to be easier
to understand where the settings come from.
For a given ServicePort `sp` and its associated healthcheck `hc`:
1. `sp` has some default settings depending on its type (e.g. IG, NEG, ILB).
2. SyncServicePort() will override those settings if the Probe exists.
Path, Host, TimeoutSec, CheckIntervalSec.
3. We then sync with what exists in GCE:
3.1 If the healthcheck is does not exist, it will be CREATED.
3.1.1 If it has a backendconfig, then the following settings are used:
CheckIntervalSec, TimeoutSec, HealthyThreshold,
UnhealthyThreshold, Type, …
```
=> Set healthcheck from BackendConfig

pkg/backends/backends.go
GCE API is updated to a version with `LogConfig` field available in https://github.com/kubernetes/ingress-gce/pull/1033. The change will be in a different PR.
=> Enable Access Logs by default

pkg/healthchecks/healthcheck.go, pkg/healthchecks/healthchecks.go
- Adds some pretty printing to the backendconfig hc options
/assign @rramkumar1 @spencerhance @freehan
=> Split large file healthchecks.go => healthcheck.go,healthchecks.go

cmd/e2e-test/asm_test.go, pkg/cmconfig/config.go, pkg/cmconfig/config_test.go, pkg/cmconfig/controller.go, pkg/cmconfig/controller_test.go, pkg/context/context.go, pkg/e2e/helpers.go
Have done e2e tests for this change.
bin/amd64/e2e-test -run -project PROJECT -region us-central1  -v 2 -logtostderr -test.run=TestNoIstioASM -network default
bin/amd64/e2e-test -run -project PROJECT -region us-central1  -v 2 -logtostderr -test.run=TestASM -network default
=> Add asm-ready as the status signal of asm mode.

pkg/l4/l4controller.go, pkg/loadbalancers/l4.go, pkg/loadbalancers/l4_test.go, pkg/metrics/features.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, pkg/metrics/types.go, pkg/neg/controller.go
=> Add L4 ILB usage metrics

cmd/glbc/app/clients.go, pkg/controller/controller.go
Fixes https://github.com/kubernetes/ingress-gce/issues/1049
=> Revert #849[Use protobufs for communication with apiserver] in v1.6

cmd/glbc/app/clients.go, cmd/glbc/main.go, pkg/controller/controller.go
Fixes https://github.com/kubernetes/ingress-gce/issues/1049
=> Fix kube-config for CRD informers

cmd/glbc/app/clients.go, cmd/glbc/main.go, pkg/controller/controller.go
https://github.com/kubernetes/ingress-gce/issues/1049
=> Cherrypick #1051[Fix kube-config for CRD informers] into release-1.9

pkg/firewalls/controller.go, pkg/firewalls/firewalls.go, pkg/firewalls/firewalls_test.go
=> Fix error message emitted during firewall create/update when using XPN.

pkg/healthchecks/healthchecks.go, pkg/healthchecks/healthchecks_test.go
Return after deleting regional health-checks and not try to delete global health checks.
Results in the following error and the ILB gets re-queued,
```
I0325 09:31:12.089142       1 healthchecks.go:310] Deleting health check k8s1-0cf92254-test-sandbox-7ca3ebc1bfe2ffbd-svc-1-80-54141625
E0325 09:31:12.308709       1 taskqueue.go:62] Requeuing "test-sandbox-7ca3ebc1bfe2ffbd/ing1-1" due to error: error running backend garbage collection routine: error GCing regional Backends: googleapi: Error 404: The resource 'projects/gke-test-ingress-11/global/healthChecks/k8s1-0cf92254-test-sandbox-7ca3ebc1bfe2ffbd-svc-1-80-54141625' was not found, notFound (ingresses)
```
Also, ignore health-check not found errors.
=> Handle health-check not found error gracefully

cmd/e2e-test/affinity_beta_test.go, cmd/e2e-test/affinity_test.go, cmd/e2e-test/app_protocols_test.go, cmd/e2e-test/backend_config_test.go, cmd/e2e-test/basic_https_test.go, cmd/e2e-test/basic_test.go, cmd/e2e-test/cdn_test.go, cmd/e2e-test/customrequestheaders_test.go, cmd/e2e-test/draining_test.go, cmd/e2e-test/finalizer_test.go, cmd/e2e-test/iap_test.go, cmd/e2e-test/security_policy_test.go, cmd/e2e-test/timeout_test.go, cmd/e2e-test/upgrade/basic_http.go, cmd/e2e-test/upgrade/finalizer.go, cmd/e2e-test/upgrade/v2frontendnamer.go, cmd/e2e-test/v2frontendnamer_test.go, pkg/e2e/adapter/beconfig.go, pkg/e2e/adapter/beconfig_test.go, pkg/e2e/adapter/ingress.go, pkg/e2e/adapter/ingress_test.go, pkg/e2e/fixtures.go, pkg/e2e/helpers.go, pkg/fuzz/default_validator_env.go, pkg/fuzz/helpers.go, pkg/fuzz/validator.go, pkg/test/utils.go
- Existing e2e tests are migrated to use backendconfig v1
- one e2e test for backendconfig v1beta1 API is added
=> Use backendconfig v1 for e2e tests

pkg/backends/backends.go
Both options work for basic routing, but we should migrate to INTERNAL_MANAGED to support advanced routing rules (https://github.com/kubernetes/ingress-gce/issues/1059)
=> Update BackendConfig LoadBalancingScheme for L7-ILB to INTERNAL_MANAGED

cmd/glbc/main.go, pkg/neg/syncers/endpoints_calculator.go, pkg/neg/types/simple_zone_getter.go, pkg/neg/types/simple_zone_getter_test.go
This is for NonGCP where node label of fault domains may not be present.
=> Allow local zone override for NonGCP NEG

pkg/apis/frontendconfig/v1beta1/types.go, pkg/apis/frontendconfig/v1beta1/zz_generated.openapi.go
This matches the same behavior of the BackendConfig CRD
This will also need to be cherry picked into v1.9
/assign @bowei
=> Update FrontendConfig v1beta1 API so that Spec and Status fields are optional

pkg/backends/features/features.go, pkg/backends/syncer_test.go, pkg/l4/l4controller_test.go, pkg/loadbalancers/l4.go, pkg/loadbalancers/l4_test.go, pkg/metrics/features.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, pkg/metrics/types.go, pkg/neg/controller.go, pkg/neg/controller_test.go, pkg/neg/manager.go, pkg/neg/manager_test.go, pkg/neg/syncers/endpoints_calculator.go, pkg/neg/syncers/endpoints_calculator_test.go, pkg/neg/syncers/transaction.go, pkg/neg/syncers/transaction_test.go, pkg/neg/syncers/utils_test.go, pkg/neg/types/interfaces.go, pkg/neg/types/types.go, pkg/neg/types/types_test.go, pkg/utils/namer/interfaces.go, pkg/utils/namer/namer.go, pkg/utils/serviceport.go
This is the new name for the L4 ILB NEG. This PR modifies the NegType as well as names of various functions to reflect the new name.
Also modified the feature name/label value for metrics since we have not pushed any metric for this new type of NEG yet.
@skmatti 
=> Replace GCE_PRIMARY_VM_IP to GCE_VM_IP NEG.

pkg/loadbalancers/addresses.go, pkg/loadbalancers/forwarding_rules.go, pkg/loadbalancers/loadbalancers_test.go
The current behavior is to create a different staticIP and use that in the forwarding rule. Once the user-specified ip becomes available, the forwarding rule ip will flip to using that, causing some downtime.
With this change, ingress creation will fail and retry until the user-specified IP has been created out of band.
@spencerhance
=> Fail ingress creation if specified staticIP name does not exist

pkg/controller/node.go, pkg/instances/instances.go
There can be a race condition where the queue somehow triggers
before the caches are able to sync.
Improve logging around the event for better debugging in the future.
=> Wait for caches to sync before running node sync

cmd/e2e-test/healthcheck_test.go, pkg/apis/backendconfig/v1/types.go, pkg/healthchecks/healthcheck.go, pkg/healthchecks/healthchecks.go, pkg/healthchecks/healthchecks_test.go
Wires in support to override the Port of a HealthCheck via BackendConfig.
This also forces the PortSpecification to be "USE_FIXED_PORT" regardless
of what type the health check is (e.g. neg, ilb etc.)
=> Add support for Port to BackendConfig HealthCheckConfig

pkg/backends/features/features.go, pkg/backends/syncer_test.go, pkg/l4/l4controller_test.go, pkg/loadbalancers/l4.go, pkg/loadbalancers/l4_test.go, pkg/metrics/features.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, pkg/metrics/types.go, pkg/neg/controller.go, pkg/neg/controller_test.go, pkg/neg/manager.go, pkg/neg/manager_test.go, pkg/neg/syncers/endpoints_calculator.go, pkg/neg/syncers/endpoints_calculator_test.go, pkg/neg/syncers/transaction.go, pkg/neg/syncers/transaction_test.go, pkg/neg/syncers/utils_test.go, pkg/neg/types/interfaces.go, pkg/neg/types/types.go, pkg/neg/types/types_test.go, pkg/utils/namer/interfaces.go, pkg/utils/namer/namer.go, pkg/utils/serviceport.go
Cherrypick of https://github.com/kubernetes/ingress-gce/pull/1090
This replaces GCE_PRIMARY_VM_IP to GCE_VM_IP NEG.
That is the new name for the L4 ILB NEG.
=> Cherrypick PR 1090 to release-1.9

hack/run-local-glbc.sh, hack/setup-local.sh
hack/run-local-e2e.sh will setup your environment and
write some scripts to help run e2e tests from a locally built
binary.
Usage
$ ./hack/run-local-e2e.sh my-cluster
...
$ bash /tmp/run-glbc.sh # run proxy and controller
=> Script to run local e2e test

pkg/apis/backendconfig/v1/types.go, pkg/healthchecks/healthcheck.go, pkg/healthchecks/healthchecks.go, pkg/healthchecks/healthchecks_test.go
#1092 
[Wire in support to override the Port of a HealthCheck via BackendConfig.
This also forces the PortSpecification to be "USE_FIXED_PORT" regardless
of what type the health check is (e.g. neg, ilb etc.)]
=> Cherry-Pick #1092 [Add support for Port to BackendConfig HealthCheckConfig] to release-1.9

pkg/backends/features/logging.go, pkg/composite/gen.go, pkg/composite/gen/main.go
=> Force send Enable field for LogConfig

pkg/loadbalancers/addresses.go, pkg/loadbalancers/forwarding_rules.go, pkg/loadbalancers/loadbalancers_test.go
Original PR - https://github.com/kubernetes/ingress-gce/pull/1080
This change will now error out ingress creation if the specified staticIP name does not exist.
/assign @bowei
=> Cherrypick PR 1080 into release-1.9

docs/deploy/resources/rbac.yaml, hack/update-codegen.sh
This will need to be cherry-picked into release-1.9 asap
Tested the rbac config in a sandbox
=> Add rbac permissions for networking.gke.io/frontendconfigs

docs/deploy/resources/rbac.yaml, hack/update-codegen.sh
=> Cherry-pick #1128 to release-1.9 [Add rbac permissions for networking.gke.io/frontendconfigs]

docs/deploy/resources/rbac.yaml
This removes `update` permissions for Pod, Service and Ingress resources.
All the `update` calls are removed in Ingress-GCE in
kubernetes/ingress-gce#1125 and kubernetes/ingress-gce#1127.
=> Remove unnecessary `update` permissions

pkg/loadbalancers/forwarding_rules.go, pkg/tls/tls.go, pkg/translator/translator.go, pkg/translator/translator_test.go
This PR adds translation for HTTP & HTTPS ForwardingRule resources inside of the translator package. 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubernetes/ingress-gce/1126)
=> Add translation for ForwardingRule

cmd/glbc/main.go, pkg/flags/flags.go, pkg/neg/controller.go, pkg/neg/controller_test.go, pkg/neg/manager_test.go, pkg/neg/types/types.go, pkg/neg/types/types_test.go, pkg/neg/utils.go, pkg/neg/utils_test.go, pkg/svcneg/svcneg.go
Add feature gate for NEG CRDs and propagate flag to neg controller and manager.
- Manager creates NEG CRs when NEG CRD is enabled
- Controller deletes neg crds when deleting negs when NEG CRD is enabled
Depends on #1154 being merged
=> Neg crd feature gate

pkg/loadbalancers/loadbalancers_test.go, pkg/loadbalancers/target_proxies.go, pkg/translator/translator.go, pkg/translator/translator_test.go
Refactors TargetHttp/Https Proxy to Translator package, including SSL Policy.
=> Initial Refactor of TargetProxy to Translator Package

pkg/loadbalancers/forwarding_rules.go, pkg/loadbalancers/l4_test.go
The L4 ILB implementation in k/k briefly reserves the ILB VIP until the forwarding rule is created, after which the reservation is released. Doing the same in the new L4 controller implementation to avoid leaking IP addresses.
=> Cleanup Internal IP reservation after L4 ILB creation

pkg/backends/ig_linker_test.go, pkg/backends/integration_test.go, pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/events/events.go, pkg/events/events_test.go, pkg/instances/instances.go, pkg/instances/instances_test.go, pkg/loadbalancers/forwarding_rules.go, pkg/loadbalancers/loadbalancers_test.go, pkg/loadbalancers/target_proxies.go, pkg/loadbalancers/url_maps.go, pkg/test/utils.go
{Add,Remove}Nodes from InstanceGroup
SyncIngress, TranslateIngress, IPChanged, GarbageCollection
=> Add events for major lifecycle events

pkg/backends/backends.go, pkg/backends/neg_linker.go, pkg/backends/neg_linker_test.go, pkg/neg/controller.go, pkg/neg/syncers/transaction.go, pkg/neg/syncers/transaction_test.go, pkg/neg/syncers/utils.go, pkg/neg/syncers/utils_test.go
This PR fixes issues identified by testing the VM_IP_NEG implementation. Fixes are:
1) Do not set "Port" field for VM_IP_NEGs, when listing existing endpoints as well as for new.
2) Skip invoking "commitPods" for VM_IP_NEGs since that prints several non-relevant warning messages for this mode.
3) Fix metrics export for VM_IP_NEGs
3) Set Balancing Mode as Connection for L4 ILB Backends.
4) Set ConnectionDrainingTimeout only for UDP
All these changes were verified in a dev setup.
=> Fix VM_IP_NEG creation and updates

pkg/controller/node.go, pkg/instances/instances.go
There can be a race condition where the queue somehow triggers
before the caches are able to sync.
Improve logging around the event for better debugging in the future.
=> Cherrypick: Wait for caches to sync before running node sync

cmd/glbc/main.go, pkg/context/context.go, pkg/controller/controller_test.go, pkg/controller/translator/translator_test.go, pkg/firewalls/controller_test.go, pkg/l4/l4controller_test.go, pkg/neg/controller.go, pkg/neg/controller_test.go, pkg/neg/manager.go, pkg/neg/manager_test.go, pkg/neg/readiness/reflector_test.go, pkg/neg/syncers/syncer_test.go, pkg/neg/syncers/transaction_test.go, pkg/neg/types/interfaces.go, pkg/neg/types/types.go, pkg/svcneg/svcneg.go
Controller accepts custom names and manager will create CRs per NEG when NEG CRD is enabled.
This PR is based on PR #1166
=> Create corresponding Neg CRs when NEG CRD is enabled

docs/deploy/resources/rbac.yaml, pkg/translator/translator.go, pkg/translator/translator_test.go
This PR:
* reverts the mechanism for fetching TLS secrets to a Get() (away from listing all secrets in a namespace in https://github.com/kubernetes/ingress-gce/pull/1101/files#r456811105)
* removes the secret list permission added in https://github.com/kubernetes/ingress-gce/pull/1134/files#r456812266
* resolves the test failure reported in https://github.com/kubernetes/kubernetes/pull/93031
/assign @bowei @rramkumar1
=> Revert to individual secret get

pkg/healthchecks/healthcheck.go, pkg/healthchecks/healthchecks.go, pkg/healthchecks/healthchecks_test.go, pkg/healthchecks/interfaces.go, pkg/translator/healthchecks.go, pkg/utils/healthchecks.go
Note that this PR does not introduce any semantic changes.
Some considerations:
1. We eventually want to start using composite.HealthCheck to represent HealthChecks rather than the existing structure. Moving it to the translator package makes it easier to slowly start chipping away at removing the legacy code.
2. Some of the methods exported in pkg/translator/healthchecks.go will eventually become internal implementation details. For example, DefaultHealthCheck, ApplyProbeSettingstoHC, etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubernetes/ingress-gce/1167)
=> Move APIs to work with health checks into translator package to prepare for future refactoring

pkg/loadbalancers/forwarding_rules.go, pkg/loadbalancers/l4_test.go
This is a follow up to https://github.com/kubernetes/ingress-gce/pull/1179, the previous PR cleaned up the reservation in case of new Forwarding rule creation or on updates. But, reservation also happens during periodic syncs which need to be cleaned up.
/assign @freehan @bowei
=> Cleanup L4 ILB IP Reservation in all cases.

pkg/neg/syncers/transaction.go
Without this check, error on endpoints calculation could briefly remove all endpoints in the NEG.
=> Handle error when calculating endpoints for NEG.

pkg/apis/svcneg/v1beta1/types.go, pkg/neg/controller.go, pkg/neg/manager.go, pkg/neg/manager_test.go, pkg/neg/syncers/syncer_test.go, pkg/neg/syncers/transaction.go, pkg/neg/syncers/transaction_test.go, pkg/neg/syncers/utils.go, pkg/neg/syncers/utils_test.go, pkg/neg/types/types.go, pkg/utils/namer/namer.go, pkg/utils/negdescription.go, pkg/utils/negdescription_test.go, pkg/utils/patch.go, pkg/utils/patch_test.go
- updates status on NEG CRs when neg crd is enabled
- errors during sync and initializations are exposed in NEG CR
=> syncer writes neg desc on initialization

pkg/neg/manager.go, pkg/neg/manager_test.go
- svcPortMap is the source of truth, so continue neg creation and
syncing even if corresponding NEG CR has a deletion timestamp
=> Ignore deletion timestamp when ensuring NEG CR

pkg/neg/controller.go, pkg/neg/controller_test.go, pkg/neg/manager.go, pkg/neg/syncers/endpoints_calculator.go, pkg/neg/syncers/endpoints_calculator_test.go, pkg/neg/syncers/transaction.go, pkg/neg/syncers/transaction_test.go, pkg/neg/types/types.go
Switching from Local to Cluster trafficPolicy (or vice versa) should change the endpoints calculator mode.
Also added logic to pick a random subset of upto 3 nodes in case of Local mode, with no endpoints. With this change, accessing the VIP will return "Connection refused" immediately, instead of timing out after a few seconds.
The behavior is unchanged for cases where there are endpoints.
=> Allow modifying trafficPolicy for L4 ILB services

pkg/neg/manager.go, pkg/neg/manager_test.go, pkg/neg/types/types.go, pkg/utils/common/finalizer.go
- Add finalizer to NEG CRs to ensure CR exists until NEG is deleted
during GC
- When neg crd is enabled, GC will use neg crs, otherwise will fallback
to regular GC using the naming to determine which NEGs are to be
deleted
=> Use NEG CRs for NEG Garbage Collection

pkg/neg/manager.go, pkg/neg/manager_test.go, pkg/neg/syncers/syncer.go, pkg/neg/syncers/syncer_test.go, pkg/neg/syncers/transaction.go, pkg/neg/syncers/transaction_test.go, pkg/neg/types/types.go
- With custom neg names, multiple negs can exist with the same syncer
key but different names. To ensure negs are properly managed and GC'd
add neg name to the syncer key so negs with different names will be
considered different
=> Add NegName to syncer key

pkg/backends/backends.go, pkg/loadbalancers/forwarding_rules.go, pkg/loadbalancers/l4.go, pkg/loadbalancers/l4_test.go
Protocol modification requires forwarding rule to be deleted before backend service update. Forwarding rule will also reuses the IP from service
status, to avoid IP address change due to proto change.
Other changes:
Also use GA API for forwarding rule creation always since Global Access is GA.
Remove feature gate logic for Custom Subnet.
Simplified Forwarding Rule Equality Logic. If the IP address in old and new FR do not match,
it is considered to be a change. Special case for empty IP removed.
/assign @freehan @skmatti
=> Allow modifying protocol in L4 ILB service

pkg/svcneg/svcneg.go
Incorrect import causes failure when ensuring svcneg crd.
=> Fix negv1beta1 import

pkg/apis/svcneg/v1beta1/types.go, pkg/apis/svcneg/v1beta1/zz_generated.openapi.go, pkg/crd/validation.go, pkg/crd/validation_test.go, pkg/neg/manager_test.go, pkg/neg/syncers/transaction_test.go, pkg/neg/syncers/utils.go, pkg/neg/syncers/utils_test.go, pkg/svcneg/client/clientset/versioned/typed/svcneg/v1beta1/fake/fake_servicenetworkendpointgroup.go, pkg/svcneg/client/clientset/versioned/typed/svcneg/v1beta1/servicenetworkendpointgroup.go
Update validation generation to allow for flattening array properties and outside types.
Regenerate Neg CRD code generation for open api definitions for missing types and change NegObjectReference.Id to string to generate proper validation
=> Validation generation

pkg/firewalls/controller.go, pkg/firewalls/controller_test.go, pkg/utils/utils.go
Also includes the commit from #1084 in order to cherry-pick in the e2e tests as well
=> Cherry-pick  #1209 [Expose custom health check ports in the firewall] into release-1-9

pkg/loadbalancers/forwarding_rules.go, pkg/loadbalancers/l7.go, pkg/translator/translator.go, pkg/translator/translator_test.go
We mistakenly provided the cluster subnet for the forwarding rule, which prevents customers
from being able to use a static ip from any subnet in the same VPC/Region as the cluster
=> Fix internal ingress static IP bug

pkg/metrics/features.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, pkg/metrics/types.go, pkg/neg/controller.go, pkg/neg/manager.go, pkg/neg/metrics/metrics.go, pkg/neg/syncers/transaction.go
* Add metrics to track custom named neg usage
* Add metrics to track internal neg latencies
=> Neg crd metrics

pkg/loadbalancers/forwarding_rules.go
Forwarding rule address needs to be reused when an ingress controller managed static IP address
exists for the ingress.
Fixes a bug introduced in https://github.com/kubernetes/ingress-gce/pull/1126
/assign @rramkumar1 @freehan 
cc @spencerhance
=> Bugfix http forwarding rule create workflow

pkg/metrics/features.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, pkg/metrics/types.go, pkg/neg/controller.go, pkg/neg/manager.go, pkg/neg/metrics/metrics.go, pkg/neg/syncers/transaction.go
Cherry pick #1222 to include custom named neg feature metrics and internal neg metrics.
=> Cherry Pick #1222 [Neg crd metrics]

pkg/apis/svcneg/v1beta1/types.go, pkg/apis/svcneg/v1beta1/zz_generated.openapi.go, pkg/crd/validation.go, pkg/crd/validation_test.go, pkg/neg/manager_test.go, pkg/neg/syncers/transaction_test.go, pkg/neg/syncers/utils.go, pkg/neg/syncers/utils_test.go, pkg/svcneg/client/clientset/versioned/typed/svcneg/v1beta1/fake/fake_servicenetworkendpointgroup.go, pkg/svcneg/client/clientset/versioned/typed/svcneg/v1beta1/servicenetworkendpointgroup.go
Cherry pick validation generation fix and updated codegen for ServiceNetworkEndpointGroup
=> Cherry Pick #1218 [Validation generation]

pkg/loadbalancers/forwarding_rules.go
Forwarding rule address needs to be reused when
an ingress controller managed static IP address
exists for the ingress.
=> Cherrypick #1225[Bugfix http forwarding rule create workflow] into release-10

cmd/e2e-test/healthcheck_test.go, pkg/firewalls/controller.go, pkg/firewalls/controller_test.go, pkg/firewalls/firewalls_test.go, pkg/utils/utils.go
=> Cherry-pick #1209  [Expose custom health check ports in the firewall] into release-1-10

pkg/loadbalancers/forwarding_rules.go, pkg/loadbalancers/l7.go, pkg/translator/translator.go, pkg/translator/translator_test.go
=> Cherry-pick #1223 [Fix internal ingress static IP bug] into release-1-10

pkg/controller/controller.go, pkg/metrics/features.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, pkg/metrics/types.go
These features have been implemented but are currently not included in the metrics
- SSLPolicy
- Regional Static IP
- Custom Health Checks
This PR adds metrics for them
All of them can be cherry-picked to v1.9 + v1.10
HTTPS Redirects will be added in a follow up since it is currently 1.10 only
=> Add missing features to ingress metrics

pkg/controller/controller.go, pkg/metrics/features.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, pkg/metrics/types.go
=> Cherry-pick #1233 [Add missing features to ingress metrics] into release-1-9

pkg/loadbalancers/forwarding_rules.go, pkg/loadbalancers/l4.go
This change will preserve the same ILB IP in case protocol changes. The previous approach to lookup the previous IP from status section is less-preferred.
=> Lookup forwarding rule before deletion on L4 ILB protocol change.

pkg/annotations/service.go, pkg/annotations/service_test.go, pkg/l4/l4controller.go, pkg/l4/l4controller_test.go, pkg/loadbalancers/l4.go, pkg/loadbalancers/l4_test.go, pkg/utils/patch.go, pkg/utils/utils.go
The resource annotations look like:
```
cloud.google.com/load-balancer-type: Internal
    cloud.google.com/neg-status: '{"network_endpoint_groups":{"0":"k8s1-eac61a5c-default-example-service-cluster2-xxwsn3m8"},"zones":["us-west1-pj1"]}'
    networking.gke.io/internal-load-balancer-allow-global-access: "true"
    svc.kubernetes.io/backend-service: k8s1-eac61a5c-default-example-service-cluster2-xxwsn3m8
    svc.kubernetes.io/firewall-rule: k8s1-eac61a5c-default-example-service-cluster2-xxwsn3m8
    svc.kubernetes.io/healthcheck: k8s1-eac61a5c8aaa0cb8l4-shared-hc
    svc.kubernetes.io/tcp-forwarding-rule: k8s1-eac61a5c-default-example-service-cluster2-xxwsn3m8-tcp
```
They get reset when service is modified to be an external LB. 
This PR also handles cleanup of util functions and adds more …
=> Add resource annotations for L4 ILB services.

pkg/backendconfig/backendconfig.go, pkg/crd/crd.go, pkg/crd/crd_test.go, pkg/crd/meta.go, pkg/crd/validation.go, pkg/frontendconfig/frontendconfig.go, pkg/svcneg/svcneg.go
`apiextensions.k8s.io/v1beta1` is deprecated as of [k8s-v1.16](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definition-versioning).
So, this works just fine with all 1.16+ GKE versions.
=> Update CRD client(apiextensions) to v1

cmd/e2e-test/ilb_test.go
This test case is a duplicate of the first one and doesn't add an extra signal.
=> Remove extra L7-ILB Testcase

cmd/e2e-test/basic_https_test.go, cmd/e2e-test/basic_test.go, cmd/e2e-test/finalizer_test.go, cmd/e2e-test/neg_test.go, cmd/e2e-test/redirects_test.go, cmd/e2e-test/sslpolicy_test.go, cmd/e2e-test/upgrade/basic_http.go, cmd/e2e-test/upgrade/finalizer.go, cmd/e2e-test/upgrade/v2frontendnamer.go, cmd/e2e-test/v2frontendnamer_test.go, pkg/e2e/helpers.go, pkg/fuzz/features/https_redirects.go, pkg/fuzz/validator.go
During the transition test refactor, a couple bugs were introduced that caused the test to not ensure the Ingress and FrontendConfig correctly.
=> Fix a couple bugs in the redirects e2e test

cmd/e2e-test/affinity_beta_test.go, cmd/e2e-test/ilb_test.go, cmd/e2e-test/neg_test.go, cmd/e2e-test/redirects_test.go, cmd/e2e-test/security_policy_test.go
Many serial transition tests loop through a variety of test cases but do not explicitly run them with t.Run().  This makes debugging more difficult since it's hard to tell in which case the test failed.
=> Refactor transition e2e tests to use t.Run()

pkg/context/context.go, pkg/healthchecks/healthchecks_l4.go, pkg/l4/l4controller.go, pkg/l4/l4controller_test.go, pkg/loadbalancers/l4.go, pkg/loadbalancers/l4_test.go, pkg/neg/controller.go, pkg/neg/controller_test.go, pkg/neg/types/interfaces.go, pkg/neg/types/types.go, pkg/neg/types/types_test.go, pkg/test/utils.go, pkg/utils/namer/interfaces.go, pkg/utils/namer/l4_namer.go, pkg/utils/namer/l4_namer_test.go, pkg/utils/namer/namer.go, pkg/utils/serviceport.go
The forwarding rule gets the protocol added as suffix. The rest of the name should be truncated to ensure a total of 63 chars.
=> Make sure L4 Forwarding rule is atmost 63 characters

cmd/e2e-test/upgrade/neg.go, cmd/e2e-test/upgrade_test.go
- ensures that upgrade does not cause issues to neg gc or neg syncing
=> Add NegCRD Upgrade Test

pkg/neg/manager.go, pkg/neg/manager_test.go, pkg/neg/types/types.go
- if neg crs are incorrectly deleted, next resync on service will
recreate the neg cr
=> Ensure neg crs for all desired ports

cmd/glbc/app/namer.go, pkg/storage/configmaps.go, pkg/storage/configmaps_test.go
This would ensure that only one ingress controller can create the `ingress-uid` config map on bootstrap.  This ensures that the provider-uid and uid are consistent.
=> ensure ingress controller always generate consistent uid and provider uid

pkg/annotations/ingress.go, pkg/controller/controller.go, pkg/loadbalancers/interfaces.go, pkg/loadbalancers/l7s.go, pkg/loadbalancers/l7s_test.go, pkg/loadbalancers/loadbalancers_test.go, pkg/loadbalancers/url_maps.go, pkg/sync/interfaces.go, pkg/sync/sync.go, pkg/utils/utils.go
The V2 GC currently doesn't support GC of duplicate frontend resources from a different scope
cc: @skmatti for V2 namer
Issue: #1252
=> Fix GC for switching between LB Scopes on Namer V2

pkg/neg/controller.go, pkg/neg/controller_test.go
When the default backend service has the NEG annotation, NEG controller currently does not create NEGs for default backend if a L7 XLB needs it. 
cc: @spencerhance @swetharepakula
=> Fix NEG handling for default backend service when it contains the NEG annotation

pkg/neg/metrics/metrics.go
Change metric name from `endpoint_operation_duration_seconds` to `neg_operation_duration_seconds`
=> Change neg metric name

pkg/metrics/metrics.go
The flag values are populated in main(),so will not be available in init()
There is no downside to always registering these metrics, even if L4 controller is not running.
cc @skmatti
=> Always register L4 ILB metrics.

pkg/neg/manager.go, pkg/neg/manager_test.go, pkg/neg/types/fakes.go
this is to prevent the small chance of GCE Get NEG API returns a non not found error.
=> only ignore not found error when getting NEG

pkg/metrics/metrics.go
The flag values are populated in main(),so will noe be available in init()
There is no downside to always registering these metrics, even if L4 controller
is not running.
https://github.com/kubernetes/ingress-gce/pull/1284
@skmatti
=> Always register L4 ILB metrics - cherrypick into release-1.10

pkg/l4/l4controller.go, pkg/loadbalancers/l4.go
This ensures that same service version is used for
populating new annotations and update the resource
in API server. Fixes a race condition where some of
the existing annotations overwritten.
=> Improve update annotations workflow for L4 ILB service

cmd/e2e-test/neg_test.go, pkg/e2e/helpers.go
- Checking for specific error messages will reduce flaking due to other
error events being emitted
=> Check for specific error events

pkg/l4/l4controller.go, pkg/loadbalancers/l4.go
This ensures that same service version is used for
populating new annotations and update the resource
in API server. Fixes a race condition where some of
the existing annotations are overwritten.
=> Cherrypick #1287[Improve update annotations workflow for L4 ILB service] into release-1.10

pkg/cmconfig/controller.go, pkg/experimental/workload/daemon/daemon.go, pkg/l4/l4controller.go, pkg/neg/controller.go, pkg/neg/manager.go, pkg/neg/readiness/utils.go, pkg/neg/syncers/transaction.go, pkg/utils/common/finalizer.go, pkg/utils/patch/patch.go, pkg/utils/patch/patch_test.go
This replaces of all instances of update calls of k8s Service resource from this controller.
Also, this uses k8s service helper function to patch Service.
=> Use Patch instead of Update for k8s Service client

pkg/composite/composite.go
Both ```SetSslCertificateForTargetHttpsProxy()``` and  ```SetUrlMapForTargetHttpProxy()``` had not been updated once regional beta and ga support was added.  This causes failures when refreshing certs or updating the url map.
This will definitely need to be cherry-picked into release-1.9
=> Fix bug in composite funcs without full regional support

pkg/healthchecks/healthchecks_test.go, pkg/loadbalancers/features/features.go
=> Cherry-pick #1091 [Update L7-ILB API to GA] into release-1-9

pkg/neg/manager.go, pkg/neg/manager_test.go, pkg/neg/syncers/transaction.go, pkg/neg/syncers/utils.go, pkg/neg/syncers/utils_test.go, pkg/neg/types/cloudprovideradapter.go, pkg/utils/negdescription.go, pkg/utils/negdescription_test.go
* Grab lock before deleting NEG CR to ensure that neg is not desired
* Verify description before deleting NEG to ensure NEG is controlled by this cluster
* Delete using name and zone when refs are not populated
* Improve logging and error messages
=> Mitigate NEG GC Race and add Logging

pkg/utils/utils.go, pkg/utils/utils_test.go
- if annotation is present, controller will manage the ingress
=> CherryPick #1308 to release 1.10 [Ignore Ingresses that have spec.ingressClassName]

cmd/e2e-test/sslpolicy_test.go, pkg/e2e/helpers.go
Sharing the policy name can cause conflicts between multiple testcases running at the same time in the same project.
Also updates the test logging.
=> Update SSLPolicy e2e test to use a unique policy name

Dockerfile.404-server-with-metrics, cmd/404-server-with-metrics/prometheus.yml, cmd/404-server-with-metrics/server-with-metrics.go
having the /mterics and /healthz handlers server from a different server
listening on default port of 8081.
=> This PR fixes the /metrics from being exposed to the Internet by

pkg/neg/manager.go, pkg/neg/manager_test.go, pkg/neg/syncers/utils.go, pkg/neg/types/fakes.go
- Return error when fail to find neg to prevent empty neg ref being set on neg cr
- attempt to delete by zone, if self link is malformed
=> Prevent Empty Neg Refs on CRs

pkg/e2e/helpers.go
- ensures 2 rounds of GC complete before test failure
=> Increase Neg GC Poll timeout

cmd/glbc/main.go, pkg/neg/controller.go, pkg/neg/controller_test.go, pkg/neg/manager_test.go, pkg/neg/readiness/poller_test.go, pkg/neg/readiness/reflector.go, pkg/neg/readiness/reflector_test.go, pkg/neg/syncers/syncer_test.go, pkg/neg/syncers/transaction_test.go, pkg/neg/types/testing.go
=> Remove pkg/context dependency from NEG controller

cmd/glbc/app/init.go, cmd/glbc/main.go, cmd/workload-controller/main.go, pkg/context/context.go, pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/controller/translator/translator_test.go, pkg/crd/crd.go, pkg/crd/crd_test.go, pkg/firewalls/controller_test.go, pkg/ingparams/ingparams.go, pkg/l4/l4controller_test.go, pkg/neg/controller_test.go, pkg/neg/types/testing.go
- only ensure if IngressClass resource type exists on cluster
- ensure GCPIngressParams as a cluster scoped CRD
- create GCPIngressParams and IngressClass indexers
=> Ensure GCPIngressParams CRD

cmd/e2e-test/sslpolicy_test.go, pkg/e2e/fixtures.go
-Change tests to transition test
-Re-use sslpolicy since we do not need to delete it
-General cleanup
=> Refactor SSLPolicy e2e tests

pkg/neg/manager.go, pkg/neg/manager_test.go
- ensure that extra user provided labels are not overwritten when
ensuring svc negs
=> Update svcNeg resources with original neg CR

pkg/loadbalancers/forwarding_rules.go, pkg/loadbalancers/forwarding_rules_test.go, pkg/loadbalancers/l4_test.go
Added logic to set AllPorts field if more than 5 ports are specified.
Also modified ForwardingRule Equals function to check for AllPorts field as well as BackendService resource URL
/assign @freehan @bowei
=> Support specifying more than 5 ports in L4 ILB service

pkg/metrics/metrics.go
The default buckets have an upper bound of 10s. Since sync latency can take upto
a couple of minutes, custom buckets will be beneficial.
@swetharepakula 
=> Add custom buckets for ILB Sync latency.

pkg/metrics/metrics.go
The default buckets have an upper bound of 10s. Since sync latency can take upto
a couple of minutes, custom buckets will be beneficial.
=> Add custom buckets for ILB Sync latency - Cherrypick https://github.com/kubernetes/ingress-gce/pull/1351

pkg/l4/l4controller.go
Since there is no guaranteed ILB service that the controller will always sync, we cannot
check for an absolute lastSync timestamp. Instead, this change tracks the last enqueue
timestamp and ensures that the last sync happened soon(15 mins later atmost) after enqueue.
This change only logs an error and does not fail the healthcheck in case of the delay. Returning error will be addressed in a follow-up - https://github.com/kubernetes/ingress-gce/pull/1350
=> Add a healthcheck for L4 ILB controller.

pkg/l4/l4controller.go
Reverts kubernetes/ingress-gce#1353
The latest image from master - gcr.io/k8s-ingress-image-push/ingress-gce-glbc-amd64:master is stuck at node.go - hasSynced(). 
```
I0116 00:32:30.893728       1 controller.go:283] Waiting for initial sync
I0116 00:32:31.052155       1 node.go:75] Waiting for hasSynced (3m10.158652854s elapsed)
I0116 00:32:32.052554       1 node.go:75] Waiting for hasSynced (3m11.159047588s elapsed)
I0116 00:32:33.053050       1 node.go:75] Waiting for hasSynced (3m12.159426409s elapsed)
I0116 00:32:34.053754       1 node.go:75] Waiting for hasSynced (3m13.160250442s elapsed)
I0116 00:32:35.054018       1 node.go:75] Waiting for hasSynced (3m14.160516214s elapsed)
I0116 00:32:35.893937       1 controller.go:283] Waiting for initial sync
```
Will revert and investigate.
=> Revert "Add a healthcheck for L4 ILB controller."

pkg/annotations/service.go, pkg/l4/l4controller_test.go, pkg/loadbalancers/l4.go, pkg/loadbalancers/l4_test.go, pkg/utils/namer/l4_namer.go, pkg/utils/namer/l4_namer_test.go
Previous code was using the same name for firewall rule for LoadBalancerIP access as well as firewall rule for healthchecks.
These should be 2 different firewall rules.
This change also includes the Healthcheck firewall name in the service annotations.
=> Generate a unique name for firewall rule for Healthchecks.

pkg/neg/manager.go, pkg/neg/manager_test.go
Cherrypick #1363 into release 1.10 to ignore 400 Bad Request errors during GC
=> Cherrypick #1363 Neg 400 gc release 1.10

pkg/loadbalancers/l7s.go, pkg/loadbalancers/loadbalancers_test.go, pkg/translator/translator_test.go, pkg/utils/namer/frontendnamer.go, pkg/utils/namer/frontendnamer_test.go, pkg/utils/namer/interfaces.go, pkg/utils/namer/utils.go, pkg/utils/namer/utils_test.go
This fixes a bug where an ingress with name that has dot character in it. Since, dot is an invalid character for GCE resource name, the load balancer will not configured. But the ingress failed to get deleted as we proactively try to delete the GCE resources when they were not created.
This ensures that those ingresses with invalid names are deleted and not re-queued by controller.
=> Skip garbage collection for invalid frontend resource names

cmd/e2e-test/neg_test.go, pkg/e2e/fixtures.go, pkg/e2e/helpers.go
- test that no errors occur when processing service recreations occur
before GC
=> Add disruptive neg e2e tests

pkg/neg/manager.go, pkg/neg/manager_test.go, pkg/neg/syncers/transaction.go, pkg/neg/syncers/transaction_test.go, pkg/neg/syncers/utils.go, pkg/neg/syncers/utils_test.go
* ensures that controller only manages custom named negs that were
created by the neg controller
* only delete custom named negs that have a populated description
=> Do not claim custom named negs with empty desc

pkg/neg/manager.go, pkg/neg/manager_test.go, pkg/neg/syncers/transaction.go, pkg/neg/syncers/transaction_test.go, pkg/neg/syncers/utils.go, pkg/neg/syncers/utils_test.go
Cherrypick #1374 into release-1.10
* ensures that controller only manages custom named negs that were
created by the neg controller
* only delete custom named negs that have a populated description
=> Cherrypick #1374 to release-1.10: Do not claim custom named negs with empty desc

cmd/e2e-test/neg_test.go, pkg/e2e/helpers.go
- syncer shutting down or service not found (due to out of date cache)
error events are temporary and can safely be ignored
=> Ignore temporary ProcessServiceFailed error events

pkg/context/context.go, pkg/e2e/framework.go, pkg/e2e/helpers.go
Fixes https://github.com/kubernetes/kubernetes/issues/100560
CRD v1beta1 is being removed in kubernetes 1.22, which starts development shortly.  This updates the GETs to be CRD v1 and tweaks the version check code to match.  From the godoc on CRD v1beta1 .spec.version: `Must match the name of the first item in the `versions` list if `version` and `versions` are both specified.`.
I haven't found these CRDs are defined.  It doesn't appear to be in this repo, but I'm concerned that they are also v1beta1.  Any hints?
@liggitt
=> update to use CRD v1

pkg/psc/controller.go
Since error is always nil, remove from error message.
=> Remove empty error from error message

pkg/controller/controller.go, pkg/translator/translator.go, pkg/translator/translator_test.go
This fixes a bug where:
1) User has existing HTTPS LB with TLS secrets
2) User adds a new TLS secret that doesn't exist yet (could be added by another controller)
3) Ingress controller sets up HTTP only, causing their HTTPS resources to be deleted and causes downtime.
What this PR does is continue syncing the HTTPS LB as long as there is at least 1 valid secret.
cc: #388
=> Continue syncing HTTPS if there is at least one valid TLS secret

pkg/backends/backends.go
Currently the function Backends.Health() returns a status of the first instance of the first backend of the given backend service. (issue #1394) This PR will fix the issue by make the function to return `Healthy` when at lease one healthy instance exists.
So the possible cases are:
1) return `Healthy` when at least one healthy instance exists
2) return `Unhealthy` when all instances are unhealthy (at least one)
3) return `Unknown` when the hs.HealthStatus is empty or nil or something unknown...
=> fix the behavior of Backends.Health() to return more reliable value

pkg/l4/l4controller.go
Error returned by k8s Patch call only has "not found" string, no HTTP 404.
@swetharepakula
=> Fix the check for not found error.

pkg/backends/backends.go, pkg/loadbalancers/l4_test.go
This is ensured by the neg linker which inserts the right NEG list as backends. Checking them in Ensure call will unnecessarily reconcile the list to empty.
=> Skip checking backend list in L4 Controller flow.

pkg/loadbalancers/l7.go
Removes "Global" so that it's not confusing to debug when deleting a Regional Forwarding Rule.
=> Fix log line in deleteForwardingRule

pkg/backends/features/securitypolicy_test.go, pkg/backends/syncer.go, pkg/composite/composite.go
1. This fixes an error where backend service scope is empty.
We emit an error that the security policy is not supported
if the scope is empty.
2. Uses full security policy resource link when updating
the backend service.
=> Fix cloud armor security policy workflow

pkg/backends/features/securitypolicy_test.go, pkg/backends/syncer.go, pkg/composite/composite.go
1. This fixes an error where backend service scope is empty.
We emit an error that the security policy is not supported
if the scope is empty.
2. Uses full security policy resource link when updating
the backend service.
=> Cherrypick #1406[Fix cloud armor security policy workflow] into release-1.11

pkg/annotations/ingress.go, pkg/annotations/ingress_test.go, pkg/backends/syncer.go, pkg/controller/controller.go, pkg/controller/translator/translator.go, pkg/firewalls/controller.go, pkg/flags/flags.go, pkg/loadbalancers/addresses.go, pkg/loadbalancers/addresses_test.go, pkg/loadbalancers/certificates.go, pkg/loadbalancers/forwarding_rules.go, pkg/loadbalancers/l7.go, pkg/loadbalancers/l7s.go, pkg/loadbalancers/loadbalancers_test.go, pkg/loadbalancers/target_proxies.go, pkg/loadbalancers/url_maps.go, pkg/neg/controller.go, pkg/neg/controller_test.go, pkg/utils/utils.go, pkg/utils/utils_test.go
Some neg controller unit tests only pass because when all tests are run and fail when run individually. This is because the EnableL7ILB flag is set in one test and all tests after that have the same flag value. This PR cleans up the test contamination and ensures that the tests will pass when run independently or together.
=> Remove Enable L7ILB Feature Gate 

pkg/metrics/features.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, pkg/metrics/types.go, pkg/neg/controller.go, pkg/neg/manager.go, pkg/neg/manager_test.go, pkg/neg/types/interfaces.go
Cherrypick #1420 into release 1.10 and introduce error metrics for NEG syncers
=> [Cherrypick #1420] Neg Error Metrics to release 1.10

cmd/e2e-test/customrequestheaders_test.go, cmd/e2e-test/ilb_test.go
Ingress V1 requires namespace to be populated at creation.
@spencerhance 
=> Populate namespace when creating ingress

pkg/backends/features/logging.go, pkg/backends/features/logging_test.go, pkg/composite/gen.go, pkg/composite/gen/main.go
This fixes an edge case where logging is enabled and sampling rate is set to 0.0
Currently, the value is treated as empty value and not sent to the server in which case the existing sampling rate is retained.
=> Fix ensure logging workflow for nil/empty sampling rate

pkg/backends/backends.go, pkg/backends/ig_linker.go, pkg/backends/syncer.go, pkg/healthchecks/healthchecks.go, pkg/healthchecks/healthchecks_l4.go, pkg/l4/l4controller.go, pkg/loadbalancers/forwarding_rules.go, pkg/neg/controller.go, pkg/neg/manager.go, pkg/neg/syncers/transaction.go, pkg/neg/syncers/utils.go
This allows the errors to be unwrapped to classify it correctly without having to do string matches - https://blog.golang.org/go1.13-errors#TOC_3.3.
One usecase is to use the GCE API errors as prometheus metric labels. Wrapping errors will make this classification easier.
@swetharepakula @spencerhance 
=> Use %w to wrap errors.
